### ISSUE TITLE
File Centipede fails to start

### ISSUE THREAD

**Issue by smaragdus** [filecxx/FileCentipede#10]
When I try to start [File Centipede](https://github.com/filecxx/FileCentipede) version [1.0](https://github.com/filecxx/FileCentipede/releases/tag/1.xx) running the executable `fileu.exe` in main directory I get this error message:

```
fileu.exe has stopped working
A problem caused the program to stop working correctly. Please close the program.
```

**screen:**
![File Centipede 1 0 - 2022-03-11 - error - 001](https://user-images.githubusercontent.com/9025757/157961228-b278baf3-32ce-4ddc-b33a-24444f64387a.png)

When I go to `lib` sub-directory and run `fileu.exe` I get the following error message:

```
error
Install failed
```

**screen:**
![File Centipede 1 0 - 2022-03-11 - error - 005](https://user-images.githubusercontent.com/9025757/157962460-3f163f3d-2e54-40a9-912a-c80f0233d5e1.png)

This happens on Windows 8 x64.

So I was unable to start and test [File Centipede](http://filecxx.com/en_US/index.html) which looks impressive in the [screen shots](http://filecxx.com/en_US/index.html#screenshot).

**Comment by filecxx** [comment]
Delete directory, re-unzip, remove space from path, this issuse will be fix few hours after, i am working on it.

**Comment by smaragdus** [comment]
@filecxx 

 thanks for the quick reply! The workaround you suggested works:

![File Centipede 1 0 - 2022-03-11 - 002](https://user-images.githubusercontent.com/9025757/157976410-16d664a1-502c-4dd8-8691-9585ba23c248.png)

I am testing it right now. For a first version my impressions are excellent. I am glad that [File Centipede](http://www.filecxx.com/en_US/index.html) is portable by design- all data and settings saved in program folder (`C:\Software\Centipede\lib`).

I may open some new issues.

Regards

**Comment by filecxx** [comment]
I believe the new uploaded zip has fixed this issue, I have tested on win10, but not on win8, win7.

**Comment by smaragdus** [comment]
@filecxx 

> I believe the new uploaded zip has fixed this issue, I have tested on win10, but not on win8, win7.

I will have a look and report. Thanks for the notification,

**Comment by smaragdus** [comment]
@filecxx 

I can confirm that the problem is solved, installation successful in a directory containing spaces:

**screen:**

![File Centipede - 2022-03-12 - install - 002](https://user-images.githubusercontent.com/9025757/157998047-32055ff0-cb84-4dd6-b192-5552954c507e.png)

and the program is starting fine:

**screen:**

![File Centipede - 2022-03-12 - 001](https://user-images.githubusercontent.com/9025757/157998061-587118ad-000e-4106-ad35-5963d10c980b.png)

Thanks for the quick fix!

I am closing this issue.

Regards

**Comment by smaragdus** [comment]
I tested the latest release and it fails to install, showing the following error message:

```
error
Install failed code: 8
```

**screen:**

![File Centipede 1 0 - 2022-03-13 - error - 001](https://user-images.githubusercontent.com/9025757/158039857-b788535f-b63d-4dd8-8337-f49348d36c32.png)

The penultimate release worked, I mean this one:

**Name: filecxx_1.0_win_x64.zip
File Size: 26175601 Byte(s) (24.96 MB)
Modified Date: 2022-03-12 02:17**
**MD5:** `a1239819919c611031b87c05c8c599a1`
**SHA1**: `eb3e0b85bac69145d697ec3214a60fa80e6b7f41`
**SHA256**: `484fd513bebff3ca4632037c307e7503fdf96b58835e5c92fb9e9a862acbfc91`
**SHA512**: `c9b68e50728e123f30d73e9171c7b05efdf47e17608181bafaa1ad595ff4c30091b14d62f910f86acaca6d05008ac979cae30a79800c13f87e14508e6a118e94`
**RIPEMD160:** `56d951a22d05b5a06cc2c757ee256a7c5dd29979`

While the latest release does not work, I mean this one:

**Name: filecxx_1.0_win_x64.zip
File Size: 26176317 Byte(s) (24.96 MB)
Modified Date: 2022-03-12 05:20**
**MD5:** `1f1dc361312eb4527053672c6b1163a6`
**SHA1:** `970c0a0e633ff1a68fdf10ad73591fce94bef3f7`
**SHA256:** `8c0f33cdce6231479d0b4d73efaa9c3c6e3ba96ba5f1daa3f723da29605e3ddb`
**SHA512:** `9c6692aee844103ac2bd789accf082b875addfae02f82109b0fd5ab6d5adc4309745abba1ff3d0e034d66ffbc3d7a62f69986d2c2b3a76c5783876f9057a6555`
**RIPEMD160:** `9c1be79256b18d5d2dcd26cee330550775115549`

Please consider keeping the old releases in [Releases](https://github.com/filecxx/FileCentipede/releases) page and publishing the new releases with new version number since publishing the new releases with the same, unchanged version number makes it a real mess- the users do not get notification for new version and the latest version may happen to not work as it is the case here,

**Comment by filecxx** [comment]
Have any files been created in the directory?? 
![image](https://user-images.githubusercontent.com/100348948/158040382-4ba316ef-4f42-4b33-b20c-1f24efa467ad.png)

this is a copy file fail error, it usually wouldn't happen since filec is running under administrator privilege, could you provide the origin directory path (install origin path -> target path).

**Comment by smaragdus** [comment]
I tried again and this time the installation was successful, strange.

Paths:

`C:\Portable Programs\File Centipede`
`C:\Portable Programs\File Centipede\fileu.exe`
`C:\Portable Programs\File Centipede\filec.exe`

UAC (User Account Control) disabled on my machine.

I really do not know what caused the problem and I do not know what is new in the latest release.

Anyway, I will close this issue as it got resolved but I do not know what actually happened when the installation failed.

**Comment by filecxx** [comment]
I think I know that's the problem, you probably renamed or moved the directory before installing, on win7,win8 because of the "system cache", filec still got the old path, this is one of the potential issues that need to be fixed.

**Comment by smaragdus** [comment]
@filecxx 

> I think I know that's the problem, you probably renamed or moved the directory before installing, on win7,win8 because of the "system cache", filec still got the old path, this is one of the potential issues that need to be fixed.

Yes, I think this was what I did and I suppose you are right.

**Comment by yanxi808** [comment]
![Uploading 微信图片_20220314175535.png…]()
为什么重启电脑后又来了这个问题？系统是win10
Why did the problem come back after restarting the computer?System is win10
