### ISSUE TITLE
建议添加保存资源链接功能

### ISSUE THREAD

**Issue by YulinChan** [filecxx/FileCentipede#100]
![image](https://user-images.githubusercontent.com/48314862/161381389-bf7b434e-ff31-47f8-a274-842d40d9b15d.png)
希望在解析链接时弹出的【添加任务】窗口那里（如上图）或者主窗口编辑配置那里保存一下资源链接（主要是磁力链接）
应用场景：
热心网友分享了一大堆磁力链接，我全部复制，此时文件蜈蚣弹出添加任务窗口，解析我复制的那一堆磁力链接，解析完成时我看到了磁力对应的文件信息，有的文件太大了我本机装不下，我需要把这个磁力链接拿出来用其他的在线工具离线下载，如果没在任务窗口那里保存有磁力链接我就分不清当前这个任务对应我复制的那一堆磁力中的哪一个了。

**Comment by filecxx** [comment]
在任务列表中，右键 -> 菜单 -> 复制 -> 复制地址

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/161383553-c2113527-9dc2-489d-9383-8a883f2b792d.png)
![image](https://user-images.githubusercontent.com/100348948/161383588-e4e9a958-45fa-4c7d-92c6-7fa67a9e4912.png)

**Comment by YulinChan** [comment]
> ![image](https://user-images.githubusercontent.com/100348948/161383553-c2113527-9dc2-489d-9383-8a883f2b792d.png) ![image](https://user-images.githubusercontent.com/100348948/161383588-e4e9a958-45fa-4c7d-92c6-7fa67a9e4912.png)

我试了一下，复制地址为乱码或空白欸，复制hash倒是正常。下图是我复制地址后粘贴板的内容
![image](https://user-images.githubusercontent.com/48314862/161414453-60e98150-cf56-4a50-8518-29370d06864c.png)

另外，地址在任务栏里的话，也就是说我要添加任务之后才能复制地址，但添加任务后就会在硬盘创建等大的空文件了，还是不太好。

**Comment by filecxx** [comment]
复制地址在windows版本有时候可能确实存在问题，这个需要被修复在下个版本中.

还有为什么一定要在确定添加任务面板中复制磁力链接呢？这个面板只是显示的一个任务中BT种子包含的文件列表，不能把其中每个文件单独分成独立的磁力链接。

**Comment by YulinChan** [comment]
> 还有为什么一定要在确定添加任务面板中复制磁力链接呢？这个面板只是显示的一个任务中BT种子包含的文件列表，不能把其中每个文件单独分成独立的磁力链接。

为了方便【批量】处理磁力链接，同时复制【一堆磁力链接】时能知道哪个任务对应哪个磁力链接。我并非是要复制任务里的单个文件的磁力链接，而是整个任务的磁力链接。

我贴的蜡笔小新那个图可能让你误解我的意思了。
