### ISSUE TITLE
报bug

### ISSUE THREAD

**Issue by Faith-YSQ** [filecxx/FileCentipede#101]
我在surface go上安装了这个软件，发现如下问题：
1、窗口大小问题，主动启动软件，窗口过大，通过字体和窗口大小进行了调整也勾选了保存窗口大小的选项，虽然主动启动界面没问题了，但是，浏览器驱动弹出来的下载框大小还是很大，无法调整。
2、浏览器拓展问题，会出现有些视频嗅探不到的问题，主要是b站。这个问题说来也奇怪、一开始还有下载按钮，但是换个视频就不行了，而且再次切换回原来的视频，竟然也不可以了。

**Comment by Faith-YSQ** [comment]
再附加提个建议，就是可不可以添加一个就是线程例外网址问题，比如对某个网站单独设置使用4个线程下载，主要是下载百度盘的某些链接要求设置UA和线程设置为4

**Comment by Faith-YSQ** [comment]
再附加提个建议，就是可不可以添加一个就是线程例外网址问题，比如对某个网站单独设置使用4个线程下载，主要是下载百度盘的某些链接要求设置UA和线程设置为4

**Comment by Faith-YSQ** [comment]
再附加提个建议，就是可不可以添加一个就是线程例外网址问题，比如对某个网站单独设置使用4个线程下载，主要是下载百度盘的某些链接要求设置UA和线程设置为4

**Comment by filecxx** [comment]
软件启动的默认大小为1024 * 768 如果调节的更小，那么是以牺牲PC体验为代价，这个不太可能会更改.

B站的视频用的JS分块编码视频分段，没有直接使用m3u8，抓取效果不好，以后会针对这类规则进行优化。

针对特定网站进行规则设置这个已经有人提出了，确定会加入。

**Comment by filecxx** [comment]
`但是，浏览器驱动弹出来的下载框大小还是很大，无法调整。`

你可以手动尝试修改文件 ui/tasks/confirm_http.sml 

Dialog#main
{
    title:"${add_task}"
    layout:VBoxLayout
    w:600
    h:400

w 宽度 
h 高度
