### ISSUE TITLE
希望支持一下Aria2协议

### ISSUE THREAD

**Issue by Dynamith** [filecxx/FileCentipede#104]

**Comment by filecxx** [comment]
为什么？

**Comment by filecxx** [comment]
写一段非常简单的循环100万次HTTP请求JS代码可以直接在任何类似或基于Aria2的机器上创建100万个任务，并且可以在任何网页上运行

但是这样的地址，需要点击时候才能添加任务
fileu:0eyJ1cmkiOiJodHRwczovL2dpdGh1Yi5jb20vZmlsZWN4eC9GaWxlQ2VudGlwZWRlL3Jhdy9tYWluL3JlbGVhc2UvY2hyb21lLmNyeCJ9

http://www.filecxx.com/zh_CN/documentation/create_address.html

在设计时候我考虑过这样的问题，所以才做出这个决定。

**Comment by Dynamith** [comment]
之前用[网盘下载助手](https://www.baiduyun.wiki/install.html)配合IDM，filecxxx不支持第一种API下载。
试了一下把第二种aria下载中的cookie和ua等提取出来，手动创建http任务是可以下载的。于是就希望支持一下。

**Comment by Dynamith** [comment]
你是为了防止让网页劫持下载器吗

**Comment by filecxx** [comment]
> 你是为了防止让网页劫持下载器吗

是的，创建垃圾任务可以在几秒钟内填满几TB的硬盘

**Comment by Dynamith** [comment]
我只是建议支持一下能解析aria2c的链接协议就行，类似这样
```aria2c "https://d.pcs.baidu.com/file/xxxxx" --out "xxxx" --header "User-Agent: pan.baidu.com" --header "Cookie: BDUSS=xxxx"```

**Comment by filecxx** [comment]
你可以鼓励[网盘下载助手](https://www.baiduyun.wiki/install.html)作者支持文件蜈蚣链接，实现这个功能只需要几分钟的时间。

**Comment by Dynamith** [comment]
好的，我也去他那里提一下issue。
不过还是希望你能考虑考虑。

**Comment by filecxx** [comment]
我尽量。

**Comment by Dynamith** [comment]
感谢啦🙏

**Comment by filecxx** [comment]
已经支持了。
