### ISSUE TITLE
磁力链接解析出的文件布局不正确

### ISSUE THREAD

**Issue by 0xfile** [filecxx/FileCentipede#106]
![image](https://user-images.githubusercontent.com/86770473/161478859-647147c3-66b8-4acb-b6d8-e122b6d68a05.png)
实际的文件布局是一个文件夹里面包含一个mp4文件。另外，文件大小也没有显示。
magnet:?xt=urn:btih:08CB1C2FE4927169D94E215CAAA32A1B96052717

**Comment by zaobaocn** [comment]
linux下是正常，windows下有问题，dpi显示那个也一样。感觉这个软件更适合在Linux下使用欸。

**Comment by filecxx** [comment]
这个问题应该已经修复了。
