### ISSUE TITLE
提一点小建议

### ISSUE THREAD

**Issue by Spturate** [filecxx/FileCentipede#108]
1.希望开机自启不要弹出软件主题窗口，后台自启就行了
2.浏览器点击下载链接时会弹出软件主窗口和下载的窗口，希望能把主窗口删掉，没必要
3.还有就是下载分类的小建议，希望能根据文件后缀名的方式自动分类文件夹

**Comment by filecxx** [comment]
1 和 2 在2.0版本中会改进 

3 已经存在了

![image](https://user-images.githubusercontent.com/100348948/161571365-4769e4d7-bd29-4534-9bf4-999f233d0456.png)

**Comment by Spturate** [comment]
顺手提一个今天发现的小bug？，我在浏览器嗅探视频资源下载.TS时，回到主界面查看是空白的,但是下载队列里面是有新加的，下面的下载网速也起来了。点全部停止也停不下来
![](https://s2.loli.net/2022/04/05/s4STdpDor7fIGKW.png)

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/161711839-801d6754-d1b7-40b0-985f-41e38909dc04.png)

你应该点全部，你筛选了分类，所以你看不到非该分类下的任务
