### ISSUE TITLE
大神，嗅探功能在YOUTUBE上怎么使用

### ISSUE THREAD

**Issue by SuperBlackWednesday** [filecxx/FileCentipede#109]
在chrome100上，嗅探功能无法开启，让我联系开发者
我用EDGE,能用嗅探功能，可以下载哔哩哔哩的某些视频，YOUTUBE上不会下载，说是远程拒绝或者链接失败

**Comment by filecxx** [comment]
youtube 你可能需要设置代理才能下载。

**Comment by lswsx** [comment]
> youtube 你可能需要设置代理才能下载。

下载的视频和音频是分离的，希望能合并下载

**Comment by filecxx** [comment]
> > youtube 你可能需要设置代理才能下载。
> 
> 下载的视频和音频是分离的，希望能合并下载

浏览器扩展目前并没有针对任何网站进行单一处理，youtube建议用y2mate获取地址，2.0之后在处理这一块。

**Comment by lswsx** [comment]
> 

好的，谢谢大神

**Comment by lswsx** [comment]
> 好的，谢谢大神



> > > youtube 你可能需要设置代理才能下载。
> > 
> > 
> > 下载的视频和音频是分离的，希望能合并下载
> 
> 浏览器扩展目前并没有针对任何网站进行单一处理，youtube建议用y2mate获取地址，2.0之后再处理这一块。



> > > youtube 你可能需要设置代理才能下载。
> > 
> > 
> > 下载的视频和音频是分离的，希望能合并下载
> 
> 浏览器扩展目前并没有针对任何网站进行单一处理，youtube建议用y2mate获取地址，2.0之后再处理这一块。

好的，谢谢大神

**Comment by SuperBlackWednesday** [comment]
好吧大神，目前用那个127.0.0.1的那个选项无法下载，我还不会设置。我得研究研究，我是挂梯子的，会不会有影响？

**Comment by filecxx** [comment]
如果直接用VPN应该不需要设置代理，当然，部分VPN可能会自动排除一些网站。
