### ISSUE TITLE
filec.exe does not terminate on program exit

### ISSUE THREAD

**Issue by smaragdus** [filecxx/FileCentipede#11]
On program exit `filec.exe` process does not terminate- it continues to run in the background:

**screen:**
![File Centipede 1 0 - 2022-03-11 - filec - 001](https://user-images.githubusercontent.com/9025757/157980535-fcc1ece7-de39-4c16-9d12-ebf686078012.png)

If I manually terminate **filec.exe** process and then restart **File Centipede** the program shows message that **filec.exe** is not running:

**screen:**
![File Centipede 1 0 - 2022-03-11 - filec - 002](https://user-images.githubusercontent.com/9025757/157980782-5a6cac56-465e-4730-92d6-0ea17c430f3a.png)

Clicking **Launch** button starts the process and the program runs fine.

This isn not a big deal but I expect when I exit a program all the associated processes to be terminated and when I start the program all the associated processes to be started automatically.

So in my opinion it would be better if:

- when **File Centipede** exits the program terminates **filec.exe** process automatically;
- when **File Centipede** starts the program restarts **filec.exe** process automatically;

This will mean that **File Centipede** exits clearly- no processes are running in the background after program exit and that **File Centipede** automatically initiates the needed process **filec.exe** on restart without the need to manually launch it.

**Comment by filecxx** [comment]
This is designed on purpose, it keeps DHT network more stable, if every time run fileu then run filec, torrent engine will refresh DHT peers, join the DHT network, find active peers gonna take time, which means if you are downloading a magnet link, torrent engine search the magnet's torrent file from DHT peers will be slow,  however, if you wish to close filec.exe process, you can make a .bat file like this:

path/filec.exe stop

-----
filec.exe is also a command-line tool.

**Comment by filecxx** [comment]
"thousands of torrents", you must be running a porn site, how about I give you a custom version?

**Comment by smaragdus** [comment]
@filecxx 

No porn site- just many books from private trackers plus lots of music too.
