### ISSUE TITLE
软件提示 文件名太长，编程我不太懂，问题是下载时把保存文件名改短了也显示文件名太长拒绝下载，强烈建议你可以做一个长文件的链接试试，作者看看有没有办法能绕过去，毕竟idm可以做到下载

### ISSUE THREAD

**Issue by qwqw8673** [filecxx/FileCentipede#111]
例子：里程碑书系（各学科史上的250个里程碑事件！7门学科的简史！全球畅销百万册！）：生物学之书+数学之书+天文之书+化学之书+心理学之书+工程学之书+医学之书（套装7册） (吉姆·贝尔 [吉姆·贝尔]) (z-lib.org).epub
idm可以下载

**Comment by filecxx** [comment]
建议缩短文件名，这个不太可能会更改.

**Comment by flwwater** [comment]
> 建议缩短文件名，这个不太可能会更改.

能不能检测文件名长度，超出范围的用QString里的left(int n)函数截断文件名？

**Comment by filecxx** [comment]
程序逻辑处理没有用到Qt的任何部分，fileu只用了Qt的widgets，目前检测长度是按照字节计算的
`
if(path.u8string().size() >= 250){
        return errors::File_Name_Too_Long;
    }
`
windows下一个汉字(UTF8) 3个字节, 如果用unicode，1个汉字算一个字节，不过不打算为windows专门做unicode版本。
