### ISSUE TITLE
关于串流功能的一点小建议

### ISSUE THREAD

**Issue by zaobaocn** [filecxx/FileCentipede#113]
1. 希望支持边下边播。也就是下载视频片段之前先保存m3u8文件到本地，然后可以调用系统默认播放器打开m3u8文件。
2. 添加串流任务的界面希望能多一点选项，比如重命名，并行下载视频片段数目，是否需要合并视频片段。我试过下载过程中在任务栏重命名，但没有成功。
3. 有AES加密的m3u8不知道能不能自动连同密钥文件一起下载，密钥文件位置应该也在m3u8文件中吧

**Comment by zaobaocn** [comment]
> 设计时候考虑过这个问题，但实际场景中大部分的m3u8文件包含地址都是相对的地址 例如 dir/1 dir/2 dir/3
> 
> 需要拼合完整URL才能播放 http://xxxx.com/xxx/dir/1 http://xxxx.com/xxx/dir/2 http://xxxx.com/xxx/dir/3

既然是相对地址，那就并不需要拼接完整url了吧。用你给出的示例，假设视频地址为 http://xxxx.com/xxx/dir/index.m3u8 , 里面包含3个文件1，2，3。那么只要下载1，2，3，index.m3u8且将它们在同一个文件夹下，用视频播放器打开index.m3u8就会从当前文件夹查找1，2，3播放了。

**Comment by zaobaocn** [comment]
举个例子
![image](https://user-images.githubusercontent.com/100590418/161970443-da1b5b6b-4009-4205-8474-45ac1ddbaa36.png)

**Comment by filecxx** [comment]
你误解了，我只是举例子，实际上内容经常是这样的
path/data?id=1&session=xxx&expire=160123415
path/data?id=1&session=xxx&expire=160123451
.........

**Comment by filecxx** [comment]
典型的是pornhub
`
#EXTM3U
#EXT-X-TARGETDURATION:6
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:3.003,
seg-1-f1-v1-a1.ts?ttl=1649250676&l=0&clientip=52.175.21.52&ipa=52.175.21.52&hash=540df15ecf14ff86e761e5270aabb195
#EXTINF:6.006,
seg-2-f1-v1-a1.ts?ttl=1649250676&l=0&clientip=52.175.21.52&ipa=52.175.21.52&hash=540df15ecf14ff86e761e5270aabb195
#EXTINF:3.003,
seg-3-f1-v1-a1.ts?ttl=1649250676&l=0&clientip=52.175.21.52&ipa=52.175.21.52&hash=540df15ecf14ff86e761e5270aabb195
#EXTINF:3.003,
seg-4-f1-v1-a1.ts?ttl=1649250676&l=0&clientip=52.175.21.52&ipa=52.175.21.52&hash=540df15ecf14ff86e761e5270aabb195
`

**Comment by zaobaocn** [comment]
那可以重写一份本地m3u8索引文件的吧，我看FileCentipede串流的时候，是按顺序下载每个视频片段并重命名为1.ts , 2.ts, 3.ts、、、，只需要将源m3u8文件的里的每个视频片段的路径替换为1.ts, 2.ts, 3.ts、、、就行了吧

**Comment by zaobaocn** [comment]
那只需要稍稍等一下就好了呀，它基本上还是总体有序的，每个视频片段大小差不多。
另外，就像我上面说的一样，能够让用户自行选择并行下载视频片段数量，也就是连接数，要边播边下的时候，选2-5连接就差不多了，连接多了体验反而不好。只用一个连接下载体验也不好，退化到用视频播放器直接打开链接播放了，速度太慢，会卡顿。

**Comment by filecxx** [comment]
这个应该不是下载工具该做的，而属于播放器的功能。

**Comment by zaobaocn** [comment]
> 提议2中的选项没问题，可以添加.

那实现提议2中的自定义连接接数，添加是否自动合并视频片段选项就好了。选择不自动合并视频时，应该在本地保留一份m3u8索引文件的吧，让用户可以自己用ffmpeg之类的工具合并视频，或者用播放器播放。
实际上，有了自定义连接数和不自动合并视频片段，不就相当于能实现边下边播了嘛，只需要到文件下载目录打开m3u8文件即可。这是属于利用下载器的参数设置来实现用户自定义需求，就像arai2进行BT下载时可以设置优先下载头部和尾部以及顺序下载，这样设置就能边下边播视频文件了，而下载参数的自定义设置显然是下载工具要做的。

**Comment by filecxx** [comment]
有这个需求的用户非常罕见，我自己也没有这个需求，可能不会被当作最优先处理事项，如果你对这个功能需求比较紧急， 建议使用更专业的工具进行这个操作，或者提供付费支持，我将把这个功能设为优先事项。

**Comment by zaobaocn** [comment]
不紧急的，实际上我只是想把FileCentipede的功能都探索一遍，发现串流功能有点简陋且合并视频时电脑变的卡顿，然后提出的一点想法。我平时串流都是用的ffmpeg和mpv等，只是希望能多一个FileCentipede选择也不错。

**Comment by filecxx** [comment]
你提议中的功能在2.0中增加了一部分，其余部分如果有充足时间会再考虑下。
