### ISSUE TITLE
任务信息里只显示五个tracker在工作

### ISSUE THREAD

**Issue by callmejoo** [filecxx/FileCentipede#114]
![2022-04-06_18-19-05](https://user-images.githubusercontent.com/18390127/161953866-48a0f30b-9920-4eaf-b208-76f60cb56496.png)
![2022-04-06_18-19-14](https://user-images.githubusercontent.com/18390127/161953937-a457294e-04a0-49a6-9629-db9ffb668af7.png)
我订阅了上百个tracker，他是随机选了五个吗还是其实都在工作只是没显示？

**Comment by filecxx** [comment]
这5个是种子里自带的，如果你希望将订阅的添加进任务，你需要这样设置
![image](https://user-images.githubusercontent.com/100348948/161957479-e1010bdf-fb4e-4982-8e51-41fc94efb8d9.png)

另外如果种子带有tracker 那么你没有必要添加，太多的tracker会导致种子文件变得非常大

**tracker不会提升速度如果只有你自己有这些tracker**

**Comment by filecxx** [comment]
如果你的任务里包含了一个tracker地址，别人的任务里也包含了这个地址，那么你们可以相互通过这个tracker服务器找到对方，如果你有这个地址，对方没有，那么这个tracker没有任何效果，反而是累赘。

**Comment by callmejoo** [comment]
> 这5个是种子里自带的，如果你希望将订阅的添加进任务，你需要这样设置 ![image](https://user-images.githubusercontent.com/100348948/161957479-e1010bdf-fb4e-4982-8e51-41fc94efb8d9.png)
> 
> 另外如果种子带有tracker 那么你没有必要添加，太多的tracker会导致种子文件变得非常大
> 
> **tracker不会提升速度如果只有你自己有这些tracker**
