### ISSUE TITLE
关于tracker的问题反馈

### ISSUE THREAD

**Issue by Waradise** [filecxx/FileCentipede#115]
大神好,目前使用中发现tracker只能更新列表,无法自动添加到新任务上去,需要手动复制列表到"自动添加到任务"栏目里面才行,不知道是不是我操作有问题,希望大神指点~

**Comment by zaobaocn** [comment]
![image](https://user-images.githubusercontent.com/100590418/161984316-871b090c-19ca-435b-b003-d312b1cc248f.png)
我这里也是诶，即使勾选了包含下载，结果还是没包含下载列表

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/issues/114

**Comment by filecxx** [comment]
> 

已经包含了，只是顺序不一样，你检查图片

**Comment by ccavbus** [comment]
> > 
> 
> 已经包含了，只是顺序不一样，你检查图片

![image](https://user-images.githubusercontent.com/72659189/162031434-362a270c-74c8-4d7a-b314-fdf33cfde8e2.png)
![image](https://user-images.githubusercontent.com/72659189/162031439-8c96b164-7d2b-4b21-8e37-e8db10d3a693.png)只包含了任务框手动添加的两个而已，没有包含下载列表，下载列表有几十个tracker的

**Comment by zaobaocn** [comment]
![image](https://user-images.githubusercontent.com/100590418/162033164-6007ae50-9dba-48dd-bea2-fe9e0417a78b.png)

![image](https://user-images.githubusercontent.com/100590418/162033108-8cd483af-65bb-4391-b20f-8ade9e7baa12.png)

下载列表有几十个个tracker的，实际上添加的只任务框里的两个

**Comment by filecxx** [comment]
是的，这就是为什么名字一个叫做 “列表” ，而另一个叫做 “自动添加到新任务”  的原因。
如果这2个名字反过来，那么就是程序的BUG导致没有添加到新任务。

**Comment by Waradise** [comment]
那大神是否可以将列表和自动添加新任务合一，这样自动更新完列表后就不用每次复制粘贴这么麻烦了，辛苦大神

**Comment by din1028** [comment]
![20220412000318](https://user-images.githubusercontent.com/97040926/162782886-60a8c07c-f2ab-47b8-b4d5-2205071f4ab8.jpg)
红框里的选项意义是什么？

如果是指将订阅下载的追踪器也添加进新任务，那么该选项显然是失灵的。

**Comment by filecxx** [comment]
> ![20220412000318](https://user-images.githubusercontent.com/97040926/162782886-60a8c07c-f2ab-47b8-b4d5-2205071f4ab8.jpg) 红框里的选项意义是什么？
> 
> 如果是指将订阅下载的追踪器也添加进新任务，那么该选项显然是失灵的。

https://github.com/filecxx/FileCentipede/issues/4
https://github.com/filecxx/FileCentipede/issues/114

所有提交有关tracker issue 的，似乎都不明白tracker真正的作用，或者错误理解为了tracker是用于加速的，确实有必要对此写一个文档。

**Comment by din1028** [comment]
你的意思是，这个追踪器，只是在发布BT任务以及下载BT任务（红框部分设置）时添加？
那么订阅功能又是为了做什么？只是为了用户省下打开网页的功夫，方便复制粘贴吗？
我当然知道tracker不是为了下载所用，但是通过tracker可以发现更多同时在下载该任务的用户，它当然也有加速的意义在里面。

**Comment by filecxx** [comment]
> 你的意思是，这个追踪器，只是在发布BT任务以及下载BT任务（红框部分设置）时添加？ 那么订阅功能又是为了做什么？只是为了用户省下打开网页的功夫，方便复制粘贴吗？ 我当然知道tracker不是为了下载所用，但是通过tracker可以发现更多同时在下载该任务的用户，它当然也有加速的意义在里面。

是的，为了方便用户打开网页。

如果自动将订阅列表添加进任务，假设任务列表有1000条， 那么每个任务都会保存这个列表，并且每个任务每隔几分钟都会向列表中的tracker发送数据，如果有1000个任务，那么数据库会非常大，并且会消耗很大的额外宽带。

如果超过1000万个用户都在所有任务中添加了这个列表，那么这会起到对tracker服务器DDOS的作用，所有tracker服务器都会死掉。

**Comment by doubinanberwan** [comment]
> 

原来如此，明白了

**Comment by doubinanberwan** [comment]
> > 你的意思是，这个追踪器，只是在发布BT任务以及下载BT任务（红框部分设置）时添加？ 那么订阅功能又是为了做什么？只是为了用户省下打开网页的功夫，方便复制粘贴吗？ 我当然知道tracker不是为了下载所用，但是通过tracker可以发现更多同时在下载该任务的用户，它当然也有加速的意义在里面。
> 
> 是的，为了方便用户打开网页。
> 
> 如果自动将订阅列表添加进任务，假设任务列表有1000条， 那么每个任务都会保存这个列表，并且每个任务每隔几分钟都会向列表中的tracker发送数据，如果有1000个任务，那么数据库会非常大，并且会消耗很大的额外宽带。
> 
> 如果超过1000万个用户都在所有任务中添加了这个列表，那么这会起到对tracker服务器DDOS的作用，所有tracker服务器都会死掉。

明白了
