### ISSUE TITLE
关于远程访问的咨询

### ISSUE THREAD

**Issue by Waradise** [filecxx/FileCentipede#119]
软件中有远程访问的设置，也有端口和密码的设置，但是我在局域网中另一台机器上应该怎么关联客户端呢？像QDOWN可以通过RPC直接关联，支持远程下载和控制，咱这个软件应该什么关联？请大神指点~最好是使用本客户端那种，不是网页端那种，网页端感觉很多功能不全面

**Comment by filecxx** [comment]
这一块功能还没有设计完，只做了一半，所以目前用不了。

**Comment by Waradise** [comment]
收到，辛苦大神，期待后续更新，大神能透露下大体啥时候不？哈哈

**Comment by filecxx** [comment]
还不确定什么时候，实际上后端已经可以通过tcp连接进行交互了，前端还没有做，应该在3.0左右。

**Comment by noxman** [comment]
tcp连接进行交互，怎样操作，有示例代码吗？

**Comment by filecxx** [comment]
> tcp连接进行交互，怎样操作，有示例代码吗？

连接到端口10111发送json字符串，例如 {"@":"task_add","uri":"http://filecxx.com"}
http://www.filecxx.com/zh_CN/documentation/create_address.html#json_fields

TCP目前可以发送数据到filec，但是不会有任何数据回复（未制作），浏览器扩展里目前是这样通信的。

**Comment by noxman** [comment]
> > tcp连接进行交互，怎样操作，有示例代码吗？
> 
> 连接到端口10111发送json字符串，例如 {"@":"task_add","uri":"[http://filecxx.com"}](http://filecxx.com%22%7D) http://www.filecxx.com/zh_CN/documentation/create_address.html#json_fields
> 
> TCP目前可以发送数据到filec，但是不会有任何数据回复（未制作），浏览器扩展里目前是这样通信的。

了解了

**Comment by noxman** [comment]
json字符串中能否再增加一些东西，例如filesize，referer

**Comment by filecxx** [comment]
Ext_Structure_initialize(config,attr.variants,(user_agent)(cookies)(headers))
Ext_Structure_initialize(config,attr,
    (mode)(state)(error)(finished)(uri)(method)(catalog)(proxy)(proxy_mode)(save_path)
    (resid)(page_url)(content_type)(data)(connect_timeout)(resumable)
    (max_connections)(max_redirect)(max_retry)(attr_last_modified)(parallel)
    (file_ready)(file_size)(file_name)(progress)(downloaded)
    (speed_limit_download)(speed_limit_upload)
    (auto_rename_file)(ignore_remote_modified)(ignore_server_busy)(ignore_http_error)(without_confirm)(confirmed)
    (etag)(last_modified)(time_create)(time_start)(time_end)
)
filesize 会自动从服务器获取，如果是上传文件，会读取本地文件大小，所以无法手动设置，referer需要放headers 里 Referer: http://yoursite.com

**Comment by filecxx** [comment]
实际上file_size 可以设置, 不过没有任何意义，只是可以在服务器返回数据之前在客户端里显示大小.

**Comment by filecxx** [comment]
> 收到，辛苦大神，期待后续更新，大神能透露下大体啥时候不？哈哈

正在制作这个功能，远程下载功能完全复用当前的界面，唯一区别是使用设置中的端口10111连接，每个主机可以创建单独的快捷方式
![image](https://user-images.githubusercontent.com/100348948/184653532-6736939a-a1c6-457b-b5fb-9b0a96bbfdd9.png)
![image](https://user-images.githubusercontent.com/100348948/184653559-8d377730-be3f-4b61-b0f7-d1166552d39f.png)

还有其他需求吗？预计2.6版本这个功能可以上线。

**Comment by filecxx** [comment]
2.6已经增加了该功能
