### ISSUE TITLE
Microsoft Edge 商店安装不了?

### ISSUE THREAD

**Issue by AUENDXYZ** [filecxx/FileCentipede#120]
Edge 商店中的文件蜈蚣插件安装不了,请及时更新和修复.谢谢!

**Comment by filecxx** [comment]
是从
https://microsoftedge.microsoft.com/addons/detail/jeekmibdibcjeihbjnjgbegjalfelhon
这个地址安装的吗

**Comment by filecxx** [comment]
有没有提示什么错误

**Comment by AUENDXYZ** [comment]
> https://microsoftedge.microsoft.com/addons/detail/jeekmibdibcjeihbjnjgbegjalfelhon
> 这个地址安装的吗

刚才从你提供的这个地址安装, 可以成功安装了. 谢谢!
