### ISSUE TITLE
[feature request]浏览器扩展加入排除名单

### ISSUE THREAD

**Issue by sino1641** [filecxx/FileCentipede#121]
RT, 目前GUI客户端内和文档都没有找到相应的设置项和介绍。
例如希望排除b站(`https://www.bilibili.com/video/*`)视频播放页或者所有网页的`.ts`文件。

**Comment by filecxx** [comment]
可以在浏览器扩展内勾选忽略此站

**Comment by sino1641** [comment]
> 可以在浏览器扩展内勾选忽略此站

点开扩展就看到了~感谢回复
（也希望相关文档可以完善，至少浏览器扩展标题下的截图可以更新）
