### ISSUE TITLE
IEEE上下载论文，得到的是jsp格式，用edge下载是正常的pdf文件

### ISSUE THREAD

**Issue by liuchang1002** [filecxx/FileCentipede#122]

**Comment by filecxx** [comment]
能提供个测试地址吗？

**Comment by liuchang1002** [comment]
https://ieeexplore-ieee-org-s.vpn.seu.edu.cn:8118/stampPDF/getPDF.jsp?tp=&arnumber=9047319&ref=aHR0cHM6Ly9pZWVleHBsb3JlLmllZWUub3JnL2RvY3VtZW50LzkwNDczMTk=
这是用校园网下的论文，我不知道你那边能不能用

**Comment by filecxx** [comment]
我访问不了，暂时可能没办法，不过我会尽可能找找原因

**Comment by liuchang1002** [comment]
谢谢你的开源软件，绝大多数时候都很好用的。
