### ISSUE TITLE
torrent DHT一直显示0

### ISSUE THREAD

**Issue by jorismq** [filecxx/FileCentipede#123]
磁力也一直显示“下载元数据”

**Comment by filecxx** [comment]
大概率是防火墙原因，可以尝试下载几个热门种子，让DHT刷新

**Comment by jorismq** [comment]
我没有开防火墙
我发现要手动停止filec这个进程，再重新打开就可以了
磁力也能解析了

**Comment by zzcbun** [comment]
> 我没有开防火墙 我发现要手动停止filec这个进程，再重新打开就可以了 磁力也能解析了

谢谢，我也是通过你说的方法暂时解决了这个问题

**Comment by login404** [comment]
开机自启时如果未联网
DHT之后都会很难连上
但手动重启filec.exe后
用重启前几分钟都连上不的相同磁链测试
不到1分钟就能连上DHT

**Comment by filecxx** [comment]
> 开机自启时如果未联网 DHT之后都会很难连上 但手动重启filec.exe后 用重启前几分钟都连不上的相同磁链测试 不到1分钟就能连上DHT

该问题已经在2.3中解决，不需要手动启动，为0之后如果持续30秒会自动恢复。
