### ISSUE TITLE
请问这个错误该如何修复？打开就是这个提示

### ISSUE THREAD

**Issue by qq528933** [filecxx/FileCentipede#124]
最新版本在Win10环境下，打开就出现错误提示，重新下载安装后依旧如此，请问该如何解决？问题如图所示。[https://i.postimg.cc/MHQpz9XN/QQ-20220408223741.png](url)
[https://i.postimg.cc/L8Rz5bLz/QQ-20220408223803.png](url)

**Comment by filecxx** [comment]
尝试任务管理器结束filec.exe 然后重新打开软件，这个是windows共享内存读取失败造成的，理论上不太可能失败，是否有其他进程阻止了程序读写共享内存？

以前是否成功运行过

**Comment by filecxx** [comment]
另外重启电脑也会自动重置共享内存，应该可能解决这个问题，除非环境比较特殊，权限受到限制。

**Comment by qq528933** [comment]
> 尝试任务管理器结束filec.exe 然后重新打开软件，这个是windows共享内存读取失败造成的，理论上不太可能失败，是否有其他进程阻止了程序读写共享内存？
> 
> 以前是否成功运行过

以前成功运行过，后来关机后第二天在开机打开软件就成这样了

**Comment by filecxx** [comment]
按照上面的方法，应该可以解决问题。

**Comment by qq528933** [comment]
> 按照上面的方法，应该可以解决问题。

按照大佬的方法竟然好了，十分感谢~

**Comment by qq528933** [comment]
> 按照上面的方法，应该可以解决问题。

大佬有好用的tracker网址吗？

**Comment by filecxx** [comment]
https://github.com/XIU2/TrackersListCollection

**Comment by qq528933** [comment]
> https://github.com/XIU2/TrackersListCollection

我是第一次用大佬的软件，请问有什么优化建议吗？

**Comment by filecxx** [comment]
没

**Comment by qq528933** [comment]
> 没

十分感谢大佬，还希望大佬能更新下国内的捐助方式，我也想尽下绵薄之力

**Comment by filecxx** [comment]
暂时还没有中国地区的相关帐号，待2.0版本发布之后一些信息都会逐渐完善，非常感谢。
