### ISSUE TITLE
开启Adguard高级设置里的：过滤localhost连接 导致浏览器插件下载不能把下载任务推送到软件里

### ISSUE THREAD

**Issue by wanghaozone** [filecxx/FileCentipede#125]
是这样的 平时用clash的时候，如果不打开Adguard 的 过滤localhost连接 功能，就会导致过滤广告失效，就是clash和Adguard同时用，就需要开启这个，但是开启了这个选项又会导致文件蜈蚣的浏览器插件不能把下载推送到文件蜈蚣里，点下载还是浏览器自带的，点视频嗅探下载，完全没反应，怎么解决呢，如果能解决这个问题，可以替代IDM来用了。

**Comment by filecxx** [comment]
这个无法解决

要么关闭localhost过滤，或者将广告过滤扩展换成ABP

https://github.com/filecxx/FileCentipede/issues/23

**Comment by filecxx** [comment]
建议反馈到 "adguard for windows" 社区,

**Comment by wanghaozone** [comment]
好的 IDM迅雷的唤起没问题 ，是用的不同的推送机制吗

**Comment by filecxx** [comment]
IDM是使用参数方式启动本地进程, File Centipede 是用HTTP协议 FILEC 头发送给filec进程, 实际上如果过滤了localhost, 任何依赖于发送给本地端口的浏览器扩展都无法使用，包括aric2等.

**Comment by filecxx** [comment]
另外，如果修改了这个启动方式，浏览器扩展中的下载全部功能可能会失效，因为如果链接过多，可能到几MB时，使用进程参数方式启动进程无法接受这么多数据。

**Comment by wanghaozone** [comment]
我试了百度网盘的 油猴下载脚本 能推送下载到Aria2呢。。。

**Comment by filecxx** [comment]
那个脚本走的应该不是JSON RPC 而是进程调用。

**Comment by wanghaozone** [comment]
原来如此 感谢解答 那我目前用的路由插件版clash不需要用电脑端clash，可关掉localhost过滤，不过要是能增加进程调用来唤起作为可选选项就好了！

**Comment by filecxx** [comment]
如果该软件与其他软件产生的冲突，属于BUG，会修复，但这个不是，对此修改会毫无意义，你把问题反馈到 “adguard” 会更有效果。

**Comment by iptvsyx** [comment]
可以使用 uBlock Origin 解决

**Comment by xaoyao** [comment]
需要开启过滤localhost的话加一条规则就可以了
<img width="760" alt="屏幕截图" src="https://user-images.githubusercontent.com/12218604/163158007-f437ebba-ad23-4ac3-961a-0b47aabdd94d.png">
