### ISSUE TITLE
Header的Host未生效

### ISSUE THREAD

**Issue by mogumc** [filecxx/FileCentipede#126]
无法定义Header中的host

**Comment by mogumc** [comment]
添加后并未生效

**Comment by filecxx** [comment]
是的，host port会从url 域名中提取，accept-encoding 也会自动设置，我不太明白你为什么有这样的需求.

**Comment by mogumc** [comment]
> 是的，host port会从url 域名中提取，accept-encoding 也会自动设置，我不太明白你为什么有这样的需求.

部分网站可用通过修改ip提升下载速度 但是同时也有域名鉴权限制 所以需要伪造host访问服务器

**Comment by filecxx** [comment]
2.0 版本中尽量取消这个限制。

**Comment by mogumc** [comment]
> 2.0 版本中尽量取消这个限制。

感谢

**Comment by filecxx** [comment]
2.0现在可以添加了，不过注意是 Host 而非 host
