### ISSUE TITLE
请问，能否支持windows X86？

### ISSUE THREAD

**Issue by zzcbun** [filecxx/FileCentipede#127]
有幸能体验到大佬的这款软件！太好用了！想问下Windows 32位操作系统有开发的意向吗？期待您的回复！

**Comment by filecxx** [comment]
如果要支持32位系统，整个程序包括底层库可能都会重写，工程量非常大，特别是底层库如果重写至少要1年时间，所以可能不会支持32位。

**Comment by zzcbun** [comment]
> 如果要支持32位系统，整个程序包括底层库可能都会重写，工程量非常大，特别是底层库如果重写至少要1年时间，所以可能不会支持32位。

Ok，明白了，工作量如此巨大，而且浪费时间，重写了意义不大，32位的系统也将面临被淘汰的事实，有这个时间完全可以把现在的版本打磨的更好，期待文件蜈蚣的新功能和ed2k的支持！
