### ISSUE TITLE
同一网站下部分视频没有解析出来

### ISSUE THREAD

**Issue by zzugyl** [filecxx/FileCentipede#128]
chrome插件v1.4版本。filec是在ubuntu20.04下使用。
1、我在下面的网站下载视频，第一集和第二集，有下载提示。第三集没有。
对比用其他解析软件，三集都能解析下载。
2、下载到98%，下载不动。只能关闭，再次开始。其他网站也遇到过。
网站 http://www.xdyao.com/oumeiju/guanghuan_diyiji/video-1-2.html
![2022-04-09_21-13](https://user-images.githubusercontent.com/27466768/162576015-cdfe2d44-c01d-4c53-ba35-783e2f4369cf.png)
![2022-04-09_21-26](https://user-images.githubusercontent.com/27466768/162576062-df8fdb30-9cbd-4180-9c5f-c4205856d704.png)

**Comment by filecxx** [comment]
我测试这个地址没问题，可以看看右上角小图标窗口列表里有对应视频没有。
另外，98%时候下载不会再继续增加新连接，剩余的1个连接可能速度非常慢，只能暂停恢复，目前没有好的应对方式。

**Comment by zzugyl** [comment]
我录制了一个视频，你看一下，我这里确实不一样。第三集没有，换第二集，就解析到地址了。
https://user-images.githubusercontent.com/27466768/162598631-9af583df-fcd7-4b49-8ef9-93e4d6aab498.mp4

**Comment by filecxx** [comment]
我按照你的流程重复了一遍，我这里没问题，很可能是被缓存了导致没捕捉到，也可能是其他原因，我会在2.0完成之前持续关注的。
