### ISSUE TITLE
建议编辑配置中增加编辑下载地址功能

### ISSUE THREAD

**Issue by player0898** [filecxx/FileCentipede#130]
部分网站下载一半失效了，点击刷新地址仍然是地址已经过期。
如果从原网站再次直接点击下载的话则会建立一个新的下载任务。
建议增加一个手动编辑下载地址的功能，可以把生成的新任务的下载地址替换到旧任务中

**Comment by filecxx** [comment]
目前只有视频能够刷新地址。
编辑下载地址确定添加（之前已经添加，之后删掉了）

**Comment by wsndjm2** [comment]
刚才也遇到了这种情况，下载到一般地址已过期，刷新地址没用，希望修复
