### ISSUE TITLE
几个BUG上报

### ISSUE THREAD

**Issue by Waradise** [filecxx/FileCentipede#132]
(一)客户端长时间挂着,时间久了就不刷新进度了,其实在资源管理器中查看进程还在下载中,重启客户端就又恢复现实了,经过观察,不管是最小化到通知栏,还是一直让软件前台显示都这样;
(二)长时间挂机下载,它会崩溃,需要重启才能恢复,这个问题很困扰,因为我是一个WIN7的自建NAS,基本不关机,基本就是一直在下载东西,一天也就远程控制几次,不知道它什么时候就崩溃了,下载也就暂停了,很影响使用体验;
辛苦大神关注下~

**Comment by Waradise** [comment]
(一)客户端长时间挂着,时间久了就不刷新进度了,其实在资源管理器中查看进程还在下载中,重启客户端就又恢复现实了,经过观察,不管是最小化到通知栏,还是一直让软件前台显示都这样;
问题一显示有问题

**Comment by filecxx** [comment]
好的，这个争取下个版本修复

**Comment by filecxx** [comment]
至于崩溃，很可能是和你之前提到的内存溢出问题导致的，还有就是一个已知问题，突然断网导致程序崩溃，这2个BUG目前是重点。

**Comment by i990049** [comment]
长时间挂机下载还是选那些已经成熟的客户端，Qbittorrent，xdown，motrix这些，毕竟这些都发展了一段时间，就算有bug也早就被别人修复了

**Comment by sino1641** [comment]
@filecxx 
> 还有就是一个已知问题，突然断网导致程序崩溃

win端的个人体验是，从休眠或长时间锁屏恢复会导致出现等待filec的弹窗，请问是否是该原因导致

**Comment by filecxx** [comment]
> @filecxx
> 
> > 还有就是一个已知问题，突然断网导致程序崩溃
> 
> win端的个人体验是，从休眠或长时间锁屏恢复会导致出现等待filec的弹窗，请问是否是该原因导致

是的，这个问题会在2.0版本中修复

**Comment by filecxx** [comment]
这个问题应该已经修复了。
