### ISSUE TITLE
改变标签位置和大小，重启软件后会恢复默认

### ISSUE THREAD

**Issue by hosxy** [filecxx/FileCentipede#133]
如图，改变这一栏标签的位置和大小，重启软件后又会变成默认
![图片](https://user-images.githubusercontent.com/17108640/162599557-29b27da1-eaca-420b-9d19-e683a78b3e30.png)

**Comment by deranged11** [comment]
对，我也这样，每次启动都会恢复默认

**Comment by filecxx** [comment]
column目前还不能保存大小。

**Comment by filecxx** [comment]
2.5可以保存column大小

**Comment by deranged11** [comment]
永久激活码需要怎么获取？以公司名义需要提供什么资料？

                                                   
 
发件人： filecxx
发送时间： 2022-08-13 20:57
收件人： filecxx/FileCentipede
抄送： deranged11; Comment
主题： Re: [filecxx/FileCentipede] 改变标签位置和大小，重启软件后会恢复默认 (Issue #133)
2.5可以保存column大小
―
