### ISSUE TITLE
希望增加设置项

### ISSUE THREAD

**Issue by deranged11** [filecxx/FileCentipede#134]
我是把下载软件作为文件管理用的，有些下载的文件要删除需要多点一下删除文件，能不能在设置里面增加选项直接删除任务和文件

**Comment by filecxx** [comment]
不显示提示，直接删除吗？鉴于这个功能非常容易实现，会加一个选项。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/182141757-7edde744-965f-4b14-b8e7-5243fa450cf3.png)
