### ISSUE TITLE
重复弹出下载窗口的BUG

### ISSUE THREAD

**Issue by Leao9203** [filecxx/FileCentipede#136]
在下载一些东西的时候，如果把文件蜈蚣关闭掉，再启动就有可能导致重复弹出下载的窗口。

有时候重启电脑之后，也可能会弹出下载确认窗口。

![image](https://user-images.githubusercontent.com/45661339/162601389-bed0fde3-0b46-44a2-acfe-04fea105f09a.png)

该文件的下载链接：https://mega.nz/MEGAsyncSetup64.exe

**Comment by Leao9203** [comment]
这个文件之前是通过浏览器调用下载过，重启电脑之后就再次弹出了一个下载确认窗口。

浏览器为 Edge浏览器，版本 100.0.1185.36 (正式版本) (64 位)
插件为 文件蜈蚣 版本1.4，通过加载解压缩的扩展方式安装的

**Comment by filecxx** [comment]
目前设置是这样的，如果不取消或者确定，这个任务会一直存在。

**Comment by Leao9203** [comment]
> 目前设置是这样的，如果不取消或者确定，这个任务会一直存在。

不是，这个文件我已经下载过一次了，并且下载完之后已经删除了。但是重启电脑之后，在没有打开浏览器的情况下，依然弹出了下载确认窗口。

**Comment by Leao9203** [comment]
![image](https://user-images.githubusercontent.com/45661339/162601599-d71d8449-c907-4907-bae8-9339e8fe79fb.png)

有可能是 Edge  浏览器的 `在 Microsoft Edge 关闭后继续运行后台扩展和应用` 影响的吗

**Comment by filecxx** [comment]
有可能，如果这个地址再次被访问了一次，会再次添加任务，或者上次打开了这个下载地址，再次启动浏览器时候恢复了之前关闭的标签导致再次添加这个任务。

**Comment by Leao9203** [comment]
> 有可能，如果这个地址再次被访问了一次，会再次添加任务，或者上次打开了这个下载地址，再次启动浏览器时候恢复了之前关闭的标签导致再次添加这个任务。

怀疑是 `启动增强` 或者 `在 Microsoft Edge 关闭后继续运行后台扩展和应用` 导致的问题，我把这两个功能关闭再看看
