### ISSUE TITLE
如何禁止后台驻留进程filec.exe

### ISSUE THREAD

**Issue by SailFlorve** [filecxx/FileCentipede#138]
我希望使用的时候打开，不用就关闭，但是关闭后后台驻留进程filec.exe，如何阻止这一情况？

**Comment by filecxx** [comment]
写一个批处理
路径/filec.exe -n

**Comment by filecxx** [comment]
关闭后再次启动filec的时候，会重新加入DHT网络，在DHT刷新完成之前，磁力下载可能会非常慢。

**Comment by SailFlorve** [comment]
> 写一个批处理 路径/filec.exe -n

 有效，但是可以在软件设置中加入一个选项嘛

**Comment by filecxx** [comment]
> > 写一个批处理 路径/filec.exe -n
> 
> 有效，但是可以在软件设置中加入一个选项嘛

可以考虑。

**Comment by filecxx** [comment]
2.82
![image](https://user-images.githubusercontent.com/100348948/216927737-036d5048-425f-41fa-8c0a-c8915aecec6d.png)
