### ISSUE TITLE
请教一下 我用mac m1 编译这个需要怎么做的 

### ISSUE THREAD

**Issue by zyxlcr** [filecxx/FileCentipede#139]
请教一下 我用mac m1 编译这个需要怎么做的

**Comment by filecxx** [comment]
当前版本不支持mac ,如果需要在mac上使用，目前只能使用wine模拟

**Comment by zyxlcr** [comment]
> 当前版本不支持mac ,如果需要在mac上使用，目前只能使用wine模拟

哦哦,感谢回复
