### ISSUE TITLE
After the installation is complete, open the prompt: filec is not started

### ISSUE THREAD

**Issue by imzhengziyi** [filecxx/FileCentipede#14]
安装完成后，打开提示：filec未启动，手动双击打开安装目录filec文件依然不能解决
After the installation is complete, open the prompt: filec is not started,Manually double-clicking to open the filec file in the installation directory still cannot solve the problem

**Comment by imzhengziyi** [comment]
System is Windows 10 64 bit

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/158034371-af2a33f8-cd93-4028-b064-06ff70f5dbe2.png)
点击按钮 "启动", 或者 运行命令行 "filec.exe start"

![image](https://user-images.githubusercontent.com/100348948/158034305-babb9620-96bf-4215-9227-55b0ed7ffaac.png)
Click the button "Launch", or run the command line "filec.exe start"

**Comment by yanxi808** [comment]
![158034371-af2a33f8-cd93-4028-b064-06ff70f5dbe2](https://user-images.githubusercontent.com/101092058/158051330-5e2adfb2-036a-4c1f-8c48-8188c7d26025.jpg)
切换到超级用户打开，再点启动就可以了

**Comment by winq2008** [comment]
对，在linux下，也是同样的问题。 并且还报selinux错误。所在fedora 35下测式。是要sudo ./filec -y  才行
还有就是我这磁力链打开，一直在下载元数据。一直停在这，试过其他链接都一样。
我用aria2c 下载就没有这个问题。

**Comment by filecxx** [comment]
> 对，在linux下，也是同样的问题。 并且还报selinux错误。所在fedora 35下测式。是要sudo ./filec -y 才行 还有就是我这磁力链打开，一直在下载元数据。一直停在这，试过其他链接都一样。 我用aria2c 下载就没有这个问题。

你执行 pkexec 是否能成功.

磁力链打开，一直在下载元数据, 这个要么是被防火墙拦截了, 要么是第一次运行DHT网络还未刷新完成, 可以尝试下载个BT任务让DHT网络找到peer

**Comment by imzhengziyi** [comment]
尝试过使用管理员权限运行，点击启动也是没有效果，还是一样的问题，

**Comment by filecxx** [comment]
> 尝试过使用管理员权限运行，点击启动也是没有效果，还是一样的问题，

你是不是用的Win10 家庭版？

**Comment by filecxx** [comment]
> 尝试过使用管理员权限运行，点击启动也是没有效果，还是一样的问题，

![image](https://user-images.githubusercontent.com/100348948/158355171-3689aa1f-5391-4465-a1b7-afe0cab32504.png)

是否能看见这个错误

**Comment by yanxi808** [comment]
能




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecxx/FileCentipede"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecxx/FileCentipede] After the installation is complete, open the prompt: filec is not started (Issue #14)





  
尝试过使用管理员权限运行，点击启动也是没有效果，还是一样的问题，
  

 
是否能看见这个错误
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by filecxx** [comment]
我正在修复这个问题、

**Comment by yanxi808** [comment]
等待你的完善


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecxx/FileCentipede"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 晚上6:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecxx/FileCentipede] After the installation is complete, open the prompt: filec is not started (Issue #14)





 
我正在修复这个问题、
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by filecxx** [comment]
我下载几个几个不同版本的WIN10, 测试并没有出现这个问题, 能否提供你们的邮箱, 我发调试版本给你们, 方便我能具体找出出错位置.

**Comment by yanxi808** [comment]
***@***.***


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecxx/FileCentipede"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 晚上8:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecxx/FileCentipede] After the installation is complete, open the prompt: filec is not started (Issue #14)





 
我下载几个几个不同版本的WIN10, 测试并没有出现这个问题, 能否提供你们的邮箱, 我发调试版本给你们, 方便我能具体找出出错位置.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanxi808** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecxx/FileCentipede"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 晚上8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecxx/FileCentipede] After the installation is complete, open the prompt: filec is not started (Issue #14)





 
我看到的是  @.***
 可能被过滤了，邮箱尝试截图试试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by filecxx** [comment]
还是看不到， 发这种格式吧，用户名 域名 点 C O M

**Comment by filecxx** [comment]
遇到这个问题，尝试使用本地英文用户名登陆，问题正在修复。。

**Comment by filecxx** [comment]
Fixed in 1.2

**Comment by imzhengziyi** [comment]
确实是区域非美国，或者语言的问题，已经解决
