### ISSUE TITLE
没有下载任务,这个网络占用正常吗

### ISSUE THREAD

**Issue by xxx975** [filecxx/FileCentipede#142]
![Lily_2022年04月12日16时11分04秒](https://user-images.githubusercontent.com/19317570/162913889-78eb1f2d-e08f-4a95-a9b4-76d509e21f5e.png)

**Comment by filecxx** [comment]
你可以抓包，这个是DHT网络刷新

**Comment by filecxx** [comment]
你无法禁用DHT和PEX, 如果使用这个软件，不能成为分布式网络的一部分为其他用户提供磁力链接的BT种子储存，那么属于0贡献，那么对生态环境将会毫无益处。

**Comment by filecxx** [comment]
程序不会扫描你的硬盘，更不会上传非BT任务的文件数据。

另外，可以尝试用这个工具捕捉程序的行为
https://docs.microsoft.com/zh-cn/sysinternals/downloads/procmon

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/162981223-7a4a031f-4eab-4f87-ab1c-1c14bb5151fb.png)
