### ISSUE TITLE
反馈一个bug

### ISSUE THREAD

**Issue by fengguowudi** [filecxx/FileCentipede#143]
浏览器托管时，要是下载微信传输的文件，会导致软件无限卡死重启。
https://filehelper.weixin.qq.com/

**Comment by filecxx** [comment]
是否可以提供一下操作流程。

是否已经成功发送到下载列表中？

或者提供一个地址
![image](https://user-images.githubusercontent.com/100348948/162973827-98f30723-1edb-4506-b55a-acefc4ab8cdc.png)

**Comment by fengguowudi** [comment]
这个下载地址是临时的

**Comment by filecxx** [comment]
这个问题用2.0版本再测试下，应该不会再出问题。
