### ISSUE TITLE
下载文件无法自动分类

### ISSUE THREAD

**Issue by yuntz8** [filecxx/FileCentipede#144]
已经设置好了自动文件分类，取消了勾选记住上次位置，但每次下载还是都要重新选择一遍文件分类

**Comment by filecxx** [comment]
匹配创建时间或者匹配文件扩展名任意一个勾选了才会自动设置分类

**Comment by filecxx** [comment]
不太可能，肯定哪里设置错了，当任务状态变为下载中的时候，会自动设置分类。

**Comment by yuntz8** [comment]
我是在添加任务时看到没有自动分类。然后尝试了下载，可以自动分类。谢谢！
