### ISSUE TITLE
批量下载文件的时候程序崩溃

### ISSUE THREAD

**Issue by asd0109** [filecxx/FileCentipede#145]
文件蜈蚣 1.9版本

网址    https://www.kugou.com/ts/album/50676851/p1-1.html

下载方式点击浏览器插件中的复制，文件蜈蚣自动打开。
![1649837623(1)](https://user-images.githubusercontent.com/37428027/163131558-3070a312-ec1d-46b1-90ad-56779bacb556.png)

下载过程中程序崩溃   点什么都退出程序
![1649837442(1)](https://user-images.githubusercontent.com/37428027/163131657-73922871-a09c-49d6-be34-f54fc927e8c8.png)

**Comment by asd0109** [comment]
感觉是相同大小的文件在同时下载完成后触发了程序崩溃

**Comment by filecxx** [comment]
崩溃之后是否还能启动

**Comment by filecxx** [comment]
程序崩溃是最严重BUG中排行第二的，属于必须解决的问题，最近工作量特别大，如果可以启动就暂时不发布修复版本，在2.0发布之前解决。

**Comment by asd0109** [comment]
刚才又试了一下，这个问题可以复现。当下载完成弹出启动界面的时候点击启动，程序会重新下载文件，只要在这次下载中批量文件不是同时下载完，程序就不会崩。

**Comment by filecxx** [comment]
好的

**Comment by filecxx** [comment]
我没有测试出这个问题，不过确实修复了可能导致类似问题的潜在BUG，新版本应该不会再有这个问题，如果还存在请继续反馈。
