### ISSUE TITLE
mega网盘跟浏览器扩展冲突

### ISSUE THREAD

**Issue by hunkdl** [filecxx/FileCentipede#146]
浏览器是edge
mega跟国内的城通网盘都是网页内传输下载完成后弹出下载完成的文件（不知道该怎么描述）
文件蜈蚣的浏览器扩展开启时就没法保存  关闭以后就正常了

**Comment by filecxx** [comment]
这个问题应该不严重，我晚一点 (2.0发布之前) 尝试解决下。

**Comment by filecxx** [comment]
这个问题已经解决了，现在不会拦截 blob: 开头的浏览器下载事件。

用JS下载到缓存里然后弹出另存为保存文件的方法方式已经发现了好几个网站在使用，主要目的应该防盗链，强制使用浏览器下载。
