### ISSUE TITLE
下载捕捉视频文件显示“地址已过期”

### ISSUE THREAD

**Issue by nyt35** [filecxx/FileCentipede#147]
1.pornhub上下载捕捉的视频文件显示“地址已过期”，IDM则没有问题。文件版本1.9，浏览器扩展1.4。
2.DHT数字显示有时候很多（重新安装），有时候为0(大部分时间)。
3.配置文件在哪里，不想重新安装折腾时候再配置文件。

不经意间邂逅了蜈蚣，发现太有潜力了！有统一下载界的希望！给作者果果大大的赞！

**Comment by filecxx** [comment]
pornhub 上下载视频会验证IP，需要设置和浏览器一样的代理，另外也有时间限制，可以用右键刷新地址重新捕获新地址。

lib目录下 *.conf *.db 为配置文件，可以备份这2个

**Comment by nyt35** [comment]
我用的clash代理，浏览器没设置，有时候偶尔可以下载，大部分是过期提示。其他都没问题，捕捉也很灵敏。时间应该也没问题。idm就没这个问题。另外对于为数不多有嗅探栏的几个软件，xdm可以突破加密视频下载，下载下来直接看。不知道蜈蚣将来会不会实现。

**Comment by filecxx** [comment]
确实应该在软件里也将代理设置上，127.0.0.1 对应 clash 的那个端口 ，另外文件蜈蚣支持自动解密加密视频，下载完之后自动解密并合并成 ts文件。

**Comment by nyt35** [comment]
行，我回去试试～如果可以，我来写个教程～你是我看见最接地气的开发者，每个问题我都看过一遍，你的态度真是biu忒佛！加密视频我还没用蜈蚣做过实验，我试试！咱们2.0啥时候出来啊？

**Comment by filecxx** [comment]
FTP文件管理一块刚完成，SSH (SFTP, SCP) 才做了不到一半, WEBDAV，HTTP蜘蛛还没开始做，预计最快也得下个月可以完成。

**Comment by nyt35** [comment]
向大家说一下，按照作者果果的说明，在蜈蚣里设置了代理地址"127.0.0.1:7890"(这是clash默认地址和端口)，相关网站的视频资源可以下载了。另外关于加密视频下载也没问题，下载下来直接能看！真是赞了！另外我将挂有SSR地址的padavan路由器做实验，软件本身不用做代理，照样可以下载！特此说明！蜈蚣大王，从什么渠道可以对你进行捐助？我想尽一点我的微薄之力。

**Comment by filecxx** [comment]
> 向大家说一下，按照作者果果的说明，在蜈蚣里设置了代理地址"127.0.0.1:7890"(这是clash默认地址和端口)，相关网站的视频资源可以下载了。另外关于加密视频下载也没问题，下载下来直接能看！真是赞了！另外我将挂有SSR地址的padavan路由器做实验，软件本身不用做代理，照样可以下载！特此说明！蜈蚣大王，从什么渠道可以对你进行捐助？我想尽一点我的微薄之力。

非常感谢，可以考虑在2.0版本时候进行捐助，现在主要收集BUG等，所有资料和信息等都还不完善。

**Comment by firstuanl** [comment]
楼上那个网站伤身呀。

奇怪，在bimiacg4.net网下载，也出现地址过期，没用代理，之前没问题。

**Comment by filecxx** [comment]
> 楼上那个网站伤身呀。
> 
> 奇怪，在bimiacg4.net网下载，也出现地址过期，没用代理，之前没问题。

我刚测试了这个地址，确实显示过期，但是在软件里复制下载地址，然后粘贴在浏览器里打开，重新捕捉却可以下载了，可能是Referer字段做了限制，下个版本修复。

**Comment by nyt35** [comment]
> 楼上那个网站伤身呀。
> 
> 奇怪，在bimiacg4.net网下载，也出现地址过期，没用代理，之前没问题。

哈哈，还好，偶尔光顾，就是遇到问题了，举个栗子，还有很多保护性的加密视频，肥鸭大大做的很不错，下载下来直接看。我很看好这个软件，真是集大成了，尤其视频捕捉这块。

**Comment by nyt35** [comment]
> > 楼上那个网站伤身呀。
> > 奇怪，在bimiacg4.net网下载，也出现地址过期，没用代理，之前没问题。
> 
> 我刚测试了这个地址，确实显示过期，但是在软件里复制下载地址，然后粘贴在浏览器里打开，重新捕捉却可以下载了，可能是Referer字段做了限制，下个版本修复。

肥鸭大大，我这几天在测试百度网盘网页版看视频时候，IDM可以弹出视频捕捉下载栏，蜈蚣没显示，扩展上也没有，你看看是怎么回事？
