### ISSUE TITLE
无法加载磁力/种子

### ISSUE THREAD

**Issue by iucii** [filecxx/FileCentipede#149]
添加磁力链接一直在  下载元数据中  转圈圈
打开正常种子文件提示无效文件

**Comment by filecxx** [comment]
初次运行DHT网络还没有任何peer, 得等到DHT网络刷新完成磁力连接才会从其他用户那里找到种子。

"打开正常种子文件提示无效文件"
是否可以提供下种子文件？

**Comment by iucii** [comment]
https://t.me/cc9527911 加我电报私聊？

**Comment by filecxx** [comment]
你可以直接发我邮箱里，我没有其他通信方式。

**Comment by iucii** [comment]
已发送，对于所有磁力/种子文件皆是如此

**Comment by filecxx** [comment]
我测试了linux版和windows版本，这个种子文件都没有问题，你确定你是打开的这个文件？

**Comment by filecxx** [comment]
尝试双击打开种子文件或者点击打开按钮，我刚测试如果拖动到软件界面中确实显示无效文件，这是个BUG，其他方式则正常。

**Comment by iucii** [comment]
我是第一次用FileCentipede，作为IDM的替代品，在浏览器上的表现我很满意。但唯独无法正常打开磁力/bt文件。
试过5个以上的磁力/种子，在qbittorrent均正常，我尝试删除重新解压装在别的地方，问题依旧。

**Comment by filecxx** [comment]
不排除可能是环境等问题造成的，我测试了这个种子没问题，另外你在qbittorrent中表现正常则问题更奇怪，因为FileCentipede和qbittorrent都是用的libtorrent, 除了界面不同外，所有其他方面是完全一样。

**Comment by filecxx** [comment]
尝试用 帮助 -> 卸载 ，然后重新安装在某个有写入权限的目录下试试，不太可能是windows 11的原因。另外确保下载地址是filecxx.com上面提供的1.9版本

**Comment by iucii** [comment]
经过一番操作，现况如下：
在帮助-卸载后从原目录C:\App清除文件夹，再到E盘根目录解压文件-安装，将种子文件由nas映射的磁盘复制到E盘根目录下可以打开，从网页复制的磁力链接也能正常加载；
再帮助-卸载后从E盘清除文件夹，再回到C:\App根目录解压文件-安装，E盘根目录的种子能打开，nas映射的磁盘中的种子无法打开，从网页复制的磁力链接也能正常加载。
一来一回之后，磁链功能恢复，种子的情况就是只认本地磁盘不认nas1映射的磁盘。
