### ISSUE TITLE
程序无法启动

### ISSUE THREAD

**Issue by zhulaojianke** [filecxx/FileCentipede#15]
win7 旗舰版 sp1
点击fileu.exe安装后，便出现以下界面：
![image](https://user-images.githubusercontent.com/16543111/158045868-12f043b4-964c-4cef-824c-87b33a972e1a.png)
希望能够解决这个问题。

**Comment by filecxx** [comment]
该问题刚刚已经修复，还未测试，稍后将发布更新后版本。

**Comment by filecxx** [comment]
> win7 旗舰版 sp1 点击fileu.exe安装后，便出现以下界面： ![image](https://user-images.githubusercontent.com/16543111/158045868-12f043b4-964c-4cef-824c-87b33a972e1a.png) 希望能够解决这个问题。

新上传的版本问题应该已经修复，至少只会弹出一次，再次运行会正常。

**Comment by zhulaojianke** [comment]
OK，还没有试用，希望会是一个好软件 :)
