### ISSUE TITLE
关于磁力下载的问题

### ISSUE THREAD

**Issue by besttoday** [filecxx/FileCentipede#150]
不知道是不是我设置得有问题，我得磁力下载一次都没有成功过。资源都找不到。magnet:?xt=urn:btih:6FC264D85BDEBAAB3841B8CC314E5BC7A156FFF8，

![QQ截图20220415081511](https://user-images.githubusercontent.com/103704086/163496420-f31b8264-1719-464a-966c-79e0b6625006.png)

**Comment by besttoday** [comment]
一直就在这个界面

**Comment by jorismq** [comment]
Torrant DHT有反应吗？没有的话手动停止下filec这个程序，再重新打开试试
我只要DHT有数字，就可以下磁力

**Comment by besttoday** [comment]
> 
![20220415150044](https://user-images.githubusercontent.com/103704086/163535089-b5a84e14-6b78-41a8-9f16-5ef167b143b7.jpg)试了很多次了

**Comment by nyt35** [comment]
你用其他常用bt软件链接一次试试

**Comment by filecxx** [comment]
等到Torrent DHT 大于0的时候再尝试下，我测试这个磁力链接很正常，如果一直是0，很大概率是和防火墙有关。

**Comment by besttoday** [comment]
> 
我用迅雷测试了是可以下载的。

**Comment by filecxx** [comment]
文件蜈蚣和qbittorrent的torrent引擎是一样的，建议搜索下 qbittorrent DHT 0

**Comment by filecxx** [comment]
或者下载一个比较热门的种子文件，DHT会自动刷新。

**Comment by zzcbun** [comment]
![屏幕截图 2022-04-18 103612](https://user-images.githubusercontent.com/102930096/163745817-5c930a2a-50d4-4adc-9d60-0516a1bc7dc3.jpg)
我这边也是这个问题，迅雷有速度，蜈蚣这边一直提示元数据下载中，torrent DHT 一直是0

**Comment by zzcbun** [comment]
> ![屏幕截图 2022-04-18 103612](https://user-images.githubusercontent.com/102930096/163745817-5c930a2a-50d4-4adc-9d60-0516a1bc7dc3.jpg)我这边也是这个问题，迅雷有速度，蜈蚣这边一直提示元数据下载中，torrent DHT 一直是0

magnet:?xt=urn:btih:169ea0eed6852c53a3c46161f1a1762d96023c3e&dn=zh-cn_windows_11_consumer_editions_updated_march_2022_x64_dvd_07cc21aa.iso
