### ISSUE TITLE
"Trying establish with filec"

### ISSUE THREAD

**Issue by YulinChan** [filecxx/FileCentipede#151]
![image](https://user-images.githubusercontent.com/48314862/163539542-7ec4db04-caf8-4436-94c8-8e64e491e8c6.png)
win10环境，用了几天，打开之后出现这个界面，开机自启动后也是这个界面。查看任务管理，发现filec已经启动了。期间我进行过win10推送的更新，不知道是不是因为这个原因。
请问如何保留配置卸载重装？这样或许能解决问题

**Comment by nyt35** [comment]
这两天我也没少折腾蜈蚣，包括5k下，界面出现比例变形问题。发现开源软件有很多都有这个问题，xdm 也是，不知道是不是很软件某个库有关系。
lib目录下 *.conf *.db 为配置文件，可以备份这2个。

**Comment by YulinChan** [comment]
好的，谢谢

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/163558581-96ff1f0f-f066-431f-938b-31a4e1c2f8a3.png)
如果一直是这个界面，只有一个按钮，那表明filec.exe进程被冻结了，如果不是杀毒软件等冻结的，应该手动结束这个进程。

**Comment by YulinChan** [comment]
应该不是杀毒软件导致的，我电脑只装了火绒，它没给出有任何提示。另外，保留配置文件重装后它又恢复正常了。如果是杀毒软件导致的话，只要杀毒软件还在，filecxx应该一直无法运行才对。

**Comment by YulinChan** [comment]
手动结束进filec.exe进程我也尝试过，没有效果诶。我甚至执行filec.exe -u, filec.exe -ss remove 先卸载filec.exe, 然后再逆向操作，安装回去，也没有用。

**Comment by nyt35** [comment]
我头几天折腾的时候，都是手动关掉进程，然后全部删除，重启，再拷贝安装。😁

**Comment by zzugyl** [comment]
我在ubuntu下待机一会儿，也是出现这个问题，只有退出后，重新打开。
![2022-04-17_20-30](https://user-images.githubusercontent.com/27466768/163765653-76932c4f-e35a-4084-aff8-c16a3a6742f4.png)

**Comment by filecxx** [comment]
所有崩溃相关的BUG应该都已经修复了。

**Comment by taofuli8** [comment]
www.taofuli8.com 淘福利,免费收集、分享最新银行,基金及名企商家的羊毛信息,致力于为财友们提供真实有效的信息,踏出理财的第一步。
