### ISSUE TITLE
已经设置好分类，退出软件再打开时会出现部分已下载项目的分类变成空白

### ISSUE THREAD

**Issue by deranged11** [filecxx/FileCentipede#153]
版本号1.9
退出软件后已经下载并且设置好分类的变成了空白，图片不会发请见谅

**Comment by filecxx** [comment]
程序内目前唯一会将任务分类设置为空白的地方就是删除对应分类，如果你没有删除该分类，那么不太可能出现任务分类空白现象，鉴于你提供的信息有限，这是我唯一能给出的结论。

**Comment by deranged11** [comment]
分类是没有删除的，退出软件后就会出现这种分类变成空白了。

**Comment by filecxx** [comment]
这个问题应该已经修复。
