### ISSUE TITLE
缓存文件路径

### ISSUE THREAD

**Issue by kentYang1124** [filecxx/FileCentipede#156]
可以告知缓存文件是保存在什么位置吗？程序中没找到相关的设置项，谢谢。

**Comment by filecxx** [comment]
程序不创建临时文件，是直接目标文件进行读写。

**Comment by guojq82** [comment]
看到这个 提个建议  右键批量下载的时候  可不可以改为默认保存目录是空的时候  出现提示  而不是直接下载，现在的不提示直接就下载了，（提示为空的时候默认保存在缓存文件夹），然后找不到这个缓存文件  相当于白白下载了好久  然后啥也没得到

**Comment by filecxx** [comment]
> 看到这个 提个建议 右键批量下载的时候 可不可以改为默认保存目录是空的时候 出现提示 而不是直接下载，现在的不提示直接就下载了，（提示为空的时候默认保存在缓存文件夹），然后找不到这个缓存文件 相当于白白下载了好久 然后啥也没得到

可以在下载完成之后在右键菜单中移动文件。
