### ISSUE TITLE
关于Logo中的动物

### ISSUE THREAD

**Issue by YulinChan** [filecxx/FileCentipede#157]
请问Logo中的动物是什么？是鸭、鹅还是其他鸟类呢，白鹅和白鸭光看卡通形象还是太难辨认了。

**Comment by filecxx** [comment]
图标是蜈蚣。

**Comment by guojq82** [comment]
是翻译问题么？？？  这怎么看都不可能是蜈蚣啊  大神。。。。
一直就奇怪为啥名字叫蜈蚣 图片是鸭子  难道这就是原因？？？

**Comment by nyt35** [comment]
肥鸭  ：P

**Comment by wanghaozone** [comment]
> 图标是蜈蚣。

图标是鸭子啊，这鸭子叫蜈蚣吗？还是有什么其他的意义

**Comment by mantis3d** [comment]
> 图标是蜈蚣。

就凭这句话，我觉得这个软zuo件zhe应该被scp收容
