### ISSUE TITLE
Chrome扩展无法正常使用，安装后无法打开

### ISSUE THREAD

**Issue by cc1983-cc** [filecxx/FileCentipede#158]
Chrome扩展无法正常使用，安装后无法打开，显示未知来源。

**Comment by filecxx** [comment]
可以尝试解压chrome.zip 之后，加载已解压的文件夹。

**Comment by cc1983-cc** [comment]
> 

使用加载解压文件夹的方法已解决，谢谢。

**Comment by login404** [comment]
Chromium扩展缺少磁力链接的右键菜单

**Comment by filecxx** [comment]
> Chromium扩展缺少磁力链接的右键菜单

磁力链接可以直接点击，为什么需要右键菜单，我不是很明白。

**Comment by cc1983-cc** [comment]
> > Chromium扩展缺少磁力链接的右键菜单
> 
> 磁力链接可以直接点击，为什么需要右键菜单，我不是很明白。

我估计是因为有需要使用不同下载软件下载磁力链接的需求。我自己最近一直尝试使用各种下载软件，发现不方便，通常是弹出默认的那个。希望贵软件越做越好。顺便提一个小小建议，软件名字是不是可以取一个广义上更美好，蜈蚣这个名词我看了有点怕怕的：）我可以用公司资源帮忙设计一个icon：）

**Comment by filecxx** [comment]
如果有好的名称和图标欢迎随时提交，不过建议名称主要涉及 "文件" 而非 "下载" ，"下载" 虽然是1.x版本主要功能，但是不会是以后的唯一功能。比如从2.0 开始 软件不仅仅只是下载工具，同时也是远程文件管理工具和上传工具。

**Comment by cc1983-cc** [comment]
> 

英文名字可以叫 
File Transfer Manager
或者
Data Express

中文名就叫文件快传

你愿意的话，我可以去帮忙搞一个专用的icon

**Comment by cc1983-cc** [comment]
> 如果有好的名称和图标欢迎随时提交，不过建议名称主要涉及 "文件" 而非 "下载" ，"下载" 虽然是1.x版本主要功能，但是不会是以后的唯一功能。比如从2.0 开始 软件不仅仅只是下载工具，同时也是网络文件管理工具和上传工具。

英文名字可以叫
File Transfer Manager
或者
Data Express

中文名就叫文件快传

你愿意的话，我可以去帮忙搞一个专用的icon

**Comment by login404** [comment]
> > Chromium扩展缺少磁力链接的右键菜单
> 
> 磁力链接可以直接点击，为什么需要右键菜单，我不是很明白。

直接点击需要注册表关联
而我是安装后生成配置文件再卸载
当作便携版用的
