### ISSUE TITLE
Trackers添加订阅后无法更新URL中的列表

### ISSUE THREAD

**Issue by cc1983-cc** [filecxx/FileCentipede#159]
如题，我在设置中添加了追踪器的订阅地址，网络可以正常访问这些URL，但是手动更新订阅后无法显示在列表中。

**Comment by guojq82** [comment]
你稍微等等 或者退出以后再进  就显示更新列表了   这块功能一直就这样  感觉反应比较慢
还有就是同样的trackers  但是链接上的dht就是没有bitcoemt多    还是等作者的3.0吧

**Comment by huanghaobaobao** [comment]
希望能增加显示trackers的成功更新时间，而不是添加时间

**Comment by filecxx** [comment]
> 如题，我在设置中添加了追踪器的订阅地址，网络可以正常访问这些URL，但是手动更新订阅后无法显示在列表中。

我完全没有看到这个问题的存在，2.5版本会完善这一块。

**Comment by filecxx** [comment]
已经完成
