### ISSUE TITLE
您好，我想问下已经下载的文件直接做种该怎么操作？

### ISSUE THREAD

**Issue by chenhao2424** [filecxx/FileCentipede#16]
我有一些需要做种子的文件，我发现拖入torrent文件之后，软件会提示文件已存在，但是未进行校验文件块的动作，如果此时点击开始，会直接进行下载。

所以想问下，如果直接做种该怎么操作？或者是还有我没搞明白的操作，烦请指教，谢谢！

**Comment by filecxx** [comment]
目前做种只能用文件蜈蚣的创建种子功能来做种，或者下载完种子文件后开始做种，用已有种子和已有本地文件来做种应该还不支持，设计时候没考虑到这个问题，不过我会把这个功能添加到待做事项中，在之后的版本中会出现这个功能。

**Comment by filecxx** [comment]
不过我认为直接用创建种子功能创建出来的种子HASH值应该和以存在种子的HASH值一样的，如果种子V1或V2对应。

**Comment by chenhao2424** [comment]
> 目前做种只能用文件蜈蚣的创建种子功能来做种，或者下载完种子文件后开始做种，用已有种子和已有本地文件来做种应该还不支持，设计时候没考虑到这个问题，不过我会把这个功能添加到待做事项中，在之后的版本中会出现这个功能。

感谢
