### ISSUE TITLE
建议支持aria2的下载链接格式

### ISSUE THREAD

**Issue by youchuanchuan** [filecxx/FileCentipede#161]
如题，这样可以配合很多插件、脚本使用了

**Comment by filecxx** [comment]
该提议已经被请求多次，确定增加

![image](https://user-images.githubusercontent.com/100348948/163804386-4adadfee-5ab3-438d-8434-f92a082ead27.png)

**Comment by youchuanchuan** [comment]
> 该提议已经被请求多次，确定增加
> 
> ![图像](https://user-images.githubusercontent.com/100348948/163804386-4adadfee-5ab3-438d-8434-f92a082ead27.png)
辛苦大佬，感谢

**Comment by filecxx** [comment]
2.0已经支持了，如果有问题请继续反馈。
