### ISSUE TITLE
需要下载B站和油管视频时，不能稳定工作

### ISSUE THREAD

**Issue by cc1983-cc** [filecxx/FileCentipede#162]
经常遇到需要下载视频时发现没有角标可以点按，还遇到过一次角标显示的条目越来越多，但都是几十KB大小，且每条都一样，明显不是视频文件的列表。预祝软件越来越好。

**Comment by filecxx** [comment]
少部分的网站没有使用m3u8作为媒体数据传输，而是使用的JS动态拼合了一大堆文件，但是仍然可以做到捕捉下载完整文件，不过需要针对该网站做专门处理，之所以没有做是因为通常该类网站变化会比较快，不通用，生命周期会比较短，以至于需要经常更新才能使用，时间是目前最缺乏的，待软件稳定之后会进一步写网站的针对性规则。

**Comment by filecxx** [comment]
请更新到1.5
