### ISSUE TITLE
插件是否会上架商店

### ISSUE THREAD

**Issue by 7sasuke7l** [filecxx/FileCentipede#167]
不知道插件能否上架Chrome Store呢？或者Firefox的扩展商店

**Comment by filecxx** [comment]
已经上架 firefox 和 edge 

好消息是 上架chrome store 被拒绝, 只能本地安装，所以确定在以后版本扩展中增加下载youtube视频的功能。

edge:
https://microsoftedge.microsoft.com/addons/detail/jeekmibdibcjeihbjnjgbegjalfelhon

firefox:
https://addons.mozilla.org/firefox/addon/filecxx/
