### ISSUE TITLE
有个小小的建议，关于m3u8下载后的

### ISSUE THREAD

**Issue by ZeparSD** [filecxx/FileCentipede#17]
有个小小的建议，可以在下载m3u8文件后能给选择是否要转换成MP4，不然还需要ffmpage去转换一次

**Comment by filecxx** [comment]
你指的是下载m3u8文件后, 还是通过m3u8文件下载到的视频合并为.ts 文件之后, 我理解应该是后者, 大部分的视频播放器都支持直接播放.ts 文件, 不过你既然提出这个问题了一定有你的原因, 我把这个功能添加到待做事项里, 以后版本以插件形式发布 (原因是ffmpage文件太大).

**Comment by ZeparSD** [comment]
我并不清楚是下载完成后还是合并之后
N_m3u8DL-CLI
这个项目做的就还不错
我用的播放器是VLC，播放TS时会有明显的卡顿，不知道是不是我的设置有问题
ffmpage或者可以让用户指定路径或者提供一个下载方式？
Captura
这个项目的不知道能不能给到你那边一些灵感

**Comment by filecxx** [comment]
这个功能其实在设计之前已经考虑过了，但这并没有作为优先开发的功能，这个可能至少等半年之后，因为现在还有很多新功能要制作。
