### ISSUE TITLE
能否增加几个下载时候的功能选择和界面选择

### ISSUE THREAD

**Issue by maioro** [filecxx/FileCentipede#170]
1、点击网页http类下载链接时，有时由于网站设置需要用浏览器下载才能成功（软件下载会提示400错误），能否增加按住键盘任意按键不使用软件下载的选项？（例如 alt键、ctrl键或自定义按键）
2、软件选择默认开机运行下，能否增加自动最小化隐藏的选择？而不是每次开机都自动打开软件主界面？
3、主界面里的 （名称-大小-进度-状态-剩余时间）这些现在可以手动拖动前后顺序，能否增加个右键选项手动选择哪些显示哪些不显示。
4、编辑配置选项好像点了没反映。
5、任务过滤 这个能否自定义拖动位置。
6、浏览器扩展能否增加显示视频类文件码率（分辨率这个有时有有时没有，不知为何）显示。
例如youtube的视频经常只有2个选择一个视频webm一个音频webm。或者多个音频webm一个视频webm。没有分辨率和对应码率的提示。只能看文件大小和时常来猜码率和分辨率

以上问题只是咨询下，如已在制定计划内，请忽略。
软件很不错

**Comment by filecxx** [comment]
1: 可以在浏览器扩展小图标中勾选忽略此站
2: 已经在计划内
3: 2.1 版本之后添加
4: 这个功能针对所有类型任务都有作用，不知是否操作不正确
5: ？
6: youtube 针对分辨率视频捕获在2.1版本之后添加

**Comment by maioro** [comment]
4、这个意思是如果不在下载列表里选择一个条下载记录时按下不会有反映，有选择后才有。改成不选择时灰色不可点击的状态。
5、意思是1.9版本这个主界面上（浏览器）按键旁的（任务过滤）这个框 能否自己手动移动到 最上面的【帮助】后面或者其他位置。
      这样【浏览器】左边图标里的所有按键就有位置都显示出来，可以直接看到并且点击，不用先打开按钮才能看到，直观些。
以上是补充。

**Comment by filecxx** [comment]
编辑配置确实应该设置为灰色。

![image](https://user-images.githubusercontent.com/100348948/165289744-dddf376b-875d-4ef9-8aaf-6803add80248.png)
这个图标可能不会变，因为某些语言，例如俄语，阿拉伯语文字非常的长，工具栏放不了几个图标。

**Comment by nyt35** [comment]
啥时候更新版本啊~~

**Comment by filecxx** [comment]
> 啥时候更新版本啊~~

5月内
