### ISSUE TITLE
下载文件即将结束时崩溃

### ISSUE THREAD

**Issue by Youxikong** [filecxx/FileCentipede#171]
已经遇到两次，下载文件的最后一点，filec进程崩溃。

**Comment by Youxikong** [comment]
最近发现的一个是一次性的地址，已经失效了，是一个5.4G的不支持多线程和续传的任务。在之前一个是发生在1.4版本上，链接已经找不到了。更新1.9之后以为类似的问题已经解决了。

**Comment by filecxx** [comment]
在2.0完成之前我会全面测试下不支持续传的大文件，在这期间如果还发现这个问题，记得保存下地址。

**Comment by Youxikong** [comment]
OK我留意。

**Comment by YohoYang** [comment]
我也有遇到类似的问题，大约是4G的http文件，把线程开到64，最后即将结束的时候就不动了，软件倒是没崩溃，但等很久都不能完成，停止重新开始后就很快能够完成剩下的一点点，并完成任务。

**Comment by filecxx** [comment]
新版本应该修复了这个问题，请重新测试下。
