### ISSUE TITLE
临时设置不使用filecxx，以及Chrome中的插件错误

### ISSUE THREAD

**Issue by olivex** [filecxx/FileCentipede#172]
两个问题：
1. 经常遇到某些网站不支持使用扩展下载的情况，或者某些情况下虽然网站支持，但需要用浏览器本身下载，虽然可以用勾选忽略此网站的方法来应对第一种情况，遇到第二种情况就很不方便，能不能安排一个附加键，例如按住INS再点下载链接，就不用filecss直接用浏览器下载？
2. 插件在Chrome里安装後显示manidest version 2不支持的错误。虽然可以忽略此错误，总是感觉不太舒服。

**Comment by filecxx** [comment]
下载地址中提供了manifest_v3 版本的 chrome扩展，但不建议使用，manifest_v3 权限非常低，捕获视频效果不是太好。

你可以Google 下 manifest_v3 为什么不受欢迎。

**Comment by olivex** [comment]
作为程序猿，我非常理解v3为啥不好用，以及你的无奈；但是作为用户，我希望有一个两全的方案。不知道别的类似软件是怎么做的有没有参考价值呢？
另外第一个问题有没有更好的解决方案。

**Comment by filecxx** [comment]
目前没有做youtube针对规则，无法捕捉到指定分辨率的视频。
