### ISSUE TITLE
下载完合成时会挂起? 另外扩展拦截会影响其他扩展

### ISSUE THREAD

**Issue by vvyoko** [filecxx/FileCentipede#173]
系统 : WIN10 LSTC 2021
浏览器 :百分浏览器(Chrome)
下载盘:HDD

下载比较大的文件(2G+)到100%时不知是在合成还是在移动
这时扩展新建任务或 `fileu.exe "url"` 都没反应
可能是在处理合成或移动中挂起了?

被影响的其他扩展
Web Clipper
https://chrome.google.com/webstore/detail/web-clipper/mhfbofiokmppgdliakminbgdgcmbhbac

此扩展有个功能是提取当成页面然后保存为MD文件到本地
此功能被本软件扩展拦截了,因为不只是保存一个网站,所以白名单不现实

截图: 提取后点击这个
![1](https://user-images.githubusercontent.com/2145741/165485074-ce8ca4bc-33ac-4d7f-b83b-865452926783.jpg)

**Comment by filecxx** [comment]
第一个问题是，在100%时候正在将内存中的数据写入到硬盘，会出现卡住情况，这个会在下个版本中改进。

第二个问题可以将扩展中下载管理器切换为浏览器，因为都调用的相同API，所以是冲突，暂时还不知道其他解决方法。

**Comment by filecxx** [comment]
第一个问题已经修复了。
第二个暂时不解决。
