### ISSUE TITLE
在Edge上使用扩展遇到了问题

### ISSUE THREAD

**Issue by Youxikong** [filecxx/FileCentipede#175]
扩展是Windows扩展商店里的版本。
当打开着大量的扩展的时候，edge的文件里，extensionactivityedge这个数据库会非常大，里面保存了大量和这个扩展的id关联的数据，导致浏览器启动非变慢。由于没有在其他chromium浏览器里发现这样的文件，网络上也找不到关于这个数据库的任何信息，所以不确定是edge自己的问题还是扩展的问题。

**Comment by filecxx** [comment]
FileCentipede 扩展不保存任何数据，除了自身配置(4个字段，内存小于1KB)，只会在内存中保存当前网页捕获到的文件信息，关闭标签后数据清空，可以检查下是否其他扩展的问题。
