### ISSUE TITLE
下载大文件出现的问题

### ISSUE THREAD

**Issue by nyt35** [filecxx/FileCentipede#177]
继续反馈，继续测试，从局域网用http下载大文件，中途莫名的卡掉(任何界面没了，进程还在)或者界面不更新(下载进度和速度不更新)。但在服务端，还是显示在下载，从本机的网络流量来看，软件也还是处于下载状态，貌似这个过程非常吃内存，内存一点点在增加，电脑变得异常卡顿。尝试退出后，再启动软件，就到了其他网友常见的问题，界面前面有一个灰色的转圈图案，点什么都没反应。后来反复测试，找到一个不是办法的办法，在圆圈附近疯狂点鼠标，会闪现启动确定的那个界面(鼠标不停按)，然后点确定，这个时候软件起来了，也正常了。继续下载的信息也都有了。

**Comment by filecxx** [comment]
局域网或者较快网络下载文件时候建议只用1个连接，已下载到内存中的数据提交到硬盘这个问题下个版本解决。

**Comment by filecxx** [comment]
这个问题2.0应该已经完全解决，并且不是以牺牲随即IO为代价，也不需要下载完成后重新合并。
