### ISSUE TITLE
无法正常下载Wing FTP Server Web Client中的文件

### ISSUE THREAD

**Issue by funnybones2015** [filecxx/FileCentipede#178]
工作中需要下载Wing FTP Server Web Client中的文件，每次下载时文件蜈蚣能调起下载窗口，但是就是没速度，然后提示远程主机不稳定，从而失败。但用浏览器默认下载器就可以正常下载，用IDM也能正常下载。试了好几个文件都是这样。

**Comment by filecxx** [comment]
前几天从邮件里收到相似问题，已经修复了，2.0版本中不会存在这个问题。

**Comment by funnybones2015** [comment]
> 

好的，感谢及时回复！！

**Comment by filecxx** [comment]
这个问题应该已经解决了，请下载新版本。

**Comment by funnybones2015** [comment]
> 这个问题应该已经解决了，请下载新版本。

多谢多谢，马上去试试！！！
