### ISSUE TITLE
我这几天在测试百度网盘网页版看视频时候，IDM可以弹出视频捕捉下载栏，蜈蚣没显示，扩展上也没有，你看看是怎么回事？

### ISSUE THREAD

**Issue by nyt35** [filecxx/FileCentipede#179]
![无标题](https://user-images.githubusercontent.com/91946870/166107405-f8c9b3a7-4344-46e2-b1ce-06b90f96adb4.jpg)

**Comment by filecxx** [comment]
发个地址测试看看

**Comment by filecxx** [comment]
你是装的manifest v3 版本扩展吗？manifest v2的正常。

**Comment by nyt35** [comment]
链接: https://pan.baidu.com/s/1MBy2bl78umL7NOGMBQyWHA 提取码: 5fxk 复制这段内容后打开百度网盘手机App，操作更方便哦

我两个浏览器都试过了，分别是edge dev 102.0.1235.1 ，另一个是360极速X21.0.1094.0

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/166108610-d4918047-965b-440c-a555-d65e6fca535a.png)

我测试几个浏览器都没有问题，你试试其他网站正常吗？

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/166108675-4fad0fd4-ae9c-4719-bebb-7a3358f88d56.png)

**Comment by filecxx** [comment]
可以尝试禁用其他扩展试试，不排除是冲突。

**Comment by nyt35** [comment]
> 你是装的manifest v3 版本扩展吗？我刚测试了所有浏览器，manifest v2的都没问题。

这个是什么意思，是谷歌系浏览器扩展最新的构件协议么？

**Comment by filecxx** [comment]
[chrome_manifest_v3_dist.crx](https://github.com/filecxx/FileCentipede/releases/download/latest/chrome_manifest_v3_dist.crx)335 KB
这个是manifest_v3 版本的扩展，google强制推广的低权限版本，捕获视频的能力比较差。

如果是edge不应该有问题，可以禁用其他扩展，或者卸载文件蜈蚣扩展之后重新安装试试。

**Comment by nyt35** [comment]
还是不行，我明天在我的WIN11上试试吧~

**Comment by nyt35** [comment]
> [chrome_manifest_v3_dist.crx](https://github.com/filecxx/FileCentipede/releases/download/latest/chrome_manifest_v3_dist.crx)335 KB 这个是manifest_v3 版本的扩展，google强制推广的低权限版本，捕获视频的能力比较差。
> 
> 如果是edge不应该有问题，可以禁用其他扩展，或者卸载文件蜈蚣扩展之后重新安装试试。

您那有manifest_v2 版本的扩展么？

**Comment by filecxx** [comment]
默认的chrome.zip 和 chrome.crx 就是 v2

**Comment by filecxx** [comment]
也可以尝试下火狐扩展是否也出现这个问题，我在多个平台测试了全部正常，暂时不知道原因。

**Comment by nyt35** [comment]
我测试了一下，沙箱里跑了EDGE/FOX/360，没问题。后来莫名其妙的EDGE又显示了~

**Comment by nyt35** [comment]
哈哈，话说间，又有一个小问题，可能是我的360个人文件夹太老，5.6年的User Data，大版本升级之类的也没换过，都是覆盖，可能出现兼容问题。然后在导出uBlock Origin和tampermonkey备份数据时候，一直没反应。查了大半天资料，也没发现有异样。后来想到可能是蜈蚣接管但数据没达到蜈蚣接管下载的门槛，就一直下载不了，禁用以后，就可以下载了。
