### ISSUE TITLE
关闭到托盘时创建任务窗口关闭后界面进程崩溃

### ISSUE THREAD

**Issue by login404** [filecxx/FileCentipede#18]
复现步骤:
1.关闭到托盘
2.复制被监视类型的链接
3.当弹出的创建任务窗口关闭后fileu.exe崩溃

建议添加BT任务将过滤规则设置为默认的功能

多文件的BT任务
若有同块文件未选中不会做种
且残留.parts临时文件
做种完成后再删除未选中?

界面BUG
必须重启fileu.exe才能恢复
![1](https://user-images.githubusercontent.com/69505914/158079673-cb72de96-86bd-4c61-94e7-4f3d66b3eb13.png)
![2](https://user-images.githubusercontent.com/69505914/158079675-3792a93e-06a2-4cad-b974-ea99dc9057ce.png)

**Comment by filecxx** [comment]
根据你的步骤, 我刚刚测试到了, 托盘创建任务, 然后关闭, 确实是个BUG.
-------
且残留.parts临时文件 <= 你确定是用文件蜈蚣留下来的吗, 我记得除了文件本身之外, 所有数据都保存在数据库里, 不创建任何临时文件.

-------
多文件的BT任务
若有同块文件未选中不会做种
且残留.parts临时文件
做种完成后再删除未选中?

这个应该属于libtorrent 的bug, 建议反馈到,或者晚一点我会反馈到 https://github.com/arvidn/libtorrent 
-----

界面BUG
必须重启fileu.exe才能恢复

用户列表残留多余的没被删除这个确实在少数时候会发生, 在发布之前我已经测试到了, 你指出的所有这些问题我现在就逐个解决, 主要是 第一个和最后一个, 感谢反馈,兄弟.

**Comment by login404** [comment]
libtorrent那边你反馈吧
我英文只会机翻…

.parts只在有未选中文件的BT任务时生成
有隐藏属性 会随"删除任务与文件"被删除

追踪器应保留空行用于分到不同层级同时使用
或添加"Always announce to all trackers in a tier"选项?

**Comment by filecxx** [comment]
OK

**Comment by filecxx** [comment]
1.1 应该解决了 托盘和残余 用户列表问题。

**Comment by filecxx** [comment]
多文件的BT任务
若有同块文件未选中不会做种
且残留.parts临时文件
做种完成后再删除未选中?

qBittorrent是否也存在相同问题？

**Comment by filecxx** [comment]
残余用户列表我很难测出来，几率出现很低，有什么技巧吗？

**Comment by login404** [comment]
我是按客户端反序排序
双向滚动频繁(看吸血)
时而切换选中行
在下载刚完成的瞬间容易复现
单纯做种不易复现(连接数少?)

**Comment by login404** [comment]
还没修复 补充下
部分下载的多文件BT任务其实是会做种的
只是界面有BUG 状态栏不会显示做种
且属性里的信息仅维持任务刚完成时的状态而不会刷新

![QQ截图20220630191900](https://user-images.githubusercontent.com/69505914/176668442-1273ccde-7111-4e5a-9e8a-4e35892d652f.png)
![QQ截图20220630192112](https://user-images.githubusercontent.com/69505914/176668469-bc21183f-679a-4ae8-a9c6-f3e0170e83dd.png)

**Comment by filecxx** [comment]
是2.1版本吗，我昨天修复了类似的问题和重复用户问题。

**Comment by login404** [comment]
是2.1版 现在正开着

**Comment by filecxx** [comment]
提供下磁力连接。

**Comment by login404** [comment]
magnet:?xt=urn:btih:fc3020ff89479bfd86ff8f34c0c37d1f6de4da6a

**Comment by filecxx** [comment]
勾选框问题和显示已完成却在实际在做种的BUG已经在2.2中修复了。
