### ISSUE TITLE
新的版本何时发布？有没有时间表？

### ISSUE THREAD

**Issue by asd0109** [filecxx/FileCentipede#181]
从1.9期盼了很久新版本了，每天都过来看看，什么时候能推出新版本呢？

**Comment by nyt35** [comment]
https://github.com/filecxx/FileCentipede/issues/147#issuecomment-1099201634

肥鸭大大：FTP文件管理一块刚完成，SSH (SFTP, SCP) 才做了不到一半, WEBDAV，HTTP蜘蛛还没开始做，预计最快也得下个月可以完成。

**Comment by asd0109** [comment]
> 正在做HTTP和WEBDAV 文件管理功能, 还有一个新的功能需要比较大的工作量, 下载/上传 整个文件夹, 例如 sftp://127.0.0.1/folder/ 以及http ftp ssh 等整站克隆
> 
> 5月内应该可以全部完工

天啊，连SFTP都要做啊，这意味着新版本上线后可能会遇到一堆问题反馈，更忙了。
还有整站克隆，需要递归整个站点的目录。。。。

想想都很麻烦。。。。。

**Comment by filecxx** [comment]
SFTP已经完成了，实现是目前最简单的，没有FTP的各种兼容性问题和主动被动连接等缺陷设计，基本上和本地文件API差不多，最难设计的是HTTP， 需要爬虫抓取整个网站，处理外部站点连接， 判断类型转换编码，参数处理等。

![image](https://user-images.githubusercontent.com/100348948/167049885-4d6807dc-de55-482b-a767-a10d1f1742bf.png)

**Comment by nyt35** [comment]
> > 正在做HTTP和WEBDAV 文件管理功能, 还有一个新的功能需要比较大的工作量, 下载/上传 整个文件夹, 例如 sftp://127.0.0.1/folder/ 以及http ftp ssh 等整站克隆
> > 5月内应该可以全部完工
> 
> 天啊，连SFTP都要做啊，这意味着新版本上线后可能会遇到一堆问题反馈，更忙了。 还有整站克隆，需要递归整个站点的目录。。。。
> 
> 想想都很麻烦。。。。。

不鸣则已一鸣惊人，直接站到了全能下载界的金字塔尖了~！

**Comment by IM515BT** [comment]
牛啊牛啊

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/releases/tag/2.0
