### ISSUE TITLE
linux 1.9版本安装后无法使用

### ISSUE THREAD

**Issue by winter110** [filecxx/FileCentipede#182]
系统是deepin linux 20.5，安装后每次打开都提示filec版本错误，点击OK后程序就自动退出。无法使用

![截图_fileu_20220505115351](https://user-images.githubusercontent.com/9690117/166861641-555505ef-30d3-4f92-aad2-edb2593a2405.png)

**Comment by filecxx** [comment]
尝试结束filec进程重新打开，这个是共享内存读取错误造成的
