### ISSUE TITLE
正在下载10个文件，关机再打开，之前正在下载的文件都没有了。

### ISSUE THREAD

**Issue by syzKEY** [filecxx/FileCentipede#184]
正在下载10个文件，关机以后再打开软件，之前正在下载的文件都没有了。

**Comment by filecxx** [comment]
什么类型的任务。

**Comment by filecxx** [comment]
另外可以检查下是否安装了多个副本，如果开启了系统服务，fileu连接到的filec可能是另一个副本。

**Comment by syzKEY** [comment]
种子文件。从网站下载的文件蜈蚣，关闭再打开，就看不到正在下载的文件

**Comment by filecxx** [comment]
新版本应该没有这个问题了。
