### ISSUE TITLE
feature: Download categorized in folders like Xdman

### ISSUE THREAD

**Issue by thebeast48** [filecxx/FileCentipede#185]
Documents:
  file1
  file2
Compressed 
Videos
. 
.
etc

**Comment by filecxx** [comment]
I believe this will do.

![image](https://user-images.githubusercontent.com/100348948/167312109-169dd3bf-3992-4fc9-9576-e5c20de69583.png)
![image](https://user-images.githubusercontent.com/100348948/167312135-686e4af3-fb92-4b77-8b03-816febf7e1d4.png)

**Comment by thebeast48** [comment]
> I believe this will do.
> 
> ![image](https://user-images.githubusercontent.com/100348948/167312109-169dd3bf-3992-4fc9-9576-e5c20de69583.png) ![image](https://user-images.githubusercontent.com/100348948/167312135-686e4af3-fb92-4b77-8b03-816febf7e1d4.png)

another question can i run file-centipede from web-extension

**Comment by filecxx** [comment]
You can.

**Comment by thebeast48** [comment]
> You can.

how i can do these

**Comment by filecxx** [comment]
edge:
https://microsoftedge.microsoft.com/addons/detail/jeekmibdibcjeihbjnjgbegjalfelhon

firefox:
https://addons.mozilla.org/firefox/addon/filecxx/
