### ISSUE TITLE
[功能建议]在添加任务对话框中取消全选

### ISSUE THREAD

**Issue by yichangshengwu** [filecxx/FileCentipede#186]
场景：
有多个项目的 hash ，
只想要其中很少的部分，
于是全选了之后，按 空格键 想要取消选中，
结果不行。。。

建议：
支持 空格键 切换选中状态，或者加个 全选 复选框，
不然好几十个点下去，太累眼了

补充：
咱是运行的 linux 版本，
如果 windows 版本没这问题的话，
那就是 bug 了

**Comment by filecxx** [comment]
没问题

**Comment by filecxx** [comment]
context-menu for torrent confirm-dialog

**Comment by yichangshengwu** [comment]
> context-menu for torrent confirm-dialog

开始下载之后？
那样硬盘上会多出一堆东西

**Comment by filecxx** [comment]
打开种子文件或者磁力连接之后会弹出一个确认框，文件列表现在可以使用右键菜单了，点击确认之后才会开始下载。

**Comment by yichangshengwu** [comment]
> 打开种子文件或者磁力连接之后会弹出一个确认框，文件列表现在可以使用右键菜单了，点击确认之后才会开始下载。

这。。。
真的没往右键上去想过。。。
