### ISSUE TITLE
无法正确复制地址

### ISSUE THREAD

**Issue by a3659950** [filecxx/FileCentipede#189]
正在下载的文件，右键复制地址，粘贴后要么是单个字母，要么是标点，无法正确复制下载文件的下载地址

**Comment by a3659950** [comment]
还有一个问题就是每次打开，窗口都自动恢复到初始大小，而不是恢复到上次调整后的大小，这种后果就是打开，先要调整下窗口，底部才能显示详情栏目。关闭再打开又变成这样了


在2022年5月11日 ***@***.***> 写道：

可以在下方详情栏目中请求标签中复制，这个问题下个版本修复

**Comment by filecxx** [comment]
你有尝试过在设置中勾选保存窗口大小吗

**Comment by filecxx** [comment]
该问题已经解决。
