### ISSUE TITLE
非常棒的工具！如果能劫持浏览器的点击下载就更完美了！

### ISSUE THREAD

**Issue by asd0109** [filecxx/FileCentipede#19]
刚从网上下载到这个工具就感觉很棒！我打算抛弃 IDM 了。
不过目前在使用中遇到一个问题，就是在浏览器中点击某些下载连接的时候 FileCentipede 不能弹出来下载，依然使用的是浏览器下载这点是我目前遇到的美中不足。

具体的链接类似于：

https://www.huorong.cn/downloadv5.html?status=hrstat&src=4      (杀毒软件火绒的下载地址)  http://huorong.cn  

https://www.downg.com/soft/61536.html    （绿软家园中火狐浏览器的下载地址） 在页面的底部 

我不知道是因为我使用的不当，还是软件目前还不支持这种方式，IDM 不会有这样的问题。

**Comment by filecxx** [comment]
浏览器扩展目前不会自动拦截网站自动下载，因为我个人偏向于右键菜单点击下载，自动下载的小文件就用浏览器默认接管，不过既然有这个需求，下个版本(扩展)我会增加一个选项 (拦截浏览器下载).

**Comment by asd0109** [comment]
感谢！  我发的那两个连接，用右键点击下载的时候也是无法下载的，我不太懂HTTP不知道网页是否采取了某些方式去判断用户是否是从网页上点击的还是导链。所以请把这个因素也考虑进去。

**Comment by filecxx** [comment]
OK

**Comment by asd0109** [comment]
大概什么时候可以发布带这个功能的版本啊？   这两天一直在关注，更新的两个版本里还没有发现。
是不是需要一些时间来开发？

**Comment by filecxx** [comment]
在主程序所有已知BUG都修复之后会继续修复浏览器扩展这块，因为BUG修复优先级放在第一的，程序从第一版本到现在发布才不到10天时间，不过这个功能会增加的，我保证。

目前：Chrome extension 版本是 1.0.1

**Comment by asd0109** [comment]
厉害了，才10天就能这么多关注和反馈。这个工具还是很成功的。

我继续等

**Comment by filecxx** [comment]
已经添加进1.3版本，浏览器扩展更新为1.2, 需要重新安装扩展.

**Comment by asd0109** [comment]
> 已经添加进1.3版本，浏览器扩展更新为1.2, 需要重新安装扩展.

半夜收到通知邮件，早上赶紧起来试试，之前的问题都解决了，太赞了！已经卸载 IDM
