### ISSUE TITLE
文件暂停下载之后，重新开始时显示地址过期

### ISSUE THREAD

**Issue by 15705212533** [filecxx/FileCentipede#190]
文件暂停下载之后，重新开始时显示地址过期，往往是下载到90%+的时候，下载速度奇慢，这个时候暂停一下重新开始往往能够快速完成，但是经常出现上述下载地址过期的现象，望修复！

**Comment by filecxx** [comment]
OK

**Comment by filecxx** [comment]
这个问题应该已经修复
