### ISSUE TITLE
1.9版本开启无法建立链接

### ISSUE THREAD

**Issue by Mivimcrs** [filecxx/FileCentipede#191]
突然出现这种情况，一开启软件就出现，软件内所有功能无法点击，也无法通过浏览器插件下载。

![文件蜈蚣](https://user-images.githubusercontent.com/40280036/168202621-6f1a080a-693a-4fc5-a003-9f638354d682.png)

**Comment by Mivimcrs** [comment]
重下覆盖安装又 OK 了😂

**Comment by filecxx** [comment]
前几天发现了http cookie中包含secure字段导致死循环的BUG，不知是否和这个有关。

**Comment by filecxx** [comment]
新版本应该没有这个问题了。
