### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by hikari668** [filecxx/FileCentipede#194]
发现这个下载器对国外这类空间下载速度不如idm，已上梯子，不知日后能改善吗 https://workupload.com/archive/GwBDgfk2

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/168954423-95b09cef-4241-4ec5-b912-57a2939c47bd.png)

目前连接数是递增的，一个连接成功之后再增加连接，这样做目的是为了减轻服务器负担，以及防止被封IP，不过下一个版本会增加这个选项。

**Comment by hikari668** [comment]
另外还发现一个问题，2MB左右的种子文件此软件加载时间超长根本加载不进来。

**Comment by filecxx** [comment]
这个网站做了防盗连，所以直接复制下载地址下载到的是一个html文件，但是如果通过浏览器扩展下载的，会自动获取该网站的cookie和设置来路地址，可以绕过。

**Comment by filecxx** [comment]
另外软件限制了大于2M的种子，这个是libtorrent的默认限制大小，也不打算更改。

**Comment by hikari668** [comment]
1.9MB左右的种子加载时间也很长。

**Comment by filecxx** [comment]
为什么种子文件会这么大，种子内文件超过1万个了吗。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/175650463-1393f992-5197-406d-b9a4-388de8cbe803.png)
