### ISSUE TITLE
正在尝试与filec建立链接

### ISSUE THREAD

**Issue by jbcfky** [filecxx/FileCentipede#195]
连接中
正在尝试与filec建立链接!
[微信图片_20220518184027](https://user-images.githubusercontent.com/74634232/169020713-c9cbc5d8-4d79-469c-b746-0f02dea1d2a6.png)
这是出了什么问题，难道是被网管封禁了吗

**Comment by filecxx** [comment]
打开任务管理器看看filec.exe进程是否CPU使用率一直超过5%,如果是这样可能是和前几天发现的一个死循环BUG有关，可以尝试重新安装。

**Comment by Liweike2022** [comment]
把文件夹copy到C:/Program Files下，安装，试试。
