### ISSUE TITLE
Kaspersky reports filec.exe as malware

### ISSUE THREAD

**Issue by aldochiu** [filecxx/FileCentipede#20]
Hi i am running Windows 11 64bit
Kaspersky Total Security notify me after first reboot of installing the FileCentipede that filec.exe contains malware.

**Comment by filecxx** [comment]
https://docs.microsoft.com/zh-cn/sysinternals/downloads/procmon

You can use this tool to check software's behavior, you decide it is malware or not, the program is compiled by MSYS MinGW, you can google it.

refer:
https://security.stackexchange.com/questions/229576/program-compiled-with-mingw32-is-reported-as-infected
https://stackoverflow.com/questions/62364507/compiled-c-executable-is-detected-as-a-virus-by-windows-defender

**Comment by aldochiu** [comment]
Thanks for your advice and explaination!

**Comment by filecxx** [comment]
Any time, thanks for noticing me before the software got a bad reputation.
