### ISSUE TITLE
检测不到视频地址

### ISSUE THREAD

**Issue by zzugyl** [filecxx/FileCentipede#201]
https://aidi.tv/play/2080-3-1.html
在这网站的视频，没法下载。

**Comment by filecxx** [comment]
这个网站似乎不仅做了防下载，而且还进行了某种程度的伪装

https://aidi.tv/m3u8/atHiRa0nccHiMw6aLnyg9lqueoDIuYWR5cy50di9wcHl1bl9tM3U4L2M5MzhkNjBjM2RkZTQ5OWZhODBkM2YwYWIwNjczMTcy/d715c9be370323409e453ec06e6bb630/1653151476.m3u8

http头回复是一个图片文件

content-disposition: attachment; filename=atHiRa0nccHiMw6aLnyg9lqueoDIuYWR5cy50di9wcHl1bl9tM3U4L2M5MzhkNjBjM2RkZTQ5OWZhODBkM2YwYWIwNjczMTcy.jpg
content-type: image/gif

下载之后却是一个文本，内容为
err:资源已失效

该方式有些特别，但是还是能做到下载，等现在已有工作全部完成之后会再继续完善视频捕捉功能。

**Comment by yichangshengwu** [comment]
还有这种：

http://wolongzyw.com/index.php/vod/detail/id/1843.html

这网页上那些链接，直接复制下来不行，
得一个个点开去视频上的本工具的扩展的下载按钮，这样一来给批量下载造成麻烦

**Comment by filecxx** [comment]
> 

这个网页上显示的m3u8地址不能直接使用，里面包含的地址是相对地址。

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2000000,RESOLUTION=1280x722
2000kb/hls/index.m3u8
```

**Comment by filecxx** [comment]
> https://aidi.tv/play/2080-3-1.html 在这网站的视频，没法下载。

正在解决这块的问题，这个地址现在访问不了。

**Comment by filecxx** [comment]
可以更新到1.5,  这个版本视频捕获进行了很大的更新，能直接从JS中提取地址和解密后的KEY，如果这个版本也抓取不到视频，其他软件也不太可能抓到。
