### ISSUE TITLE
这个软件挺好的，怎么还不更新啊

### ISSUE THREAD

**Issue by liuyuchenai** [filecxx/FileCentipede#202]
这个软件很喜欢，，界面也好看，用来提取网页视频简直不要太方便，还可以用来下种子，软件和插件配合很好用

**Comment by filecxx** [comment]
这次添加的功能非常多，不过大部分已经完成，还未完成的主要有：针对各种协议地址的文件夹下载，服务器克隆，站点规则，以及对Web蜘蛛抓取的网站文件进行布局等。

预计需要延迟到6月中旬才发布2.0版本。

**Comment by asd0109** [comment]
> 

我们等的好辛苦，其实可以先发布一个版本主要的下载功能有了就行，服务器克隆之类平时使用比较少的可以靠后慢慢开发。

**Comment by nyt35** [comment]
蜈蚣只要这个路子走下去，必定是集大成者！

**Comment by zzcbun** [comment]
好饭不怕晚，我反正等得起！

**Comment by filecxx** [comment]
已经更新了。
