### ISSUE TITLE
迅雷好像有新的标识了，希望可以加到反吸血虫的名单里

### ISSUE THREAD

**Issue by ghost** [filecxx/FileCentipede#204]
前几天下载的时候无意间看到有个客户端的标识是XL0012开头的，可能也和迅雷有关，希望核实后可以放在名单里面

**Comment by filecxx** [comment]
你可以手动添加保存，反吸血虫功能目前设计的比较简单。

**Comment by login404** [comment]
反吸血有时会失效
![1](https://user-images.githubusercontent.com/69505914/172524774-c65ec37c-d829-4742-b0c7-face67e14cb1.png)

**Comment by filecxx** [comment]
我注意到这个问题了，是字符串末尾有一些特殊字节码导致的std::regex正则表达式匹配时出错，所以有时候会失效。

**Comment by fengguowudi** [comment]
> 出错
佬，有没有可能伪装成迅雷客户端，给下载速度偷回来。

**Comment by filecxx** [comment]
> > 出错
> > 佬，有没有可能伪装成迅雷客户端，给下载速度偷回来。

可以，以后版本增加逆向吸血功能，大概3.0之后

**Comment by filecxx** [comment]
我刚注意到，实际上是换行符导致的匹配失败，可以把
-XL00.* 
替换为
-XL00[\s\S]*

**Comment by filecxx** [comment]
> 反吸血有时会失效 ![1](https://user-images.githubusercontent.com/69505914/172524774-c65ec37c-d829-4742-b0c7-face67e14cb1.png)

我刚注意到，实际上是换行符导致的匹配失败，可以把
-XL00.*
替换为
-XL00[\s\S]*
