### ISSUE TITLE
filec未启动，请手动启动

### ISSUE THREAD

**Issue by kyzhdraq** [filecxx/FileCentipede#205]
每次电脑黑屏待机后再亮屏就会出现这个提示，软件没下任何东西，就是纯挂在后台。
不知道是不是因为开着动态壁纸软件Wallpaper Engine和屏幕保护程序的问题。

**Comment by filecxx** [comment]
这个问题已经在2.0版本中修复了。

**Comment by sino1641** [comment]
> 这个问题已经在2.0版本中修复了。

请问2.0计划什么时候发版哇:pleading_face:

**Comment by filecxx** [comment]
> > 这个问题已经在2.0版本中修复了。
> 
> 请问2.0计划什么时候发版哇pleading_face

最快应该在6月15日之后

**Comment by sfanking** [comment]
期待中

**Comment by filecxx** [comment]
OK
