### ISSUE TITLE
Win11 安装错误 Code

### ISSUE THREAD

**Issue by smallironman666** [filecxx/FileCentipede#206]
ARM架构的Win 11 安装失败，显示的错误如图所示
<img width="486" alt="image" src="https://user-images.githubusercontent.com/80607005/170618218-61a2de2f-85a9-4ce5-9c8a-2ea187670e84.png">

**Comment by filecxx** [comment]
错误号3 ： 路径无效

**Comment by smallironman666** [comment]
感谢🙏，已经解决，是因为我的Mac 里的Parallel虚拟机的Win11路径和Mac的路径问题
