### ISSUE TITLE
1.9版的另一个问题

### ISSUE THREAD

**Issue by hikari668** [filecxx/FileCentipede#207]
用了一周左右这个工具是真的不错，发现同一个bt种子在迅雷上下载永远都是比这个工具下载速度高的，就算是热门的bt种子都比不过迅雷的速度。这是什么原因

**Comment by filecxx** [comment]
目前Bittorrent功能和速度几乎和qbittorrent完全一样，迅雷吸血导致的其他客户端下载速度不如迅雷这个问题3.0之后再解决，以后可能增加一个逆向吸血功能，原理是进入迅雷P2P网络伪装成迅雷VIP客户端下载数据，而不上传。目前工作量比较大还没有足够时间做这功能。

**Comment by zzcbun** [comment]
因为迅雷吸血啊，不分享，只吸血，然后放在自己的服务器上，下载就快了，咱们都是靠大家上传来下载的，上传的人越多，下载的越快呢
