### ISSUE TITLE
b站视频chrome插件报错Uncaught TypeError

### ISSUE THREAD

**Issue by sino1641** [filecxx/FileCentipede#208]
浏览b站视频会在chrome插件出现报错：`Uncaught TypeError: r.toFixed is not a function`
1. 已在插件内勾选忽略该网站
2. 有安装[Bilibili-Evolved](https://github.com/the1812/Bilibili-Evolved)油猴脚本
3. 其实不影响正常浏览

附错误内容如下：
"use strict";function float(e,t){e=parseFloat(e);return!0===t?Math.ceil(e)-e!=0:e}function is_numeric(e){return!isNaN(float(e))&&isFinite(e)}function parse_content_ranges(e){if(-1===e.indexOf("bytes "))return null;var t=e.indexOf("-",6);if(-1===t)return null;var n=e.indexOf("/",t);return-1!==n?[parseInt(e.substr(6,t-6)),parseInt(e.substr(t+1,n-1-t))]:null}function extract_url_suffix(e){let t=e.pathname;if(0<t.length){e=t.lastIndexOf(".");if(-1!==e)return t.substr(e+1).toLowerCase()}return""}function extract_file_name(e){let t=e,n=t.lastIndexOf("/");return-1===n&&(n=t.lastIndexOf("\\")),t=-1!==n?t.substr(n+1):t}function extract_headers_value(t,n){for(let e=t.length-1;0<=e;--e)if(t[e].name.toLowerCase()===n)return t[e].value;return null}function try_remake_url(e,r){let a=new URL(e),i=0;return a.searchParams.forEach((e,t)=>{var n,e=e.match(/\d+/g);e instanceof Array&&2===e.length&&((n=parseInt(e[1]))-(e=parseInt(e[0]))!=r-1&&n-e!==r||(++i,a.searchParams.delete(t)))}),0<i&&a.toString()}function remake_url(r,e){let a=new URL(e),i=0;return a.searchParams.forEach((t,n)=>{if(t===r[0]+"-"+r[1])return i++,void a.searchParams.delete(n);for(let e=0;e<r.length;++e)t===r[e]+""&&(i++,a.searchParams.delete(n))}),a.toString()}function bytes_to_str(e){var t=["B","KB","MB","GB","TB","PB","EB","ZB","YB"];let n=0,r=e;if(1024<=e)for(;n<t.length-1&&!(r/1024<1);++n)r/=1024;return r.toFixed(2)+t[n]}function duration_to_str(e){var t=Math.floor(e/60);let n=Math.floor(e-60*t);return t+":"+n.toFixed(0)}String.prototype.hashCode=function(){let e=0,t=0,n=this.length;for(;t<n;)e=(e<<5)-e+this.charCodeAt(t++)<<0;return e};let create_element=function(e,t){let n=document.createElement(e);return t&&(n.className=t),n};function element_offset(e){e=e.getBoundingClientRect();return{left:e.left+(window.pageXOffset||document.scrollLeft||0)-(document.clientLeft||0),top:e.top+(window.pageYOffset||document.scrollTop||0)-(document.clientTop||0)}}function change_page_url(e){let t=document.createElement("a");t.setAttribute("href",e),t.setAttribute("rel","noreferrer"),t.style.display="none",document.body.appendChild(t),t.click()}function copy_to_clipboard(e){const t=document.createElement("textarea");t.style.position="fixed",t.style.opacity=0,t.value=e,document.body.appendChild(t),t.select(),document.execCommand("Copy"),document.body.removeChild(t)}function create_download_links_uri(e,t,n,r,a){let i={"@":"task_confirm_links",links:e,page_url:t,user_agent:n,cookies:r,headers:""};if(t&&"about:blank"!==t&&(i.headers+="Referer: "+t+"\r\nOrigin: "+new URL(t).origin+"\r\n"),"object"==typeof a)for(var o in a)i.headers+=o+": "+a[o]+"\r\n";return JSON.stringify(i)}function create_filec_uri(e,t,n,r,a,i,o){let l={"@":t.stream?"task_add_stream":"task_add","-":"01",uri:e,user_agent:r},s=(a&&(l.cookies=a),"");if("object"==typeof o)for(var f in o)s+=f+": "+o[f]+"\r\n";if(n&&"about:blank"!==n&&(s+="Referer: "+n+"\r\nOrigin: "+new URL(n).origin+"\r\n"),"object"==typeof i)for(var u in i){var c=i[u];c&&(l[u]=c)}return 0!==s.length&&(l.headers=s),"resid"in l&&(l.resid=encodeURIComponent(l.resid)),"string"==typeof t.file_name&&(64<(l.file_name=t.file_name).length&&(e="",-1!==(r=l.file_name.lastIndexOf("."))&&l.file_name.length-r<=8?(e=l.file_name.substr(r),l.file_name=l.file_name.substr(0,r).substr(0,64)+e):l.file_name=l.file_name.substr(0,64)),l.file_name=encodeURIComponent(l.file_name)),config.scheme_u+":0"+Base64.encode(JSON.stringify(l))}function create_filec_magnet_uri(e,t){return config.scheme_u+":0"+Base64.encode(JSON.stringify({"@":"task_add","-":"01",uri:e,page_url:t}))}

**Comment by filecxx** [comment]
这个错误不影响使用，是截取数字小数精度时候发生的，以后有时间时候再修复。
