### ISSUE TITLE
谷歌浏览器插件错误

### ISSUE THREAD

**Issue by yllgod** [filecxx/FileCentipede#211]
{
    "manifest_version":2,
    "name":"__MSG_appname__",
    "version":"1.4",
    "description":"Download files and videos, save your time.",
    "homepage_url": "http://www.filecxx.com",
    "default_locale":"en",
    "icons": {
        "128": "icons/icon.png"
    },
    "background":{
        "scripts":["config.js","libs/base64.js","libs/functions.js","background/mimes.js","background/background.js"],
        "persistent": true
    },
    "browser_action":{
        "default_icon":"icons/icon.png",
        "default_popup":"popup.html"
    },
    "content_scripts":[
    {
        "all_frames":true,
        "js":[
            "config.js",
            "libs/base64.js",
            "libs/functions.js",
            "parser/parser_m3u8.js",
            "content/content_ui.js",
            "content/content_video_bar.js",
            "content/content_injector.js",
            "content/content.js"
        ],
        "matches":["http://*/*","https://*/*","ftp://*/*","file:///*"],
        "run_at":"document_start",
        "css": ["default.css"]
    }],
    "web_accessible_resources": ["config.js","icons/*","content/*","icons/*","libs/*","libs/*/*"],
    "permissions":[
        "<all_urls>","tabs","cookies","contextMenus","notifications","webRequest","webRequestBlocking","webNavigation","storage","downloads",
        "*://*/*","http://*/*","https://*/*"
    ]
}

**Comment by filecxx** [comment]
你可以安装https://github.com/filecxx/FileCentipede/releases里的manifest v3版本的扩展程序，但是manifest v3权限非常低，可能导致一些网站无法正常捕获到视频。
