### ISSUE TITLE
下载的视频没有声音

### ISSUE THREAD

**Issue by ucyo123** [filecxx/FileCentipede#212]
视频是可以下载，但下载的视频没有声音

**Comment by filecxx** [comment]
对应网站提供的资源可能是视频和音频分离的，你需要把音频也下载用其他相应软件来手动合并。

**Comment by HiPowehi** [comment]
学习一下idm的处理方式吧，idm就可以直接下音视频合一的文件。

**Comment by filecxx** [comment]
> 学习一下idm的处理方式吧，idm就可以直接下音视频合一的文件。

建议直接使用IDM下载。
