### ISSUE TITLE
支持 m3u8 完整下载

### ISSUE THREAD

**Issue by isPoto** [filecxx/FileCentipede#213]
我尝试下载 m3u8 链接，结果只能下载该片段。似乎没作支持。

希望能支持 m3u8 链接的所有片段下载、合并，就像 m3u8 下载器的那种效果

**Comment by filecxx** [comment]
m3u8下载提供了完整的支持

![image](https://user-images.githubusercontent.com/100348948/172140762-0b9e91b1-8449-4a00-837b-72c9cf5c3610.png)
![image](https://user-images.githubusercontent.com/100348948/172140804-75dd69bd-50d0-4e55-9019-0bfaad886ab3.png)

或者也可以直接打开本地m3u8文件


![image](https://user-images.githubusercontent.com/100348948/172141107-c53ed49b-ceca-4d87-b667-0351949b179a.png)

**Comment by isPoto** [comment]
理解，感谢您的讲解！
