### ISSUE TITLE
没有上传速度

### ISSUE THREAD

**Issue by Lakida0** [filecxx/FileCentipede#214]
使用Motrix时能正常上传，检查设置发现没有修改DHT和BT监听端口的选项，目前检查怀疑是使用的qbittorrent默认的6881端口导致没有速度，变成吸血端了，即便有upnp和NATPMP，并且有公网ip，建议以后增添随机5位数端口功能

**Comment by filecxx** [comment]
qbittorrent和FileCentipede都用到了libtorrent，由于是端口可以重复使用的，如果2个客户端分配在了同一个端口，确实可能会出现这个情况。自定义端口以后会增加。
