### ISSUE TITLE
网页登录NAS，下载回来的全是1KB的无用文件。

### ISSUE THREAD

**Issue by xingkaijun** [filecxx/FileCentipede#216]
![image](https://user-images.githubusercontent.com/73053408/172534422-8fd18d35-3b2b-4b48-98d5-b35e6b7c50d3.png)
![image](https://user-images.githubusercontent.com/73053408/172534505-478930d1-9bde-401d-a4a0-a32f04058711.png)

**Comment by filecxx** [comment]
比较小的文件是网页上的广告视频，如果在网页上看不到，那是因为被广告过滤插件隐藏了。

**Comment by filecxx** [comment]
另外，用记事本打开那些文件看看是什么内容。

**Comment by xingkaijun** [comment]
代理关了也试过，一样的。
记事本打开内容：

{"error":{"code":119},"success":false}

其他文件下载正常。

**Comment by filecxx** [comment]
是否可以提供下测试地址，这个很大概率是做了防盗链导致的。

**Comment by xingkaijun** [comment]
不好意思公司的群晖，没法提供地址。不过用浏览器和IDM都能正确下载，包括在下载框也能正确识别文件大小。
![image](https://user-images.githubusercontent.com/73053408/172574161-3d70b434-2565-499d-ad1e-7e4c08df8187.png)

**Comment by filecxx** [comment]
如果是webdav可能需要
在headers中添加
Authorization: Basic 帐号:密码(base64编码后)

在新版本发布前我尽量关注下这个问题。

**Comment by filecxx** [comment]
这个问题应该已经解决，请用2.0版本进行测试。
https://github.com/filecxx/FileCentipede/releases/tag/2.0
