### ISSUE TITLE
使用大量下載時是否能增加手動命名的功能

### ISSUE THREAD

**Issue by bear0316** [filecxx/FileCentipede#219]
首先這個軟件十分好用，謝謝大大的開發
想問問有沒有機會在使用Download all和Copy all的時候加入手動輸入檔名的功能
舉例來說某頁面有1-50張jpg，我能夠輸入test，
就能夠得到test_1.jpg,test_2.jpg.......test_50.jpg這樣的功能，十分感謝！

**Comment by filecxx** [comment]
批量設置名稱的功能在2.0-3.0版本期間增加，感謝翻譯，將翻譯檔名設置爲zh_TW.lang之後進行備份，近期將發布2.0版本，增加了很多新條目，請在2.0發布之後提交這個該翻譯，感謝你的貢獻。

**Comment by filecxx** [comment]
2.7 添加了

![image](https://user-images.githubusercontent.com/100348948/187089749-ea8f0af1-489d-4e21-828e-1f923e5075ba.png)
