### ISSUE TITLE
win11安装到指定目录报错

### ISSUE THREAD

**Issue by xaoyao** [filecxx/FileCentipede#22]
win11安装到指定目录报错
![屏幕截图 2022-03-15 141838](https://user-images.githubusercontent.com/12218604/158319094-a401b86a-8891-4b41-ac01-7c59b978988e.png)
手动复制解压的文件也报错，不知道安装失败是不是这个原因
![屏幕截图 2022-03-15 141925](https://user-images.githubusercontent.com/12218604/158319154-aa9a873d-37c8-4b25-aa89-b79866f7dff0.png)
安装到解压目录可以安装成功。

**Comment by filecxx** [comment]
确实是这个符号链接导致的，非常抱歉，我的失误。

**Comment by filecxx** [comment]
新上传的版本已经修复了该问题，感谢测试。
