### ISSUE TITLE
反饋一個BUG

### ISSUE THREAD

**Issue by jhk138** [filecxx/FileCentipede#220]
EDGE狀態下正常下載騰訊企業郵箱的郵件附件（.xlsm),文件蜈蚣下載的EXCEL表格打開後沒有內容，改用瀏覽器下載後，表格是有內容的。請看一下是怎麼回事，謝謝！
騰訊企業郵箱：https://exmail.qq.com/login
電腦系統：WIN10正常更新

![Quicker_20220611_180905](https://user-images.githubusercontent.com/106797383/173183740-3e78463b-4194-434e-80a6-28b8021191e0.png)
![Quicker_20220611_181844](https://user-images.githubusercontent.com/106797383/173183799-1ee701e9-450b-4840-9c4e-ace4f7590462.png)

**Comment by filecxx** [comment]
感謝報告此問題，這個BUG會得到修復。

**Comment by jhk138** [comment]
> 感謝報告此問題，這個BUG會得到修復。

謝謝！

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/releases/tag/2.0
