### ISSUE TITLE
是否不支持ipv6？

### ISSUE THREAD

**Issue by OR120** [filecxx/FileCentipede#222]
特征码2c6b6858d61da9543d4231a71db4b1c9264b0685
![qqqqqq](https://user-images.githubusercontent.com/45073607/173229028-6410425e-1148-4969-b2ee-2236bb71a116.jpg)
![图片](https://user-images.githubusercontent.com/45073607/173229092-62556a4d-4fd4-4873-93b5-53858a1c6359.png)
可以看到文件蜈蚣完全没速度，我没有ipv4公网，有ipv6

**Comment by filecxx** [comment]
支持IPV6, Bittorrent这块的功能和qBittorrent几乎完全一样，比特彗星有速度是因为
![image](https://user-images.githubusercontent.com/100348948/173236050-fca7b31b-fd50-4567-913c-fae629d7cf48.png)
