### ISSUE TITLE
反饋：現在軟件下載完畢後，會自動彈出下載框，希望能增加隱藏软件主题窗口的選項。謝謝！

### ISSUE THREAD

**Issue by jhk138** [filecxx/FileCentipede#223]
現在軟件下載完畢後，會自動彈出下載框，勾選”不顯示已完成對話框“不起作用。
![QQ截图20220612185002](https://user-images.githubusercontent.com/106797383/173229667-72ad06be-c00f-413a-a2d3-a5103f807514.png)

**Comment by jhk138** [comment]
看了下其他人的反饋，發現這個”不顯示已完成對話框“是指其他方面，所以從新修改下反饋：
1.希望开机自启不要弹出软件主题窗口，后台自启就行了；
2.希望能增加隱藏文件蜈蚣的選項，就是點擊下載或添加下載任務開始下載後，一切在後臺處理，可以有聲音提示或在狀態欄圖標閃爍來提示下載完成，軟件的頁面就不要彈出來了。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/173236405-9119b261-6480-4407-ae6a-a17d0b293f5e.png)
1. 在2.0中增加了該選項.
2. 這個也添加了, 2.0版本添加任務之後, 如果啓用了託盤圖標,確實會閃爍, 從瀏覽器添加任務時, 會有氣泡音效.

**Comment by jhk138** [comment]
謝謝！

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/releases/tag/2.0
