### ISSUE TITLE
开启adguard for windows 后浏览器插件不能唤起下载

### ISSUE THREAD

**Issue by xaoyao** [filecxx/FileCentipede#23]
开启adguard for windows 后浏览器插件不能唤起下载，我把adguard保护关了就可以唤起程序下载了

**Comment by filecxx** [comment]
建议反馈到 "adguard for windows" 社区, 应该是把浏览器插件当广告也给过滤了。

**Comment by xaoyao** [comment]
我看日志好像没有拦截
<img width="761" alt="2022-03-15 214607" src="https://user-images.githubusercontent.com/12218604/158392140-616a9ea2-cc28-48b0-b155-01037574daeb.png">
我导出了下，不知道有没有用
[127.0.0.1_adguard_filtering_log_records.zip](https://github.com/filecxx/FileCentipede/files/8253883/127.0.0.1_adguard_filtering_log_records.zip)

**Comment by xaoyao** [comment]
好像是没有过滤，不知道为什么发不过来，我把这个选项关了就好了
![2022-03-16 095501](https://user-images.githubusercontent.com/12218604/158501247-94af47a5-3b75-48ac-8e54-5c52b43a5f19.png)
