### ISSUE TITLE
磁盘缓存

### ISSUE THREAD

**Issue by QAQ5555** [filecxx/FileCentipede#230]
可以出个调整磁盘缓存的设置吗，写入太频繁了

**Comment by filecxx** [comment]
1.9版本在windows上只有暂停或者完成时候才会写磁盘，linux版本由操作系统决定写磁盘频率。

正是因为这个问题导致windows版本下载大文件时候导致内存占用太大，正在修复这个BUG，需要提高写磁盘的频率，2.0版本开始单个文件写磁盘为最低16M

如果1.9版本遇到 "写入太频繁" 肯定不是FileCentipede程序导致的。
