### ISSUE TITLE
匹配文件扩展名 功能部分失效

### ISSUE THREAD

**Issue by HiPowehi** [filecxx/FileCentipede#235]
比如jpg文件，明明匹配文件扩展名中并没有jpg，但实际仍然会调用文件蜈蚣下载。

**Comment by filecxx** [comment]
扩展程序并没有匹配扩展名的功能，匹配扩展名是目前只有分类目录才有该功能，用于自动设置分类。

**Comment by HiPowehi** [comment]
哦，原来如此，那还是应该学一下idm，匹配的就很自然了
