### ISSUE TITLE
1.9 问题咨询

### ISSUE THREAD

**Issue by kkznb** [filecxx/FileCentipede#236]
有这个情况，有的BT文件前一天下载的时候，在任务列表里还能看到，可是隔了一天，就发现不见了。“所有任务”“已完成”等等这些都找了一遍都找不到，“过滤任务”选框搜索也搜不到，然后重新添加BT任务,又提示“重复任务”，想问下有什么办法解决吗？或者是我的操作不正确？

**Comment by kkznb** [comment]
刚才打开软件后，任务列表里又不见了2个种子任务，在下载目录里能看到前几天下载的这个两个种子的文件夹，里边的文件都没下完。可在软件的任务列表里就是找不到。想重新下载吧，但是添加不了任务，软件错误提示“重复的种子”。大佬有什么办法吗？

**Comment by filecxx** [comment]
可以尝试结束filec.exe进程重新打开试试，通常可以解决问题，我目前没有遇到过，确实可能整个列表全部丢失（该问题2.0中修复了），但是单个任务丢失就比较奇怪。

**Comment by kkznb** [comment]
感谢大佬，停用filec，重新启动，问题解决了。丢失的任务又显示出来了。
