### ISSUE TITLE
很多一样ip端口的用户连接

### ISSUE THREAD

**Issue by QAQ5555** [filecxx/FileCentipede#238]
这是bug还是什么新吸血手段啊
![图片](https://user-images.githubusercontent.com/61168182/175079916-71fda590-31bb-4682-9684-b5b67ace6fae.png)

**Comment by filecxx** [comment]
这是BUG，重复字段，没找到问题所在，2.1版本时候修复。

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/releases/tag/2.0
