### ISSUE TITLE
windows 版本中下载文件图标的问题

### ISSUE THREAD

**Issue by asd0109** [filecxx/FileCentipede#239]
![2022-06-23 11 40 38](https://user-images.githubusercontent.com/37428027/175204352-2368bd9f-c199-4665-86c1-10d1ce5a37e7.png)
下载过程和下载结束时图标都会是这样，需要手动刷新一下图标才会变成正常图标。

![2022-06-23 11 40 51](https://user-images.githubusercontent.com/37428027/175204451-e328e52b-4577-41bd-90d8-dadddf0b7aa8.png)

保存位置是桌面，刷新后图标正常。

![2022-06-23 11 41 22](https://user-images.githubusercontent.com/37428027/175204492-51e05718-c7d5-4fb7-876c-391c49e0e5d1.png)

在下载的过程中会发现文件的后缀名都是 EXE 那么如果文件没下载完，图标又没有区别所以用户很难看出来文件是不是下完了。

可以在下载过程中生成一个临时文件     文件.jc     等全部下载完或者合并完后修改为    文件.exe   这样系统估计也会自动修改图标，用户一眼就能看出来哪些文件下载完了，哪些是下载中的。

**Comment by filecxx** [comment]
以后有时间时候增加这个选项，其中有一个副作用是部分的媒体播放器并不具备根据文件元数据判断类型的能力，而是根据文件扩展名，例如mp4等，这可能会导致无法在下载过程中播放。

**Comment by asd0109** [comment]
> 以后有时间时候增加这个选项，其中有一个副作用是部分的媒体播放器并不具备根据文件元数据判断类型的能力，而是根据文件扩展名，例如mp4等，这可能会导致无法在下载过程中播放。

原来这样，那在文件下载完成后让系统刷新一下这样图标也可以变过来，也不会影响那些MP4文件。

**Comment by filecxx** [comment]
下载完之后自动执行某些操作的功能确定会添加。
