### ISSUE TITLE
下载视频总是一段一段的，一个视频有几十段，怎么弄？

### ISSUE THREAD

**Issue by ucyo123** [filecxx/FileCentipede#240]
下载视频总是一段一段的，一个视频有几十段，怎么弄？

**Comment by filecxx** [comment]
对应网站的视频并不是用的m3u8作为流媒体视频，应该是使用js脚本加载的segments进行的进度控制，捕获所有片段进行合并不能解决问题，因为这些分段只会在播放到对应位置时候才会产生，应该解析js文件然后通过猜测的方式进行判断，这能从根本上解决，视频捕获功能在以后版本中会继续完善。

**Comment by filecxx** [comment]
请更新到1.5
