### ISSUE TITLE
这个能解决扩展冲突的问题吗?

### ISSUE THREAD

**Issue by vvyoko** [filecxx/FileCentipede#241]
问题见这个
#173 

最近想到我常用的一个扩展
https://github.com/alexhua/Aria2-for-chrome
它里面有这样的选项
接受来自其他扩展的下载请求
如下图,看起来这个是不接管其他扩展的下载
大大能参考下看看这个能解决本扩展的问题吗
文本大小的选项看起来也不错,小文件就不用调用了...
![1](https://user-images.githubusercontent.com/2145741/175511135-f46a5762-e88d-4eca-b1b6-75240ad4ceff.png)

2,有个小问题
主窗口激活状态下点击托盘图标会正确的显隐窗口
主窗口未激活情况下点击托盘图标会正确隐藏,但显示时不前置,需要手动点任务栏

3,想问下TODO列表中有类似调用外部脚本的东西吗?
就是在某种event时调用外部脚本,传递一些参数给脚本
类似 `Aria2 `的` on-bt-download-complete`
比方说当 下载完成时 -  自定义参数(路径,文件名等等.) - 将参数传递给脚本执行
这样一些需求就可以由它来解决了
比方说下载后改名,下载后移动文件夹等等.

**Comment by filecxx** [comment]
1: 浏览器扩展以后可能会增加这些功能，实现也很简单，不过重要性并不高，在有充足时间时候会添加。

2: 可能不会修复，平台有一定差异性。

3: 任务状态触发事件的功能确定会增加，但是不会在近期添加，最终样式应该是执行一个sml脚本，这样具备更好的灵活性，例如
```
Completed
{
$move_file(path)
$rename(new_name)
$http_get("http://........")
....
}

Created
{
....
}

Error
{
....
}
```
