### ISSUE TITLE
能加入scoop的仓库吗

### ISSUE THREAD

**Issue by CronusLM** [filecxx/FileCentipede#242]
我希望能通过scoop管理文件蜈蚣，想知道用户的配置文件保存在哪，好设置成持久数据

**Comment by filecxx** [comment]
用户配置保存在软件内的lib目录下的，软件目录必须保持可写入才能正常运行。

**Comment by CronusLM** [comment]
https://github.com/ivaquero/scoopet/blob/master/bucket/filecentipede.json
我在这个scoop仓库里添加了文件蜈蚣

**Comment by filecxx** [comment]
2.0版本开始还有3个需要加入
cache/filesystem.db
cache/filesystem.db-shm
cache/filesystem.db-wal

**Comment by CronusLM** [comment]
> 用户配置保存在软件内的lib目录下的，软件目录必须保持可写入才能正常运行。

scoop的数据持久化是将软件的配置文件放在persist文件夹里面，然后硬链接到软件目录

**Comment by CronusLM** [comment]
> 2.0版本开始还有3个需要加入
> cache/filesystem.db
> cache/filesystem.db-shm
> cache/filesystem.db-wal

我是按2.02写的脚本

**Comment by CronusLM** [comment]
> 2.0版本开始还有3个需要加入 cache/filesystem.db cache/filesystem.db-shm cache/filesystem.db-wal

lib\data_windows.db
lib\data_windows.db-shm
lib\data_windows.db-wal

是这三个文件吧，我在脚本里写了

**Comment by filecxx** [comment]
使用文件浏览器访问过任何一个地址之后
cache/filesystem.db
cache/filesystem.db-shm
cache/filesystem.db-wal

这3个文件会自动创建，是用于储存文件列表缓存的。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/175782698-ce8f3e15-26b8-4680-870e-84d94b3c7a0b.png)

**Comment by CronusLM** [comment]
> 使用文件浏览器访问过任何一个地址之后
> cache/filesystem.db
> cache/filesystem.db-shm
> cache/filesystem.db-wal
> 
> 这3个文件会自动创建，是用于储存文件列表缓存的。

根据脚本scoop会在安装时检查persist里是否有这三个文件，有就会直接连接使用，没有就会创建然后连接
