### ISSUE TITLE
提一些小建議：

### ISSUE THREAD

**Issue by jhk138** [filecxx/FileCentipede#243]
文件蜈蚣到目前爲止比較全面的了，等到2.0版本出來就基本OK了。

還是提一些小建議：
1.現在的白名單還是不是很完善，如果現有做法的不能很好支持白名單設置的話，建議參考IDM的類似設置，在白名單方面會有很完善的設置；
2.某些網站下載附件會產生異常，當然，如果白名單可以有專門針對具體網站的設置的話，這個可以系統接管；
3.合適的時候考慮黑暗模式，就是設置跟隨系統設置。

感謝作者的付出！

**Comment by filecxx** [comment]
下載附件的問題應該已經解決了，界面風格你可以嘗試手動修改 ui/css/default.css
