### ISSUE TITLE
webdav 无法使用

### ISSUE THREAD

**Issue by hosxy** [filecxx/FileCentipede#245]
我使用了 webdavs 协议连上了 yandex.disk ，但是不显示任何内容，一片空白。但是使用右键菜单 `新建-创建文件`  创建的文件在 yandex.disk 的网页版确实是存在的，说明确实是连上了。

另外我在 Android 上用 mixplorer 走 webdav 协议连 yandex.disk 没有问题，可以正常显示内容

**Comment by filecxx** [comment]
刚调试找到了原因，程序是获取的D:response ,而返回的是 d:response ,是未对大小写进行转换导致的，感谢能这么快发现这个问题，我稍后更新。

**Comment by filecxx** [comment]
该问题已经在2.02中解决了。
