### ISSUE TITLE
更新到2.02，但之前在youtube等正常下載的視頻，現在點擊沒反應。

### ISSUE THREAD

**Issue by jhk138** [filecxx/FileCentipede#247]
更新到2.02，但之前在youtube等正常下載的視頻，現在點擊沒反應。愛奇異也有一部分沒反應。

https://www.youtube.com/watch?v=ewQk11whVt0

![QQ截图20220625235336](https://user-images.githubusercontent.com/106797383/175781314-f25d06aa-4364-44ba-9c3a-c56333c38095.png)

**Comment by filecxx** [comment]
这应该不是更新到2.02版本导致的问题，因为浏览器扩展还是1.4版本，并未更新。

**Comment by jhk138** [comment]
哦，好的，是會放出瀏覽器擴展的更新嗎?

**Comment by filecxx** [comment]
這個地址我剛才測試是沒有問題的
![image](https://user-images.githubusercontent.com/100348948/175782481-8c191ee8-72f9-4f30-8d07-884689a0de16.png)

目前瀏覽器擴展在youtube上捕獲到的視頻是聲音和視頻分離的，以後瀏覽器擴展版本會添加分辨率的捕獲， 瀏覽器擴展近期不更新。

**Comment by jhk138** [comment]
後來我看了半小時，點擊有反應了。之前1.9是一點就出來的，不知是哪裏出了問題。

**Comment by filecxx** [comment]
不排除是廣告過濾插件將某個遮擋層設置爲了透明。
