### ISSUE TITLE
更新到2.02后，程序无法启动，点击lib文件夹下的fileu.exe没反应

### ISSUE THREAD

**Issue by funnybones2015** [filecxx/FileCentipede#248]
删除了旧版文件后，复制了新版的文件，但双击fileu.exe没反应。。

**Comment by filecxx** [comment]
可以多测试下，我在windows7 和 windows10 全裸系统上测试过无论是覆盖旧版本还是重新安装到新位置，都没有出现问题。

**Comment by sino1641** [comment]
重启试试

**Comment by funnybones2015** [comment]
> 可以多测试下，我在windows7 和 windows10 全裸系统上测试过无论是覆盖旧版本还是重新安装到新位置，都没有出现问题。

我是在删除旧版文件时发现filec.exe这个系统服务进程占用了删不掉，于是结束该进程，再删除了旧版文件。然后换上了新版的文件，然后启动fileu.exe这个主程序文件，无论怎么也启动不了。。。

**Comment by funnybones2015** [comment]
> 重启试试

重启试了不行。又下载了好几次新版的文件压缩包，重新解压出来，然后启动主程序，还是没反应，重启不行。然后重新下载，解压，重启，启动主程序还不行。

**Comment by funnybones2015** [comment]
> 可以多测试下，我在windows7 和 windows10 全裸系统上测试过无论是覆盖旧版本还是重新安装到新位置，都没有出现问题。

或者能否做个安装包而非便携版呢？

**Comment by filecxx** [comment]
这时候再使用1.9版本能够正常启动吗？

**Comment by filecxx** [comment]
在安装时候可以直接覆盖，会自动关闭旧版本的进程，不需要删除。

**Comment by funnybones2015** [comment]
> 在安装时候可以直接覆盖，会自动关闭旧版本的进程，不需要删除。

直接把解压后的新版文件复制到旧版文件夹下就可以吗？因为有进程在使用，以为直接覆盖，会提示文件正在使用中。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/175784910-411aeb4e-23eb-46c0-a809-9a5543c19d87.png)
选择旧版本的路径，点击安装，会自动关闭旧版本进程。

**Comment by funnybones2015** [comment]
> ![image](https://user-images.githubusercontent.com/100348948/175784910-411aeb4e-23eb-46c0-a809-9a5543c19d87.png) 选择旧版本的路径，点击安装，会自动关闭旧版本进程。
> 
> 同时旧版本的数据也会保留。

不是便携版吗？如何出现这个安装界面呢？

**Comment by filecxx** [comment]
安装界面一直存在，这用于初始化一些基础数据保存在lib目录下，安装之后卸载了也可以使用，你确定你使用过之前的版本吗？

**Comment by funnybones2015** [comment]
> 

忘了之前是怎么安装，怎么调出安装界面了。现在下载的都是zip压缩包文件呀。

**Comment by funnybones2015** [comment]
> 忘了之前是怎么安装，怎么调出安装界面了。现在下载的都是zip压缩包文件呀。

忘了之前是怎么安装，怎么调出安装界面了。现在下载的都是zip压缩包文件呀。

> 安装界面一直存在，这用于初始化一些基础数据保存在lib目录下，安装之后卸载了也可以使用，你确定你使用过之前的版本吗？

忘了之前是怎么安装，怎么调出安装界面了。现在下载的都是zip压缩包文件呀。

**Comment by funnybones2015** [comment]
> 安装界面一直存在，这用于初始化一些基础数据保存在lib目录下，安装之后卸载了也可以使用，你确定你使用过之前的版本吗？

忘了之前是怎么安装，怎么调出安装界面了。现在下载的都是zip压缩包文件呀。

**Comment by filecxx** [comment]
可以尝试命令行执行 filec.exe 和 fileu.exe 看看有没有输出任何形式的错误。

**Comment by funnybones2015** [comment]
![image](https://user-images.githubusercontent.com/15063728/175811238-226ae33f-b578-47eb-928a-65fda472d6b2.png)


![image](https://user-images.githubusercontent.com/15063728/175811224-d16c7243-1bd4-4614-babc-6b80c511fbc9.png)

**Comment by filecxx** [comment]
如果UAC确定框没有弹出来，需要右键以管理员权限执行.

**Comment by funnybones2015** [comment]
> 如果UAC确定框没有弹出来，需要右键以管理员权限执行.

命令行就是用管理员权限运行的

**Comment by filecxx** [comment]
这肯定是系统设置问题导致的，或者是其他“安全”软件的干扰，可以在lib目录下创建一个
fileu_win32.conf 文件内容为

```
{"lang":null,"installed":2,"silent_mode":false,"view_nav":null,"fonts":null,"save_window_size":false,"watch_clipboard":true,"no_refresh_address_dialog":false,"view_catalogs":null,"view_statusbar":null,"sound_effects":true,"autostart":false,"no_completed_dialog":false,"font_size":0,"tray_icon":false}
```
然后直接直接fileu可以跳过安装

**Comment by filecxx** [comment]
另外
![image](https://user-images.githubusercontent.com/100348948/175811907-b0f4a9c4-ccdd-4344-ab8a-bcb7b8067b86.png)
是不正确的用法，应该为
filec.exe -i 或者 filec.exe install

**Comment by funnybones2015** [comment]
> 



> 这肯定是系统设置问题导致的，或者是其他“安全”软件的干扰，可以在lib目录下创建一个 fileu_win32.conf 文件内容为
> 
> ```
> {"lang":null,"installed":2,"silent_mode":false,"view_nav":null,"fonts":null,"save_window_size":false,"watch_clipboard":true,"no_refresh_address_dialog":false,"view_catalogs":null,"view_statusbar":null,"sound_effects":true,"autostart":false,"no_completed_dialog":false,"font_size":0,"tray_icon":false}
> ```
> 
> 然后直接fileu可以跳过安装

可以跳过安装了，能启动下载界面了，但是关了以后，下次双击fileu.exe还是打不开的。总不能每次都用命令行来启动吧。。

**Comment by funnybones2015** [comment]
如何进行全新安装呢？能在桌面上也生成图标，双击图标也能启动程序

**Comment by filecxx** [comment]
在软件菜单 - 视图 - 桌面快捷方式 中可以创建。

**Comment by funnybones2015** [comment]
> 在软件菜单 - 视图 - 桌面快捷方式 中可以创建。

为什么双击lib下的fileu.exe就是启动不了程序呢？

**Comment by filecxx** [comment]
我完全不清楚到底怎么回事。
