### ISSUE TITLE
2.02 win10 内存异常占用

### ISSUE THREAD

**Issue by CoderAndHuman** [filecxx/FileCentipede#250]
使用release  filecxx_2.02_win_x64，在新位置重新安装，下载多个种子文件一段时间后，内存占用仍然会一直升高，直到系统卡死。
资源占用情况及系统版本详见截图
![资源占用](https://user-images.githubusercontent.com/61447758/175794313-fb678756-06df-4097-8c78-a77b97e3b5c6.png)
![系统版本](https://user-images.githubusercontent.com/61447758/175794315-1f4f9d90-a212-4d0d-9d52-b0631999162e.png)

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/175794582-5a685377-52ec-45bd-bbbb-0692bd3768a8.png)
Torrent任务是每下载16MB进行一次磁盘写入，如果同时下载多个种子文件，并且速度太快等其他原因，随即磁盘IO消耗太高，写入磁盘的速度跟不上下载速度，这部分内存确实会堆积在内存中，我测试过单个任务20GB，普通机械硬盘，11M/s 没有任何问题，内存使用率保持在30M-70M之间滑动，限制一下同时下载数量试试？

**Comment by filecxx** [comment]
可以尝试安装 system explorer 工具，可以看到进程实际使用的内存，包括未被系统写入硬盘的那一部分缓存。

**Comment by CoderAndHuman** [comment]
通过文件下载速度、磁盘IO及内存占用的对比，我认为问题不在于磁盘IO
![磁盘IO及内存占用](https://user-images.githubusercontent.com/61447758/175812266-b91d3d63-e5b3-4f6f-91bc-10dca9a16f2a.png)
如截图所示，磁盘占用不高（截图时为0），下载速度不快（5KB/s以内），任务不多（一个），仍然出现内存占用持续增加的情况。
在刚开filec的时候，下载速度10MB/s左右，内存占用稳定在30%左右。半分钟到一分钟之后，内存占用慢慢增加，文件下载速度从满带宽到低速，磁盘占用一直没有超过70%。
因此我认为是其他原因导致内存占用升高

**Comment by filecxx** [comment]
能否提供下 磁力连接地址，这个问题似乎没有解决彻底，我尽量今天内尝试把这问题解决。

**Comment by filecxx** [comment]
另外 3.97 GHz 主频CPU 使用率32.7% 也不太正常。

**Comment by CoderAndHuman** [comment]
截图中正在下载的文件是
magnet:?xt=urn:btih:a183ef995a0269f6e2916ee302302ca9cc3bdc44

**Comment by filecxx** [comment]
OK

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/175815219-994a5e22-a1c6-4fcc-8af0-d75826eb518e.png)

我在windows上测试不存在这个问题，内存最高时才50M，CPU平均6%左右，在linux上测试内存始终低于30M.

能提供更多一点的信息吗，比如磁盘空间剩余，分区格式，是否网络映射磁盘，等等。

**Comment by filecxx** [comment]
另外下载进度%0.75 / 46GB  进程内存使用却有9.16G，这一点是最异常的。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/175815475-b63e030f-80d2-4e8b-97db-eef7c2fb1e4a.png)

**Comment by CoderAndHuman** [comment]
![磁盘信息](https://user-images.githubusercontent.com/61447758/175815532-554cc13a-0065-48a7-9aac-47e63a8ba9f6.png)
磁盘为移动硬盘，NTFS类型，使用USB3.0接口，剩余空间4TB以上

**Comment by filecxx** [comment]
换成本地硬盘试试？

**Comment by CoderAndHuman** [comment]
![本地磁盘下载](https://user-images.githubusercontent.com/61447758/175815982-383abf86-f7b3-4931-9c2a-091b2685c500.png)
使用内置磁盘后不再出现内存占用过高的情况。
C盘（NTFS，m.2接口，nvme协议SSD），D盘（NTFS，sata接口，SSD）均无此问题。内置硬盘无机械盘。


![外接硬盘速度](https://user-images.githubusercontent.com/61447758/175816184-9c50d00d-3fd7-4a6c-ae27-af4c037bdf93.png)
外接硬盘理论传输速度足够。出现这个现象原因不明..
.

**Comment by filecxx** [comment]
我测试是使用的机械硬盘，应该不是这个原因，可以尝试随机下载一个http大文件到移动硬盘，如果不会出现内存太大问题那么这个就是libtorrent的BUG。

**Comment by CoderAndHuman** [comment]
![FMD资源占用](https://user-images.githubusercontent.com/61447758/175816673-73cc2d15-af13-4d2a-80d0-19ec62c0d08f.png)
这个截图是使用FDM([Free Download Manager) v5.1进行下载时的资源占用，可以做一个参考

**Comment by filecxx** [comment]
我不确定FDM是使用的libtorrent2.0 可以测试下 qBittorrent

**Comment by CoderAndHuman** [comment]
![qBittorrent资源占用](https://user-images.githubusercontent.com/61447758/175817404-8a9b8ad7-c10d-4c7c-8710-7a61f8b918a2.png)
qBittorrent v4.4.2，未发现问题

**Comment by filecxx** [comment]
我发布下个版本时候更新一下libtorrent试试，我认为应该是libtorrent导致的，因为就一个flush_cache() 函数。

**Comment by filecxx** [comment]
我不确定libtorrent是否修复了这个问题，在qbittorrent中flush_cache似乎下载过程中从未调用，可以试试新版本。
