### ISSUE TITLE
软件能自动检测更新就好了

### ISSUE THREAD

**Issue by hikari668** [filecxx/FileCentipede#251]
1.9自动更新检测不了，要手动下载来替换

**Comment by huanghaobaobao** [comment]
激活码只能激活一天吗？

**Comment by filecxx** [comment]
提供了7天的激活码在某个地方，你能找到。

**Comment by filecxx** [comment]
> 1.9自动更新检测不了，要手动下载来替换

暂时没服务器提供。

**Comment by zzl221000** [comment]
> 暂时没服务器提供。

可以用github release做更新

**Comment by cxrcool** [comment]
> > 暂时没服务器提供。
> 
> 可以用github release做更新

https://github.com/filecxx/FileCentipede/releases
这个链接？

**Comment by filecxx** [comment]
github有流量限制，根据cloudflare上的统计,软件的 zip文件下载总请求次数已经超过 150万，更新一次版本会消耗几TB的宽带，软件现在是公益性质，暂时不提供自动更新。

**Comment by zzl221000** [comment]
> > > 暂时没服务器提供。
> > 
> > 
> > 可以用github release做更新
> 
> https://github.com/filecxx/FileCentipede/releases 这个链接？

对的，用github的Open API

**Comment by filecxx** [comment]
2.5
