### ISSUE TITLE
提示激活码是怎么回事呢？？

### ISSUE THREAD

**Issue by IM515BT** [filecxx/FileCentipede#252]

**Comment by IM515BT** [comment]
![螢幕擷取畫面 2022-06-26 130452](https://user-images.githubusercontent.com/59956201/175800199-ee4d4eaf-e8e1-4569-8439-90fab979429d.png)

**Comment by IM515BT** [comment]
2.0版本

**Comment by IM515BT** [comment]
现在1.3k，目标100k。还有很远的里程嘞

**Comment by filecxx** [comment]
有难度，但是可以实现的。

**Comment by filecxx** [comment]
计算了cloudflare上统计的从1.0开始 filecxx_latest_win_x64.zip 下载次数，如果能做到让每个用户都点个star，现在都能超过500K。
