### ISSUE TITLE
未启动

### ISSUE THREAD

**Issue by xsfh1975** [filecxx/FileCentipede#254]
刚开始用1.9版的时候就出现过，后来不知怎么就好了，现在用2.02又出现了(系统服务打勾了，开机自启没打勾）
![屏幕截图 2022-06-26 165426](https://user-images.githubusercontent.com/78246915/175808902-95f2d8a6-fa52-4cd0-9bd4-34b072c17ab9.png)

**Comment by filecxx** [comment]
点击启动按钮能正常启动吗？这个问题我以为已经完全解决了。是在什么情况下发生的。

**Comment by xsfh1975** [comment]
对，点启动按钮就能正常启动了，就是开机第一次启动文件蜈蚣的时候出现的。如果不启动一下文件蜈蚣，直接点击链接下载文件，会弹出一个红色提示框，我忘了截图了，大概意思也是说文件蜈蚣未启动

**Comment by filecxx** [comment]
系统服务器没有安装成功，在设置里取消勾选，保存之后再次勾选应该可以解决问题，如果不能，表示安装系统服务时候被某个其他软件拦截了。

**Comment by xsfh1975** [comment]
好的，我试试，谢谢

**Comment by xsfh1975** [comment]
刚刚试了，可以
