### ISSUE TITLE
激活码问题

### ISSUE THREAD

**Issue by ArriettyQAQ** [filecxx/FileCentipede#255]
可以给不愿意等待项目标星总量的用户提供收费版吗？愿意为此付费

**Comment by filecxx** [comment]
没有问题，近期内会添加 贡献者 与 赞助者 的永久激活码。

**Comment by ArriettyQAQ** [comment]
> 没有问题，近期内会添加 贡献者 与 赞助者 的永久激活码。

那没问题，赞助的价格能透露下吗？以及赞助方式和授权方式

另外，希望可以推出正式的商业版授权，并改善UI表现，主要是太Linux味了

**Comment by filecxx** [comment]
应该在 20 USD 左右，应该会设计为根据 CPU ID 进行机器绑定，不会联网进行检查，即便有破解也无所谓，我不打算依赖这个赚钱，真正会带来收入的第一个功能是即将添加在文件浏览器 中的 HTTP协议，用户免费使用，而目标网站的站长需要付费（原因暂时不透露）。
