### ISSUE TITLE
新版2.02版从Wing FTP Server站点下载的文件为0字节

### ISSUE THREAD

**Issue by funnybones2015** [filecxx/FileCentipede#256]
如题，从Wing FTP Server站点下载的文件为0字节：

![image](https://user-images.githubusercontent.com/15063728/175868881-9bc98f4f-6807-46fd-a7d2-7b1ab38d565b.png)

![image](https://user-images.githubusercontent.com/15063728/175869136-3f685424-ee88-40dd-bea2-111772409cb2.png)

用浏览器内置下载和其他下载工具下载的文件是正常的。

**Comment by filecxx** [comment]
我稍后修复。

**Comment by filecxx** [comment]
另外只是网页版下载文件是0字节，通过FTP方式下载是正常的吗？

**Comment by funnybones2015** [comment]
> 另外只是网页版下载文件是0字节，通过FTP方式下载是正常的吗？

嗯  目前只是发现网页版下载的文件是0字节，您是指在文件蜈蚣里用FTP协议的链接下载？还是指用专门的FTP客户端下载？

**Comment by filecxx** [comment]
FTP协议下载。

**Comment by filecxx** [comment]
我刚测试了官网的ftp demo,没有问题，似乎就网页版0字节。修复之后和2.1一起发布。

**Comment by funnybones2015** [comment]
> 

ok 谢谢！！

**Comment by filecxx** [comment]
http://www.filecxx.com/en_US/update_log.html

some web servers accepted HTTP range requests but the response code is 200 with 0-byte content, instead of 201, causing a 0-byte file to be downloaded. (wingftp)

**Comment by funnybones2015** [comment]
> http://www.filecxx.com/en_US/update_log.html
> 
> some web servers accepted HTTP range requests but the response code is 200 with 0-byte content, instead of 201, causing a 0-byte file to be downloaded. (wingftp)

用了2.1版后，Wing FTP Server下载文件正常了。太感谢了！！
