### ISSUE TITLE
谷歌拓展程序视频大小显示错误

### ISSUE THREAD

**Issue by mochuen** [filecxx/FileCentipede#259]
在更新了25号的文件后，原1.4版本的拓展程序在下载B站的视频时，显示的视频大小与下载下来的视频大小不匹配。
显示的大小基本都不超过2M，但是下载后的视频却是几百M的。
而youutube等平台未发现此类情况
以上

**Comment by mochuen** [comment]
还有拓展程序也无法拉去B站视频的音频文件

**Comment by filecxx** [comment]
扩展程序还没有更新。

**Comment by filecxx** [comment]
1.5版本扩展进行了很大的更新，可以试试。
