### ISSUE TITLE
下载视频一直出现“地址已过期”，怎么解决

### ISSUE THREAD

**Issue by yuntz8** [filecxx/FileCentipede#26]
下载视频一直出现“地址已过期”，无法正常下载

**Comment by filecxx** [comment]
检查下载视频时候浏览器使用的代理是否和下载时候使用的代理一样，刷新地址之后如果还是出现“地址已过期”，只有少部分防下载处理特别严格的网站会这样，如果方便可以提交下地址，在所有主程序BUG修复完之后会继续修复浏览器扩展相关BUG，感谢提交。

**Comment by mantis3d** [comment]
我今天遇到一样的问题，把浏览器扩展里的“cookie”内容复制到下载任务里就好了。

![图片](https://user-images.githubusercontent.com/2351096/158575498-fd795520-75b9-4e25-a9f6-6ebc0cf2d68a.png)

![图片](https://user-images.githubusercontent.com/2351096/158575532-1c1563a0-6aa6-42dc-8644-6817be5a1c1f.png)

**Comment by yomyo** [comment]
遇到同样的问题，我用的v2raya透明代理
视频地址 https://anime1.me/17155
![image](https://user-images.githubusercontent.com/28732622/158592142-cbfaf2a9-4380-4e01-80b0-59564a7b4921.png)

**Comment by yuntz8** [comment]
> 
按此方法修改后，问题依旧

**Comment by yuntz8** [comment]
> 我今天遇到一样的问题，把浏览器扩展里的“cookie”内容复制到下载任务里就好了。
> 
> ![图片](https://user-images.githubusercontent.com/2351096/158575498-fd795520-75b9-4e25-a9f6-6ebc0cf2d68a.png)
> 
> ![图片](https://user-images.githubusercontent.com/2351096/158575532-1c1563a0-6aa6-42dc-8644-6817be5a1c1f.png)

按此方法修改后，问题依旧

**Comment by filecxx** [comment]
根据你提供的测试地址，这个问题已经在1.3版本中被修复.

**Comment by CAELANYA** [comment]
https://missav.com/abw-326
下载时出现地址已过期，将Cookies复制进url也没用，这个网站的视频都是地址过期

![V8Q%LNSS$TFTK4DHA O 6](https://user-images.githubusercontent.com/125647499/219605269-e7480fa8-3ab3-4b96-8832-2f004fbd0b34.png)

**Comment by filecxx** [comment]
> https://missav.com/abw-326

这个BUG在新版本中已经被修复了，使用2.82版本可以下载

![image](https://user-images.githubusercontent.com/100348948/219669885-158bde25-c9fe-4be7-be41-25654396a346.png)
