### ISSUE TITLE
下载视频提示“地址已过期”

### ISSUE THREAD

**Issue by zzugyl** [filecxx/FileCentipede#260]
1.9版本和最新的版本2.02，都试过，在https://ddrk.me/下载视频，提示“地址已过期”。但是这个网站下载广告正常。
替换过user-agent，也是一样的结果。
这个网站用IDM下载正常。
![2022-06-28_14-40](https://user-images.githubusercontent.com/27466768/176113365-38d57c62-2a0b-4de4-9518-801e4f2af80a.jpg)
![QQ截图20220628143951](https://user-images.githubusercontent.com/27466768/176113441-b90794be-8424-44d0-8e44-334890482109.png)

**Comment by filecxx** [comment]
这确实是一个BUG，2.1版本会修复。

**Comment by filecxx** [comment]
http://www.filecxx.com/en_US/update_log.html
