### ISSUE TITLE
从网页微信下载文件导致filec进度异常无限崩溃

### ISSUE THREAD

**Issue by rihalvnium76** [filecxx/FileCentipede#262]
Win10 LTSC 2019 x64
FileCentipede v2.02和v1.9
Chrome 102
浏览器插件 1.9

手机将一个100kb的doc转发到文件传输助手，在网页版微信用filecxx下载，导致filec进度异常崩溃，且无法停止/删除异常任务，重启filec也会很快就崩溃

![image](https://user-images.githubusercontent.com/57667144/176188251-67228cda-ab69-46af-ad32-5d5a6dd3b164.png)

**Comment by filecxx** [comment]
这个问题会在2.1版本时候修复。

**Comment by filecxx** [comment]
我无法对网页微信进行测试，我借来的微信帐号登陆网页版时候提示
```
由于安全原因，此微信号不能使用网页版微信。你可以前往微信官网 https://weixin.qq.com/ 下载客户端登录。
```

有什么建议吗？

**Comment by rihalvnium76** [comment]
> 我无法对网页微信进行测试，我借来的微信帐号登陆网页版时候提示
> 
> ```
> 由于安全原因，此微信号不能使用网页版微信。你可以前往微信官网 https://weixin.qq.com/ 下载客户端登录。
> ```
> 
> 有什么建议吗？

再换一个号试试？或者创建一个小号？

**Comment by filecxx** [comment]
使用2.4版本再试试，我没办法测试，不过确实修复了几个潜在问题。
