### ISSUE TITLE
2.02版本连接FTP提示504不支持的命令错误

### ISSUE THREAD

**Issue by ChasLeung** [filecxx/FileCentipede#264]
![ftp错误](https://user-images.githubusercontent.com/20138469/176339476-79531101-cfbd-4a89-b654-5769b56f01c7.png)

**Comment by filecxx** [comment]
是打开文件列表吗？还是其他操作例如创建文件等，如果无法列出文件列表，那么属于服务器禁止LIST命令。

**Comment by ChasLeung** [comment]
![GIF 2022-6-29 18-40-41](https://user-images.githubusercontent.com/20138469/176417754-d1cea00f-f032-46d7-bb0c-acdc8685e682.gif)

**Comment by ChasLeung** [comment]
有时候还会出现未处理的错误
![QQ截图20220629184300](https://user-images.githubusercontent.com/20138469/176418095-e798bdae-d28f-429e-8320-fe8ea418f188.png)

**Comment by ChasLeung** [comment]
路径填了也不管用 宝塔里面的 Pure-Ftpd 1.0.49

**Comment by filecxx** [comment]
FTP 504 错误通常只有2种可能性，一个是服务器不支持被动模式，另一个是不支持或者禁用了LIST命令，我稍后测试一下 Pure-Ftpd
