### ISSUE TITLE
filec未启动，请手动启动

### ISSUE THREAD

**Issue by zoenbo** [filecxx/FileCentipede#265]
大佬，始终是“等待中” “filec未启动，请手动启动”，而且重启了也不好使，点“启动”也是无动于衷~退出再打开暂时没问题，过不久就又会弹出来。

**Comment by filecxx** [comment]
是否能够提供一些更详细的信息，比如是否有任务正在上传/下载 ,弹出该界面是否有一定规律等。

**Comment by zoenbo** [comment]
确定是2.02版本，我的是WIN11系统。浏览器是Chrome最新版。就是论坛帖子下载附件时，总是会出现下载失败，然后无限弹出启动Filec，删除任务都无法删除，停止也不行。

**Comment by zoenbo** [comment]
https://bbs.125.la 或者52pojie里随便一个带附件的帖子，论坛需要注册

**Comment by filecxx** [comment]
我刚对 https://bbs.125.la/forum.php?mod=viewthread&tid=13927450 进行了多个平台下测试，都没有发现问题，你使用2.1版本再测试下。

**Comment by filecxx** [comment]
另外文件保存路径是否有特殊符号？ 下载其他网站文件是否正常等。

**Comment by zoenbo** [comment]
路径没有特殊符号，全英文，目前就是任何网站都不能下载，始终就是"filec未启动，请手动启动"，我重装试一下。

**Comment by filecxx** [comment]
你的环境可能比较特别，你确定软件目录有可写权限吗？

**Comment by zoenbo** [comment]
软件目录完全可读写，是本地硬盘。

**Comment by yichangshengwu** [comment]
咱是 linux 用户，
也有遇到会出现 “filec 未启动” 这问题的时候，
基本都是网络意外断开的时候，

还有，
是不是什么优化类工具 ***管家 ***卫士 之类干掉了 filec ？

**Comment by simonecho** [comment]
不启用服务的话就会有这个提示，非常烦人

**Comment by filecxx** [comment]
该问题应该已经在2.3中被修复了。
