### ISSUE TITLE
弹弹play怎么被识别为吸血客户端了

### ISSUE THREAD

**Issue by GitHubXieYihang** [filecxx/FileCentipede#266]
弹弹play在下载磁力链接时也会上传啊，而且它的定位就是共享，我觉得它不应该被认定为吸血虫吧

**Comment by filecxx** [comment]
第二个列表中的属于不持久上传的客户端，也就是当程序关闭之后就停止上传了，所以在做种过程中才会断开，而非第一个列表中的总是断开。你可以把它从列表中删除。

**Comment by GitHubXieYihang** [comment]
嗯，的确是这样
