### ISSUE TITLE
写入文件错误-只读

### ISSUE THREAD

**Issue by ucyo123** [filecxx/FileCentipede#272]
<img width="343" alt="微信截图_20220701223218" src="https://user-images.githubusercontent.com/44857623/176914947-7533388e-93ec-4042-9c82-0a881c6d6e4d.png">
写入文件错误-只读

咋回事？之前1.9都ok

**Comment by filecxx** [comment]
换个目录尝试下，可能是没有写入权限，或者其他问题导致无法写入配置文件。

**Comment by ucyo123** [comment]
果然目录重命名下OK
