### ISSUE TITLE
报错fileu2.2 filec1.9 是因为之前没删干净吗？如何解决

### ISSUE THREAD

**Issue by sbbsdd** [filecxx/FileCentipede#274]

**Comment by filecxx** [comment]
1.9版本的filec正常运行，而fileu是2.2版本的，2者不匹配，建议覆盖安装1.9版本客户端

**Comment by sbbsdd** [comment]
> 1.9版本的filec正在运行，而fileu是2.2版本的，2者不匹配，建议覆盖安装1.9版本客户端

解决了，谢谢
