### ISSUE TITLE
MEGA在CHROME仍然無法下載, 任何一個版本的蜈蚣都不可以(1.9-2.21)

### ISSUE THREAD

**Issue by postman1year** [filecxx/FileCentipede#276]
例如: https://mega.nz/file/LjhimYBJ#4zUi8yPZpzQe0o7SRIx3BL0PNmOCyPalRY7i5prRAYo

在該網頁顯示"已完成", 但無法激活蜈蚣, 而把上述網址複製貼上到EDGE內則可以正常下載(EDGE下載, 非蜈蚣)

**Comment by filecxx** [comment]
我不清楚mega的下載是如何實現的, 似乎應該是自動保存到臨時文件夾完成之後彈出移動文件, 而非傳統方式下載, 我在建設完網站之後會開始完善瀏覽器擴展. 可以在File browser中通過webdav協議 來使用mega.

**Comment by filecxx** [comment]
mega無法通過蜈蚣下載，但2.5+1.6擴展開始已經不會繼續攔截blob:鏈接了。
