### ISSUE TITLE
任务栏图标建议

### ISSUE THREAD

**Issue by bobo521bobo** [filecxx/FileCentipede#277]
任务栏图标下载时给一个状态点，下载完成给一个状态点就行。

ps：能提供换图标功能么？？(￣▽￣)"

**Comment by filecxx** [comment]
从浏览器下载文件时候目前任务栏图标会闪烁几次，如果有好的设计方案请别忘了告诉我。

你应该可以通过exe图标修改器更换图标。

**Comment by bobo521bobo** [comment]
![image](https://user-images.githubusercontent.com/878648/177179187-c8a1fba8-2134-4bee-8b76-7f0d0d827dbf.png)

**Comment by filecxx** [comment]
之前windows状态栏图标闪烁失效，是个BUG，2.4应该修复了这个问题。
