### ISSUE TITLE
分类在缩小窗口的时候不能压缩

### ISSUE THREAD

**Issue by Evilfoxster1981** [filecxx/FileCentipede#278]
分类在缩小窗口的时候不能事先压缩,里面只有一个默认的"全部",可以让缩短的窗口事先压缩么?
还有就是软件名叫蜈蚣下载,但是图标是一个鸭子/鹅,可以统一么?图标难画,就叫DuckDown?

**Comment by Evilfoxster1981** [comment]
我的意思是分类在缩小窗口的时候不能事先压缩高度,里面只有一个默认的"全部",可以让缩短的窗口事先压缩高度么?

**Comment by filecxx** [comment]
我完全不理解 "压缩" 的含义，你是指的不显示空白区域吗？

**Comment by Evilfoxster1981** [comment]
我的意思是.拉动缩小窗口的时候,应该先让空白处先缩短,再是文字的地方.但是这个好像是分类窗口后压缩不管是不是空的.还有就是分类和全部分组之间的分割线应该也是可以拉动缩短空白区域的高度的,但是好像不行.我看windows和linux都是这样.

**Comment by filecxx** [comment]
目前还不足以达到这样的精细程度，我有打算以后放弃Qt5而重新设计一套c++ UI库，到时候会再考虑这些细节设计。

**Comment by Evilfoxster1981** [comment]
就是界面更像一个windows程序么?我看QT的界面总是感觉是在一个模拟机里面.

**Comment by filecxx** [comment]
差不多。
