### ISSUE TITLE
部分界面元素应当设置最小宽度

### ISSUE THREAD

**Issue by zhangleijuly** [filecxx/FileCentipede#28]
设置界面有些问题，左边的选项栏没有设置最小宽度。
默认情况下torrent显示不全，选http就只能看到图标了。
![2022-03-16_163600](https://user-images.githubusercontent.com/1475065/158549734-4cf69124-0416-4e14-9942-036227a89aec.png)
![2022-03-16_163612](https://user-images.githubusercontent.com/1475065/158549778-3225a898-fa92-4d01-a3ec-0f01478aef0d.png)

**Comment by filecxx** [comment]
是的，这个界面让我感觉很不适应，很明显我没有考虑到字体因素带来的影响，这是一个不可忽视的问题，我会修复。

**Comment by filecxx** [comment]
1.3设置里应该没有这个问题

**Comment by zhangleijuly** [comment]
> 1.3 设置里应该没有这个问题
![2022-03-19_091647](https://user-images.githubusercontent.com/1475065/159101016-0bbb4ec8-a004-42e9-8182-8081b15adb24.png)
![2022-03-19_091635](https://user-images.githubusercontent.com/1475065/159101021-cd4ceead-8329-478f-86e1-ba646c49c70a.png)
有点瑕疵，HTTP选项宽度还是比其他选项窄，其他选项宽度一致。

**Comment by filecxx** [comment]
DPI显示问题在1.4版本中会修复.

**Comment by filecxx** [comment]
> > 1.3 设置里应该没有这个问题
> > ![2022-03-19_091647](https://user-images.githubusercontent.com/1475065/159101016-0bbb4ec8-a004-42e9-8182-8081b15adb24.png)
> > ![2022-03-19_091635](https://user-images.githubusercontent.com/1475065/159101021-cd4ceead-8329-478f-86e1-ba646c49c70a.png)
> > 有点瑕疵，HTTP选项宽度还是比其他选项窄，其他选项宽度一致。

已经修复 https://github.com/filecxx/FileCentipede/releases/tag/latest

**Comment by zhangleijuly** [comment]
> > > 1.3 设置里应该没有这个问题
> > > ![2022-03-19_091647](https://user-images.githubusercontent.com/1475065/159101016-0bbb4ec8-a004-42e9-8182-8081b15adb24.png)
> > > ![2022-03-19_091635](https://user-images.githubusercontent.com/1475065/159101021-cd4ceead-8329-478f-86e1-ba646c49c70a.png)
> > > 有点瑕疵，HTTP 选项宽度还是比其他选项窄，其他选项宽度一致。
> 
> 已经修复 https://github.com/filecxx/FileCentipede/releases/tag/latest

默认没有问题，修改字体之后问题就又会出现
