### ISSUE TITLE
激活码到期怎么取消？

### ISSUE THREAD

**Issue by kyzhdraq** [filecxx/FileCentipede#280]
不填新的激活码就一会弹出来一次 怎么才能取消激活码啊

**Comment by IM515BT** [comment]
star要到100k

**Comment by filecxx** [comment]
如果你是项目贡献者(翻译 / 宣传 / 写文档等) ，我能提供给你永久的激活码，非常感谢。

**Comment by kyzhdraq** [comment]
卸载重装了后不填也是过一会就自动弹出来，目的是好的，但是每天都要去找一下激活码填进去就太恶心人了。只能先用回IDM了

**Comment by cocolight** [comment]
加油，以前我也没有意识给优秀的项目点star，后来自己写博客，每次看到有人给点赞或者评论都很开心。这个下载工具很好用，希望作者一直更新下去。
