### ISSUE TITLE
No audio in video stream downloaded files

### ISSUE THREAD

**Issue by IIIPeAceIII** [filecxx/FileCentipede#281]
There's no audio in downloaded files. The files are video only without audio captured from Youtube.

**Comment by filecxx** [comment]
Youtube is not supported yet, maybe the next version will (Chrome extension 1.5).

**Comment by filecxx** [comment]
Try FileCentipede 2.3 with the 1.5 version of the browser extension. It also provided a tool to merge video and audio. See "file merge" from the main menu.
