### ISSUE TITLE
未启动

### ISSUE THREAD

**Issue by xsfh1975** [filecxx/FileCentipede#282]
以前反馈过一次了，大佬告诉我系统服务关闭再打开就好使了，确实管用，但是最新的文件蜈蚣2.21同样的操作就不管用了，系统是win11正式版
![屏幕截图 2022-07-05 183452](https://user-images.githubusercontent.com/78246915/177310801-b771e1ab-b2f8-46de-86dd-6cbee364d346.png)
，大佬原来说是什么拦截系统服务了，电脑并没有装什么管家助手之类的软件，就是系统自带的，而且没有什么拦截的提示

**Comment by filecxx** [comment]
点击启动按钮后可以正常启动吗？

**Comment by xsfh1975** [comment]
点击启动按钮可以正常启动

**Comment by filecxx** [comment]
或者卸载一次再安装。

**Comment by xsfh1975** [comment]
好的，电脑关机了，明天我试试。请问大佬，这个总得关闭系统服务再打开。这是软件bug还是系统原因？

**Comment by filecxx** [comment]
我认为应该是环境问题，出于某种原因而导致的系统服务安装失败。

**Comment by xsfh1975** [comment]
好的，谢谢

**Comment by xsfh1975** [comment]
按你的操作好使了，帮助-安装，那天覆盖安装好像没弄明白，大概是这个原因，请教如何覆盖安装？

**Comment by xsfh1975** [comment]
按你的操作好使了，帮助-安装，那天覆盖安装好像没弄明白，大概是这个原因，请教如何覆盖安装？

**Comment by filecxx** [comment]
安装时候使用以前的路径，就是覆盖安装了。

**Comment by xsfh1975** [comment]
好的，多谢
