### ISSUE TITLE
使用过程中遇到的几个小问题

### ISSUE THREAD

**Issue by huanghaobaobao** [filecxx/FileCentipede#284]
1.同一网络，同一种子文件，对比motrix下载后不上传或上传量很少
2.能否记住软件位置，每次打开软件都会被任务栏遮住一部分，调整后关闭下次打开还是一样
3.trackers能否增加成功更新的时间，而不是链接添加时间

**Comment by filecxx** [comment]
OK

**Comment by filecxx** [comment]
有部分人抱怨上传量太大，这让我有些为难。

**Comment by filecxx** [comment]
2.5
