### ISSUE TITLE
同样的视频，用1.9就能下载，2.21就下载不动。

### ISSUE THREAD

**Issue by mantis3d** [filecxx/FileCentipede#285]
我现在用2.21试图下载[这个网站](https://jable.tv/videos/dass-011/)的视频的时候，发现他下载速度比之前的1.9慢很多，我一开始以为是最大连接数的问题，可是改了也没用，下载速度始终在100左右徘徊。到最后，不是地址过期，就是合并文件出错，总之就是试了好几遍都不行。
于是我又换回1.9下载，结果速度基本保持在2mb每秒，很快下载完成，一次就成功。
麻烦你看看咋回事。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/177807171-cfbd8d22-c668-40a1-aa10-c00a05e2ca6c.png)

我这里是正常的，在设置里把 并行连接 选项的“平滑的”改为“最快的” 试试。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/177807861-0c9a50d7-3f01-4013-a502-c079cf3b4d3f.png)

**Comment by mantis3d** [comment]
果然是把平滑改成最快就好了
