### ISSUE TITLE
窗口显示问题

### ISSUE THREAD

**Issue by xsfh1975** [filecxx/FileCentipede#286]
点击下载链接，弹出的是主界面，把确认窗口挡住了，觉得有点不方便

**Comment by xsfh1975** [comment]
能明白我说的吗？主窗口挡的死死的，这是我挪开了
![屏幕截图 2022-07-09 184757](https://user-images.githubusercontent.com/78246915/178102575-c1d6b760-c0d6-4b88-857d-428b45cf611e.png)

**Comment by filecxx** [comment]
出窗口并不会出现置顶现象，是否和系统设置有关？

**Comment by xsfh1975** [comment]
不太清楚啊，我是win11系统，这个问题已经很久了，不知道别人有没有同样的情况

**Comment by filecxx** [comment]
win11我没有测试过，其他用win11的用户没有反馈过这个问题，程序里确实也不具备置顶到最前的功能，是程序本身导致的这个问题的概率比较小，不过我还是会在下个版本发布前检查一下。

**Comment by xsfh1975** [comment]
好的，多谢

**Comment by filecxx** [comment]
这个问题应该解决了，确实有一处在show() 时候让窗体置顶了。
