### ISSUE TITLE
关于自动更新

### ISSUE THREAD

**Issue by cxrcool** [filecxx/FileCentipede#287]
可不可以让有服务器的自行搭建更新服务，不管是自己用或者公开，有限制的使用的。。。
不能自动更新很难受

**Comment by filecxx** [comment]
可以，但是用户需要添加或者修改这一部分

![image](https://user-images.githubusercontent.com/100348948/178081302-78bf7bac-2981-4e05-844f-86531942a495.png)

**Comment by cxrcool** [comment]
可以呀，服务器直接拉取github存档到服务器中，然后可以直接通过服务器进行下载。这样就避免了git的下载量过高。还可以增加P2P下载，添加一个特定的设置，类似于WINDOWS的传递优化，个人设置是否开启客户端之间的相互更新，不知道这样可不可以

**Comment by filecxx** [comment]
你可以提供一下 2.21 版本的磁力连接地址，或者HTTP地址（未测试），自动更新会根据似钥验证文件完整度，只有我这里可以生成.

这个是从github地址下载的，你保存为 http://yoursite.com/1.json 尝试一下

```
{"version":2.21,"details":"2.21 version.","uri_mac_x64":"","uri_win_x64":"https://github.com/filecxx/FileCentipede/releases/download/2.0/filecxx_2.21_win_x64.zip","checksum_win_x64":3948933090,"checksum_verify_linux_x64":"LAN1lMzad8m4/Zwt2EV1cqY1OFPZYA/A3vgDp+Pdn7GXXZzgOmFHcadrPie4T1RALyfNb7koX3YNgvWqDRjoLL8zwrsa5Bn87/o/tixW+td469yz9FIqGDI19z604mP15DWLiINQiYvssNkQ3tr0UzgsXYSHP61u9mAGtG9ek4c=","checksum_verify_win_x64":"rnB3FGqUdgkS9gI59Q6Y3k/IC+wVq4XzU/qTQQax04fLZ+OKVQ8wZ/WDh9UTOPC1yc+SyC5kAK3DxS6PA6+s0Uk2P4Clep2b/4WzoQ3ksfX2O0sRWm9yQRE6SmX81Vpz43qGx2adkX99oWrjIqmJ7sqkoWOPdGvuoIlScj2ppIY=","checksum_mac_x64":0,"checksum_verify_mac_x64":"LAN1lMzad8m4/Zwt2EV1cqY1OFPZYA/A3vgDp+Pdn7GXXZzgOmFHcadrPie4T1RALyfNb7koX3YNgvWqDRjoLL8zwrsa5Bn87/o/tixW+td469yz9FIqGDI19z604mP15DWLiINQiYvssNkQ3tr0UzgsXYSHP61u9mAGtG9ek4c=","uri_linux_x64":"","checksum_linux_x64":0}
```

**Comment by filecxx** [comment]
这个是通过http下载的，没有测试过，不确定是否能够成功，磁力连接地址是经过测试的，github的地址不能保证所有人可以成功连接。

**Comment by cxrcool** [comment]
[https://cxr.cool/1.json](https://cxr.cool/1.json)
我用2.02版本的测试一下。。。失败了（😔）

**Comment by filecxx** [comment]
你在客户端里创建一个种子，把磁力链接替换json中的http链接试试。

**Comment by filecxx** [comment]
checksum_ 中的数字不能变，程序会解密 checksum_verify 之后判断是否和这个相同，确保本地的zip压缩包的crc32为这个数字。

**Comment by cxrcool** [comment]
![image](https://user-images.githubusercontent.com/93246862/178082903-71eb22d1-4594-4c7d-a10e-1d8854d4b3c6.png)
这样就是正确的吧

**Comment by filecxx** [comment]
是的，正确。

**Comment by cxrcool** [comment]
那就是磁力可以

**Comment by cxrcool** [comment]
之前用2.02做种，本体没办法更新。
后来我用比特彗星重新制作了种子，这次可以下载升级了
![image](https://user-images.githubusercontent.com/93246862/178083698-375d8b99-442e-4ad0-913f-6cf3a0f07dee.png)

**Comment by cxrcool** [comment]
![image](https://user-images.githubusercontent.com/93246862/178083940-c704e20c-14a1-413a-a101-e4cdafb86505.png)
可以正常更新了

**Comment by filecxx** [comment]
这个是libtorrent的机制，有时候需要暂停，然后恢复，不然需要等好一会才能下载，你使用qbittorrent做种你会发现一模一样。

**Comment by cxrcool** [comment]
一直显示正在更新文件，是不是有问题？

**Comment by filecxx** [comment]
这个过程应该不会超过10秒，你关掉对话框，打开软件查看是否已经更新成功了。

**Comment by cxrcool** [comment]
是不是因为我装了两个版本的，一个在C一个在D
启动服务冲突了

**Comment by filecxx** [comment]
不排除这个可能，不过自动更新过程中会遍历进程强行关闭当前软件目录下已经打开文件的进程，你可以尝试下保留一个试试，我测试过并没有问题，另外检查下upgrading里的zip文件是否和做种时候的一样。

**Comment by cxrcool** [comment]
还是不行，upgrading文件夹里的文件已经被解压，手动执行安装后，服务还是会提醒正在更新。。。
重启电脑后运行2.02无法连接服务（服务已启动）

**Comment by filecxx** [comment]
软件下一个版本时候我修复一下自动更新相关功能。

**Comment by cxrcool** [comment]
好的，麻烦了

**Comment by filecxx** [comment]
2.5已经可以自动更新了
