### ISSUE TITLE
url有空格的文件无法下载

### ISSUE THREAD

**Issue by eaglepride** [filecxx/FileCentipede#288]
如题。。。

**Comment by eaglepride** [comment]
还有就是，我安装的第一天进行测试的时候下了两个文件，一个处于选中状态（没留意焦点是否在选中这一行）的文件，右键删除，然后完全删除，结果把两个都给删掉了。。。
另一点是用鼠标选取多个下载文件的时候，有时候只能选中一个

**Comment by filecxx** [comment]
右键删除是删除整个任务，包含子文件，无法对Torrent任务下子文件进行单独删除。

包含空格无法下载的URL是否能够提供下，默认情况程序会把空格转换为 +

**Comment by eaglepride** [comment]
放了个测试文件：
http://s1.d9.fit/tmp/te st.zip
有空格的话，会返回404。

删除的那个，我意思是说，当时有2个任务，我删除其中一个，但结果是把两个都删了。而且这两个都是http，不是bt

**Comment by filecxx** [comment]
http://s1.d9.fit/tmp/te st.zip 
应该是一个BUG，应该转换为
http://s1.d9.fit/tmp/te%20st.zip

删除应该是人为失误，只有选中行和当前行才会删除。

**Comment by eaglepride** [comment]
嗯，还有一种情况，比如我有多个服务器，拖文件回来的时候如果原节点比较慢，我会编辑地址换到另一节点，比如s2.d9.fit，但是似乎已经下载一部分的任务无法编辑url

**Comment by eaglepride** [comment]
或者，有没有可能支持这样的格式  http://s[0..9].d9.fit/xxxxx.zip

**Comment by filecxx** [comment]
编辑任务需要暂停后再编辑，因为已经在下载的连接不会主动断开。

根据规则生成地址已经在计划中了。

**Comment by eaglepride** [comment]
好吧，刚试了下，确实可以编辑，前天试的时候不行。。。
加油，程序做的漂亮

**Comment by eaglepride** [comment]
https://www.tingtao.org/archives/3049.html
做了个推荐，我这有闲置带宽，需要给你弄个下载节点不？

**Comment by filecxx** [comment]
下载节点暂时不弄了，下个版本发布之后我可能会开始推广，流量消耗会非常大，让cloudflare缓存这些会好一点，非常感谢。

**Comment by eaglepride** [comment]
好。我这1G多带宽没地方用，除了下片都不知道干嘛。。。

**Comment by filecxx** [comment]
多下载一点，以后会推出服务器版本和软件内自定义加速服务器。如果提供加速服务器是付费的，我收取20%。

**Comment by eaglepride** [comment]
呵呵，好啊好啊，我这带宽闲置着

**Comment by filecxx** [comment]
2.3中已经修复了这个问题。
