### ISSUE TITLE
希望改进 DPI 自适应

### ISSUE THREAD

**Issue by chrisxvin** [filecxx/FileCentipede#29]
200%缩放的时候，文字相对正常，但图标都很小，然后 UI 控件的缩放没有跟随文字，显得控件小文字大。
![屏幕截图 2022-03-16 170908](https://user-images.githubusercontent.com/628293/158555905-c2da93b4-2042-4482-926c-4cf233e336b8.png)

**Comment by chrisxvin** [comment]
图片在网页上被放大了，不过还是能看出来一些问题的

**Comment by filecxx** [comment]
这个问题会修复，预计一周左右，到时候麻烦您再次帮忙测试。

**Comment by filecxx** [comment]
@[chrisxvin](https://github.com/chrisxvin) 已经修复 https://github.com/filecxx/FileCentipede/releases/tag/latest
