### ISSUE TITLE
任务完成后丢失路径重新下载不显示预估剩余时间

### ISSUE THREAD

**Issue by JohnnyWoong** [filecxx/FileCentipede#293]
![image](https://user-images.githubusercontent.com/5661094/178626995-37e5bed6-0741-4a42-a928-6863cfce1eeb.png)
![image](https://user-images.githubusercontent.com/5661094/178627018-22bc6492-e574-4b0a-a3ba-4d16343dee38.png)

**Comment by filecxx** [comment]
我正在修复BT相关BUG，但我不太明白 "丢失路径" 是什么意思。

**Comment by JohnnyWoong** [comment]
删除下载完成的文件夹重新开始下载

**Comment by filecxx** [comment]
这个问题在2.3中应该已经被修复。
