### ISSUE TITLE
BT任务完成后删除文件重启软件进度归0

### ISSUE THREAD

**Issue by JohnnyWoong** [filecxx/FileCentipede#294]
BT任务完成后删除任务文件, 重启软件, 任务会变成已失败, 再次重启软件, 任务进度就会归0
希望能保留原进度

**Comment by filecxx** [comment]
我尽量，因为BT任务在软件启动时候会验证文件完整度，所以文件不存在时候可能会认为文件损坏了自动重新下载。

**Comment by filecxx** [comment]
这个问题在2.3中应该已经被修复。
