### ISSUE TITLE
torrent统计数据有误

### ISSUE THREAD

**Issue by JohnnyWoong** [filecxx/FileCentipede#296]
完成4个torrent任务, 但显示只完成一个
![image](https://user-images.githubusercontent.com/5661094/178676519-9915be7e-88e5-4962-90a5-c0450d61c9b0.png)

**Comment by filecxx** [comment]
应该是2.2版本更新之后出现的这个BUG。

**Comment by JohnnyWoong** [comment]
是的, 2.2版本

**Comment by filecxx** [comment]
该问题和你提的其他问题一起修复了。
