### ISSUE TITLE
2.21下载视频仍然会有“文件合并错误”

### ISSUE THREAD

**Issue by mantis3d** [filecxx/FileCentipede#299]
如图，最上面三个都是“文件合并错误”
![图片](https://user-images.githubusercontent.com/2351096/179346190-531ac7ed-3798-4008-9233-be5ceb43c330.png)

奇怪的是，我的同一局域网的领一台电脑下载就没问题，设置都是一样的：
![图片](https://user-images.githubusercontent.com/2351096/179346246-6d39d582-6dc4-497b-87ae-21c62983d0cf.png)

最大的区别可能是出现错误的电脑是win7，而正常下载的电脑是win10，但是我不知道这个问题跟系统有关还是由于别的原因。

**Comment by filecxx** [comment]
提供下地址，另外下载过程中是否有暂停恢复。

**Comment by mantis3d** [comment]
[sw859](https://jable.tv/videos/sw-859/)
[rbk051](https://jable.tv/videos/rbk-051/)
[stars625](https://jable.tv/videos/stars-625/)

没有暂停恢复，就是一次性下载到最后就合并文件错误

**Comment by filecxx** [comment]
好的。

**Comment by filecxx** [comment]
m3u8任务现在进行了比较大的完善，应该不会再出现这个问题了。
