### ISSUE TITLE
是否考虑加上，并可以自由选择是否弹出下载确认框呢？

### ISSUE THREAD

**Issue by paynewangw** [filecxx/FileCentipede#30]
刚刚下载试用，绝对是可以打一百分的软件，感谢开发！！！

不过有个小问题就是点击了视频链接就是马上自动按默认下载了，没有给我重命名的机会，也没有给我重新选择存放位置的机会，下版本开发是否考虑加上，并可以自由选择是否弹出下载确认框呢？

**Comment by filecxx** [comment]
没问题，不过应该不是下一个版本，近期几个版本主要发布BUG修复，不过以后版本会增加一个勾选框，由自己决定是否弹出。

**Comment by filecxx** [comment]
1.3 版本已经支持HTTP弹出确定框.
