### ISSUE TITLE
网页下载excel文件，文件名乱码

### ISSUE THREAD

**Issue by jyligx** [filecxx/FileCentipede#300]

**Comment by jyligx** [comment]
![微信截图_20220719101158](https://user-images.githubusercontent.com/29768578/179882847-c6889012-249c-47f3-add2-e8b6797c138b.png)
![微信截图_20220719101209](https://user-images.githubusercontent.com/29768578/179882850-bcad60e5-a188-4575-9395-d916c77a3255.png)
![微信截图_20220719101549](https://user-images.githubusercontent.com/29768578/179882851-c6e97109-ea77-4173-a923-839bb2c9162d.png)

**Comment by filecxx** [comment]
请提供下地址。

**Comment by jyligx** [comment]
网易邮箱  邮件内的附件excel文件和word文件

**Comment by jyligx** [comment]
顺便询问一下激活码功能是什么作用？为什么经常会过期跳出来？需要怎么样才可以不让他跳出来

**Comment by filecxx** [comment]
ok

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/discussions/244

**Comment by jyligx** [comment]
> ok



> #244

激活码我知道在哪里寻找，但是这个每天都要更新激活码吗？有效期只有一天？

**Comment by filecxx** [comment]
这几天内会有用户后台网站，你能在后台中兑换长期激活码。

**Comment by jyligx** [comment]
> 这几天内会有用户后台网站，你能在后台中兑换长期激活码。

上述下载excel文件乱码的问题的确存在的吧？长期激活码哪里兑换？

**Comment by filecxx** [comment]
https://w.filecxx.com/
你可以在这里兑换长期激活码。

**Comment by filecxx** [comment]
> _No description provided._

正在修复这个问题，是否能提供一个临时的账号，因为网易邮箱需要中国大陆手机号才能注册。

**Comment by filecxx** [comment]
> _No description provided._

hello?

**Comment by jyligx** [comment]
> > _No description provided._
> 
> hello?

不好意思这几天忙没看到邮件，测试邮箱：ceshi20220728@163.com     密码：Ceshi$zhanghu

**Comment by filecxx** [comment]
已经在2.3中修复。
