### ISSUE TITLE
[Bug] Downloading Issue

### ISSUE THREAD

**Issue by back2Lobby** [filecxx/FileCentipede#301]
I downloaded a 5GB file this is the output. The file can't be opened (of course).

![bug screenshot](https://user-images.githubusercontent.com/29447722/179946096-e1203408-a705-4416-90f1-e96023796689.PNG)

### So What Actually Happened
It was downloading that file smooth. Then I stopped it at around 40% and after sometime I resumed it. It resumed perfectly and continued downloading but when I checked after sometime it was at around 65% with the status "**operation failed**".

When I tried resuming (pressed start button), it immediately jumped to 100% with status "**completed**" and the file sized turned to **7 Bytes**. I can't resume the download any longer cause its already complete according to this software.

> It was my second attempt downloading that same file. First one was stopped with some kind of expired status at 99.45% 😭 ik it wasn't this software's fault.

Hope it helps finding and fixing the bug.

**Comment by back2Lobby** [comment]
ooops I didn't noticed there was an issue open for this

**Comment by filecxx** [comment]
If the address is expired, the status should be an error instead of completed with 7.00 B size, this is a bug.

Could you provide the URL address? 

I will fix this in the next version.

**Comment by back2Lobby** [comment]
one more thing maybe it has something to do with vpn 😕

**Comment by filecxx** [comment]
Changing the IP address will cause an "Address Expired" error for some websites like "racaty.net", but the "Refresh address" 
 from the context menu only works for online videos, thanks for reminding me.

**Comment by filecxx** [comment]
Fixed in FileCentipede 2.3
