### ISSUE TITLE
在部分网站上接管有问题

### ISSUE THREAD

**Issue by YandLiu** [filecxx/FileCentipede#302]
从这网站下报告，弹不出来下载框
勾选“忽略此站”后，也没有变成浏览器下载，在“下载管理器”中切换为浏览器才行

**Comment by filecxx** [comment]
能提供下地址吗? “忽略此站” 应该和 “下载管理器”中切换为浏览器 是一样的，除非下载地址和当前网站的域名不一样。

**Comment by YandLiu** [comment]
忘贴了
https://www.yanbaoke.com/index

**Comment by YandLiu** [comment]
提供出现此问题的另一个网站，这个不用注册
https://oec.world/en/profile/hs/pharmaceutical-products
![image](https://user-images.githubusercontent.com/26127104/182125160-94d443a4-bea8-4697-8612-dad78c2bb196.png)
![image](https://user-images.githubusercontent.com/26127104/182125225-e98eaa25-5ed3-4153-ae8e-3f2832c8dad5.png)

**Comment by YandLiu** [comment]
更新到2.4，问题已解决
