### ISSUE TITLE
Increase activation duration if possible 

### ISSUE THREAD

**Issue by noobgitusr** [filecxx/FileCentipede#304]
Firstly, Thanks for this awesome software ♥️. Btw, one day activation duration is a big problem for an end user, so please consider alternative solution to this method, Thanks

**Comment by filecxx** [comment]
OK

**Comment by filecxx** [comment]
Please go to the dashboard to exchange a long-term activation code.

https://w.filecxx.com/

**Comment by noobgitusr** [comment]
> Please go to the dashboard to exchange a long-term activation code.
> 
> https://w.filecxx.com/

nice ❤️

![Screenshot from 2022-07-22 14-43-36](https://user-images.githubusercontent.com/106970070/180407028-04b551e6-2159-48b3-9126-9f9dd247bf92.png)
