### ISSUE TITLE
退出程序后为什么任务管理器进程的filec.exe一直会联网传输数据

### ISSUE THREAD

**Issue by arobot1125** [filecxx/FileCentipede#305]
![image](https://user-images.githubusercontent.com/33320479/180597794-7a94ba98-6b6c-48a9-962b-e9d44e0b6c07.png)

并不反感后台服务，流量损耗也不高，但是对这个问题特别好奇。没有下载任务为何会有数据传输？

**Comment by arobot1125** [comment]
![image](https://user-images.githubusercontent.com/33320479/180598094-3b0886f7-58b3-4754-9835-2157b057a2c8.png)

观察了一下，大概5-6s会有0.5KB/s的数据上传。

**Comment by filecxx** [comment]
请问您在发表这个问题之前是否有参考其他BT下载软件，例如qBittorrent deluge uTorrent 等，是否完全一样，因为所有的BT下载软件都会连接DHT网络，这个是用户之间共享元数据的，在安装时候用户隐私条款中有详细说明。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/180598192-ff722422-f5df-4019-a208-683ca1593696.png)

**Comment by filecxx** [comment]
细节方面可以咨询 https://github.com/arvidn/libtorrent 作者

**Comment by arobot1125** [comment]
好的，刚刚测试了BitComet比特彗星，确实同样存在该现象。抱歉，我本以为只使用HTTP不使用磁力不会用到DHT。😀

**Comment by arobot1125** [comment]
请关闭此Issure吧。
