### ISSUE TITLE
以下網站後綴.CSV的文檔無法下載，麻煩看下能否解決？

### ISSUE THREAD

**Issue by jhk138** [filecxx/FileCentipede#306]
https://barge.oneport.com/downloadReport

點下載完全沒反應，選擇 忽略此站都不行，一定要在下載管理器選瀏覽器才能下載到文件；

另外，可否在CHROME網上應用店上架個插件，3的也行啊，現在每重啓一次電腦就要重新裝一次插件，挺麻煩的。
![Snipaste_2022-07-24_00-21-11](https://user-images.githubusercontent.com/106797383/180613764-7ae4d214-2cc1-4444-8b25-67fb839b53b8.png)

**Comment by filecxx** [comment]
麻煩把測試登錄賬號發我郵箱。

**Comment by filecxx** [comment]
把瀏覽器擴展更新至1.6可以解決這個問題。
