### ISSUE TITLE
软件限速没法实现

### ISSUE THREAD

**Issue by lzymbz** [filecxx/FileCentipede#310]
目前使用的是2.21版本，限速功能不起作用

**Comment by filecxx** [comment]
不太可能，你是怎么设置的？

**Comment by lzymbz** [comment]
我想可能是我理解错了
刚开始我设置的这里
![2](https://user-images.githubusercontent.com/110078020/181755690-340fd23f-3c2c-4115-bc7c-cf7acfd76114.png)
然后结果如图

![1](https://user-images.githubusercontent.com/110078020/181755890-8469434b-a54b-40a0-9706-a7017a52f4d4.png)


然后我通过下面的设置好像起作用了

![3](https://user-images.githubusercontent.com/110078020/181756020-f9722aba-10b7-407b-ba3b-7f37671a6e73.png)

**Comment by filecxx** [comment]
设置里的限制速度也是有效的，不过那是默认值，如果任务已经创建之后再修改，那么就会无效，需要从菜单中编辑任务，然后设置速度限制。
![image](https://user-images.githubusercontent.com/100348948/181781486-e0549eee-c52a-4dce-85ce-ca6445173b47.png)

**Comment by lzymbz** [comment]
> 设置里的限制速度也是有效的，不过那是默认值，如果任务已经创建之后再修改，那么就会无效，需要从菜单中编辑任务，然后设置速度限制。 ![图片](https://user-images.githubusercontent.com/100348948/181781486-e0549eee-c52a-4dce-85ce-ca6445173b47.png)

好的，感谢，有没有考虑建个QQ群呢，这个网站使用还是有些不方便。

**Comment by filecxx** [comment]
https://gitter.im/filecxx/FileCentipede
