### ISSUE TITLE
下载大文件时遇到的问题

### ISSUE THREAD

**Issue by 1779587460** [filecxx/FileCentipede#317]
在下载大文件的时候，过一会就会突然没速度，而暂停又开始后恢复正常，但过会又会没速度
这个没速度的意思是文件那栏是又下载速度的，但进度不会加，客户端右下角的下载速度显示0
[这是当时下载的文件](http://assets1.xboxlive.cn/10/de07f245-b452-444e-8ef4-67811de7467b/c3b62490-4b26-4191-a3d2-3704cbdeb301/1.0.26.0.0648f5d3-d66e-47ec-bd0b-b74ba2dddfa3/IOInteractiveAS.PC-HITMAN3-BaseGame_1.0.26.0_x64__6h0y724g59e1w.msixvc)

**Comment by filecxx** [comment]
我现在测试这个链接是正常的，我明天再测试一下，是否磁盘空间不足？

**Comment by 1779587460** [comment]
磁盘空间足够

**Comment by filecxx** [comment]
这个问题应该属于任务正常下载，但是界面上没有刷新，2.3版本应该没有这个问题了。
