### ISSUE TITLE
关于缓存路径不可选的问题

### ISSUE THREAD

**Issue by kofzhanganguo** [filecxx/FileCentipede#321]
![image](https://user-images.githubusercontent.com/32073931/182186510-3b6131c9-aa0d-4520-be6a-9ac2187c335d.png)
这两个位置选择为什么是灰色的，而且不可以选择自己设置的路径位置？

**Comment by filecxx** [comment]
功能已经存在，但未做完全的测试，例如下载过程中暂停修改，移动等，完全测试之后会取消禁用。
