### ISSUE TITLE
Chrome的CRX和ZIP里面的LOCAL沒有加繁體

### ISSUE THREAD

**Issue by postman1year** [filecxx/FileCentipede#322]
[chrome_crx_mv3_add-TW.zip](https://github.com/filecxx/FileCentipede/files/9240463/chrome_crx_mv3_add-TW.zip)
Chrome的CRX和ZIP里面的LOCAL沒有加繁體, 我加了, 麻煩有時間查看一下, 如果有需要就更新, 沒有需要就算了(我自用)

**Comment by filecxx** [comment]
我忘記了瀏覽器擴展的翻譯，我已經放入資源中，會出現在1.6，暫時可能不會更新，因爲EDGE商店審查很慢。感謝。
