### ISSUE TITLE
win映射的smb网盘无法成为下载保存地址

### ISSUE THREAD

**Issue by 23Ben** [filecxx/FileCentipede#323]
win映射的smb网盘无法成为下载保存地址。麻烦up主看看能否修复。

**Comment by filecxx** [comment]
不行，以后也不行，非本地磁盘不支持文件映射，这是操作系统的限制。

**Comment by 23Ben** [comment]
我不太懂，就是好奇，请问idm，迅雷等弱鸡下载软件都是怎么做到通过smb写入的呢？

**Comment by filecxx** [comment]
写入方式不同，大多数其他下载工具都是通过 FILE* fopen(path,"wb") 方式写文件
文件蜈蚣使用的是文件映射，libtorrent2.0开始也是使用的文件映射 （windows上的mapviewoffile）, 这样的方式对文件读写效率更高, 对比IDM，可以不用在下载完毕之后花很长时间合并文件, 对比迅雷，下载大文件不会几秒卡一次.

但是windows系统的SMB是2.0的，不支持文件映射, SMB3.0才开始支持。
