### ISSUE TITLE
赞助终身的激活码能激活几台电脑呀

### ISSUE THREAD

**Issue by qiaoyun680** [filecxx/FileCentipede#325]
开发不易 但是不知道终身激活码可以激活几台电脑呀…重装电脑或者换了电脑 还需要再次购买吗

**Comment by filecxx** [comment]
绑定的CPU，只要是同一型号同一批出货的CPU ID可以使用，重装系统，更换/添加 其他硬件是可以继续激活的。

**Comment by qiaoyun680** [comment]
能否考虑增加点儿激活电脑的数量…家里三台电脑…=.=

**Comment by filecxx** [comment]
激活一台之后把另外2台的UID发我邮箱，我给你生成.
