### ISSUE TITLE
關於繁體中文的強逼症狀

### ISSUE THREAD

**Issue by postman1year** [filecxx/FileCentipede#326]
[zh-TW-Fix0803-Postman1year.zip](https://github.com/filecxx/FileCentipede/files/9249233/zh-TW-Fix0803-Postman1year.zip)

重新修正如上, 發現有些仍然是繁簡混合, 所有錯誤已修正在上面ZIP包內, 有時間對照一下, 謝謝!
![1](https://user-images.githubusercontent.com/7483788/182556784-460f1ac4-2a3c-459c-b911-d130bcae324d.jpg)
![2](https://user-images.githubusercontent.com/7483788/182556843-34f345f8-aee3-429f-9039-e807cea63226.jpg)
![3](https://user-images.githubusercontent.com/7483788/182556891-af7b1646-7673-4cf7-840b-30517a0ac046.jpg)
![4](https://user-images.githubusercontent.com/7483788/182556937-361d4f70-c803-44b5-bb23-c86b683a4977.jpg)
![5](https://user-images.githubusercontent.com/7483788/182557017-9779344f-af7b-443d-bed8-41589600ef11.jpg)

**Comment by filecxx** [comment]
已經替換爲新翻譯，感謝。
