### ISSUE TITLE
How can I build the target with source code?

### ISSUE THREAD

**Issue by cucube** [filecxx/FileCentipede#327]
How can I build the target with source code?  There are many dependency librarys error when configure the project with cmake.
TKS

**Comment by filecxx** [comment]
Depended libraries are not open source yet. Those are different projects, and (more) bigger than this one.

**Comment by cucube** [comment]
> Depended libraries are not open source yet. Those are different projects, and (more) bigger than this one.

So, this repo is a fake open source code project?

**Comment by filecxx** [comment]
see RESUME.MD, I made it very clear.

```
FileU source code is in the source_code directory, this source code is for demonstration purposes only, it's full source code, but dependent libraries are not open source.
```
