### ISSUE TITLE
还是老问题（无法启动）

### ISSUE THREAD

**Issue by xsfh1975** [filecxx/FileCentipede#329]
win11专业版，文件蜈蚣版本2.4，开机第一次打开还是无法启动，用你以前教我的方法（重新关闭打开系统服务）也不好使
![屏幕截图 2022-08-07 082912](https://user-images.githubusercontent.com/78246915/183270211-48f7b7be-50e9-4a31-816f-c928da9486af.png)

**Comment by filecxx** [comment]
在帮助-> 安装 上勾选系统服务，安装, 或者以管理员权限执行 ```filec -i system_service```尝试下。

并没有收到其他win11用户反馈该问题，可以检查下是否被 安全软件(病毒) 把系统服务禁用了.

**Comment by xsfh1975** [comment]
点击下载链接就出现这个
![Uploading 1.png…]()

**Comment by xsfh1975** [comment]
点击下载链接就出现这个
![1](https://user-images.githubusercontent.com/78246915/183285851-0cf9e2c4-9779-4238-8b2d-76dfe56222d2.png)

**Comment by filecxx** [comment]
点击 
![image](https://user-images.githubusercontent.com/100348948/183286097-0e5fa4c6-5c9e-4100-a9a5-acc1f6014959.png)
