### ISSUE TITLE
Release 命名问题

### ISSUE THREAD

**Issue by alex3236** [filecxx/FileCentipede#33]
1. Github 已经自带 Latest 提示，不需要将版本命名为 latest

![图片](https://user-images.githubusercontent.com/45303195/158708002-ef080997-9c08-4c05-a20c-4b40e3ca9f60.png)

2. 建议每个大版本只发一次 Release（如 1.0~1.x.x只发1.0，之后每个小版本修改 Release 的 tag 为最新版本），
或者每个小版本发一次，不要 `1.0` 发一次， `1.1` `1.2` 合在一起。

3. 以上只是个人建议，这样方便管理，如果有个人习惯请忽略（

**Comment by filecxx** [comment]
从2.0开始用你建议的方式, 现在给一些下载站提交了PAD文件，地址是1.0地址，1.0有大量BUG，所以才有了这个问题。
