### ISSUE TITLE
Chromium 1.51扩展导致部分网页无响应

### ISSUE THREAD

**Issue by login404** [filecxx/FileCentipede#331]
复现步骤:
1.启用1.51mv2扩展
2.打开https://bbs.kafan.cn/thread-2241037-1-1.html
3.网页会有一段时间无响应 此时CPU使用率飙升
关闭1.51mv2扩展后问题消失

**Comment by filecxx** [comment]
1.5版本扩展开始已经支持了从JS中分析视频地址，但是JS中如果深度过大，确实可能很慢，下个版本修复。

**Comment by filecxx** [comment]
这个页面中的JS有很多个数组，数组只有1-2个元素，不过数组的length值却超过500万，这是个虚假的值。

通过这种方式定义的
```
var temp = [];
temp[5623245] = 1;
```
对方应该是把数组当作对象在使用了，这确实是个潜在的问题，已经修复，会和2.5版本一起发布。

**Comment by filecxx** [comment]
网站上和扩展商店里提供了1.6版本，可以更新尝试下，该问题已经解决。
