### ISSUE TITLE
界面卡死

### ISSUE THREAD

**Issue by JohnnyWoong** [filecxx/FileCentipede#332]
从2.2的版本到目前版本(2.4) 下载磁力任务时缩小到托盘区挂机一段时间, 再次点开发现界面卡死(指任务进度, 即时上传速度和下载速度, 以及统计信息不会变更, 但任务实际上仍在下载, 且无法正常添加其他下载任务, 无法弹出下载任务窗口), 重启界面程序并未好转且数据错误, 需结束filec进程并重启才会恢复, 并且任务进度和统计都会正常增长

**Comment by filecxx** [comment]
能否提供一下复现步骤，和对应的磁力链接。

**Comment by filecxx** [comment]
前几天收到过类似的反馈
```
If the app is left running for a while and I hibernate the OS for very long hours, and I resume back, all the download tasks disappear from the table, and I can't add any new task. I would have to exit the app and also terminate the filec process and restart before everything starts working again with the previous tasks now showing. Couldn't really verify the cause because just hibernating and resuming doesn't cause the issue. It could be Windows Defender interfering with the filec process if left running for a long time so not sure if it is a bug.
https://i.imgur.com/4GW9O6v.png
```
情况是否和图片中的一样，2.2之前是否发生过这样的情况。

**Comment by JohnnyWoong** [comment]
不太一样, 这是我尝试只重启界面端会出现的样子, 未重启前任务数和正在下载的任务都在, 只是上传和下载速度不会动了;
2.2版本前我个人是没有遇到, 个人觉得跟磁力链接没有关系, 因为不止一个遇到这个问题, 复现步骤我无法准确提供, 因为不知道具体是什么原因导致的. 我只做了以下3步
1.  下载磁力任务
2.  缩小至托盘区
3.  一段时间后从托盘区打开
2到3步会重复执行, 中间隔一段时间

**Comment by filecxx** [comment]
```
不太一样, 这是我尝试只重启界面端会出现的样子
```
重启界面之后也是任务列表没有任务，但是左侧仍然有数字吗？

**Comment by JohnnyWoong** [comment]
> 

是的

**Comment by filecxx** [comment]
目前已知BUG中应该只剩下这一个还没修复了，如果想起其他细节，或者需要补充的，请尽量补充。

**Comment by filecxx** [comment]
这个很难测试出来，所以细节越多越好。

**Comment by JohnnyWoong** [comment]
好的, 是否有日志之类的, 下次遇到时我直接导一份日志

**Comment by filecxx** [comment]
这个版本没有日志，下个版本增加了一个程序抛出异常时候写日志文件，不过这个问题应该是其他导致的，因为确实正确统计出了数字，因为不知道问题所在，我只能反复测试。 

另外
```
重启界面程序并未好转且数据错误
```
数据错误是什么样子的，我不是很理解。

**Comment by JohnnyWoong** [comment]
数据错误就是

> https://i.imgur.com/4GW9O6v.png
这张截图展示的内容, 左边有数字, 但统计出的数字和我实际下载的并不一致

**Comment by filecxx** [comment]
好的。

**Comment by filecxx** [comment]
我测试了2天，没有测试出来，我不确定2.5版本是否还存在这个问题，不过文件菜单中增加了强制重启项，无法复现的情况下我没办法定位问题所在，如果还遇到了这个问题留意一下，并且查看下cache目录下是否有exception.log文件。

**Comment by DLXCTV** [comment]
下载 磁力链接或者种子，然后最小化到托盘，这时候你可以去忙其他的事情，每次我发现都是玩几个小时游戏之后才发现的，这时候，你增加任务，点击做种的任务停止，或者停止任务等等所有操作都不好使，在托盘右击退出后 ，再打开发现里面没有任何任务，必须任务管理器里 把fileu这个进程给结束任务后  再开程序 才会出现之前的任务。

**Comment by DLXCTV** [comment]
说错了  是任务管理器里关闭 filec.exe，另外  cache目录 我不清楚在哪里找

**Comment by filecxx** [comment]
> 下载 磁力链接或者种子，然后最小化到托盘，这时候你可以去忙其他的事情，每次我发现都是玩几个小时游戏之后才发现的，这时候，你增加任务，点击做种的任务停止，或者停止任务等等所有操作都不好使，在托盘右击退出后 ，再打开发现里面没有任何任务，必须任务管理器里 把fileu这个进程给结束任务后 再开程序 才会出现之前的任务。

程序目录下cache目录是自动创建的，默认没有，我怀疑很可能是磁力或者种子任务的关系，下次如果还遇到，麻烦提供下对应的磁力链接。

**Comment by DLXCTV** [comment]
我是 win10专业版  版本号是2004  操作系统版本是  19041.329    不知到这个有没有帮助

**Comment by DLXCTV** [comment]
> > 下载 磁力链接或者种子，然后最小化到托盘，这时候你可以去忙其他的事情，每次我发现都是玩几个小时游戏之后才发现的，这时候，你增加任务，点击做种的任务停止，或者停止任务等等所有操作都不好使，在托盘右击退出后 ，再打开发现里面没有任何任务，必须任务管理器里 把fileu这个进程给结束任务后 再开程序 才会出现之前的任务。
> 
> 程序目录下cache目录是自动创建的，默认没有，我怀疑很可能是磁力或者种子任务的关系，下次如果还遇到，麻烦提供下对应的磁力链接。

这个 经过我这一段时间上 使用时发现  不管你是下 正经的电影，还是不正经的电影，或者是种子、磁链的游戏 都会发生这种问题

**Comment by filecxx** [comment]
2.5还有这个问题吗？

**Comment by JohnnyWoong** [comment]
> 2.5还有这个问题吗？

目前用了两天, 暂未复现

**Comment by DLXCTV** [comment]
单位太忙了 ，这两天没回家，今晚上回家试试

**Comment by login404** [comment]
同时挂着做种几小时就会复现了
快的话不到2小时

magnet:?xt=urn:btih:9fb9254c1f93c02bd5c62cbf4ce13cdb0d77071b
magnet:?xt=urn:btih:3b902be0d117d1c4b55c334ddb2a533e6ffa7ab4
magnet:?xt=urn:btih:068d579c98c9b9612c8f20b0d024528d51f6e894
magnet:?xt=urn:btih:f8f5f2e14a1e354779c56379276c2c3552a024ca
magnet:?xt=urn:btih:273d52d8bb60da79fdc7aef5101cfa1f8b7092b9
magnet:?xt=urn:btih:fde7aa4e93b319cdb28b9466f7c7493df04170b4

**Comment by DLXCTV** [comment]
还有 这个问题

**Comment by filecxx** [comment]
软件的目录下的 cache目录下是否存在exception.log文件

**Comment by login404** [comment]
没有exception.log文件
不过我现在也复现不了了

**Comment by wsy998** [comment]
> 2.5还有这个问题吗？

我的是win11 也出些类似的问题，界面完全任何反应，但右击能和菜单能呼出，但单击没有任何反应（包括删除任务说明的），重启软件之后才能恢复

**Comment by wsy998** [comment]
版本是2.5

**Comment by filecxx** [comment]
> 版本是2.5

左侧是否也有小数字，但任务列表为空？
另外任务列表如果为空是否能选中，只是文件名显示为空。

**Comment by wsy998** [comment]
界面显示的很完整，就是操作不了

**Comment by filecxx** [comment]
这几天一直在找该问题，没办法复现，所以定位不到问题，还有其他细节能提供吗？

**Comment by wsy998** [comment]
个人感觉是好像是挂起后没有及时恢复，而且是时不时出现，有日志会生成吗

**Comment by JohnnyWoong** [comment]
刚刚也复现了, 后台挂了不到3分钟, 再打开就出现问题, 没有exception.log文件

**Comment by filecxx** [comment]
> 个人感觉是好像是挂起后没有及时恢复，而且是时不时出现，有日志会生成吗

如果cache/exception.log 不存在那就没日志了，IPC共享内存通信也不太好做日志，另外是否只有系统挂起恢复之后才会出现这个问题。

**Comment by wsy998** [comment]
我这连cache目录都没生成。。。

**Comment by filecxx** [comment]
> 刚刚也复现了, 后台挂了不到3分钟, 再打开就出现问题, 没有exception.log文件

是否也是win11系统

**Comment by wsy998** [comment]
![image](https://user-images.githubusercontent.com/62003729/185738695-09f66365-73bc-4dc6-84ed-218ba96db005.png)


貌似还堵塞了下载界面弹出，这个问题就有点大了

**Comment by filecxx** [comment]
推出软件界面，重新打开，任务列表是否能加载

**Comment by wsy998** [comment]
> 退出软件界面，重新打开，任务列表是否能加载

可以，但是删除之类的操作是没有执行的，还是删除之前的列表，还有我发现BT追踪器的列表也会被卡没，点更新订阅也没效果，重启后就恢复了

**Comment by filecxx** [comment]
希望别是我最担心的问题，线程死锁，这几天会发布2.6版本，提供了远程功能，到时候测试一下通过 127.0.0.1 连接的是否也存在这个问题。

**Comment by wsy998** [comment]
就是webui？

**Comment by filecxx** [comment]
和当前软件界面完全一样。只是通过IP/域名连接，webui应该不需要了，会无限延期。

![image](https://user-images.githubusercontent.com/100348948/185739289-b85bcc7c-0749-42df-826b-4cc3457a1b6a.png)

**Comment by wsy998** [comment]
就是从IPC变成网络连接是吧

**Comment by filecxx** [comment]
是的

**Comment by JohnnyWoong** [comment]
> > 刚刚也复现了, 后台挂了不到3分钟, 再打开就出现问题, 没有exception.log文件
> 
> 是否也是win11系统

是的, win11, 确实会卡死下载界面弹窗, 并且强制重启后之前未弹出的下载弹窗会一次性弹出

**Comment by JohnnyWoong** [comment]
win10也有这个问题

**Comment by filecxx** [comment]
再出现的时候试试执行 filec torrent_port ，看看是否有任何输出，或者执行 filec stop 是否能够成功停止，这样我大概知道是否IPC问题了。

**Comment by filecxx** [comment]
更新至2.6版本试试，我确实测试不出来，如果2.6版本还有这个问题可以使用远程127.0.0.1尝试下。

这个问题如果不解决应该不会再发布新版本了。

**Comment by login404** [comment]
刚更新就复现了…
filec ports没有输出
filec stop因为路径搞错了没试出来
不过filec ports都直接卡住了应该也是无效的

![动画](https://user-images.githubusercontent.com/69505914/185790267-c4cbe8bc-46e7-4418-8db4-f45452b4ae4f.gif)

**Comment by filecxx** [comment]
> 刚更新就复现了… filec ports没有输出 filec stop因为路径搞错了没试出来 不过filec ports都直接卡住了应该也是无效的
> 
> ![动画](https://user-images.githubusercontent.com/69505914/185790267-c4cbe8bc-46e7-4418-8db4-f45452b4ae4f.gif) [ ![动画](https://user-images.githubusercontent.com/69505914/185790267-c4cbe8bc-46e7-4418-8db4-f45452b4ae4f.gif) ](https://user-images.githubusercontent.com/69505914/185790267-c4cbe8bc-46e7-4418-8db4-f45452b4ae4f.gif) [ ](https://user-images.githubusercontent.com/69505914/185790267-c4cbe8bc-46e7-4418-8db4-f45452b4ae4f.gif)

更新到2.61试试，2.6版本之前升级了wolfssl导致了出现很多问题，现在降级回去了。

**Comment by JohnnyWoong** [comment]
> 再出现的时候试试执行 filec ports ，看看是否有任何输出，或者执行 filec stop 是否能够成功停止，这样我大概知道是否IPC问题了。
> 
> 另外注意下这时候filec的cpu使用率是否正常。

WIN10: cpu使用率正常, ports正常输出, STOP未能停止, stop可以停止, CPU使用率正常
![image](https://user-images.githubusercontent.com/5661094/185854737-43f661c0-be98-4404-8ef6-eec9941eee7a.png)

**Comment by login404** [comment]
建议添加任务的窗口打开时
自动禁用剪贴板监视

**Comment by filecxx** [comment]
我通过远程连接到服务器上复现了这个问题，几次 连接 -> 断开 后就会出现，filec ports 命令冻结，下个版本应该可以修复。

**Comment by DLXCTV** [comment]
喜大普奔

**Comment by filecxx** [comment]
这个问题确实是线程死锁导致的，造成该问题的前提条件为：任务列表中存在 种子/磁力 任务，不论这个任务是否正在下载/上传。

**Comment by filecxx** [comment]
http://www.filecxx.com/release/filecxx_2.7a_win_x64.zip
测试一下这个版本，该问题应该完全解决了，但涉及到构架变化，不排除创造了新BUG。如果该版本没有问题，这2天就发布正式版本。

**Comment by login404** [comment]
> http://www.filecxx.com/release/filecxx_2.7a_win_x64.zip 测试一下这个版本，该问题应该完全解决了，但涉及到构架变化，不排除创造了新BUG。如果该版本没有问题，这2天就发布正式版本。

配置不能正常读取跟保存…

**Comment by filecxx** [comment]
> > http://www.filecxx.com/release/filecxx_2.7a_win_x64.zip 测试一下这个版本，该问题应该完全解决了，但涉及到构架变化，不排除创造了新BUG。如果该版本没有问题，这2天就发布正式版本。
> 
> 配置不能正常读取跟保存…

什么配置

**Comment by login404** [comment]
![动画](https://user-images.githubusercontent.com/69505914/186400494-df6b9a86-32f5-4488-9894-5e593daef98e.gif)

**Comment by filecxx** [comment]
在这种状态下是否能下载文件。

**Comment by login404** [comment]
无法下载 直接无效路径

**Comment by filecxx** [comment]
http://www.filecxx.com/release/filecxx_2.7b_win_x64.zip 

之前犯了个错误，当任务数量为空的时候没有触发回调，导致客户端认为filec还没启动完成，这个应该没问题了。

**Comment by filecxx** [comment]
另外注意一下2.7版本DHT是否还会出现为0的状况。

**Comment by login404** [comment]
这是界面BUG?

![QQ截图20220824205149](https://user-images.githubusercontent.com/69505914/186423224-0f461059-bf6a-4de4-a2ed-cd04f73b7f1f.png)

**Comment by filecxx** [comment]
确实应该是libtorrent的BUG, 计数不正确，有时候会卡在某个固定数字上。

**Comment by login404** [comment]
这个老BUG升级了…

![动画](https://user-images.githubusercontent.com/69505914/186468887-501c375b-e4d9-4eef-8986-984b3957cf75.gif)

**Comment by filecxx** [comment]
任务面板重复弹出，我注意到了。

**Comment by filecxx** [comment]
http://www.filecxx.com/release/filecxx_2.7c_win_x64.zip
测试下这个版本，如果没有问题就作为2.7正式版，另外BT DHT换了个统计方式，应该不会出现显示为0的问题了。

**Comment by login404** [comment]
> http://www.filecxx.com/release/filecxx_2.7c_win_x64.zip 测试下这个版本，如果没有问题就作为2.7正式版，另外BT DHT换了个统计方式，应该不会出现显示为0的问题了。

文件损坏了
! E:\Download\filecxx_2.7c_win_x64.zip: lib\filec.exe 校验和错误。文件被破坏
! E:\Download\filecxx_2.7c_win_x64.zip: lib\platforms\qwindows.dll 校验和错误。文件被破坏
! E:\Download\filecxx_2.7c_win_x64.zip: lib\libstdc++-6.dll 校验和错误。文件被破坏
! E:\Download\filecxx_2.7c_win_x64.zip: 压缩文件损坏

**Comment by filecxx** [comment]
重新下载，刚才应该是我上传到一半时候被cloudflare缓存了。

**Comment by login404** [comment]
仍然复现
filec ports可以输出
filec stop可以退出
远程主机(127.0.0.1)正常

**Comment by filecxx** [comment]
是重复弹出任务确认面板，还是界面操作没反应。

**Comment by login404** [comment]
> 是重复弹出任务确认面板，还是界面操作没反应。

界面操作没反应

**Comment by filecxx** [comment]
现在磁力任务已经没有锁，其他操作都正常，所以不可能是线程死锁，我确实找不到问题了。

**Comment by login404** [comment]
会跟内存占满有关么?
我看视频时可能有占满的情况

**Comment by filecxx** [comment]
不排出这个可能，这时候如果重启fileu，列表会完整吗。

**Comment by login404** [comment]
这版还没试过重启fileu
下次复现我试试

**Comment by login404** [comment]
重启fileu列表完整且操作恢复正常
重复弹出任务确认面板也复现了

![动画](https://user-images.githubusercontent.com/69505914/187011527-f0df4696-98a3-4860-a87f-117943486aa2.gif)

**Comment by filecxx** [comment]
这是好消息，之前的问题已经不存在了，只是2个客户端同时开启时候其中一个没有接收到数据，问题会比较好修复。

**Comment by JohnnyWoong** [comment]
> http://www.filecxx.com/release/filecxx_2.7a_win_x64.zip 测试一下这个版本，该问题应该完全解决了，但涉及到构架变化，不排除创造了新BUG。如果该版本没有问题，这2天就发布正式版本。

还是有哦, 而且触发后统计数据也全是0了, 重启后正常

**Comment by filecxx** [comment]
出现这个问题的时候，远程连接是否处于已连接状态。

**Comment by login404** [comment]
> 出现这个问题的时候，远程连接是否处于已连接状态。
> 
> 或者是出现了这个问题才执行的远程连接。

出现了这个问题才执行的远程连接

**Comment by filecxx** [comment]
http://www.filecxx.com/release/filecxx_2.7d_win_x64.zip 

测试一下这个版本, 如果出现这个问题了，点击菜单 帮助 -> 故障解决 -> 状态
然后提供一下图片。

我不太确定是 filec 接收数据失败还是 fileu 发送数据失败，这个能够大致定位到。

**Comment by filecxx** [comment]
http://www.filecxx.com/release/filecxx_2.7e_win_x64.zip

测试一下这个版本,  如果出现这个问题了，点击菜单 帮助 -> 故障解决 -> 状态

我认为应该没有问题了。

另外，开启了远程连接情况下，远程连接的任务确认面板也会弹出，不算是重复弹出。

**Comment by filecxx** [comment]
另外不要使用之前版本的 filec和这个版本的fileu 混合运行，否则还会出现老问题。

**Comment by login404** [comment]
发现另一个BUG
磁链添加任务时选择稍后下载
添加到列表后无法直接删除
要先点删除再点开始才能删除
且删除后该磁链无法再次下载
会提示重复的种子

**Comment by filecxx** [comment]
是的，确实。

界面操作无反应的情况还有复现吗？

**Comment by login404** [comment]
> 是的，确实。
> 
> 界面操作无反应的情况还有复现吗？

目前没有复现过了

**Comment by filecxx** [comment]
2.7我认为应该没问题了，如果还存在，可以在开一个帖子。

另外如果需要终身激活码可以在w.filecxx.com注册个帐号把用户名给我下。

**Comment by login404** [comment]
> 2.7我认为应该没问题了，如果还存在，可以在开一个帖子。
> 
> 另外如果需要终身激活码可以在w.filecxx.com注册个帐号把用户名给我下。

刚注册了 用户名一样

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/187950415-c3b0ac26-79dd-4b4d-8121-37937c7da5f9.png)

begin 大于 end 确实是 fileu IPC写入问题，这样的情况重新打开fileu会自动恢复，对吗。

**Comment by filecxx** [comment]
2.71应该不存在这个问题了。
