### ISSUE TITLE
对删除功能的建议

### ISSUE THREAD

**Issue by YandLiu** [filecxx/FileCentipede#333]
方式1：希望能做成如图所示，并且默认**不勾选**`删除硬盘相应文件`，比起现在这样要更不容易误删文件
![image](https://user-images.githubusercontent.com/26127104/184100697-6bbd18bc-090d-47e9-aef0-21552cadeebd.png)

方式2：像Windows那样，区分Delte和Shift+Delete：Delte删除掉任务，Shift+Delete删除掉任务+文件

**Comment by filecxx** [comment]
不打算这么做，实际上最初设计时候考虑过这样设计，但最后还是做成了3个按钮，我自己更偏向这样的使用方式，少一次点击。

**Comment by YandLiu** [comment]
那能否加上方式2？
另外可以在设置里给个选项，删除文件删除到回收站而不是直接删除掉吗？

**Comment by filecxx** [comment]
没问题。
