### ISSUE TITLE
增加FTP显式加密选项

### ISSUE THREAD

**Issue by shz42** [filecxx/FileCentipede#334]
目前实现的FTPS似乎是隐式加密？如果可以希望能增加FTP显式加密的选项(explicit FTP over TLS)，如下图中filezilla的选项
<img width="265" alt="屏幕截图" src="https://user-images.githubusercontent.com/63167402/184294276-37682c73-1156-4f80-96b9-0a9ebab2b17f.png">

**Comment by filecxx** [comment]
似乎意义不大，各个FTP服务器软件几乎都不按照标准来实现， 我都不太想碰FTP这一块，除非是BUG修复，SFTP非常不错，不过速度非常的慢(应该是最慢的)，WebDAV用的xml格式，超过80%数据都是多余的，远程文件管理这一块在软件3.0之后会设计一个新的协议.

**Comment by shz42** [comment]
主要是我使用的服务器不提供sftp，用隐式也连不上，但显式倒可以连上。不过如果比较难实现的话那还是先用着明文吧。

**Comment by filecxx** [comment]
实现倒是不难，发送登陆命令之前发送AUTH，不过服务器也有可能不支持这个命令，也有可能支持，但是没按照标准实现各个服务器返回的号码不同，测试起来很麻烦，在以后有充足时间时候再弄。
