### ISSUE TITLE
无法启动：一直显示“正在尝试与fliec建立链接”

### ISSUE THREAD

**Issue by dalegecheng** [filecxx/FileCentipede#336]
一直显示“正在尝试与fliec建立链接”

点退出就整个退出，根本无法点击软件。

win10系统
<img width="506" alt="Snipaste_2022-08-14_02-10-44" src="https://user-images.githubusercontent.com/111197175/184505863-79df5a0a-8a7d-4987-bd4c-83d95d446798.png">

**Comment by filecxx** [comment]
关闭filec.exe进程试试，应该可以解决问题，如果还是不行，把lib/data_windows.db* 3个文件发我邮箱，我马上处理。

**Comment by filecxx** [comment]
另外，是否为从低版本自动升级为2.5的

**Comment by dalegecheng** [comment]
> 关闭filec.exe进程试试，应该可以解决问题，如果还是不行，把lib/data_windows.db* 3个文件发我邮箱，我马上处理。

已解决。原来要安装在原文件所在地。

我是下载你的安装包在C盘桌面，然后安装的时候选择装在了E盘，就导致了这个情况。

建议加个提醒。像我这样的小白估计很多。

**Comment by filecxx** [comment]
这也是一个BUG，下个版本会修复。
