### ISSUE TITLE
建议安装包添加自动卸载旧版的功能

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [filecxx/FileCentipede#34]
虽然文件蜈蚣网站提示“在安装新版本之前卸载老版本”，但是我最近碰到的几个软件包括 Inkscape、Java、Shotcut、VLC 的安装包都有卸载旧版软件的选项，勾选就能自动卸载旧版，建议您也添上。

**Comment by filecxx** [comment]
好的。

**Comment by filecxx** [comment]
1.3版本开始会自动关闭旧版本进程。
