### ISSUE TITLE
扩展嗅探功能

### ISSUE THREAD

**Issue by huanghaobaobao** [filecxx/FileCentipede#340]
请问如何禁止嗅探ts，现在打开一个视频扩展悬浮窗里直接出现几百个ts，直接m3u8就行了

**Comment by filecxx** [comment]
对于 ts 和 m4s 等文件程序里做了判断，直接跳过，确定是使用的1.5版本以上的扩展吗，有没有测试地址。

**Comment by huanghaobaobao** [comment]
> 对于 ts 和 m4s 等文件程序里做了判断，直接跳过，确定是使用的1.5版本以上的扩展吗，有没有测试地址。 

扩展是edge商店装的，打开A站任何一个视频都这样，不知道是不是我这边问题

**Comment by filecxx** [comment]
AV站吗？能不能提供下网址。

**Comment by huanghaobaobao** [comment]
> AV站吗？能不能提供下网址。

呃，A站是acfun，www.acfun.cn

**Comment by asd0109** [comment]
2.61  版本  从这个网址下载的视频有问题无法播放

**Comment by filecxx** [comment]
> 2.61 版本 从这个网址下载的视频有问题无法播放

把浏览器扩展升级到1.7以上应该没有问题。

**Comment by filecxx** [comment]
已修复。
