### ISSUE TITLE
激活窗口增加暂时不弹出的按钮

### ISSUE THREAD

**Issue by Passerby1011** [filecxx/FileCentipede#341]
每日的激活窗口总是会自动弹出，哪怕点了稍后过会还是会自动弹出，在处理一些工作时，总是弹出非常的闹心，能否增加一个暂停弹出的按钮，直至下次使用时下载时在弹出激活

**Comment by filecxx** [comment]
这个问题有点别扭和尴尬。

你是从1.x开始使用的老用户，多次提交BUG，提供一下w.filecxx.com的帐号，我能给你永久激活码，这是至少我能做的。

**Comment by Passerby1011** [comment]
这真的非常感谢！
用户名：Light-power
邮箱：1535871428@qq.com

**Comment by filecxx** [comment]
OK

**Comment by filecxx** [comment]
直接在后台兑换就可以了。

**Comment by Passerby1011** [comment]
好的谢谢
