### ISSUE TITLE
最新的浏览器扩展会导致有些油猴脚本加载的错误

### ISSUE THREAD

**Issue by Passerby1011** [filecxx/FileCentipede#343]
最新的浏览器扩展导致了油猴脚本的加载失败，以及报错，脚本是一个较大的bilibili脚本，地址https://github.com/the1812/Bilibili-Evolved
https://github.com/the1812/Bilibili-Evolved/issues/3604
并且相较于之前版本，最新的浏览器扩展，在没有其他东西的影响下会导致bilibili加载缓慢，如果加上油猴脚本这个影响会变得更明显

**Comment by login404** [comment]
建议加个关闭嗅探功能的开关
把浮动栏关了还是会在后台分析

**Comment by Passerby1011** [comment]
确实即便勾上忽略的按钮，还是会后台分析

**Comment by filecxx** [comment]
OK

**Comment by filecxx** [comment]
确实是个BUG，在分析之后会自动清理*_filecxx这个临时值，似乎没有清理完全，下个版本会修复。

**Comment by ERUJRF** [comment]
快点修复。

**Comment by filecxx** [comment]
1.7版本扩展已经修复了这个问题，至于加载缓慢问题，bilibili经过测试网页加载完毕，分析平均耗时只有25毫秒，全部过程大概50毫秒，装10个都没问题。

关闭嗅探功能之后版本再添加，在完全没有BUG之前应该不会增加新功能了。

**Comment by ERUJRF** [comment]
还是不行 ，组件"16595001742633 flexx加载失败。

**Comment by filecxx** [comment]
> 还是不行 ，组件"16595001742633 flexx加载失败。

1.7版本的浏览器扩展已经不会在对象中添加临时的 时间截_filexxx 变量了，实际上已经完全移除，还出现这个提示是因为缓存问题，我也不知道怎么清空，似乎清空浏览器缓存没有用。

**Comment by Passerby1011** [comment]
> 还是不行 ，组件"16595001742633 flexx加载失败。

完全删除脚本，清理脚本管理器的回收站，重新安装
