### ISSUE TITLE
电脑卡死

### ISSUE THREAD

**Issue by 1409109991** [filecxx/FileCentipede#344]
![1](https://user-images.githubusercontent.com/79674967/185380853-39ecd3c2-1a60-40a0-acea-68bd38384422.png)
我在下载一个BT种子，不知道怎么回事电脑卡死了（这个不知道怎么回事。当时我在打游戏，后台在下载文件）
电脑刚开机这个filec就占用很高，如果不管，过一会电脑会卡死。

**Comment by filecxx** [comment]
是否可以提供下这个种子文件，另外下载保存的目录是否位于本地硬盘。

**Comment by 1409109991** [comment]
magnet:?xt=urn:btih:E4023F665B6066116CE1538320A9DAB41012178A
(滑稽）

文件是在本地

**Comment by filecxx** [comment]
你使用的是2.0以上版本吗？

**Comment by filecxx** [comment]
尝试下2.7版本。
