### ISSUE TITLE
无法下载视频

### ISSUE THREAD

**Issue by jyligx** [filecxx/FileCentipede#345]
![微信截图_20220818232325](https://user-images.githubusercontent.com/29768578/185433512-53b06dca-ffa1-4411-9d3c-13f80a51bf6b.png)
![微信截图_20220818232352](https://user-images.githubusercontent.com/29768578/185433525-70fd883d-d05f-48c6-b5e7-41c6406d0b3c.png)

**Comment by filecxx** [comment]
文件蜈蚣的服务必须为启动状态才能接收来自其他程序发送的数据。

**Comment by wsy998** [comment]
> 文件蜈蚣的服务必须为启动状态才能接收来自其他程序发送的数据。

我觉得这能否改为自动调用，就是没启动时，自动自动，已启动则直接调用，还有那个filec能否直接自动启动，不需要手动启动

**Comment by asd0109** [comment]
这个服务是可以自动启动的，有可能是你的安全软件禁止了它自动启动。

1.你在服务里手动把他设置为开机启动。
2.你在软件里卸载软件（输入123），然后重新安装它试试。
