### ISSUE TITLE
更新2.5版本，覆盖旧目录。报错无法使用

### ISSUE THREAD

**Issue by 23Ben** [filecxx/FileCentipede#346]
![image](https://user-images.githubusercontent.com/34782014/185781405-7ff5c406-2302-427e-aa37-883a9ea79c18.png)
更新2.5版本，覆盖旧目录。报错无法使用。按确定后软件闪退。

**Comment by filecxx** [comment]
可以手动关闭filec.exe进程，或者重启电脑，可以解决这个问题，稍后会更新2.6版本，添加了远程下载功能，自动更新功能已经开启。

**Comment by filecxx** [comment]
请在帮助菜单中更新至2.6
