### ISSUE TITLE
2.5版本无法输入激活码

### ISSUE THREAD

**Issue by DLXCTV** [filecxx/FileCentipede#347]
2.5版本 粘贴进当天的激活码 显示  无效激活码   
激活码都是 按时间 复制的  比如 20号的 就复制的20号的激活码

**Comment by filecxx** [comment]
时间是按照系统日期计算的。如果系统是19号，就复制19号的激活码。

**Comment by filecxx** [comment]
刚在多个系统测试，没有问题。

**Comment by DLXCTV** [comment]
我系统是 8月21日  18点57分  但是我复制21号的激活码  粘贴进去提示无效激活码
![{Q$18 {P$3R2~1J7A@6XKGQ](https://user-images.githubusercontent.com/103501313/185787799-33e2f710-fd13-4103-9c4e-e8aaa2a53be8.png)
![7A8G`Q@)NZ4I@__6W_K )OM](https://user-images.githubusercontent.com/103501313/185787803-3960e6a2-a797-407b-82b9-3743aed4baba.png)
![XSKU54B4H_T$H`_%G~7`V$Q](https://user-images.githubusercontent.com/103501313/185787809-a7503a53-a39e-4cbe-858f-d0e4ede80dad.png)

**Comment by DLXCTV** [comment]
![%NDKSHHB5J~1F581Q OLQ%Q](https://user-images.githubusercontent.com/103501313/185787836-5b22a764-69b9-44db-96ce-a21fb9ca1e3b.png)

**Comment by filecxx** [comment]
0k_C7vThaRRHF3RkFd6haP3fjwkOXoQRyWMLPaur7fPO4sA3-MJuecvIFYfU8mo-UKCW52ujEiLGuMf5lTueWDWCl7yR1Tg6C1AaV8BGlK3PXZPOHS8RlALWSVvbX2U9YTPSQMTFt7pwrArr0wfsL77yMp9jTDChPrrgUm-_dOWOY

你没有复制完全

**Comment by filecxx** [comment]
检查下你浏览器的扩展或者脚本，你访问网页被修改了。

**Comment by DLXCTV** [comment]
找到问题了  用极速浏览器 兼容模式 复制的就可以了，极速模式 复制下来就是 激活码无效
