### ISSUE TITLE
后台服务需要root权限问题

### ISSUE THREAD

**Issue by firstuanl** [filecxx/FileCentipede#35]
这个是见过最好用的下载器了。

ubuntu，后台服务需要root权限问题不太理解，每次启动，或息屏开机后，都要重新输入密码。能否免掉这步。

**Comment by filecxx** [comment]
linux下可以不需要root权限, windows下没有administrator权限没办法监听端口, linux下可以直接 filec -y

**Comment by filecxx** [comment]
我尽量考虑去掉linux版本root权限要求的问题，不过安装和卸载还是需要，否则/usr/share目录无法读写没办法注册协议和文件关联
