### ISSUE TITLE
激活码的建议

### ISSUE THREAD

**Issue by Liweike2022** [filecxx/FileCentipede#354]
新版软件每天需要一个激活码，作者说当星星为100K时，不再需要激活码。我一直在关注星星数，长期停留在2.2K，说明这个激活码模式并没有使用户数量增加。请作者重新评估这个激活码模式。如果希望大家都来用，快速增加用户数，建议取消激活码。就我个人而言，我已经不再使用该软件。改用其他，如IDM。

**Comment by filecxx** [comment]
别再发了，已经决定的不会取消，倒是会考虑停止更新（已付费用户和1.x老用户会继续提供更新）。

任何形式的贡献，包括提BUG，或者宣传赞助等等都能得到终身激活码。

你可以将他人的劳动成果看作应得的，不给予任何一点点的回报，但请不要抱怨。

请重新评估一下你的问题，如果你不使用这个软件，我会有任何损失？我还能少支付一点服务器流量费用。

不需要激活码时候有人会骂，有激活码时候也有人会骂，但现在骂的是激活码，这是在软件最初设计时期就构思好的。
