### ISSUE TITLE
音频采集没有名称，有时还采集不到

### ISSUE THREAD

**Issue by 64566455** [filecxx/FileCentipede#355]
音频采集没有名称，有时还采集不到

**Comment by filecxx** [comment]
提供下测试地址。

**Comment by 64566455** [comment]
网易云自测，问题都出现了

**Comment by 64566455** [comment]
网易云自测，问题都出现了

**Comment by 64566455** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecxx/FileCentipede"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 晚上10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecxx/FileCentipede] 音频采集没有名称，有时还采集不到 (Issue #355)





 
提供下测试地址。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。Message ID: ***@***.***&gt;

**Comment by filecxx** [comment]
视频音频名称只能从标题和ogg:title 获取，没其他办法。

**Comment by 64566455** [comment]
音频也没有名称

**Comment by 64566455** [comment]
音频也没有名称
