### ISSUE TITLE
重启系统或者软件分类丢失的反馈

### ISSUE THREAD

**Issue by deranged11** [filecxx/FileCentipede#357]
下载时设置好的分类，在重启系统或者重启软件后经常丢失（变成空白分类，但是软件下载目录是在分类里面），这个从很早1.x就存在了，请及时修复。
![下载完成有分类](https://user-images.githubusercontent.com/99341668/186511727-2a4f5f47-f120-4d6a-adeb-2adecfd7cb77.png)
![重启就没有分类了](https://user-images.githubusercontent.com/99341668/186511759-410a11f1-15bb-45ad-bed0-4e37efbb4220.png)

**Comment by filecxx** [comment]
这个问题我没有测试出来，我自己使用也没有遇到过这情况。可以检查下是否本地写入权限的问题。

**Comment by deranged11** [comment]
我这里测试基本上是100%，下载时设置好分类，下载完成后退出软件，再打开就没有分类了，这个问题搞得我头很大，下载数据是保存在哪里的呢？好像也没有看到有写入权限限制
                   
 
发件人： filecxx
发送时间： 2022-08-27 16:36
收件人： filecxx/FileCentipede
抄送： deranged11; Author
主题： Re: [filecxx/FileCentipede] 重启系统或者软件分类丢失的反馈 (Issue #357)
这个问题我没有测试出来，我自己使用也没有遇到过这情况。可以检查下是否本地写入权限的问题。

**Comment by filecxx** [comment]
你再安装一个版本到另外一个目录试试。

**Comment by filecxx** [comment]
在任务列表中重命名文件，然后退出再打开看看，如果重命名成功了但是分类没设置成功，那就有点不符合逻辑。

**Comment by deranged11** [comment]
尝试了安装您给的新版在其它英文目录
![下载完成](https://user-images.githubusercontent.com/99341668/187057690-5d45652d-e165-47f8-b38c-8a5016f05b54.png)
![分类消失](https://user-images.githubusercontent.com/99341668/187057692-08a0d898-1939-435f-ad21-1e3f8c916578.png)
还是存在分类消失
然后新版再次尝试下载完成就改名，然后再重启
![改名](https://user-images.githubusercontent.com/99341668/187057713-7329d5b1-7412-4658-8484-bd1ea575936c.png)
![改名重启后分类仍然丢失](https://user-images.githubusercontent.com/99341668/187057719-ba523d06-0d4c-47a7-b4b8-3fbe59a32451.png)
确实我也无法理解这个改名都能改分类会丢失

**Comment by deranged11** [comment]
蜈蚣下载各方面都很好，准备从IDM全面换过来，就是这个分类丢失没法解决很让人头痛

**Comment by deranged11** [comment]
刚才测试了消失分类后重新设置分类，重启就保存了分类

**Comment by deranged11** [comment]
我测试了您给的新版，如果下载结束退出软件就会出现分类丢失。
如果下载完成手动设置成其它分类，则可以保留分类。
是不是下载的时候没有写入分类信息？
                                                   
 
发件人： filecxx
发送时间： 2022-08-28 10:05
收件人： filecxx/FileCentipede
抄送： deranged11; Author
主题： Re: [filecxx/FileCentipede] 重启系统或者软件分类丢失的反馈 (Issue #357)
在任务列表中重命名文件，然后退出再打开看看，如果重命名成功了但是分类没设置成功，那就有点不符合逻辑。
―

**Comment by deranged11** [comment]
同时下载2个文件一个下载完成之后不手动设置分类（前下载有设置分类），一个下载完成之后手动再设置同一分类，重启软件，手动设置了分类的文件没有丢失分类，另一个下载完成没有手动设置分类的文件就出现分类丢失

**Comment by filecxx** [comment]
下载过程中除非状态改变，例如 下载中 变为 已完成，或者间隔30秒才会保存设置，强制重启确实对丢失没保存的设置。

**Comment by filecxx** [comment]
当然，如果只是关闭fileu界面，并不会有任何影响。

**Comment by deranged11** [comment]
不是用的强制重启，只是退出软件再打开


                                                   
 
发件人： filecxx
发送时间： 2022-08-28 21:30
收件人： filecxx/FileCentipede
抄送： deranged11; Author
主题： Re: [filecxx/FileCentipede] 重启系统或者软件分类丢失的反馈 (Issue #357)
当然，如果只是关闭fileu界面，并不会有任何影响。

**Comment by filecxx** [comment]
我再多检查下。

**Comment by deranged11** [comment]
下载完成后我专门等了10分钟，退出软件，再打开，没有手动设置的分类都消失了。不知道什么情况，可能我这个是个例。
                                                   
 
发件人： filecxx
发送时间： 2022-08-28 21:30
收件人： filecxx/FileCentipede
抄送： deranged11; Author
主题： Re: [filecxx/FileCentipede] 重启系统或者软件分类丢失的反馈 (Issue #357)
当然，如果只是关闭fileu界面，并不会有任何影响。

**Comment by filecxx** [comment]
我会尽可能检查问题。

**Comment by filecxx** [comment]
我在多个平台进行了测试，并没有这个问题，设置分类名称和重命名代码差不多，只是字段不同，如果重命名成功了分类不太可能设置不成功，或者只是没有显示出来文字？

尝试全新安装2.7版本测试下，有没有可能是出现了某种幻觉？或者在疲劳状态下出现了即使现象认为自己做了某些实际上并没有做过的操作？

**Comment by deranged11** [comment]
我录了个屏，麻烦抽空看看是哪里操作不对
                                                   
 
发件人： filecxx
发送时间： 2022-08-29 02:49
收件人： filecxx/FileCentipede
抄送： deranged11; Author
主题： Re: [filecxx/FileCentipede] 重启系统或者软件分类丢失的反馈 (Issue #357)
我在多个平台进行了测试，并没有这个问题，设置分类名称和重命名代码差不多，只是字段不同，如果重命名成功了分类不太可能设置不成功，或者只是没有显示出来文字？
尝试全新安装2.7版本测试下，有没有可能是出现了某种幻觉？或者在疲劳状态下出现了即使现象认为自己做了某些实际上并没有做过的操作？
―

**Comment by filecxx** [comment]
然后，录的屏在哪？

**Comment by deranged11** [comment]
> 然后，录的屏在哪？

https://user-images.githubusercontent.com/99341668/187189810-6f624395-90a6-4f88-b825-b58f6d67637c.mp4

因为发帖限制下载完成之后退出软件了，但是分类消失的下载项进行了改名操作，我发您邮件有一个20多m的附件，是有等待1分多钟时间的。

另外，一直反馈问题仅仅是喜欢这个软件，希望软件能符合使用需求，越做越好，如果不是因为喜欢相信大家都没不会在与已无关的事情上花那么多时间。

**Comment by filecxx** [comment]
我知道哪里的问题了，我还没有想到过是弹出下载时候确认面板上设置分类。

**Comment by filecxx** [comment]
下个版本会修复。感谢提交。

**Comment by deranged11** [comment]
> 

太好了，期待新版本

**Comment by filecxx** [comment]
2.71解决了这个问题。
