### ISSUE TITLE
建议出个绿色便携版

### ISSUE THREAD

**Issue by StrollStars** [filecxx/FileCentipede#358]
软件很强大，作者很厉害。
希望能够出个绿色版，解压即用，不用安装，也不注册协议这样的。

**Comment by filecxx** [comment]
你可以直接在安装之后在帮助中点击卸载，然后就成为绿色版了。

**Comment by StrollStars** [comment]
@filecxx 那有办法不注册或者取消注册的协议吗？比如BT和迅雷的。

**Comment by filecxx** [comment]
直接在lib目录下创建文件fileu_win32.conf 或者 fileu_linux.conf
写入{"installed":2}
可以不需要安装

**Comment by StrollStars** [comment]
@filecxx 感谢告知
