### ISSUE TITLE
下载CCTV的节目，解密失败

### ISSUE THREAD

**Issue by By-Tian** [filecxx/FileCentipede#36]
CCTV的节目，下载了但是无法本地观看，解密失败应该是。使用央视影音的某个PC版本下载了可以本地观看的。
测试连接https://tv.cctv.com/2016/11/11/VIDEyh3RPji1jL0RvI05flOc161111.shtml?spm=C53173422422.PLY0jF8YhmJQ.0.0

**Comment by asd0109** [comment]
这个感觉和下载工具没什么关系，因为 idm 下载下来也是同样的。

有些网站甚至把视频和音频分开，你要下两个文件然后手动合并成一个才行。

**Comment by filecxx** [comment]
这个比较特殊，得到的加密方式似乎是假的，我留着以后有空时候再弄。
