### ISSUE TITLE
到底怎么才能做贡献获得激活码啊？

### ISSUE THREAD

**Issue by pkouji** [filecxx/FileCentipede#360]
到底怎么才能做贡献获得激活码啊？
电脑小白看不懂

**Comment by pkouji** [comment]
有没有人能给点提示啊

**Comment by filecxx** [comment]
翻译，宣传，提交并帮助解决BUG，写文档，等等任何形式都属于贡献，或者在仪表盘中通过引荐方式获得点数兑换终身激活码，已经接近100人通过这种方式获得了。
