### ISSUE TITLE
什么都不能下载？

### ISSUE THREAD

**Issue by ScienceZone** [filecxx/FileCentipede#361]
不知何故，下载什么东西都无法成功，一概提示“未处理的错误”! 如何解决？谢谢！

**Comment by filecxx** [comment]
2.6版本是一个BUG版本，请升级到2.61

**Comment by ScienceZone** [comment]
> 2.6版本是一个BUG版本，请升级到2.61

使用的就是2.6.1版本，windows10 64位，网络防火墙进出无拦截，手机电信网络给电脑开的热点上网，尝试各种设置都无法下载！希望查明情况解决！

**Comment by ScienceZone** [comment]
> 2.6版本是一个BUG版本，请升级到2.61

今天凌晨是下载解压后安装在了非系统盘，地址名称中包含汉字，后来无法下载，卸载后暂时放在了系统盘的桌面，尝试了再次安装没法下载；刚才再次尝试了安装在桌面，发现可以下载了，再次下载后安装在之前的非系统盘某指定文件夹下，发现还是无非下载，会报错，希望解决这种问题，谢谢！

**Comment by filecxx** [comment]
如果和路径有关安装时候就会失败，但是无法下载这个问题就很难理解，我windows下使用并不是安装在系统盘的，并且带有特殊符号并不会出现这个情况。

**Comment by filecxx** [comment]
2次下载文件保存路径是否相同的

**Comment by filecxx** [comment]
我认为很大可能是权限问题，或者是某些磁盘监控程序，类似杀毒软件之类的拦截了磁盘操作。

**Comment by ScienceZone** [comment]
后来发现应该不是中文路径或是否卸载重写安装的问题，安装后如果移动安装目录或修改目录名称即便卸载后重新安装也需要关机或重启才能正常使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月29日(周一) 凌晨2:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [filecxx/FileCentipede] 什么都不能下载？ (Issue #361)




 
我认为很大可能是权限问题，或者是某些磁盘监控程序，类似杀毒软件之类的拦截了磁盘操作。
