### ISSUE TITLE
新功能需求——指定文件名批量下载、使用抓包工具抓取的Raw数据下载

### ISSUE THREAD

**Issue by ScienceZone** [filecxx/FileCentipede#363]
您好，希望增加如下功能：

1. 指定文件名批量下载功能，格式如“文件名 | 链接”等类似形式，一行一个，支持剪切板或文件批量导入即可。此功能常用于知道大量文件下载链接及其文件名，但下载工具默认识别的文件名并不符合命名所需的情况，比如文件名应是网页显示的名称，但下载工具却使用了下载链接的字符串（如MD5值等）命名文件的情况。迅雷、IDM等工具提供的形似链接批量下载功能不具有灵活性，可以批量下载大量具有形似链接(如http://www.×××.com/(*).jpg)的文件，但是文件名称不能指定，不如用Excel编辑好文件名和链接后大量下载文件方便。为解决类似需求网上有“IDM批量下载导入工具”等软件出现，希望本软件可以从源头直接解决。

2.  软件已可以下载需特定权限才能下载的文件，希望可以增加使用特定格式的请求数据下载文件的功能，比如直接使用或修改特定参数后使用浏览器开发者工具、Fiddler、HttpAnalyzer等抓取的原始请求数据下载文件，文件蜈蚣现在下载需权限文件需要分地址、cookie、header分别设定，略有复杂，如果可以直接使用或修改后使用Fiddler等抓取的“Raw”数据下载文件将方便不少。

以上功能希望酌情考虑添加，谢谢！

**Comment by filecxx** [comment]
1. https://github.com/filecxx/FileCentipede/issues/86 2.7版本已经增加。
2. 是否可以举个例子，raw数据是二进制的，不能复制粘贴，除非编码为base64。

**Comment by ScienceZone** [comment]
> 1. [通配符批量下载建议加上 #86](https://github.com/filecxx/FileCentipede/issues/86) 2.7版本已经增加。
> 2. 是否可以举个例子，raw数据是二进制的，不能复制粘贴，除非编码为base64。

1. 通配符批量下载不具有灵活性，希望如我上面讲的一样可以任意指定文件名和下载地址后批量下载，可以用Excel编辑大量文件名和下载地址后可以复制出来批量下载。
2. 我在此处说的“Raw”指的是Fiddler抓取的下载请求原始数据，也就是HttpAnalyzer中的原始流，比如：
GET https://static.hetaousercontent.com/static/assets/8ab07c6.logo.svg HTTP/1.1
Host: static.hetaousercontent.com
Connection: keep-alive
DNT: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
【此处可以有cookie数据】

**Comment by filecxx** [comment]
可以的，直接通过http头创建下载任务我还没有想到过。

**Comment by filecxx** [comment]
第二个很简单，第一个描述比较模糊，是否可以提供一些具体信息，例子等，不知道从哪开始设计。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/188026249-45877f6e-6ad1-402d-8dcc-766dcd0d37c5.png)
![image](https://user-images.githubusercontent.com/100348948/188026301-a7a58b1b-477e-4ac6-9984-54f0b5c07f98.png)

**Comment by ScienceZone** [comment]
需要重新给链接创建文件名，而不是使用默认文件名的情况往往出现在靠抓包获得下载链接的时候，此时靠下载工具默认的文件名往往无法知道下载的文件是何内容。有时默认的文件名是以链接中代表文件MD5或其他校验值的字符串命名的。比如：
1.链接：http://×××.ac4cac6a.pdf，默认文件名：ac4cac6a.pdf，抓包知道的正常文件名：成神.pdf
2.链接：https://×××.ASD5ACGR.zip，默认文件名：ASD5ACGR.zip，知道的正常文件名：拯救世界.zip
当存在大量链接时，尤其是有时文件名和链接存在于抓取的jason文件中时，就可以将文件名和链接做到一一对应：
在Excel中编辑好文件名和链接，粘贴到下载工具做到批量下载，但是除了IDM批量下载导入工具外，还没见到过原生支持批量指定文件名下载的工具，望完善支持！
A列&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; B列
文件名（往下一万行）&nbsp; &nbsp; &nbsp; &nbsp; 链接（一万行）







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月1日(周四) 凌晨4:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [filecxx/FileCentipede] 新功能需求——指定文件名批量下载、使用抓包工具抓取的Raw数据下载 (Issue #363)




 
第二个很简单，第一个描述比较模糊，是否可以提供一些具体信息，例子等，不知道从哪开始设计。

**Comment by ScienceZone** [comment]
需要重新给链接创建文件名，而不是使用默认文件名的情况往往出现在靠抓包获得下载链接的时候，此时靠下载工具默认的文件名往往无法知道下载的文件是何内容。有时默认的文件名是以链接中代表文件MD5或其他校验值的字符串命名的。比如：
1.链接：http://×××.ac4cac6a.pdf，默认文件名：ac4cac6a.pdf，抓包知道的正常文件名：成神.pdf
2.链接：https://×××.ASD5ACGR.zip，默认文件名：ASD5ACGR.zip，知道的正常文件名：拯救世界.zip
当存在大量链接时，尤其是有时文件名和链接存在于抓取的jason文件中时，就可以将文件名和链接做到一一对应：
在Excel中编辑好文件名和链接，粘贴到下载工具做到批量下载，但是除了IDM批量下载导入工具外，还没见到过原生支持批量指定文件名下载的工具，望完善支持！
A列                                    B列
文件名（往下一万行）     链接（一万行）

**Comment by ScienceZone** [comment]
需要重新给链接创建文件名，而不是使用默认文件名的情况往往出现在靠抓包获得下载链接的时候，此时靠下载工具默认的文件名往往无法知道下载的文件是何内容。有时默认的文件名是以链接中代表文件MD5或其他校验值的字符串命名的。比如：
1.链接：[http://×××.ac4cac6a.pdf，默认文件名：ac4cac6a.pdf，抓包知道的正常文件名：成神.pdf](http://xn--rcaaa.ac4cac6a.xn--pdf%2C:ac4cac6a-st3uj60dh49ddoxhhi0c.xn--pdf%2C:-pn2hm6vn7bk34bizi9mbjzsdztux0bjleu2gk37i.pdf/)
2.链接：[https://×××.ASD5ACGR.zip，默认文件名：ASD5ACGR.zip，知道的正常文件名：拯救世界.zip](https://xn--rcaaa.asd5acgr.xn--zip%2C:asd5acgr-st3uj60dh49ddoxhhi0c.xn--zip%2C:-ck1hg6c35tk5w7ykzrgnsak32dbx6ap2dmxgxn0k.zip/)
当存在大量链接时，尤其是有时文件名和链接存在于抓取的jason文件中时，就可以将文件名和链接做到一一对应：
在Excel中编辑好文件名和链接，粘贴到下载工具做到批量下载，但是除了IDM批量下载导入工具外，还没见到过原生支持批量指定文件名下载的工具，望完善支持！
A列                                            B列
文件名（往下一万行）            链接（一万行）
