### ISSUE TITLE
Username/Password for Websites?

### ISSUE THREAD

**Issue by rayman3003** [filecxx/FileCentipede#364]
Where can I add & save the "username & password" for the password-required websites, in the FileCentipede?!

**Comment by filecxx** [comment]
Which website?

**Comment by filecxx** [comment]
Do you mean HTTP Authentication?

**Comment by filecxx** [comment]
add headers:

Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=

![image](https://user-images.githubusercontent.com/100348948/187093921-ee62327c-2988-4d7e-b357-63c64e2852fe.png)

**Comment by rayman3003** [comment]
I mean websites that needs password. for example sharing websites, that after making an account for them, u must use the registration info (username & password) to download from them. Here is some examples:

https://uploaded.net/

https://www.zippyshare.com

I tried Header solution that u mentioned, But it doesn't work.

**Comment by filecxx** [comment]
Use the browser extension to download files.

Or, you need cookies from the website.

![image](https://user-images.githubusercontent.com/100348948/187185998-cece5b97-ac64-47ad-bf53-7e9949746894.png)

**Comment by rayman3003** [comment]
Bcuz most of the times, I want to download a huge number of files from those websites, using browser extension, is out of option.

So many download managers have an option to save username & password of websites, in their settings. Even old managers like "FlashGet", has such an option!

I don't know why u don't want to add such an easy & common option to your download manager! Your download manager has a potential to be a good manager. Don't make it incomplete.

**Comment by filecxx** [comment]
OK
