### ISSUE TITLE
无法用内置的更新功能更新文件蜈蚣

### ISSUE THREAD

**Issue by existisempty** [filecxx/FileCentipede#365]
2.5版时，用文件蜈蚣内置的更新功能，检测到2.61，点击升级，进度条不动，一直0%。

我只好手动下载2.61，卸载2.5，解压2.61，安装。

2.61也是只能检测到2.7，还是无法用内置的更新功能更新。
![文件蜈蚣无法正常更新](https://user-images.githubusercontent.com/112362309/187132766-2179b629-6fbe-44bf-bf87-561984a0afc8.png)

**Comment by filecxx** [comment]
需要多等一会。

**Comment by existisempty** [comment]
等了应该起码有一个小时了，还是不动，我就关闭升级窗口了。

**Comment by filecxx** [comment]
关闭对话框不影响，不需要管它，会自动升级的，根据地区不同有时候会比较慢。

**Comment by existisempty** [comment]
又等了很久，重启了笔记本，还是不行啊

**Comment by filecxx** [comment]
重启电脑试试，笔记本可能因为经常待机导致没有连接到DHT网络。

**Comment by existisempty** [comment]
重启了，不行。
还有，下载一个Photoshop自学资源也是久久不动0%。
![文件蜈蚣下载PS资源不动](https://user-images.githubusercontent.com/112362309/187438521-1e20f2fe-6323-41ce-875d-ce1f732fe5f6.png)
不知这和升级不动是不是一个原因造成的？

**Comment by filecxx** [comment]
DHT 0 ,我认为应该是一个原因，无法连接上DHT网络。
