### ISSUE TITLE
浏览器插件安装后显示错误。

### ISSUE THREAD

**Issue by FACETOSOUTH** [filecxx/FileCentipede#366]
![image](https://user-images.githubusercontent.com/112393836/187190263-d85f1c72-3c9a-490d-9236-be38d45161bd.png)
![image](https://user-images.githubusercontent.com/112393836/187190296-56665030-08d7-4714-8380-fc5826a71e32.png)

**Comment by FACETOSOUTH** [comment]
浏览器用的是chrome，已是最新版本 104.0.5112.102（正式版本） （64 位）

**Comment by filecxx** [comment]
可以忽略这个错误，如果有强迫症，可以安装 chrome_mv3.zip  
mv2版本的效果会稍微好一点。
