### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by BOSS-LongYing** [filecxx/FileCentipede#374]
运行fileu.exe文件就会弹出安装窗口，然后点击安装就会卡死，
之前用win7挺好，重装win10系统后，就装不上了，各个版本都试过了

**Comment by filecxx** [comment]
点击安装按钮之后界面无响应，还是按钮变为一直为灰色状态？

**Comment by BOSS-LongYing** [comment]
按钮为灰色，然后没有反应，不过这个窗口的其他选项依然可以点，比如勾选、缩小、选择安装目录这些都可以，但点右上角的×就会卡死 只能用任务管理器结束任务

**Comment by BOSS-LongYing** [comment]
> 点击安装后界面无响应，还是变成了灰色状态？

在选择的安装目录文件夹内确实会生成新的文件，文件内容是和下载的压缩包一样的内容，但是用浏览器的插件下载东西时，仍然提示没有安装软件

**Comment by filecxx** [comment]
在弹出安装完成对话框之前不应该运行安装目录下的文件，安装过程速度取决于本地磁盘写入速度。下个版本我会优化一下安装界面。

**Comment by filecxx** [comment]
github上传图片非常方便，只需要粘贴图片就可以了。重新安装不需要卸载，有一个可以不需要安装就使用的方法是直接在 软件lib目录下创建一个文件fileu_win32.conf 写入 {"installed":2}

**Comment by BOSS-LongYing** [comment]
文件夹里有那个文件

**Comment by BOSS-LongYing** [comment]
好家伙！可以了

**Comment by BOSS-LongYing** [comment]
试了一下，在B站上下了两个视频，无法播放，试了两个播放器都不行，百度上随便下了个视频可以播放

**Comment by filecxx** [comment]
提供一下链接。

**Comment by BOSS-LongYing** [comment]
![image](https://user-images.githubusercontent.com/35135134/187956939-3448fbe6-fb0b-46bc-8bf4-b4232afbf1b4.png)
哪个链接？视频的链接是随便找的，就是试了一下不同网站的视频下载情况。B站 https://www.bilibili.com/

**Comment by filecxx** [comment]
我测试主页随便找的一个下载没有问题。需要一个有问题视频URL链接进行测试。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/187963841-e63f2dbf-684a-45d4-9603-4af81a29ecd4.png)

![image](https://user-images.githubusercontent.com/100348948/187963761-2c755433-0b82-48b5-aa3a-18ef1f372fe0.png)

这个地址我测试正常，你是安装的1.7以上的浏览器扩展吗？

**Comment by BOSS-LongYing** [comment]
是早期的1.4的

**Comment by filecxx** [comment]
1.7，视频嗅探功能进行了很大升级，更新一下。

**Comment by BOSS-LongYing** [comment]
好的，我试试，打扰你了早点休息吧

**Comment by BOSS-LongYing** [comment]
![image](https://user-images.githubusercontent.com/35135134/187969575-31fd44d7-5a97-4db3-81ff-651c70db0282.png)
试了个B站视频，下载之后只有声音没有画面，是不是下载最后合成的时候有点问题
https://www.bilibili.com/video/BV1Xa411G7mZ?spm_id_from=333.1007.tianma.2-3-6.click&vd_source=3d8e4965f64248c4426967a6503b7db3
.
下面的两个问题无所谓了，只是有这个情况给你反馈一下
![image](https://user-images.githubusercontent.com/35135134/187968355-ef709cf4-3f69-4824-ad1c-08e25dab2785.png)
![image](https://user-images.githubusercontent.com/35135134/187968403-1c8d23d2-7e09-439a-90ea-1180b0ca2ae1.png)
这个链接下载的视频是广告视频，不是再看的视频内容：
https://haokan.baidu.com/v?pd=wisenatural&vid=10169811009695454584
这个链接下的两个不同的版本的视频 一个有画面没声音，一个有声音没画面：
https://haokan.baidu.com/v?pd=wisenatural&vid=6067162863828997082

**Comment by BOSS-LongYing** [comment]
![image](https://user-images.githubusercontent.com/35135134/187970121-9085d130-faca-4d8d-9e09-af562a6a4661.png)
k扩展提示错误，不过不影响下载
![image](https://user-images.githubusercontent.com/35135134/187970209-b9f96b8d-2315-4f71-b508-9639cb47a314.png)

**Comment by filecxx** [comment]
bilibili网站最近应该进行了更新，和youtube一样提供的资源是视频和音频分开的，需要下载之后手动合并，在工具菜单上提供了合并工具。

**Comment by BOSS-LongYing** [comment]
![image](https://user-images.githubusercontent.com/35135134/188040442-ad456ef3-b8fb-47d5-b5e4-cc1f0b5a78ea.png)
这个界面已经持续十几分钟了，时钟一直转，应该是卡在了某个点上

**Comment by filecxx** [comment]
如果换个目录也这样，那么如果不是权限问题，肯定是被某个其他软件冻结了，唯一方法只有点击跳过按钮，不过文件并联等不会被注册。

**Comment by BOSS-LongYing** [comment]
跳过是灰的不能点，点右上角的叉就会和之前一样卡死未响应，只能强行关闭了，这个不着急，用你前面说的加个文件的方式也能用

**Comment by filecxx** [comment]
只有在点击安装时候才会变为灰色，点击跳过按钮和创建文件方式完全一样的。
