### ISSUE TITLE
下载YouTube视频提示“地址已过期”

### ISSUE THREAD

**Issue by YandLiu** [filecxx/FileCentipede#377]
![image](https://user-images.githubusercontent.com/26127104/188319675-67996262-7444-45d1-8777-109dbe9efb33.png)
例子：https://www.youtube.com/watch?v=zB3yApA60N4

**Comment by filecxx** [comment]
youtube视频链接有时间限制，出现地址已过期需要通过右键菜单刷新地址。

**Comment by YandLiu** [comment]
现在变成了下载WEBM会显示服务器忙，其他格式文件没问题
新打开一个视频就立马下载，不存在时间太久的问题
而且也试过了刷新地址，依旧是同样的问题

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/192421625-49288d0e-4e91-4443-b57f-babb2c720a5e.png)

我测试这个地址没有问题，你访问网页的代理是否和软件中设置的代理一样？ youtube会对IP进行判断。

**Comment by YandLiu** [comment]
使用一样的代理

**Comment by filecxx** [comment]
2.71版本吗？

**Comment by YandLiu** [comment]
是的

**Comment by filecxx** [comment]
可以换一种格式，例如MP4，或者刷新下网页，youtube会随机分配视频地址到不同服务器，有一些服务器地址不能下载。

**Comment by YandLiu** [comment]
了解了
