### ISSUE TITLE
Love the program but... what are all these hosts and connections?

### ISSUE THREAD

**Issue by LokeYourLord** [filecxx/FileCentipede#380]
I love the program, it's better than _any other_ download manager I've used by far.

But I am slightly concerned as to what these constant connections are to mainland China. I don't mind downloading anything or connecting to China, but a constant data exchange to constantly new hosts & IP Addresses **_to any country is concerning_**, not because it's China. Could you explain to me what all these different hosts exactly are and what they are doing and what data they are receiving? I don't want to necessarily go on to using Wireshark in order to check, as I really just want to know what exactly they're doing.

![Untitled](https://user-images.githubusercontent.com/5807595/188880935-e8d5be52-40d0-453d-9d44-921e069e06d9.png)

Connection analysis courtesy thanks to Glasswire.

**Comment by filecxx** [comment]
DHT network 
![image](https://user-images.githubusercontent.com/100348948/188980327-c59913d4-fd17-4860-9920-d121229bf854.png)


The software uses the P2P network to update.
![image](https://user-images.githubusercontent.com/100348948/188980233-4c00c52f-31cd-4b0a-ad15-36de595d6a26.png)


Please read:
![image](https://user-images.githubusercontent.com/100348948/188980656-f5594625-ca3d-4eeb-8975-d96118c77b3f.png)

**Comment by filecxx** [comment]
More:
https://en.wikipedia.org/wiki/Distributed_hash_table
https://en.wikipedia.org/wiki/Kademlia

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/188986236-48e974fc-38fd-4b05-bd55-f992d67db12d.png)
I am using this software, what more do you wish to know?

**Comment by LokeYourLord** [comment]
Alright that is all I wanted to know, I was merely curious why at least 80% of connections are to China, but seeing here on GitHub that the vast majority of users for this software are Chinese users, that makes totally sense that DHT and BT are the cause.

Thanks for the explanation, everything has been answered ^-^
