### ISSUE TITLE
Allow payment with crypto

### ISSUE THREAD

**Issue by LokeYourLord** [filecxx/FileCentipede#384]
Just a suggestion, but I'd personally prefer paying you with Bitcoin or Ethereum for a Lifetime license if that is possible :)

**Comment by filecxx** [comment]
Do you have Dogecoin? transfer fee is lower and more difficult to trace (compared to Bitcoin).

**Comment by LokeYourLord** [comment]
I do but not as much as Ethereum. I have the 28$ in Ethereum, but only about 5$ in DOGE. Ethereum would ultimately be the best because I can give you 30$ even :)

**Comment by filecxx** [comment]
Sure, my Ethereum.
0x12C5BfDAcaaCf98bE7fb671598F5dDCEdf06274C

**Comment by LokeYourLord** [comment]
Here you go, sent:
![image](https://user-images.githubusercontent.com/5807595/189467689-a7cce70e-56c0-48bf-9b92-bb1d95111f4e.png)

https://etherscan.io/tx/0xbe28eb01c0d6fc7493ee13e256c93e87645d5282a8273b680a2323fad38a9a7a

Please add the lifetime license key to my account at the "https://w.filecxx.com" page. My name is: C3PHIR0TH
If you need any more info then let me know 🙂!

**Comment by filecxx** [comment]
It's done, thank you.

**Comment by LokeYourLord** [comment]
Thanks, got it. I have a question: If I reinstall my PC and the UID changes, is there a way to reset it on the website? If not, can you add a reset button so that we can reset the UID?

**Comment by filecxx** [comment]
The UID is following your CPU, so, you can reinstall your operating system.

Each year your balance will be automatically restored, 2023-09-11 it will become 30 again.

**Comment by LokeYourLord** [comment]
> The UID is following your CPU, so, you can reinstall your operating system.
> 
> Each year your balance will be automatically restored, 2023-09-11 it will become 30 again.

Ahhh okay that's great. I mean I usually spoof all of my Hardware ID's and such though, and sometimes build a new PC as well, so it could be better down the line to have a reset button, but balance reset once a year should be okay for now I think.

**Comment by filecxx** [comment]
I will refine the dashboard when my next project is finished, thanks for the suggestion.
