### ISSUE TITLE
我想知道怎么弄到激活码，我也转发了。

### ISSUE THREAD

**Issue by q290549129** [filecxx/FileCentipede#390]
我想知道怎么弄到激活码，我也转发了。而且用户名是什么啊 哪清册去啊？

**Comment by fy007** [comment]
http://filecxx.com/zh_CN/activation_code.html

按日期来，一天换一次码，好麻烦的。你用1,9吧，这个不用码，只是功能没有这么多。

**Comment by filecxx** [comment]
帮助宣传是一种贡献，可以得到永久激活码。
最直接的方式是使用w.filecxx.com内提供的引荐地址。

**Comment by q290549129** [comment]
可是这仪表盘打开没东西啊。

**Comment by filecxx** [comment]
> 可是这仪表盘打开没东西啊。

我不太明白你的意思。
