### ISSUE TITLE
有很基礎的問題需要解決

### ISSUE THREAD

**Issue by martjay** [filecxx/FileCentipede#392]
首先是下載速度，我這邊用IDM下載速度差不多4M/S，文件蜈蚣只能1M/S。

然後是下載後，經常文件損壞，在IDM沒有任何問題，哎，想放棄可是我還是希望你們盡快解決問題，表示支持。

**Comment by filecxx** [comment]
http://www.filecxx.com/zh_TW/documentation/how_to_increase_download_speed.html

所有多線程HTTP下載工具如果沒有網絡環境影響速度基本上是一樣的。
```
首先是下載速度，我這邊用IDM下載速度差不多4M/S，文件蜈蚣只能1M/S。
```
如果遇到了相關問題還希望多花時間檢查下本地原因，是否使用相同代理等。
除非設置中勾選了忽略服務器已更改否則不太可能出現文件損壞的問題，另外檔案蜈蚣不支持網路映射的磁盤。

有太多人發表沒有經過仔細調查的問題，我現在都不願意把精力放在這個項目上。

**Comment by martjay** [comment]
如果你把原因都归结到用户问题上，基本上就可以不做了，我说的不仅仅是IDM，XDOWN也比你的软件快，并且也没有文件损坏的问题，为什么你从来你从自己身上找问题？
