### ISSUE TITLE
How to change IP for Chrome Extension?

### ISSUE THREAD

**Issue by R1D3R175** [filecxx/FileCentipede#394]
Hi, as stated in the title I'd like to download through the extension to a remote PC. Is there anyway that i could change that "localhost" to another IP?

**Comment by filecxx** [comment]
I have not provided the feature yet, but yes you can.

You need to do these steps:

1: unzip browser_extensions/chrome.zip
2: open background/background.js
3: searching and replace http://localhost with http://your_IP
4: go to the chrome extension page, and load the unpacked directory.

**Comment by R1D3R175** [comment]
Thanks, that solves the issues. Are you planning to implement a way to run FileCentipede in the background (but still accessible in the Windows Tray) so that I don't have to keep it open to download stuff?

**Comment by filecxx** [comment]
I don't understand, filec is the background service, it can be running without the user interface.

**Comment by R1D3R175** [comment]
Basically when I try to download something without the UI open, the "pop-up" for adding the task doesn't show.

**Comment by filecxx** [comment]
Goto settings -> 
general -> uncheck the "No completed dialog"
http, FTP, ssh, torrent, stream -> check the "without confirm"

**Comment by R1D3R175** [comment]
Solved, thanks.
