### ISSUE TITLE
你好，想请教下有关激活软件的问题！

### ISSUE THREAD

**Issue by zzcbun** [filecxx/FileCentipede#399]
目前免费使用中，每天激活一次，这么好的软件，做为使用者当然想要购买成为终身用户。在仪表盘中看到了成为终身用户的购买选项，但是有两个疑问，还请解答，谢谢。
第一：购买后可以在几台电脑上使用？目前手里有3台电脑，发现每台的UID是不同的。激活的绑定机制是绑定机器还是绑定购买账号？
第二：一次性付款28刀后，终身免费吗？是否大版本升级及新功能推出后也可以免费使用？
谢谢！！

**Comment by filecxx** [comment]
1.目前是绑定的CPU，不会联网验证，支付28USD 会赠送 56USD，相当于可以绑定3台电脑。之后每年可以重置一次（如果每年都多次换新电脑相信也不会介意这28USD）。

2.是终身的，包括大升级。

**Comment by filecxx** [comment]
另外一个软件大概1-2月内会完成，是一个免费软件，但内置的机器人程序（自动发批量发广告功能）是收费的，大概120USD左右一年，发布时期会免费赠送给文件蜈蚣终身用户永久使用权。

**Comment by zzcbun** [comment]
好的，感谢您如此高效的回复！忘记还会有赠送56刀了！！

**Comment by zzcbun** [comment]
新开发的软件是个什么功能的软件？谢谢！

**Comment by filecxx** [comment]
邮件客户端 & 通用即时聊天工具 & 通用网站和论坛工具(整合在一个聊天对话框中) 
打算兼容所有协议，包括IRC 等，会整合其他软件例如ICQ等，内置爬虫。

功能比较多有些还没完全确定，这是个还没成型的原型界面
![image](https://user-images.githubusercontent.com/100348948/191147953-393901a2-0635-407d-bfd5-1887d6ae977c.png)
![image](https://user-images.githubusercontent.com/100348948/191148031-016f7805-d24e-4cf4-a046-01cd0772f14a.png)
