### ISSUE TITLE
追踪器未自动添加到任务

### ISSUE THREAD

**Issue by login404** [filecxx/FileCentipede#4]
订阅跟设置的追踪器不会被添加到任务里
追踪器面板右键添加是正常的

浏览器扩展建议添加热键切换点击拦截
用于支持sourceforge.net之类的网站

界面位置大小跟项目列宽不能保存…

**Comment by filecxx** [comment]
订阅跟设置的追踪器不会被添加到任务里
追踪器面板右键添加是正常的
 => 
追踪器自动添加是用于创建种子时候使用的。
如果下载任务追踪器地址只有自己拥有，而其他人没有这些地址，那么添加之后没有太大意义。
不过下一个版本我会加一个选项，自动添加到下载任务。

------------------------------------
浏览器扩展建议添加热键切换点击拦截
用于支持sourceforge.net之类的网站
=>
这个功能在火狐扩展中心审核通过之后添加

------------------------------------
界面位置大小跟项目列宽不能保存…
=>
在我把网站和相关文档等一系列工作完成之后会添加这部分功能，同样，在下一个版本中会出现。
