### ISSUE TITLE
Chromium扩展未传递cookie

### ISSUE THREAD

**Issue by login404** [filecxx/FileCentipede#401]
https://gofile.io/d/eIfcCQ
该网站接管下载跟右键添加任务都不会传递cookie

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/192077571-58c8b23f-33a1-444b-b38b-a3aa83b80173.png)
我点击下载能够获取到cookie，你检查下是否包含accountToken=

**Comment by login404** [comment]
我知道问题了
是隐身模式下不行

**Comment by login404** [comment]
我又复现了
跟隐身模式无关
出现时托盘图标会显示感叹号
此时任何网页都不会传递cookie
重启flec.exe跟浏览器进程都不行

隐身模式
![1](https://user-images.githubusercontent.com/69505914/192156428-ed320acf-4b8a-4252-aab1-95a8180934f1.gif)

非隐身模式
![2](https://user-images.githubusercontent.com/69505914/192156434-ede25164-cca2-47a9-bfc0-d19e3f695c1f.gif)

**Comment by filecxx** [comment]
浏览器扩展的cookie面板内cookies是否也是空的。

**Comment by login404** [comment]
> 浏览器扩展的cookie面板内cookie是否也是空的。

面板内不是空的
第一张图有录到

**Comment by filecxx** [comment]
我也不太确定是哪里的问题，下载之前使用浏览器API获取的cookies，应该不太可能为空
```
/*
     * get cookie
    */
    let get_cookie = function(url,callback)
    {
        let cookies_obj = chrome.cookies || chrome.experimental.cookies;

        if(!cookies_obj){
            return callback("");
        }
        cookies_obj.getAll({url: url},function(cookies)
        {
            let str = "";

            for(let i=0;i<cookies.length;i++){
                if(i !== 0){
                    str += ";";
                }
                str += cookies[i].name + "=" + cookies[i].value;
            }
            callback(str);
        });
    }
    /*
     * start download file
    */
    let start_download_file = function(tab_id,url,filename,filesize,referer,page_url)
    {
        get_cookie(url,(cookie)=>
        {
            let extra = {file_size:filesize};

            if(page_url !== url){
                extra.page_url = page_url;
            }
            let uri = create_filec_uri(url,{file_name:filename},referer,navigator.userAgent,cookie,extra,default_http_headers);

            start_download_request(uri,tab_id);
        });
    }
```
当然可能是当前域名和下载文件的域名不同导致获取为空或者被浏览器禁止跨域，但我这简单的测试确又获取到了，表示不是一定会发生这情况，下次更新时候我尽量检查下。另外其他网站有出现这个情况吗？

**Comment by login404** [comment]
> 我也不太确定是哪里的问题，下载之前使用浏览器API获取的cookies，应该不太可能为空
> 
> ```
> /*
>      * get cookie
>     */
>     let get_cookie = function(url,callback)
>     {
>         let cookies_obj = chrome.cookies || chrome.experimental.cookies;
> 
>         if(!cookies_obj){
>             return callback("");
>         }
>         cookies_obj.getAll({url: url},function(cookies)
>         {
>             let str = "";
> 
>             for(let i=0;i<cookies.length;i++){
>                 if(i !== 0){
>                     str += ";";
>                 }
>                 str += cookies[i].name + "=" + cookies[i].value;
>             }
>             callback(str);
>         });
>     }
>     /*
>      * start download file
>     */
>     let start_download_file = function(tab_id,url,filename,filesize,referer,page_url)
>     {
>         get_cookie(url,(cookie)=>
>         {
>             let extra = {file_size:filesize};
> 
>             if(page_url !== url){
>                 [extra.page](http://extra.page)_url = page_url;
>             }
>             let uri = create_filec_uri(url,{file_name:filename},referer,navigator.userAgent,cookie,extra,default_http_headers);
> 
>             start_download_request(uri,tab_id);
>         });
>     }
> ```
> 
> 当然可能是当前域名和下载文件的域名不同导致获取为空或者被浏览器禁止跨域，但我这简单的测试确又获取到了，表示不是一定会发生这情况，下次更新时候我尽量检查下。另外其他网站有出现这个情况吗？

跟网站好像没关系
出现时任何网站在创建任务时cookie都为空

第二张图里直接在本页面右键下载1楼的链接
正常时也是会有cookie的

**Comment by filecxx** [comment]
这个时候重启浏览器还会正常吗？

**Comment by login404** [comment]
> 这个时候重启浏览器还会正常吗？

不会 重启过几次浏览器了
也试过关闭其他扩展 没用
现在都没恢复正常

**Comment by filecxx** [comment]
好奇怪的问题，我认为和filec没关系，应该是浏览器插件的BUG。

**Comment by filecxx** [comment]
1.8版本的浏览器扩展应该修复了。

**Comment by login404** [comment]
好像还是不行
必须在非隐身窗口有cookie时
才能在隐身窗口获取到
而且获取到的是非隐身的cookie


https://user-images.githubusercontent.com/69505914/210129193-7eb340ab-dc23-4c4a-92cb-cfc9f05a15b6.mp4

**Comment by filecxx** [comment]
这不太好解决，chrome的隐身窗口和普通窗口用的同一个background.js ,下载事件触发也是在background.js中，cookie共享的，chrome.tabs.query查询到的窗口是非隐身的窗口，即便我关掉了查到的还是非隐身的窗口，不确定是不是浏览器的BUG，下次更新时候再深入测试下。

**Comment by login404** [comment]
https://github.com/alexhua/Aria2-for-chrome
该扩展的下载拦截可以正常获取隐身cookie
虽然它的右键导出也有相同问题
或许能参考下?

**Comment by filecxx** [comment]
> https://github.com/alexhua/Aria2-for-chrome 该扩展的下载拦截可以正常获取隐身cookie 虽然它的右键导出也有相同问题 或许能参考下?

这个问题已经在1.81浏览器chrome 扩展中修复了，但是firefox仍然存在这个问题。
