### ISSUE TITLE
磁力链接一直显示下载元数据

### ISSUE THREAD

**Issue by imwushicy** [filecxx/FileCentipede#403]
magnet:?xt=urn:btih:576ca02db5b3d98a237de508139f9f471e69e247&dn=zh-cn_windows_11_consumer_editions_version_22h2_x64_dvd_59cfe6ee.iso&xl=5517127680

**Comment by filecxx** [comment]
软件是哪个版本，状态栏中的BT DHT 是否显示为 0

我使用2.71版本 测试这个链接没问题，而且非常快。

![image](https://user-images.githubusercontent.com/100348948/193378561-d954b774-920f-4fd9-b738-0d912808e7bb.png)

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/193378568-a9d435a5-466d-4452-ba39-629c14a38b44.png)

**Comment by huanghaobaobao** [comment]
> ![image](https://user-images.githubusercontent.com/100348948/193378568-a9d435a5-466d-4452-ba39-629c14a38b44.png)

请问我的BT DHT经常打开显示0是怎么回事？如何解决？

**Comment by filecxx** [comment]
> > ![image](https://user-images.githubusercontent.com/100348948/193378568-a9d435a5-466d-4452-ba39-629c14a38b44.png)
> 
> 请问我的BT DHT经常打开显示0是怎么回事？如何解决？

通常是防火墙造成的，可以点击菜单中的强制重启。
