### ISSUE TITLE
下载某些网站速度极慢，请问如何解决

### ISSUE THREAD

**Issue by Fmanys** [filecxx/FileCentipede#407]
我在下载本网站（https://80wvdrf.jiuse800.com/）的内容时下载速度长期保持在100k左右，但是其他网站都能跑满，想请问如何解决

**Comment by filecxx** [comment]
网站对连接或者IP进行了限速我暂时没有解决方法，如果你知道怎么绕过我可以帮你实现这个功能。

**Comment by Fmanys** [comment]
感谢
