### ISSUE TITLE
[Questions] 是否考虑改名？

### ISSUE THREAD

**Issue by alex3236** [filecxx/FileCentipede#41]
文件蜈蚣这个名字给人的印象并不好。小众软件论坛上的网友给了不少意见，我认为优于现在的名字。

**Comment by mantis3d** [comment]
名字和图标至少得改一个

**Comment by filecxx** [comment]
🤣 为什么这么多人在意图标和名字，我打算以后版本中增加一个修改图标和名字的功能，现在版本可以通过修改lang目录下文件实现改名字，用图标修改器改图标。

**Comment by filecxx** [comment]
1.3版本支持安装时候设置软件名称。
