### ISSUE TITLE
建议完善此类m3u8地址的兼容

### ISSUE THREAD

**Issue by rhaxs** [filecxx/FileCentipede#415]
类似http://www.setv.fjtv.net/live/等网址的回看，通过xxx.m3u8地址下载视频，首先下载得到m3u8文件，再使用此文件下载时，提示无法下载，需要手动补全基础URL。使用如N_m3u8DL-CLI下载则不会。建议完善此功能。

**Comment by filecxx** [comment]
如果M3U8文件内的片段URL为相对地址如 1.ts 而非http://xxx.com/1.ts 程序是没办法下载的，你的意思应该是
通过http://xxx.com/xxx.m3u8 下载这个文件之后，自动将http://xxx.com作为基础URL，这个确实可以让部分单服务器的小型网站m3u8文件做到不需要手动设置基础URL。

**Comment by filecxx** [comment]
2.8版本可以直接下载
