### ISSUE TITLE
千图网图片文件下载，错误号400

### ISSUE THREAD

**Issue by Bellain** [filecxx/FileCentipede#417]
**Please provide as much information as possible.**

version(>=2.0) :

screenshot:
![image](https://user-images.githubusercontent.com/38975278/196096180-bcf847f9-f383-4905-ba9f-6553e83c9467.png)
![image](https://user-images.githubusercontent.com/38975278/196096258-d6ce4568-3f2a-4675-9c53-c4b5a59fa540.png)

URL:https://dl.58pic.com/44342679.html

.......

**Comment by filecxx** [comment]
我没办法测试这个网站，是否可以提供下 软件内的文件URL地址和浏览器下载文件时的文件URL地址

**Comment by filecxx** [comment]
1.8版本的浏览器扩展应该修复了。
