### ISSUE TITLE
[Bug] 无法接管 Edge 下载

### ISSUE THREAD

**Issue by alex3236** [filecxx/FileCentipede#42]
## 版本信息
```plain
Microsoft Edge 99.0.1150.39 (64 位)
操作系统：Windows 11 Version 21H2 (Build 22000.556)
```

## 问题
完全无法接管下载任务。

**Comment by filecxx** [comment]
接管浏览器下载任务已经添加进1.3版本，很快将发布。

**Comment by alex3236** [comment]
> 接管浏览器下载任务已经添加进1.3版本，很快将发布。

原来现在是没有这个功能吗

**Comment by filecxx** [comment]
原来没有接管浏览器下载的功能，这个已经添加了，正在测试

![image](https://user-images.githubusercontent.com/100348948/158991673-15947f6f-e5b3-473c-9b8f-277c51f6f6b8.png)

![image](https://user-images.githubusercontent.com/100348948/158991552-c233f6c6-4972-4183-a757-d709764d3599.png)

**Comment by alex3236** [comment]
> 原来没有接管浏览器下载的功能，这个已经添加了，正在测试
> 
> ![image](https://user-images.githubusercontent.com/100348948/158991673-15947f6f-e5b3-473c-9b8f-277c51f6f6b8.png)
> 
> ![image](https://user-images.githubusercontent.com/100348948/158991552-c233f6c6-4972-4183-a757-d709764d3599.png)

既然要做我给个建议，做个像 IDM 那样的可选的下载完成窗口，可以快速打开文件、打开所在文件夹、拖放以移动文件

**Comment by filecxx** [comment]
如果连使用软件使用习惯都做的和其他软件一样了，这不是我的风格，也是抢了别人的工作，我比较倾向于简易，有创意，风格独特的设计。使用体验为资源的内容，而非软件本身 （主要方便我自己使用）。

**Comment by alex3236** [comment]
> 如果连使用软件使用习惯都做的和其他软件一样了，这不是我的风格，也是抢了别人的工作，我比较倾向于简易，有创意，风格独特的设计。使用体验为资源的内容，而非软件本身 （主要方便我自己使用）。 不过右下角弹出提示应该不错。

不一定要做得一样，但至少提供一个下载完成后无需查看主界面就可以快捷操作文件（打开、打开文件夹）的方式。这个功能对于捕获浏览器下载任务的下载器很有用。

**Comment by filecxx** [comment]
没问题，这个功能在 1.5 之后的版本中增加一个选项，如果能提供一个原型设计作为参考可以更快。

**Comment by filecxx** [comment]
根据浏览器扩展里面主版面点击复制时候右下角弹出框那种样式应该没问题

**Comment by filecxx** [comment]
1.3 
http://www.filecxx.com/en_US/update_log.html

**Comment by filecxx** [comment]
> ![image](https://user-images.githubusercontent.com/45303195/159027124-541eed30-e77a-4f54-b73d-2b8b0b5cbbc8.png) 这是 IDM 的下载完成对话框，右下角给了个拖放快速移动文件的功能。 但如果秉持简易的理念，弹窗显示下载完成，提供 `打开文件` 和 `在文件夹中显示` 两个按钮也就够了。 Win 10+ 和 Linux 的通知 API 实现应该比较方便？总之可以取舍一下找个好一点的方案

这个功能已经添加进了1.5版本。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/159415305-f7c14c7f-e60e-406b-a4c8-134a6f3067f0.png)
![image](https://user-images.githubusercontent.com/100348948/159415350-dffdbf9f-d1c3-43c8-9e9d-ecd7a1545624.png)

如果不满意，请重新开个isusse，给予你期望的样式。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/159415515-bba4a935-2623-48b4-acbb-87d4e36d0501.png)
![image](https://user-images.githubusercontent.com/100348948/159415571-5494dc5b-cd99-43f7-a899-5cb02645e9fd.png)

如果不满意请重新开个isusse, 提供你期望的方式。
