### ISSUE TITLE
[Bug report] 下载OneNote时区块显示错误

### ISSUE THREAD

**Issue by CKlimeths** [filecxx/FileCentipede#425]
**Please provide as much information as possible.**

version(>=2.0) : 
2.71

screenshot:
![image](https://user-images.githubusercontent.com/86591721/200105681-10a33a7d-5d8b-4a36-8bd4-6e53724cd0e1.png)
![image](https://user-images.githubusercontent.com/86591721/200105683-d7a3a23a-0e27-4bf0-8aed-5f047f13a584.png)
![image](https://user-images.githubusercontent.com/86591721/200105684-eb61018a-278e-466a-9df9-c9419c325793.png)

URL: 
https://go.microsoft.com/fwlink/?linkid=2110341

description:
如图所示，下载OneNote的时候，随着下载进度的增加，区块中显示的进度反而在不断变少，进度显示弄反了。

.......

**Comment by filecxx** [comment]
😲😲😲😲😲
不可断点续传的任务区块显示确实反了，好尴尬的BUG。

**Comment by filecxx** [comment]
已修复。
