### ISSUE TITLE
知网下载文件有问题

### ISSUE THREAD

**Issue by Passerby1011** [filecxx/FileCentipede#426]
从知网下载的论文有问题，显示下载成功但是文件大小不对，打不开
![image](https://user-images.githubusercontent.com/63802758/200131306-3c423c11-b740-4ed9-aac7-2f4bea2a4763.png)
![image](https://user-images.githubusercontent.com/63802758/200131354-d8e22e83-f352-4091-8411-a6fe2112c92d.png)
这是下载地址：https://wuxi.cnki.net/kfdproxy/file/kfd/download/single/PDF.action?param=eyJEaXNjTm8iOiJTQ1RDMTkwMiIsIkZpbGVOYW1lIjoiU0NMSDIwMTkwMTAzMiIsIk5vbmNlIjoiMTI0MDMwODg2MCIsIlBhZ2UiOiIiLCJSZXF1ZXN0Q2xpZW50IjoiU0RLXzEuMC4wIiwiUmVzb3VyY2VUeXBlIjoiY2pmZCIsIlNlY3JldElkIjoiMjAxODAwMiIsIlNpZ25hdHVyZSI6IjhraGRNOWdpUEh6THRBNFBSaUZBMDJxK09haz0iLCJUaW1lc3RhbXAiOiIxNjY3MjE1NzA5IiwiVGl0bGUiOiLmjqjmnYbpkojova7mtLvpvb/pvb/lvaLmlrnnqIvnmoTnroDljJblu7rmqKHkuI7kvKDliqjop5LliIbmnpAifQ$2D$$2D$

**Comment by filecxx** [comment]
{"Message":"无效的签名"} 
刚好29字节，检查下任务中的cookie和浏览器cookie是否一样的。

**Comment by Passerby1011** [comment]
好像是cookie的获取有问题，下载用的和从网页获取的并不一样

**Comment by Passerby1011** [comment]
这是旧的知网空间，出现的问题新版知网没这个问题

**Comment by filecxx** [comment]
好的

**Comment by filecxx** [comment]
1.8版本的浏览器扩展应该没有问题了
