### ISSUE TITLE
what will happen if the Activation code is not executed?

### ISSUE THREAD

**Issue by candrapersada** [filecxx/FileCentipede#429]

**Comment by candrapersada** [comment]
will there be a `Lite` version in the future without many features without Activation code, with the latest FileCentipede version?

**Comment by filecxx** [comment]
Yup, but it will be very `Lite`, and only supports HTTP.
The classic IE downloader style.

**Comment by LokeYourLord** [comment]
Honestly, you're making such a much better product than JDownloader and IDM, that if you add a few more features, make it catch absolutely all downloads without fail, and maybe change logo & name, you could make it full commercial software. Well, that and make your website/dashboard run on HTTPS 😅

**Comment by filecxx** [comment]
> Honestly, you're making such a much better product than JDownloader and IDM, that if you add a few more features, make it catch absolutely all downloads without fail, and maybe change logo & name, you could make it full commercial software. Well, that and make your website/dashboard run on HTTPS sweat_smile

Don't worry, this project just started this year (IDM 20+ years old).
there are tons of features on my TODO list, I will be back on this project as soon as possible.
