### ISSUE TITLE
软件似乎在占用我的USB设备

### ISSUE THREAD

**Issue by ShoreNinth** [filecxx/FileCentipede#432]
软件版本：1.9免费版
系统版本：Windows 11 22H2

我单击了托盘的”安全删除硬件并弹出媒体“，准备拔出我的外接硬盘。但Windows提示“该设备正在使用中”：
![屏幕截图 2022-11-12 171635](https://user-images.githubusercontent.com/54047776/201467896-469d68c4-f5ec-4ff9-ac59-8e18aae25cc4.png)
在资源监视器中发现是filec.exe在占用我的硬盘。
![屏幕截图 2022-11-12 171610](https://user-images.githubusercontent.com/54047776/201467939-72d9548a-2f6f-433a-be45-d1eb81eb69a0.png)
我并没有把软件安装在移动硬盘里，也没有把移动硬盘设为文件蜈蚣的下载目录，那么请问它为什么要占用我的设备呢

**Comment by filecxx** [comment]
你需要使用 Microsoft Process Monitor 监视 filec.exe 进程查看其行为，用来证明是在官方网站下载的 1.9版本 ，因为软件内并没有任何与USB相关的代码（std::filesystem 根本就不能实现这样的功能），也没有任何递归软件自身目录以外行为。

你需要自己检查出现问题的原因，实际上我非常不喜欢这样的问题。

你需要提供 filec.exe 具体打开了哪个文件的相关证明。

**Comment by ShoreNinth** [comment]
感谢开发者在百忙之中给予回复！
经过排查，我发现是其他软件在占用设备，现已解决。
