### ISSUE TITLE
下载速度太慢还有的无法下载

### ISSUE THREAD

**Issue by Invinciblecod** [filecxx/FileCentipede#433]
![捕获1](https://user-images.githubusercontent.com/118048906/201468363-682b3af1-b7b9-40ce-a697-75985af418e1.PNG)
网卡正常，路由器重启后依旧

**Comment by filecxx** [comment]
从你的截图中看到 没有速度那个任务的用户数量为1, 文件蜈蚣当前并没有提供CDN服务器来提供额外加速，暂时不能下载死种。
