### ISSUE TITLE
浏览器拦截下载不正常

### ISSUE THREAD

**Issue by guojq82** [filecxx/FileCentipede#44]
点击直接下载的链接  浏览器闪一下 没有拦截下载  使用右键下载正常

**Comment by guojq82** [comment]
对了 托盘图标双击显示  建议加个置顶  目前双击唤醒在浏览器后面  还得去任务栏点击一次
右键托盘显示/隐藏 功能是置顶的

**Comment by filecxx** [comment]
你确定是装的1.2版本的插件吗，理论上和右键下载应该是一样的，置顶我会尝试弄下。

**Comment by guojq82** [comment]
的确是最新版 早上刚升级的  主程序1.3  扩展1.2
测试的网站是微当下载（这网站有点那个。。。注意点下面本地下载那一排的下载链接）  环境：win11.22572.201 浏览器：猫眼浏览器（catxp）  点击以后会新建个标签页 然后标签页关闭 但是没有传输下载

**Comment by guojq82** [comment]
测试了几个网盘 全都没有问题 就是这个直接下载链接的有这个问题

**Comment by filecxx** [comment]
我刚测试微当下载用的chrome没问题，firefox也没问题，我晚点测试下 "猫眼浏览器"

**Comment by guojq82** [comment]
呃  辛苦  这样的话 我找找自己问题吧  看看是不这浏览器广告拦截或者其他插件的问题

**Comment by asd0109** [comment]
我刚才也试了一下的确是不能下载，我是新装的 chrome 也是 1.2的插件  1.3 的主程序。 操作系统是 win11

https://www.weidown.com/yasuojieya/35.html    下载页面在这里

**Comment by filecxx** [comment]
如果再遇到该问题在扩展popup面板里的下载管理器 切换成浏览器 试试是否也是弹出一个新页面就没反应了，我刚才测试了，确实微当上部分页面会出现这个情况，无论是浏览器下载还是文件蜈蚣下载。

**Comment by guojq82** [comment]
好吧 顺便发现个问题  浏览器扩展 会间歇性出现不加载  扩展栏不显示 右键里面也没有  然后进去扩展管理 怎么也不做 再退出来就好了
不知道是不是猫眼浏览器的问题

**Comment by filecxx** [comment]
可以尝试下解压chrome.zip ,然后加载已解压的文件夹试试。

**Comment by guojq82** [comment]
尝试解压加载 有条错误提示Manifest version 2 is deprecated, and support will be removed in 2023.
高亮  "manifest_version":2,   貌似不影响使用
再问下 蜈蚣的配置文件保存在哪个文件 每次升级删除老文件会丢失配置

**Comment by guojq82** [comment]
额 又碰到一个奇怪问题  卡饭论坛 下载一个名为[Chrome＋＋_v1.4.2_x64_By_shuax.7z]的论坛附件 会直接导致蜈蚣无法使用
弹框“正在尝试与filec建立链接” 一直连接不上  结束进程重启都没有  除非重新安装     而且就这个附件有问题  下载其他论坛附件都没事
https://bbs.kafan.cn/thread-1419691-1-1.html  这是帖子地址

**Comment by filecxx** [comment]
可以直接覆盖安装，lib目录下有个.db文件，这个是数据库文件，另外，建议直接下载filecxx.com网站上提供的最新版本 （这个论坛链接我打不开）

**Comment by filecxx** [comment]
这个确定了是浏览器的BUG，主要是在https网站上打开http下载链接会出现这个情况，下载站和浏览器扩展都没问题。

**Comment by filecxx** [comment]
https://www.ssl2buy.com/wiki/google-chrome-to-block-http-downloads-on-https-page
