### ISSUE TITLE
请教：磁力链接无法下载，DHT一直是0，请问如何处理？谢谢

### ISSUE THREAD

**Issue by Jason-cc66** [filecxx/FileCentipede#442]
**Please provide as much information as possible.**

version(>=2.0) :1.9

screenshot:

URL:magnet:?xt=urn:btih:39d30a0a2807391cd5594db45860e9a27eb256a5&dn=1080p.HD%e5%9b%bd%e8%af%ad%e4%b8%ad%e5%ad%97%e6%97%a0%e6%b0%b4%e5%8d%b0

.......

**Comment by filecxx** [comment]
1.9版本存在BUG，有时候会出现这个情况，请更新到2.71

**Comment by Jason-cc66** [comment]
您好，您发送的邮件我已收到，我将尽快查阅，谢谢。

**Comment by Jason-cc66** [comment]
已解决，非常感谢！软件超级棒！

**Comment by Jason-cc66** [comment]
.
