### ISSUE TITLE
所以为什么叫“文件蜈蚣”而不叫“文件鸭”（

### ISSUE THREAD

**Issue by meiruitesi** [filecxx/FileCentipede#444]
![image](https://user-images.githubusercontent.com/84609642/203689882-dfa22b75-784c-457d-b498-e6350fe40432.png)

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/203706181-98d18d90-5eb0-42c0-aedf-98d8d98ff2fa.png)
从这个视角来看，这个名字还是比较合适的
