### ISSUE TITLE
提示“发送失败, 无法连接到 localhost:10111文件蜈蚣 要么没有安装,或者没有启动, 选择一个操作”

### ISSUE THREAD

**Issue by alsa001** [filecxx/FileCentipede#446]
在启动软件的情况下，视屏浮动栏点击下载提示“发送失败, 无法连接到 localhost:10111文件蜈蚣 要么没有安装,或者没有启动, 选择一个操作”.手动添加复制的链接点击下载也没有任何反应[](url)

**Comment by alsa001** [comment]
版本号为2.7.1，无法使用的网站链接https://gaze.run/filter，这个网站以前是可以正常使用的

**Comment by filecxx** [comment]
出现这个情况只有2个可能性
第一个是软件设置-服务 状态为禁用或者端口不是10111
第二个是这个端口被防火墙等屏蔽了

**Comment by filecxx** [comment]
[https://gaze.run/filter](https://gaze.run/filter%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E4%BB%A5%E5%89%8D%E6%98%AF%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A8%E7%9A%84)

我刚测试这个网站，确实会弹出这个提示，可能是数据包超过2M，下个版本尽量修复这个问题。

**Comment by filecxx** [comment]
这是浏览器扩展上处理URL的BUG，预计是遇到 blob://blob://http://www .....com 这样的字符串了

临时解决方案
![image](https://user-images.githubusercontent.com/100348948/204083145-549b800e-889f-4a6f-a516-c6fe0a2f8b32.png)
点击复制
然后打开 
软件 - 工具 - base64

![image](https://user-images.githubusercontent.com/100348948/204083192-a5644a9e-9097-4cdb-8488-085710265d4e.png)
从字符串中删除fileu:0 ，点击解码

![image](https://user-images.githubusercontent.com/100348948/204083233-abd78c5f-fcc7-4750-8676-d1b356b5f465.png)

从解码后的字符串中找到 "uri":"blob:

删除blob: ，然后复制全部
在软件中打开任务对话框，粘贴已经复制的字符串

![image](https://user-images.githubusercontent.com/100348948/204083296-af8fb3b3-a737-49c4-8fda-c7b4ddd7be9a.png)

点击下载

**Comment by kotobuki09** [comment]
> This is a bug in the processing of URLs on the browser extension. It is expected to encounter a string like blob://blob:// [ http://www ](http://www) .....com
> 
> temporary solution ![image](https://user-images.githubusercontent.com/100348948/204083145-549b800e-889f-4a6f-a516-c6fe0a2f8b32.png) click to copy then open Software - Tools - base64
> 
> ![image](https://user-images.githubusercontent.com/100348948/204083192-a5644a9e-9097-4cdb-8488-085710265d4e.png) Remove fileu:0 from the string, hit decode
> 
> ![image](https://user-images.githubusercontent.com/100348948/204083233-abd78c5f-fcc7-4750-8676-d1b356b5f465.png)
> 
> Find "uri" from the decoded string: "blob:
> 
> delete the blob: , then copy all Open the task dialog box in the software, paste the copied string
> 
> ![image](https://user-images.githubusercontent.com/100348948/204083296-af8fb3b3-a737-49c4-8fda-c7b4ddd7be9a.png)
> 
> click to download

I got the same issue and the temporary solution working as well

**Comment by filecxx** [comment]
已修复。

**Comment by crazy-zxx** [comment]
2023.08.20

今晚一直报这个错误，所有网站的下载都报这个错，即便卸载了重新安装也没法解决。

难道是千年虫？？？QWQ
