### ISSUE TITLE
请问做种时哪里看进度呢？

### ISSUE THREAD

**Issue by End-Satan** [filecxx/FileCentipede#449]
不然比较大的文件看不到进度不知道具体还要等多久

**Comment by filecxx** [comment]
做种没有进度，会根据设置的上传的字节数或者比例自动停止，可以在属性面板中看到上传字节和比例。

**Comment by filecxx** [comment]
上传1M - 下载1M
比例为 1:1

上传0.5M - 下载1M
比例为 0.5:1

**Comment by End-Satan** [comment]
> 下载1M
> 比例为 1:

然后我分享种子禁止某个ip为什么无法禁止，根本没用，它还是会继续下载

**Comment by filecxx** [comment]
不可能，我每天都在禁止，禁止IP是禁止IP+端口，例如禁止 127.0.0.1:12345 ，127.0.0.1:12346 还是可以连接。

**Comment by filecxx** [comment]
这个过程可能有延迟，你可以再选择断开连接。
