### ISSUE TITLE
youtube 下载的视频没有声音

### ISSUE THREAD

**Issue by asd0109** [filecxx/FileCentipede#45]
https://www.youtube.com/watch?v=Vaz_kpmTi0M&ab_channel=1MILLIONDanceStudio

在这个连接上测试的，下下来的文件打开后没有声音。

**Comment by asd0109** [comment]
https://www.bilibili.com/bangumi/play/ss27767?from_spmid=666.9.hotlist.6     这里下载的视频也没有声音

**Comment by filecxx** [comment]
现在浏览器扩展没有对一些视频音频分离的网站做针对处理，只能把视频和音频下载下来合并。
