### ISSUE TITLE
浏览器插件问题？导致大流量不停下载东西？还是？

### ISSUE THREAD

**Issue by niu12503** [filecxx/FileCentipede#452]
**Please provide as much information as possible.**

version(>=2.0) :2.71

screenshot:

URL:
安装完chrome 插件，观看youtube使用后，网络监控显示不停的大流量下载东西，哪怕把网页关掉，也停不下来。
关掉翻墙软件，网速正常。再次打开翻墙，看youtube看视频，又是同样情况。

但是如果把插件禁止，在看youtube，就没有任何问题,还以是插件后台监测导致不停的下载？
.......

**Comment by filecxx** [comment]
整个插件的实现你可以解压chrome.zip 查看 background/background.js 中的源码。

**Comment by niu12503** [comment]
不懂这些，只是反应问题，是否有决绝方法呢，软件还是很好用的

**Comment by filecxx** [comment]
你应该检查下 chrome://downloads/ 是否浏览器本身在下载某个文件，或者检查下油猴脚本，因为chrome插件本身是做不到这件事的，包括其他牌子的chrome插件。
