### ISSUE TITLE
我下载流文件时也出现地址已过期

### ISSUE THREAD

**Issue by flwwater** [filecxx/FileCentipede#454]
version(>=2.0) :2.71

screenshot:
![图片](https://user-images.githubusercontent.com/67504938/206434304-415dcda9-0650-4241-b51d-3d9c48aade62.png)

URL:
https://7mmtv.me/zizg-003/

stream设置里都试过了,有时下载10%就过期,有时能下载到30%,搞不明白是怎么回事,下载了半天都好好的,成功下载过几个文件,后来当出现地址已过期后重新下载就一直有问题,是不是被服务器加黑名单了?无论怎么使用刷新地址功能都无法下载.
下载流的时候我注意到是从最后一个segment开始往前下载的.会被服务器认为非法吗?

**Comment by filecxx** [comment]
部分的流服务器确实会根据下载速度和并发连接数量封IP一段时间，这个时候需要换IP，然后刷新地址。

最好是选一个常用的流服务器
![image](https://user-images.githubusercontent.com/100348948/206536830-98c36432-ed19-43c5-9dac-0988253ccae3.png)
比如VV这个流，几乎不封IP

**Comment by filecxx** [comment]
已修复。
