### ISSUE TITLE
高级版和免费版有什么区别？谢谢

### ISSUE THREAD

**Issue by NickPetrelli** [filecxx/FileCentipede#457]
高级版和免费版有什么区别？谢谢

**Comment by filecxx** [comment]
版本号区别，免费版是1.9 
可以查看更新日志
http://www.filecxx.com/zh_CN/update_log.html

**Comment by NickPetrelli** [comment]
> 

下载速度和功能上没有区别吗？感谢

**Comment by filecxx** [comment]
下载种子和磁力查找peer会快一些，对于HTTP下载所有多线程下载工具速度都差不多，不过相对于1.9设置里多了并行选项(平滑的/最快的)。不过1.9有一些BUG。
