### ISSUE TITLE
设置中”未完成的保存路径”的保存路径无法修改吗？

### ISSUE THREAD

**Issue by wy3388** [filecxx/FileCentipede#458]
设置中”未完成的保存路径”的保存路径无法修改吗？旁边的选择框也无法勾选。

version：2.7.1

![image](https://user-images.githubusercontent.com/33230030/206836677-84c60a5f-e999-413a-857e-448d5e018024.png)

![image](https://user-images.githubusercontent.com/33230030/206836695-155fe445-045a-459a-8051-bcf007bc073a.png)

**Comment by filecxx** [comment]
这个功能未完全测试，可能有BUG，所以暂时禁用了，3.0之后再开放。

**Comment by wy3388** [comment]
好的，感谢大神开发的软件
