### ISSUE TITLE
关于激活码

### ISSUE THREAD

**Issue by noxsave** [filecxx/FileCentipede#460]
首先感谢作者大大，喜欢文件蜈蚣简洁且功能强大的设定，不过每天一次的激活码着实影响体验，想入永久激活码吧又囊中羞涩觉得太贵。所以弱弱问一下怎样才能成为贡献者，多少贡献才能换到永久激活码？

另外提一下仪表盘中居然没有账号密码找回功能T.T

**Comment by filecxx** [comment]
仪表盘上有个引荐功能，大概1400个IP访问可以兑换成28 USD。

或者帮助翻译也不错。

任何能够对这个项目起到正面作用，帮助发育的都是贡献。

**Comment by noxsave** [comment]
好的，谢谢鹅大。那么那个仪表盘登陆界面中能加一个“找回密码“功能么，毕竟忘记密码的现象挺普遍的，而且注册的时候一般也都填了邮箱。

**Comment by filecxx** [comment]
没问题，下次升级仪表盘时候添加一个这功能。
