### ISSUE TITLE
The program used 1,4 GB in two days without even being used once or the extension being enabled(the system service was on)

### ISSUE THREAD

**Issue by yolorag** [filecxx/FileCentipede#464]
Not accusing anyone or anything, just asking why?

Over 20k connections to Chinese IPs.

The app is still running in the background and downloading and uploading even with the system service being turned off
![Zrzut ekranu (144)](https://user-images.githubusercontent.com/22390622/208231392-ad697712-9a91-4403-83fc-6a04996f9bde.png)

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/issues/380
