### ISSUE TITLE
Google Drive file download mistake changes to file identifier.html 

### ISSUE THREAD

**Issue by cuonglb696** [filecxx/FileCentipede#466]
Google Drive file download mistake changes to file identifier.html. it's ok to download the second time

**Comment by filecxx** [comment]
Thanks for the feedback.

**Comment by cuonglb696** [comment]
> Thanks for the feedback.

I hope this bug is soon fixed.

**Comment by cuonglb696** [comment]
I hope this bug is soon fixed.

**Comment by filecxx** [comment]
It will be fixed, eventually.

**Comment by DirgaBrajamusti** [comment]
i'm using brave browser and enable cross-site cookies in google drive to fix it, maybe you try that? but i can't open refresh address dialog anywhere (maybe different bug?) when download is address expired

**Comment by filecxx** [comment]
> i'm using brave browser and enable cross-site cookies in brave blocker for google drive to fix it, maybe you try that? but i can't open refresh address dialog anywhere (maybe different bug?) when download is address expired

"refresh address" currently is for videos only, that's not a bug, I just forgot to implement it.

**Comment by DirgaBrajamusti** [comment]
> "refresh address" currently is for videos only, that's not a bug, I just forgot to implement it.

Okay, I'm gonna wait this implemented before i'm trying it again

**Comment by filecxx** [comment]
> Google Drive file download mistake changes to file identifier.html. it's ok to download the second time

I just tested many times, all passed through, I don't think it's a bug, maybe that was reCaptcha.

**Comment by BoscoFZ** [comment]
> > Google Drive file download mistake changes to file identifier.html. it's ok to download the second time
> 
> I just tested many times, all passed through, I don't think it's a bug, maybe that was reCaptcha.

It still happens when I use an incognito window. You should try checking this case again and see what's going on.

**Comment by filecxx** [comment]
It has been fixed in version 2.82, but only for chrome.

Firefox is still unable to query cookies from the private window (I don't know how).

**Comment by filecxx** [comment]
Please update the FileCXX web browser extension to 1.81
