### ISSUE TITLE
建议：增加黑暗模式，跟随系统明暗主题自动适应

### ISSUE THREAD

**Issue by crazy-zxx** [filecxx/FileCentipede#467]
期待开发大佬增加自适应系统主题的白天和黑暗模式切换，强迫症患者受不了晚上刺眼的白色主题。

**Comment by filecxx** [comment]
如果有适应黑色主题的白色图标这个任务可以很快完成。

**Comment by crazy-zxx** [comment]
[dark.zip](https://github.com/filecxx/FileCentipede/files/10299438/dark.zip)

我简单处理了一下icons图标的颜色，并试着改了一下css文件里的配色，貌似效果也还可以，不过不是很熟悉代码所以有些地方的颜色没调好。

![image](https://user-images.githubusercontent.com/29439759/209457212-3039159c-6e4c-48a4-be17-493f7e7c3a43.png)

![image](https://user-images.githubusercontent.com/29439759/209457241-419a7dea-b11c-4074-8394-32df41de5093.png)

**Comment by filecxx** [comment]
能改成这样已经非常不错了，部分的颜色在sml文件里，其中一些比如组合框等样式不是很容易改。

Qt的css不是很强大，差不多10多年都没更新了，软件3.0之后UI库可能会换成GTK4 ，对css支持比较完全，包括css3动画, box-shadow 等，并且原生支持黑暗风格。

有合适的图标可以提交给我，到时直接应用到发布版里。

**Comment by crazy-zxx** [comment]
![image](https://user-images.githubusercontent.com/29439759/209757160-1c2dcd6e-307b-4fc5-8169-f1175528a71a.png)
![image](https://user-images.githubusercontent.com/29439759/209757215-87502389-7e77-4ccd-9953-a97b5045cee0.png)


淡紫色的图标，能同时适应黑白色背景：
[icons-Lavender.zip](https://github.com/filecxx/FileCentipede/files/10312084/icons-Lavender.zip)

白色的图标，适应黑色背景：
[icons-white.zip](https://github.com/filecxx/FileCentipede/files/10312097/icons-white.zip)

**Comment by filecxx** [comment]
Thank you.

**Comment by 1mathart** [comment]
> [dark.zip](https://github.com/filecxx/FileCentipede/files/10299438/dark.zip)
> 
> 我简单处理了一下icons图标的颜色，并试着改了一下css文件里的配色，貌似效果也还可以，不过不是很熟悉代码所以有些地方的颜色没调好。
> 
> ![image](https://user-images.githubusercontent.com/29439759/209457212-3039159c-6e4c-48a4-be17-493f7e7c3a43.png)
> 
> ![image](https://user-images.githubusercontent.com/29439759/209457241-419a7dea-b11c-4074-8394-32df41de5093.png)

huge thank to you !
