### ISSUE TITLE
希望能增强排除功能以及一bug报告

### ISSUE THREAD

**Issue by YandLiu** [filecxx/FileCentipede#468]
1. 增加排除文件类型：PDF/DOC/XLS/PPT之类一般比较小，希望用浏览器直接下载
2. 排除小文件：另外还有一些其他的小文件，希望也能够直接用浏览器就下载了
3. 现在这个“忽略此站”有时并不管用啊，有的网站依然会被filecxx接管，目前我遇到的是部分需要账号的网站是如此，等我遇到适合分享出来的网站时再多举例

**Comment by filecxx** [comment]
“忽略此站” 只会根据当前域名进行判断，有时候下载地址和当前域名不同，所以不起作用，排除等功能下次更新时候尽量添加。

**Comment by filecxx** [comment]
浏览器扩展2.2版本中增加了 “设置” 功能，可以手动指定不下载的扩展名或MIME
