### ISSUE TITLE
Firefox拦截下载器没有效果

### ISSUE THREAD

**Issue by Dynamith** [filecxx/FileCentipede#47]
试了一下，把所有其它扩展都禁用了也不行。但在edge上是正常可以拦截的。

**Comment by filecxx** [comment]
火狐需要点击保存按钮之后才能拦截, 因为浏览器缺少ondeterminatefilename 这个函数.

**Comment by Dynamith** [comment]
哪里有保存按钮啊

**Comment by filecxx** [comment]
火狐浏览器下载时候会自动弹出一个保存文件的对话框，有2个按钮，一个保存，一个取消，点击保存。

**Comment by Dynamith** [comment]
哦哦哦！我明白了，多谢指导
