### ISSUE TITLE
请问能否设置小文件不调用文件蜈蚣下载？谢谢。

### ISSUE THREAD

**Issue by Jason-cc66** [filecxx/FileCentipede#470]
**Please provide as much information as possible.**

version(>=2.0) :2.71

screenshot:

URL:

.......

**Comment by filecxx** [comment]
可以增加类型和扩展名判断，小文件判断可能不会很准确。

**Comment by filecxx** [comment]
浏览器扩展2.2 版本中添加了设置，可以在 “不下载” 中添加 “不调用文件蜈蚣下载” 的文件扩展名和MIME

**Comment by Jason-cc66** [comment]
您的邮件已送达，谢谢。
