### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by 6677028** [filecxx/FileCentipede#472]
Filecxx Download failed
![osin8AZ 1](https://user-images.githubusercontent.com/43196562/210127735-2b6a65ae-da7e-42f8-bfa9-0c0186b171aa.png)

**Comment by filecxx** [comment]
Please provide me with at least one URL address.

**Comment by filecxx** [comment]
There are two potential causes for the "Operation failed" error:

1. The error may occur if the program cannot open files from the disk.

2. The error may also occur if your IP address has been banned by the remote HTTP server, which can happen if you have made too many connections to the server.

**Comment by 6677028** [comment]
Here is the link I downloaded. It's a youtube playlist

https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY4HPBq6C6dsPmo23OA&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-APGYxVbdbm4R9ik-8_6fCqtAx3VPlKeVr1iMbhqFnD7-&itag=22&source=youtube&requiressl=yes&mh=9i&mm=31%2C29&mn=sn-4g5ednd7%2Csn-4g5lznls&ms=au%2Crdu&mv=m&mvi=2&pl=48&initcwndbps=315000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=156.479&lmt=1663253171234556&mt=1672532934&fvip=3&fexp=24001373%2C24007246&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJgrH3n2dnYJ1G2tfAYbsBgD7fmrmNUdTz1eUeFNosMMCIBlUuzYxaLKZcqV9JN6qsno3jULli3vXXFgate97KXRC&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgeXTou4oOLqs2idLETBoW-n-eCjdmCet2zH6p4LmBXMYCIBPxU31S2Omwmdc7AE8A0AId1TzbvlsPxKwsW822mOzC&title=09.Power%20Query%20Challenge%20-%20Creating%20a%20Merge%20Duplicates%20Alert
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY6erB9mU1gKxs7HgCw&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-APmlgGtyp1RMk3tXLzP1ctX-KeVtxZggzEctGs_pnf0w&itag=22&source=youtube&requiressl=yes&mh=u2&mm=31%2C29&mn=sn-4g5e6nzs%2Csn-4g5edndr&ms=au%2Crdu&mv=m&mvi=4&pl=48&initcwndbps=315000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=618.974&lmt=1649465013651429&mt=1672532934&fvip=2&fexp=24001373%2C24007246&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgBV2L-gfS3qJJx9Acod6jnHeopWC5ao3ESaU87tY1vJMCIA2U0wlpx356iiWWa9zuT0oRRudOkPN9kqGKs4O_iaz4&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgQdXj_C2gSvyvr6ynOpEnwkVh1zrwCfo1MuBZM9zsmccCIEgh07VTDXokeSZn1_wCBQOxjgfZ-9HlpWvFVYMKwc6h&title=01.Power%20Query%20Dates%20and%20Time%20Challenge
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY9X-BsWj1gL0po6oAw&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AG8IqtZCz8t8gWdarmSWMBQskF_pgXd6x06kzLhpUbVg&itag=22&source=youtube&requiressl=yes&mh=Dx&mm=31%2C29&mn=sn-4g5e6ns7%2Csn-4g5ednsr&ms=au%2Crdu&mv=m&mvi=3&pl=48&initcwndbps=313750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=738.278&lmt=1636279474770468&mt=1672532934&fvip=3&fexp=24001373%2C24007246&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAL3r0byRXpPQk-nM1mQBQRKkGCQNw9WiTo9mZS2dbtF3AiBAZMTe8lPGT75F4XVqm0f7EiiaRGVYqKVFbEXTHgd8OA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgZJdNlBwdYxxqDwRA9bfTqm0YD99YcAozVmERlMFZBjgCIQDoW9buMN93xKfhEqlGk6kXGp5x2H83aTLXcn0vKGqTtw%3D%3D&title=05.Power%20Query%20Cost%20Allocation%20Challenge
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY4vMBoOE8gP-o6aoDw&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AAa4ERbclC11sin4SbYNUzJkqa-Lvk88hBb5eA2Ov1Ye&itag=22&source=youtube&requiressl=yes&mh=FU&mm=31%2C29&mn=sn-4g5edn6k%2Csn-4g5e6nsd&ms=au%2Crdu&mv=m&mvi=5&pl=48&initcwndbps=315000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=547.247&lmt=1669111027190360&mt=1672532934&fvip=2&fexp=24001373%2C24007246&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKdmchjqg7cM3eDCtE1EK4rJlGWaEXF8_pnH0sInAmcUAiBsbk0ymlBuSJIEz0eeoJD8TQJwLKaUwBWA71WBIZWt_Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAO7YIAr2ADv5WC-8OFHod-E5hbxKc01IEtbTK366UNWwAiBlIbeDHkolkqZdHW_hBAkRbqYrvIArCMqPfQuKxaSouw%3D%3D&title=11.Convert%20Range%20of%20Values%20to%20a%20List%20%20-%20Power%20Query%20Challenge
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY4mHBpH51wLh9oOABA&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AJm7E7Lbbb_Zs-jYUaV3Oe9gUJK4mNJfytvHy_G7btT5&itag=22&source=youtube&requiressl=yes&mh=Hg&mm=31%2C29&mn=sn-4g5lznl7%2Csn-4g5edndy&ms=au%2Crdu&mv=m&mvi=4&pl=48&initcwndbps=313750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=911.313&lmt=1664727125991401&mt=1672532934&fvip=3&fexp=24001373%2C24007246&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAI5PGotxTp9UNp71IqYvM-mZiJfzKHI5XXq8-UW9wS_LAiBXBLcpnanmFusXcowE283IoYDTATK9MOSHOYgXC0sWzA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOPDcAvGL3L3isQreHOn5uXDkryjg8IRPxUXOEQ_OBVBAiEAvR_uf6lgJx2FmTldr304in27XALPAqyy0B6dv8ia8OQ%3D&title=10.Power%20Query%20MERGE%20Challenge%20Solution%20-%20DUPLICATES%20Alert
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY4nRB82c8gPoj6rIDQ&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AHPXwKG9HW0mWK_PaF5LpV8oKHc3_5eeRM802RRUE2Mn&itag=22&source=youtube&requiressl=yes&mh=qs&mm=31%2C29&mn=sn-4g5e6nze%2Csn-4g5edn6k&ms=au%2Crdu&mv=m&mvi=4&pl=48&initcwndbps=315000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=386.496&lmt=1652610545718640&mt=1672532934&fvip=3&fexp=24001373%2C24007246&beids=24432614&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQSAML3HjNPUjoLTb3DGcCX5xmbNvTToaCQhmH78Yv-sCIQCjB4O6l4nVNmRKq6dUZwe_K5Sc6mlEmO0qZS9_9QfKjA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJIiV2c3SO-OQ7Nk07mbUhFH-I4N0Zl1t29FAmMR7c6WAiEAlXs0pyTgNcnXWKNZUkO4OZJNmsUy0lm4L-8MnhgMMIk%3D&title=07.Power%20Query%20Pivot%20and%20adding%20an%20Index%20column%20to%20a%20Grouped%20Field
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY6npB6GJ6dsPpMKyuAE&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AOyEzLtxbWdyVXGTxl0BWIIYhNSpcZ86qE9WJlerqKHT&itag=22&source=youtube&requiressl=yes&mh=Xj&mm=31%2C26&mn=sn-4g5e6nsk%2Csn-5hne6nzy&ms=au%2Conr&mv=m&mvi=3&pl=48&initcwndbps=313750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1022.351&lmt=1671536443775154&mt=1672532934&fvip=3&fexp=24001373%2C24007246&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJOu1EmSGjTJTEcumByepaoVbdx8Qv-n43X9EDnX-5yACIQDgOfa1un0tM4GNI5RMS985fKHuCX1pBQsqxtHa-XNBRA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgNtFw4Q5frP-NaovUZmNZB6gh8b2SKLdoc3BmOVCKyTMCIQCB9Psyw32wP_9HBba6ptdC_NDwDwpIkHSX_5BhgNnKlw%3D%3D&title=12.Power%20Query%20Multi%20Column%20Data%20%20-%20Best%20In%20Class%20Challenge
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY4XxB5XO1wKb6I_QAQ&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AKgx6GkZGkoud9Rh2mfrrO1mR-22VV5fZkHdaUGVxmbT&itag=22&source=youtube&requiressl=yes&mh=cw&mm=31%2C29&mn=sn-4g5lzne6%2Csn-4g5ednsy&ms=au%2Crdu&mv=m&mvi=3&pl=48&initcwndbps=315000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1075.826&lmt=1642927494086473&mt=1672532934&fvip=4&fexp=24001373%2C24007246&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgIxrxV0INXagJbviw-xr79UZXRgOIp17-AE__9dT-jgICIGsNi-b21QakgzWLTrzxk0ou71lUKtf77hRYbDjPt9Ez&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTlNQCBkdKGzwxBsPkvh2Nz6V-Cqb5WhNWVrnz5Eil_YCIQDQ0q02raZxfQlyTDFdi4vMy6anY4HjM3kLqSLmciqyqw%3D%3D&title=03.PQ%20Challenge%20Splits%20and%20Lists
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY-yeB9Wd8gPTlrXoBQ&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AIwZ3JVamqWr8EiokaMp3RRQJH2LdJl0hFd1eESHu9ut&itag=22&source=youtube&requiressl=yes&mh=ER&mm=31%2C29&mn=sn-4g5ednsk%2Csn-4g5e6nz7&ms=au%2Crdu&mv=m&mvi=3&pl=48&initcwndbps=315000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=945.075&lmt=1651980223696387&mt=1672532934&fvip=3&fexp=24001373%2C24007246&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgVp-1J3vlzewOKomyzmPoOJYKgHlQ9Ll2k-c3k7DHZUoCIQCLpIrUFeQDVZIvvHJo2qJXz1rJkNlq-1avKU1nBVQaDA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMPvE77DjF0DzjNNrz9tvKplhqKjANyMicQo_BVTub2_AiEAyd0X7-xGtVk0-tIYBZ-VIWX6y6jNMYSqY-Dr3mjGBfs%3D&title=06.Power%20Query%20Convert%20Columns%20to%20Rows%20for%20groups%20and%20expand%20columns%20dynamically%20in%202%20ways
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY5XXCMfa1gKLzZf4BA&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AHdJVVmOtLMPFmfhmwY-w0qLARMbDzX7JzBszh0zYGII&itag=22&source=youtube&requiressl=yes&mh=RW&mm=31%2C26&mn=sn-4g5lzney%2Csn-5hne6n6e&ms=au%2Conr&mv=m&mvi=2&pl=48&initcwndbps=313750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=872.280&lmt=1661512493671665&mt=1672532934&fvip=5&fexp=24001373%2C24007246&txp=6318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJJzK7N3HgEZSg1kMTcZL7prfr3tiME67Kqc_oRynRT0AiA3AWoW1KvAfyQ_8tEYX7kRveMzzMIA5R-cjAtdVvZK_w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgBDEEjA0Awlejca96LVsGT4809OW0AmCeJfiM5VJBO0QCIBsupjhcPSU2I0r641SPQKYuBH0zhmkjrfhtkPo4FjaP&title=08.Excel%20Power%20Query%20%20Start%20Stop%20Challenge
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY6ndCIed8gOm3aTIDA&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AJjyKLn5-NG-BW7mDzuoxKDlWPpe7b0Dgjuzw5VBH2AE&itag=22&source=youtube&requiressl=yes&mh=ef&mm=31%2C29&mn=sn-4g5lzney%2Csn-4g5ednsy&ms=au%2Crdu&mv=m&mvi=2&pl=48&initcwndbps=313750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=737.837&lmt=1646471494424946&mt=1672532934&fvip=3&fexp=24001373%2C24007246&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIjT2HrZwV-f6Lu-Wpx0oL5snJeH7z2Yh7zIsF7RpQNsAiEA64TWfnCcb4kjxM8Tx9oa_zeZ6JpRf0o49mTwGShnI_g%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMCFgBe7Id8_-J36bdt48T04WCkNJlytsRPERRnn9ZSmAiEA2SuVBtiGyGAsx5q42yKZjq4e2ZE0ihpWDqa7hVCUI5w%3D&title=02.Combining%20Excel%20Tables%20in%20a%20highly%20flexible%20way
https://redirector.googlevideo.com/videoplayback?api=youtubemultidownloader.com&expire=1672554813&ei=3dSwY8eLB4yE8gPzuJbAAQ&ip=2a03%3Ab0c0%3A3%3Ae0%3A%3Ae6%3Af001&id=o-AFKfQ1Dq_b7tFJYWvvqzQgLuJWC2EPyTLOMPqD_mJDVj&itag=22&source=youtube&requiressl=yes&mh=RU&mm=31%2C29&mn=sn-4g5lzned%2Csn-4g5edndr&ms=au%2Crdu&mv=m&mvi=1&pl=48&initcwndbps=315000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=907.273&lmt=1638694560501599&mt=1672532934&fvip=5&fexp=24001373%2C24007246&beids=24432615&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgMmO9n_biXZq88JLnv5P0DmGqpp_kBmWHV7-j4BTBqS4CIQDsqOziCx6_Z0dqaX0q_xNM4W8pZo1NaU9Q-ggMvW_A5w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgRrRx1PC-S8dg8NpSdx0uRdjNZJRYKTGodVXy9nkdl1kCIC-F-uJAaMKz4mVKlXa1_hh2gC9yyoEG0U2TdXexewEU&title=04.Power%20Query%20Table%20Flip%20Challenge

**Comment by filecxx** [comment]
Thank you, I just fixed 
![image](https://user-images.githubusercontent.com/100348948/210159119-d0a89a63-09c3-4852-bdf5-9cfad67dbdb0.png)

It's a redirect bug.

**Comment by 6677028** [comment]
Now what should I do to fix this error.

**Comment by filecxx** [comment]
I will release 2.81, maybe tomorrow.

**Comment by 6677028** [comment]
ok thank. i will wait

**Comment by 6677028** [comment]
When will update 2.81?

**Comment by filecxx** [comment]
tomorrow.

**Comment by 6677028** [comment]
ok fixed successfully

**Comment by 6677028** [comment]
Strange error.
 After downloading video1, continue to download video 2, the name of video 2 is the same as the name of video 1.
 these 2 videos have different names.
![8SqW0RK 1](https://user-images.githubusercontent.com/43196562/211154724-ae90a737-b89f-4d9b-ac3f-aad49b7dd66f.png)

**Comment by filecxx** [comment]
Could you provide me with the URL of the two videos?

**Comment by 6677028** [comment]
Video 1: https://rr2---sn-8pxuuxa-i2iel.googlevideo.com/videoplayback?expire=1673121313&ei=wXm5Y8iKBMKkvcAPrJqf6AM&ip=2402%3A800%3A61d0%3Ad6d3%3A3de2%3Accca%3A7f52%3Abf15&id=o-ADbHBnGG-CSPButV_vK2Z5EHqlPkJqepN-xtUU_aAMFX&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=7l&mm=31%2C29&mn=sn-8pxuuxa-i2iel%2Csn-8pxuuxa-i5o6d&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=50&initcwndbps=1046250&spc=zIddbDD2LzS52zX8QHaL7AHUWzYzfeV4fyOVI2v5UqUK&vprv=1&mime=video%2Fmp4&ns=LKB9RwB-eil0kewxZXqh8D0K&gir=yes&clen=77053802&dur=999.633&lmt=1639904774251293&mt=1673099385&fvip=6&keepalive=yes&fexp=24007246&c=WEB&txp=5316224&n=s8ZskEEOQyOJqyXN4&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMLcnit1NQcaq7efwXDvyrWuCeTUTqYVUBbpz1FWAi_hAiEAwcYFgSoAbg5PIdWiVtT6dE6hii00dK_pcK_SQqRvSFQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgE1JlbTTyqKRXFinVPNeZpWFOnwbaNt6hJ92JWvoCfg0CIQCPj_Z_F76vkQj84x80GegaskxwAVXsUZOxAtg71AwEnA%3D%3D
 
Video2: 
https://rr1---sn-8pxuuxa-i2iel.googlevideo.com/videoplayback?expire=1673121353&ei=6Xm5Y-eBJKiNvcAPhPS0wAc&ip=2402%3A800%3A61d0%3Ad6d3%3A3de2%3Accca%3A7f52%3Abf15&id=o-APfz6o5V7JXyJbgnxfn5k0-cXvf9Vm-UQdOABRSFEpHC&itag=136&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=KD&mm=31%2C29&mn=sn-8pxuuxa-i2iel%2Csn-8pxuuxa-i5o6d&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=50&initcwndbps=1046250&spc=zIddbBqzLMBti5K5jitq5sChjn1Iwk4RBzFMESP_KBy6&vprv=1&mime=video%2Fmp4&ns=epplSV8bMoORdfgNM0L9oQcK&gir=yes&clen=15069440&dur=355.899&lmt=1637537705295619&mt=1673099385&fvip=1&keepalive=yes&fexp=24007246&c=WEB&txp=5316224&n=RoUnYprmncGN4aiGb&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgTZ8E3ZjG-JScySo7GcZMs6K9k_KzAxWY8eUc8-U9j9sCIH_SaMP_VquJpxVCbuJQX7hVPUkZDcaSmwQANZBbaX0q&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgSCBEzmcrVRueKMzGpBdLT4G-RQ4Lhz2-Sn-fzrcU-BcCIB52H7Mbf1BVs9-IFf7vJNKgUW_edRJHmcRGwxnUkK1v

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/211155464-a353a424-0362-4d9b-a8c4-843dd15cbcbb.png)

I think the file names were obtained from the title of your web browser.

**Comment by 6677028** [comment]
No. They are different
![Captursse](https://user-images.githubusercontent.com/43196562/211155859-a2d36539-3f23-4f82-801a-b012df03e77d.PNG)

**Comment by filecxx** [comment]
I meant the URL does not contain a filename, so the FileCentipede browser extension will use the title as the filename.
