### ISSUE TITLE
程序卡死崩溃The program freezes and crashes

### ISSUE THREAD

**Issue by 522247020** [filecxx/FileCentipede#474]
**Please provide as much information as possible.**

version(>=2.0) : 2.8

screenshot:
![image](https://user-images.githubusercontent.com/38172233/210313155-09e188fd-9918-47c0-b229-f0e07fa8d497.png)
![image](https://user-images.githubusercontent.com/38172233/210313242-aae2bd47-3e08-4a74-b654-04274ef008fa.png)

URL: ...

zh: 多选编辑时会引发大量弹窗，导致程序卡死崩溃。

en: Multiple selection editing will cause a large number of pop-ups, resulting in program stuck and crash.

**Comment by filecxx** [comment]
zh: 如果同时打开这么多编辑窗口还不发生卡死或崩溃的现象那么就会是个BUG，目前看来这是正常的。

en: If it doesn't crash or freeze when you open so many editor windows at the same time, then it would be considered a bug. As it stands, it seems to be functioning normally.

**Comment by 522247020** [comment]
> zh: 如果同时打开这么多编辑窗口还不发生卡死或崩溃的现象那么就会是个BUG，目前看来这是正常的。
> 
> en: If it doesn't crash or freeze when you open so many editor windows at the same time, then it would be considered a bug. As it stands, it seems to be functioning normally.

zh: 这个是正常情况，希望能添加批量修改的功能。
en: This is the normal situation, hope to add the function of batch modification.

**Comment by filecxx** [comment]
How should I design that feature?

**Comment by 522247020** [comment]
## CN
1. 如果不能在下版本改进，请先设置最大的窗口弹出数量。
2. 增加批量修改功能：
  - 选择多个文件，点击修改配置时，弹出一个窗口进行批量设置属性
  - 文件名，地址编辑框禁用，其他对话框可修改。
  - 点击保存后循环对选中文件的属性进行修改

文件名后续可以增加自定义的格式化方法那就更棒了！

---
## EN
1. If it cannot be improved in the next version, set the maximum number of pop-up Windows.
2. Add batch modification function:
- Select multiple files, click Modify configuration, pop up a window to batch set properties
- Disable the file name and address editing box. Modify other dialog boxes.
- Click the Save loop to modify the properties of the selected file
It's even better that you can add a custom formatting method to the filename.


> How should I design that feature?

**Comment by 522247020** [comment]
> How should I design that feature?
## CN
既然你已知晓这个问题，我可以给这个问题关闭了吗？

---
## EN
Now that you know the problem, can I close the problem?

**Comment by filecxx** [comment]
## CN
像Excel一样的表格进行任务属性的编辑，这个功能可以在3.0或者之后实现。

请暂时不要关闭这个issue，否则我会忘记去实现。

---
## EN
Edit task attributes in a table like Excel. It can be implemented in version 3.0 or later. 

Please keep this issue open, so I won't forget to implement it.
