### ISSUE TITLE
请问有考虑在文件浏览器内添加修改文件权限功能吗？

### ISSUE THREAD

**Issue by hao1196561270** [filecxx/FileCentipede#482]
![image](https://user-images.githubusercontent.com/34802963/211178097-09014505-39a3-4662-a35c-69f3866adf21.png)
昨天想更新一下adg的内核发现并没有更改文件权限的功能

**Comment by filecxx** [comment]
这个功能已经设计好了，不过因为修改权限各个协议不通用，只适用于SSH(SFTP)，所以没有在fileu中添加这个UI。3.0时候会加上。

**Comment by hao1196561270** [comment]
好的 收到
