### ISSUE TITLE
Dowloaded files owner is  root user on ubuntu

### ISSUE THREAD

**Issue by divyam234** [filecxx/FileCentipede#483]
**Please provide as much information as possible.**

version(>=2.0) :2.81

screenshot:

URL:
![Screenshot from 2023-01-08 16-07-26](https://user-images.githubusercontent.com/47589864/211191709-ff2d88e8-abb6-45a0-8075-eca71f217d7a.png)

.......

All files downloaded have root user as owner so I have change the ownership everytime new file downladed otherwise I can't access file in ubuntu as current user.Is this a normal behaviour ?

**Comment by filecxx** [comment]
On Linux, FileCentipede requires root privilege to create system service, nothing more, you can run "./filec -y" to start filec, then the ownership will be the current user.

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/211192628-4cdcbbbf-983a-465d-9955-536585225b72.png)

It works fine on my OpenSUSE.

**Comment by divyam234** [comment]
> On Linux, FileCentipede requires root privilege to create system service, nothing more, you can run "./filec -y" to start filec, then the ownership will be the current user.

This one fixed the problem I was solely using UI earlier  with was starting filec service as root user.
