### ISSUE TITLE
[BUG]: 批量添加下载链接时，设置的Cookie和代理设置只对最后一行链接生效

### ISSUE THREAD

**Issue by cesaryuan** [filecxx/FileCentipede#485]
version(>=2.0) : 2.81

screenshot: 
![image](https://user-images.githubusercontent.com/35998162/212351567-d788e754-19a5-46a1-98e6-68d9eef11515.png)

URL: 
```
https://zenodo.org/record/1240534/files/Bridge6.bin?download=1
https://zenodo.org/record/1240534/files/Bridge7.bin?download=1
https://zenodo.org/record/1240534/files/Bridge8.bin?download=1
https://zenodo.org/record/1240534/files/Bridge9.bin?download=1
```

.......

**Comment by filecxx** [comment]
所有的任务默认属性是从设置里获取的，修改任务属性时候需要将下拉列表中每个任务属性都修改
![image](https://user-images.githubusercontent.com/100348948/212354506-d8b07056-9e43-4b61-989e-9e44713c632d.png)

这里只有最后一个生效是因为，只修改了最后一个的属性。

**Comment by cesaryuan** [comment]
> （对于这样的同一个域名的多个任务建议的方式是使用站点规则）

谢谢！才发现站点规则这么好用的东西

**Comment by cesaryuan** [comment]
> 只修改了最后一个的属性。

嗯呢，知道原因所在了。不过感觉这样设计确实容易误导人哈哈

**Comment by filecxx** [comment]
3.0版本时会增加一个按钮 ：“应用到所有任务”

**Comment by cesaryuan** [comment]
> 3.0版本时会增加一个按钮 ：“应用到所有任务”

嗯嗯，期待！需要关闭issue吗
