### ISSUE TITLE
Youtube下载的时候，音频视频是分开的

### ISSUE THREAD

**Issue by paynewangw** [filecxx/FileCentipede#49]
如题，目前只能下载完成借用第三方软件来合并音视频吗？还是咱们软件就有更好的方法呢
![image](https://user-images.githubusercontent.com/88674185/159229955-402b8c3e-b91a-44f3-8867-0c5cf0fce10c.png)

**Comment by filecxx** [comment]
暂时没有针对Youtube做针对的下载捕获，videos.google.com/**** 里面有video视频多个分辨率的完整视频，主程序没有BUG之后有时间了再来弄这块，既然这么人多人提议，那么以后肯定会加这个功能。
