### ISSUE TITLE
你好，求教下载".m3u8"文件方法,感谢！

### ISSUE THREAD

**Issue by szxchj** [filecxx/FileCentipede#492]
你好这个软件似乎不能下载m3u8文件，N_m3u8DL-CLI可以正常下载的链接，这个软件只能得到".m3u8"
比如https://github.com/clitic/vsd 这个项目的测试链接 https://test-streams.mux.dev/

https://test-streams.mux.dev/x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8
https://test-streams.mux.dev/test_001/stream.m3u8

**Comment by szxchj** [comment]
明白了，感谢！祝新年快乐！！！

**Comment by szxchj** [comment]
#你好,在下载前能不能批量起名,比如《001, https://test-streams.mux.dev/x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8
                                                               002,https://test-streams.mux.dev/x36xhzz/url_6/193039198_mp4_h264_aac_hq_7.m3u8
                                                               003,https://test-streams.mux.dev/x36xhzz/url_6/193039197_mp4_h264_aac_hq_7.m3u8
                                                                                                                                                                                                         》

**Comment by filecxx** [comment]
只能手动在下拉框中选择之后设置文件名
![image](https://user-images.githubusercontent.com/100348948/214644427-4a7f6d5f-f4ca-43aa-9c01-0d3a60ef38db.png)
不过已经有用户提议增加类似表格的方式批量更改任务属性，这个功能大概会在3.x 版本中增加。

**Comment by szxchj** [comment]
要是能批量更改，或者有个固定命名格式就好了，毕竟现在m3u8很流行。再次感谢你的软件！！！

**Comment by Evilfoxster1981** [comment]
有个同样的问题.如果直接通过filecxx的插件下载可以直接开始下载,但是如果通过add stream添加的一样的m3u8,总是会弹出"密钥请求失败",我在自己加的stream里面把user agent还有header都改的和通过插件生成的下载一样了,还是不行.

**Comment by Evilfoxster1981** [comment]
有个同样的问题.如果直接通过filecxx的插件下载可以直接开始下载,但是如果通过add stream添加的一样的m3u8,总是会弹出"密钥请求失败",我在自己加的stream里面把user agent还有header都改的和通过插件生成的下载一样了,还是不行.

**Comment by filecxx** [comment]
> 有个同样的问题.如果直接通过filecxx的插件下载可以直接开始下载,但是如果通过add stream添加的一样的m3u8,总是会弹出"密钥请求失败",我在自己加的stream里面把user agent还有header都改的和通过插件生成的下载一样了,还是不行.

m3u8文件包含的密钥地址可能是一个相对地址，所以无法直接请求, filecxx插件给本地程序发送任务时候会把插件内 “潜在URL” 也发送给程序，本地程序有地址修正再请求的策略，所以会根据 “潜在URL” 作为基础地址 和这个密钥地址组合成新URL地址，所以下载密钥可能会成功。

也有可能是filecxx插件已经获取到了密钥，直接发送给了本地程序。

**Comment by Evilfoxster1981** [comment]
> > 有个同样的问题.如果直接通过filecxx的插件下载可以直接开始下载,但是如果通过add stream添加的一样的m3u8,总是会弹出"密钥请求失败",我在自己加的stream里面把user agent还有header都改的和通过插件生成的下载一样了,还是不行.
> 
> m3u8文件包含的密钥地址可能是一个相对地址，所以无法直接请求, filecxx插件给本地程序发送任务时候会把插件内 “潜在URL” 也发送给程序，本地程序有地址修正再请求的策略，所以会根据 “潜在URL” 作为基础地址 和这个密钥地址组合成新URL地址，所以下载密钥可能会成功。
> 
> 也有可能是filecxx插件已经获取到了密钥，直接发送给了本地程序。

那就只有等3.0发布了.2.82插件会让下载的东西变位置.

**Comment by Evilfoxster1981** [comment]
> > 有个同样的问题.如果直接通过filecxx的插件下载可以直接开始下载,但是如果通过add stream添加的一样的m3u8,总是会弹出"密钥请求失败",我在自己加的stream里面把user agent还有header都改的和通过插件生成的下载一样了,还是不行.
> 
> m3u8文件包含的密钥地址可能是一个相对地址，所以无法直接请求, filecxx插件给本地程序发送任务时候会把插件内 “潜在URL” 也发送给程序，本地程序有地址修正再请求的策略，所以会根据 “潜在URL” 作为基础地址 和这个密钥地址组合成新URL地址，所以下载密钥可能会成功。
> 
> 也有可能是filecxx插件已经获取到了密钥，直接发送给了本地程序。

那就只有等3.x更新了.现在的插件会让其他下载位置变动.
