### ISSUE TITLE
Issue when using a private browser to download files from Google Drive

### ISSUE THREAD

**Issue by BoscoFZ** [filecxx/FileCentipede#495]
**Please provide as much information as possible.**

version(>=2.0) : 2.81

**With Chrome using private browser :** 
Google Drive file download mistake changes to file identifier.html
You can check the video link bellow
https://streamable.com/iay1fa

**With Firefox using private browser :**
Displaying Redirect Error
![Capture10000](https://user-images.githubusercontent.com/70411098/215274535-f9e50778-9eea-4bc9-bc88-245b56aacba9.PNG)

**Comment by filecxx** [comment]
I will try to fix this, but I can do nothing if it's Cloudflare or google reCaptcha.

**Comment by filecxx** [comment]
It has been fixed in version 2.82, but only for chrome.

Firefox is still unable to query cookies from the private window (I don't know how).

**Comment by filecxx** [comment]
Please update the FileCXX web browser extension to 1.81
