### ISSUE TITLE
在已经明确手动设定下载目录的情况下，文件还是会自动分类

### ISSUE THREAD

**Issue by Passerby1011** [filecxx/FileCentipede#496]
**Please provide as much information as possible.**

version(>=2.0) :2.8.1

文件浏览器webdav，下载，在已经明确手动的设定下载文件夹后，还是被自动分类走了

**Comment by filecxx** [comment]
目前分类的优先级太高，确实会造成这个问题，3.0版本时候会修改。

**Comment by filecxx** [comment]
这个问题在2.82版本中被修复了。
