### ISSUE TITLE
希望可以增加激活码转移的功能

### ISSUE THREAD

**Issue by fdasfas** [filecxx/FileCentipede#501]
我在仪表盘购买了一个终身激活码，可以现在我更换了电脑，UID发生了变化，希望可以增加转移激活的功能

**Comment by filecxx** [comment]
充值的 28 USD 有赠送的2800点卷，可以兑换成 56 USD ，这样可以额外再领2个终身激活码，另外有个重置按钮，每间隔1年可以将已充值的金额还原为余额。如果是充值的 1USD 然后再 27USD 这样导致没有得到赠送可以将仪表盘账号名称提供给我，我手动帮你增加。

**Comment by fdasfas** [comment]
好的，谢谢，我去试试
