### ISSUE TITLE
一个永久的激活码是可以激活多个设备的吗？

### ISSUE THREAD

**Issue by IcarusAegis** [filecxx/FileCentipede#504]
想知道28刀赞助的那个激活码是不是只支持永久激活一个设备，谢谢。

**Comment by wanaoggb** [comment]
一个激活码只永久激活一个设备， 重装系统后仍可以激活同一设备，我记得好像是这样的

**Comment by filecxx** [comment]
UID是硬件ID，一个激活码对应的UID只能激活一个设备，但考虑了一个用户有多个设备的情况所以一次性充值28USD会额外赠送56USD，可以兑换3个永久激活码，另外每年可以通过重置按钮重置余额，这用于解决上班族每年换工作导致UID变化的问题， 换算为： 第一年 兑换3个，之后每年可以再次兑换一个。

**Comment by IcarusAegis** [comment]
> UID是硬件ID，一个激活码对应的UID只能激活一个设备，但考虑了一个用户有多个设备的情况所以一次性充值28USD会额外赠送56USD，可以兑换3个永久激活码，另外每年可以通过重置按钮重置余额，这用于解决上班族每年换工作导致UID变化的问题， 换算为： 第一年 兑换3个，之后每年可以再次兑换一个。

非常感谢！
