### ISSUE TITLE
BT客户端伪装不完全

### ISSUE THREAD

**Issue by fengguowudi** [filecxx/FileCentipede#516]
**Please provide as much information as possible.**

version(>=2.0) :2.82

screenshot:
![image](https://user-images.githubusercontent.com/55879152/217455525-104bbef7-6ac2-4d9d-af5a-bcbf052694b4.png)

BT客户端伪装并不完全，仅伪装了User-agent，却没有伪装Peerid的选项

导致一些 Pt站点无法进行使用

**Comment by filecxx** [comment]
3.0版本时候会把自定义Peerid加上。

**Comment by filecxx** [comment]
FileCentipede和Aria2没有任何关系，Aria2的代码质量很低而且没有低级API，只能当工具使用，不能作为库。

**Comment by ted423** [comment]
能否考虑不伪装客户端呢

**Comment by ted423** [comment]
> FileCentipede和Aria2没有任何关系，Aria2的代码质量很低而且没有低级API，只能当工具使用，不能作为库。

如果我没弄错的话，他是想在pt站里使用

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/227898847-a216f318-eedd-40a3-a1cb-5724abc408a7.png)

客户端指纹知道的有其他吗？我把这些都加入到预设置列表里。

**Comment by filecxx** [comment]
-DE13F0- 这些是前缀

TR2940-tyyz4k6tzpz2
UT2210-%d6bE%c7L7%d8%aeD1%1e%c3

这样是完整的

**Comment by filecxx** [comment]
完全足够了，还会增加一个自动生成的工具用于避免多个用户peerid重复的情况。
