### ISSUE TITLE
必须设置开机启动和托盘图标保持后台运行吗？

### ISSUE THREAD

**Issue by xaoyao** [filecxx/FileCentipede#52]
我没有设置开机启动和托盘图标，点击下载程序看不到主界面，能看到进程，手动启动也不可以，必须结束进程手动打开程序才行
![gif](https://user-images.githubusercontent.com/12218604/159385569-4bc64825-c143-4f47-a5e2-d6cf63d830ed.gif)

**Comment by guojq82** [comment]
正准备反馈这个 好像从1.3开始的  但是1.4比较严重
顺便提个建议  在安装扩展的情况下  可不可以考虑 拦截后在主程序未开启的情况下  直接拉起主程序  或者做个提示顺便提个建议  在安装扩展的情况下  可不可以考虑 拦截后在主程序未开启的情况下  直接拉起主程序  或者做个提示框 选择也行框 选择也行

**Comment by filecxx** [comment]
这个问题似乎比较严重，我正准备发布1.5版本，感谢提交，我修复之后再发布。

**Comment by filecxx** [comment]
> 正准备反馈这个 好像从1.3开始的 但是1.4比较严重 顺便提个建议 在安装扩展的情况下 可不可以考虑 拦截后在主程序未开启的情况下 直接拉起主程序 或者做个提示顺便提个建议 在安装扩展的情况下 可不可以考虑 拦截后在主程序未开启的情况下 直接拉起主程序 或者做个提示框 选择也行框 选择也行

filec.exe 必须运行才能启动fileu, 否则浏览器扩展找不到文件路径，或者系统服务勾选项已经勾选.

**Comment by filecxx** [comment]
这个问题在1.5版本中已经解决，请下载尝试。
