### ISSUE TITLE
无法添加任务，立即下载和稍后下载，没有任何反应，列表中没有任务

### ISSUE THREAD

**Issue by 51522tt** [filecxx/FileCentipede#520]
本版：2.82
激活：已激活7天
![image](https://user-images.githubusercontent.com/39977972/219527908-ae965777-8cbc-461a-b1dc-078441775027.png)
![image](https://user-images.githubusercontent.com/39977972/219527938-958df844-28bd-4192-8442-9e1e72369187.png)

**Comment by 51522tt** [comment]
正在尝试下载免费版试试

**Comment by filecxx** [comment]
ed2k连接 3.0版本才会开始支持。当前版本不可用。
