### ISSUE TITLE
生成恶意文件

### ISSUE THREAD

**Issue by ggkj123** [filecxx/FileCentipede#526]
今天发现了有个文件捆绑到你的恶意文件
![2023-02-25-214023417 png](https://user-images.githubusercontent.com/121037789/221363205-138f41bc-3017-4cd5-a22c-d36ac8353ea2.jpg)
在迅雷下载文件夹内恶意生成了恶意文件当电脑重启后将会自动生成在第二个文件夹内发现无法删除并提示被文件蜈蚣正在使用此文件导致无法删除在尝试关闭后依然提示正在使用中
![2023-02-25-204021594 png](https://user-images.githubusercontent.com/121037789/221363602-7b5b9082-88e1-41dc-b3b8-d12d3ad71fe3.jpg)
......请作者大大进行相关的修复

**Comment by filecxx** [comment]
这是其他程序或者木马使用的线程注入的方式将自身寄生到其他进程里，即便文件被删除了也能无限复活，你能看到 explorer.exe 进程也被注入了，这是你电脑中病毒，和文件蜈蚣没有任何关系，你需要把这个问题提交到杀毒软件网站上去。

另外请更改标题，以免引起其他人的误导。
