### ISSUE TITLE
为什么这个网站视频没法获取下载呢？

### ISSUE THREAD

**Issue by bamboo3650** [filecxx/FileCentipede#528]
为什么这个网站视频没法获取下载呢？http://www.tv7box.com/vod-play-id-21095-sid-2-pid-1.html

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/221401994-d3cdb757-d698-437f-9246-b3b374911916.png)

![image](https://user-images.githubusercontent.com/100348948/221401969-5afa399e-b602-4b94-8e18-749a66688809.png)

我能下载

**Comment by bamboo3650** [comment]
可是我播放的时候没有右上角的这个下载的按钮出现！

**Comment by filecxx** [comment]
浏览器扩展最新版本号是 1.81

**Comment by filecxx** [comment]
另外可以从右上角小图标里下载
![image](https://user-images.githubusercontent.com/100348948/221464627-be795bca-8f95-4cb9-b06c-54f38265e58f.png)

**Comment by bamboo3650** [comment]
浏览器扩展最新版本号是 1.81.1版的
