### ISSUE TITLE
下载文件不完整

### ISSUE THREAD

**Issue by sherlockking** [filecxx/FileCentipede#53]
在下载不稳定，最后到99%的时候会很慢，而且大概率下载的文件会不完整

**Comment by stdjs** [comment]
1.4版本中应该修复了文件不完整(1字节丢失) 问题。

**Comment by filecxx** [comment]
是的，1.4版本已经修复这个问题了， 99%时候不会继续增加连接数，只有一个连接，部分任务会相对比较慢，可以暂停恢复。
