### ISSUE TITLE
filec未启动

### ISSUE THREAD

**Issue by zmyjoe94** [filecxx/FileCentipede#530]
![b1939f6c6a84fbf982ac4311681466f](https://user-images.githubusercontent.com/97775623/221557532-9738f6ac-24fc-4329-aadd-d7bfa806eb2f.png)

每次开机后想下载，需要进入软件启动一下才行，这是为什么？

**Comment by filecxx** [comment]
打开 设置 -> 通用 把系统服务勾选上。

**Comment by zmyjoe94** [comment]
> 打开 设置 -> 通用 把系统服务勾选上。

嗯嗯这样就好了，谢谢
