### ISSUE TITLE
西瓜视频里的某些视频无法被探测到，但是老牌的video downloadhelper可以

### ISSUE THREAD

**Issue by flwwater** [filecxx/FileCentipede#537]
**Please provide as much information as possible.**

version(>=2.0) :
火狐插件1.81版

screenshot:
<img width="1561" alt="filecxx_firefox_xigua" src="https://user-images.githubusercontent.com/67504938/222366333-1fffa720-c65a-4807-bf70-af800214d6e0.png">
<img width="378" alt="filecxx_videodownloadhelper" src="https://user-images.githubusercontent.com/67504938/222366837-702c7816-ad18-43bb-a190-94ba6131e47b.png">

URL:
https://www.ixigua.com/7111636385802977829?logTag=7f0cbf121e7f119dd142
.......

**Comment by filecxx** [comment]
禁用video downloadhelper试试，可能是冲突。
![image](https://user-images.githubusercontent.com/100348948/222367607-92661421-55fe-4681-a8e7-d65b30bea369.png)

**Comment by filecxx** [comment]
chrome可以，firefox确实不行，应该是一个BUG。

**Comment by filecxx** [comment]
安装2.0版firefox扩展
https://addons.mozilla.org/firefox/addon/filecxx/

![image](https://user-images.githubusercontent.com/100348948/225253943-0092bed6-dd3f-42b7-9137-d6c8f9ed75e0.png)
