### ISSUE TITLE
磁链，经常出现“正在下载元数据”

### ISSUE THREAD

**Issue by phoetry** [filecxx/FileCentipede#538]
于是出门半小时后回来，还是正在下载元数据。

**Comment by xiaohei6856** [comment]
我也遇到了这个问题实例（magnet:?xt=urn:btih:S73TMBJC3JAMJU7OWHKSAKILG53BQ6MR）

**Comment by filecxx** [comment]
这个文件在 DHT网络上 找不到正在做种的用户，即便能完成元数据下载，资源下载也不会有速度。

**Comment by phoetry** [comment]
原来如此，感谢。
