### ISSUE TITLE
可否增加批量下载功能

### ISSUE THREAD

**Issue by asd0109** [filecxx/FileCentipede#54]
![图像 002](https://user-images.githubusercontent.com/37428027/159396269-0cab6f3f-e978-4721-93b8-31489b5db9e7.png)

例如这样的下载会比较麻烦，可否添加一个批量下载功能。

**Comment by filecxx** [comment]
当然，预计1.6-1.8版本之间添加这个功能，你有好的思路在这期间可以提供下。

**Comment by asd0109** [comment]
> 当然，预计1.6-1.8版本之间添加这个功能，你有好的思路在这期间可以提供下。

其实我想的是视频网站下载视频的时候能够把那种音视频分离的自动合并成一个文件，因为用户下载下来合并的话需要装一堆东西很麻烦。

**Comment by asd0109** [comment]
刚想到一个，悬浮窗。

如果有了悬浮窗，在下载开始的时候就可以看到下载的网速而不用打开整个软件的大窗口查看了。

**Comment by asd0109** [comment]
以 INI 之类的方式存储软件配置。
现在软件处于一个更新频繁的阶段，基本每个版本我都会第一时间下载使用，配置会比较麻烦。

比如默认下载位置，剪贴板里面的后缀名，代理。。。    每次更新我都要手动调整一次。

如果可以有一个配置文件就好了，这样每次把配置文件复制到新目录里就可以了。

**Comment by alex3236** [comment]
> 当然，预计1.6-1.8版本之间添加这个功能，你有好的思路在这期间可以提供下。

浏览器扩展提供右键菜单，下载本页所有链接。

这个各大下载器的思路似乎就是捕获所有 <a> 标签，把链接提取出来，应该不难

**Comment by filecxx** [comment]
更新导致配置文件丢失在1.6版本中已经修复，批量下载功能已经添加进了1.6版本，扩展版本1.3

**Comment by asd0109** [comment]
> 更新导致配置文件丢失在1.6版本中已经修复，批量下载功能已经添加进了1.6版本（浏览器右键），扩展版本1.3 （流量悬浮窗暂时没有好的设计方案）


我先试试批量下载

**Comment by asd0109** [comment]
![image](https://user-images.githubusercontent.com/37428027/160030717-ca3e12da-aff5-485f-bda0-9b1b1c7e0bd6.png)


这个过滤功能真的太棒了！建议增加全选和反向选择，这样就可以很方便的挑选某个文件。

**Comment by filecxx** [comment]
全选和反向选择，已经增加在1.7版本中的右键菜单。

**Comment by asd0109** [comment]
> 全选和反向选择，已经增加在1.7版本中的右键菜单。

收到    我会继续关注
