### ISSUE TITLE
代理功能有较多bug

### ISSUE THREAD

**Issue by yeluonight** [filecxx/FileCentipede#541]
**Please provide as much information as possible：一是设置里代理选项里那个“总是”无法修改，导致选择代理后所有下载都经过代理；二是莫名出现代理地址端口正确却无法使用代理的情况，但是测试其他软件同样的端口地址却是正常使用，而且怎么调整代理软件都无效，但是即时不调整过一会又能正常使用；三是在未选择代理的情况下添加的下载链接，会出现之后选择了代理，但是不走代理的情况，此时不管是暂停-开始还是重开软件都不行，必须将此链接添加新下载才可以

version(>=2.0) :2.82

screenshot:
![image](https://user-images.githubusercontent.com/31738833/222939847-8e3d8505-5c0c-415c-9348-67ae228ddf9e.png)
![image](https://user-images.githubusercontent.com/31738833/222939849-b4038543-3d3d-439e-ba28-32c011c445e4.png)

**Comment by filecxx** [comment]
每个下载任务都有单独的代理设置选项，设置 - 网络中的代理是任务默认值，而不是始终使用那个代理，如果你需要更改，需要编辑任务设置。你应该是根据其他下载软件的使用习惯来作出的结论。
