### ISSUE TITLE
关于永久会员的问题

### ISSUE THREAD

**Issue by Waradise** [filecxx/FileCentipede#542]
永久会员需要绑定设备ID，请问重装系统或者换了新电脑之后设备ID变更了还能重新绑定新ID吗？另外永久会员支持几台设备同时登录？比如，我在NAS上安装一个用于下载，在其他电脑上安装一个作为远程管理，购买一个永久会员能实现吗？

**Comment by filecxx** [comment]
可以参考这个

https://github.com/filecxx/FileCentipede/issues/504

**Comment by Waradise** [comment]
> 可以参考这个
> 
> #504 #465 #503

建议以账号形式鉴权,然后根据不同会员等级限制同时在线设备,后台可以任意解绑设备,这样比较方便~
