### ISSUE TITLE
浏览器插件的探测列表能增加一个清除按钮吗？

### ISSUE THREAD

**Issue by flwwater** [filecxx/FileCentipede#547]
<img width="498" alt="filecxx_list" src="https://user-images.githubusercontent.com/67504938/225884471-61d92762-78c3-407e-ae4e-d6eb901f18df.png">

有时候资源太多，最新的资源总是在添加到列表的最下方，动动鼠标有点麻烦啊~~~

另外：万众期待的3.0快发布了吧？

**Comment by filecxx** [comment]
清楚按钮下个版本添加。

3.0版本可能还需要一段时间，在这之前会先发布一个新的编程语言项目，目前编译器还没做完。

**Comment by filecxx** [comment]
https://addons.mozilla.org/firefox/addon/filecxx/

更新到了2.1 ，增加了过滤功能

![image](https://user-images.githubusercontent.com/100348948/226089715-d22b5f9e-8a39-49c0-997b-6076ebaa8eb5.png)
