### ISSUE TITLE
firefox extension doesn't work effectively like chrome ....

### ISSUE THREAD

**Issue by Nabil-Nasr** [filecxx/FileCentipede#552]
in firefox the extension doesn't grab the videos effectively (take youtube as an example it can't grab videos or audios) but in chrome it can

... i tested it in two firefox versions (the standard version and developer edition version) ==> all in linux kubuntu (ubuntu with kde desktop environment)

**Comment by filecxx** [comment]
Try the firefox extension version 2.1:
https://addons.mozilla.org/firefox/addon/filecxx/

**Comment by Nabil-Nasr** [comment]
i tried 2.1 but it has conflicts with the default downloader
then i installed 2.0 and now it works fine like chrome and edge
but i want you to add a method to merge on download like youtube videos(choose the preffered video quality and audio quality then merge automatically with download)
because services like youtube has video and audio separated for all qualities except 360p and 720p in the last years

but the videos that was uploaded on youtube  years  ago are not separated.

**Comment by filecxx** [comment]
It's impossible. Compared to 2.0, version 2.1 only fixed an issue.

**Comment by Nabil-Nasr** [comment]
no problem 
but what about the auto merge feature in my comment ?

**Comment by filecxx** [comment]
auto merge will be implemented through the plugin.

**Comment by Nabil-Nasr** [comment]
thank you i'm waiting
