### ISSUE TITLE
用的edge拓展，iqiyi网页抓取好像不对劲啊

### ISSUE THREAD

**Issue by TinySome** [filecxx/FileCentipede#557]
用的是edge extension 更新到最新的版本了
抓iqiyi网页端1080P链接的时候
它会显示出来的TS或者是视频链
要么是出现的链接以.jpg结尾，下载404错误
https://i.imgtg.com/2023/03/24/93Jes.png
要么是出现抓到的就直接是网页地址.html
根本就不是视频
https://i.imgtg.com/2023/03/24/93poB.png

这是个什么原因？
我用我以前抓m3u8链的方式找iqiyi网页端1080P的m3u8，和以前没有区别啊
为什么蜈蚣没抓到啊

**Comment by filecxx** [comment]
我刚刚尝试了一下，新版本的扩展确实抓取到的有问题，我换回2.0版本之前的扩展抓到的视频正常，这个BUG这几天会修复。

**Comment by filecxx** [comment]
2.2已经修复了这个问题。
