### ISSUE TITLE
添加任务的时候选择下载名称，有全选或全不选的设置项。

### ISSUE THREAD

**Issue by ZhongMoDao** [filecxx/FileCentipede#558]
添加任务的时候默认的过滤其实大多数都失效，希望加上全选或全不选的设置项，不然只想下载一个需要一个一个点。

**Comment by filecxx** [comment]
Torrent任务确认面板中可以点击右键，会有全选

![image](https://user-images.githubusercontent.com/100348948/227716293-9849890c-5b23-4a97-90f0-caf4ae0755fc.png)
