### ISSUE TITLE
你好 激活码时间可否修改回00:00:00

### ISSUE THREAD

**Issue by hao1196561270** [filecxx/FileCentipede#559]
![image](https://user-images.githubusercontent.com/34802963/227788495-551afaa7-9008-4f7a-941e-c18261248dfe.png)
从26日开始就变成晚上20:00:00了

**Comment by filecxx** [comment]
下次改回 00:00:00

如果是用程序自动获取，根据 yy-MM-dd hh:mm::ss - yy-MM-dd hh:mm::ss 来格式化会准确一点。
