### ISSUE TITLE
已经购买了终身激活码，现在换电脑了，没法使用了该怎么处理啊

### ISSUE THREAD

**Issue by Aming999** [filecxx/FileCentipede#563]
**Please provide as much information as possible.**

version(>=2.0) :已经购买了终身激活码，现在换电脑了，该怎么处理啊，现在用原来的激活码显示无效，请作者帮忙答复一下，相信还有很多使用者会遇到这个问题，本身是为了支持作者和方便自己使用购买的，接近200块钱也不便宜，还往作者帮忙处理，谢谢，我的邮箱：491181779@qq.com，谢谢

screenshot:

URL:

.......

**Comment by filecxx** [comment]
将赠送的2800点卷兑换成56USD继续获取新激活码。
