### ISSUE TITLE
视频没声音，激活码不能购买

### ISSUE THREAD

**Issue by Jackeechen** [filecxx/FileCentipede#566]
有些视频下载下来没声音，比如说这个https://vimeo.com/810307772/49c8210c3a，然后就是激活码购买不了，输入uid以后提示出错

**Comment by filecxx** [comment]
这个地址上的视频和音频是分离的，需要把2个都下载下来之后使用工具 - 文件合并 来进行手动合并。

提示 "UID错误" 是因为 "UID错误",  打开软件 -> 菜单 -> 帮助 -> 激活码 

复制编辑框中的软件UID

![image](https://user-images.githubusercontent.com/100348948/230423814-9aa5d332-8b34-4612-825f-976546eafe22.png)

**Comment by Jackeechen** [comment]
没有看到音频相关下载按钮么，然后还是购买激活码的问题，操作顺序没问题但是问题依然存在
![1680828422935](https://user-images.githubusercontent.com/11692272/230518782-c9a5d738-af23-490f-8799-69f78517eaad.png)
![1680828494235](https://user-images.githubusercontent.com/11692272/230518795-95a5e9aa-6802-4565-bf71-5f0da5bfa5a4.png)
![1680828543731](https://user-images.githubusercontent.com/11692272/230518807-ad372f35-69b4-4f00-ae89-6beda021404f.png)

**Comment by filecxx** [comment]
视频音频扩展名是一样，检测不到哪个是音频，通常选择最小那个文件。

余额不足会弹出失败。

**Comment by Jackeechen** [comment]
是要先充值啊，我去试试， 多谢
