### ISSUE TITLE
配置长久的代理服务器以及在主界面中增加日志标签

### ISSUE THREAD

**Issue by asd0109** [filecxx/FileCentipede#57]
![图像 002](https://user-images.githubusercontent.com/37428027/159477901-de968125-95b5-484c-9514-cc540d9f542a.png)

在某些局域网中是通过代理上网的，这样的话每次下载都要手动选择一次代理服务器，看看能不能放置一个永久的代理开关。

![图像 001](https://user-images.githubusercontent.com/37428027/159478175-fe450b5c-544b-40e9-ae46-a270e9c00ed0.png)

建议增加一个标签，里面记录每个任务的连接日志，方便用户在遇到问题的时候提供参考。
这些日志在用户从蜈蚣中删除任务后一起清空。

**Comment by filecxx** [comment]
设置 - 网络里选中那个代理，之后新任务面板里就会默认选中了。

**Comment by filecxx** [comment]
torrent日志如果记录所有，文件可能会非常大，热门的种子可能日志会达到几百MB
