### ISSUE TITLE
浏览器插件会接管所有的下载请求(比如点击图片右键另存为),是否可以提供一个选项以使用浏览器自带的下载功能?

### ISSUE THREAD

**Issue by pedoc** [filecxx/FileCentipede#575]
如题,保存图片的时候右键另存为的话一般不需要调用下载工具这么重量级的功能,请问现在具备此功能吗?谢谢

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/232637900-ea16a040-3dbe-429f-b894-0d161924dfdd.png)
![image](https://user-images.githubusercontent.com/100348948/232637922-cebe30ec-c37f-4b87-9018-13c9e6014474.png)
![image](https://user-images.githubusercontent.com/100348948/232637937-f57bcbe4-f59f-42ca-91c1-d31c7a84e489.png)
![image](https://user-images.githubusercontent.com/100348948/232637956-dfb822cf-dca4-4fb8-9292-09f5353354f4.png)

**Comment by pedoc** [comment]
好的,非常感谢
