### ISSUE TITLE
搜狗输入法会下载失败

### ISSUE THREAD

**Issue by pedoc** [filecxx/FileCentipede#576]
**Please provide as much information as possible.**
如果使用浏览器自带下载或者使用wget下载都是可以的.

version(>=2.0) :2.82

screenshot:
![image](https://user-images.githubusercontent.com/6604230/233252539-b1b3bd5a-4bb1-4b7f-b4a5-96c538ae85ad.png)

URL:
https://ime-sec.gtimg.com/202304201136/368b1811ca15d0211c84fe2a9b0c2a6a/pc/build/_sogou_pinyin_[release_yyb_13_4]_13.4.0.7182_1111.exe
.......

**Comment by filecxx** [comment]
我使用浏览器和wget这个地址都返回403, 应该是需要cookie.

**Comment by filecxx** [comment]
提供一下 Page URL
![image](https://user-images.githubusercontent.com/100348948/233288600-b8d99a75-630d-45af-8aae-8e426a890db7.png)

**Comment by pedoc** [comment]
https://shurufa.sogou.com/
这个应该是公开的,服务器没有鉴权.

![image](https://user-images.githubusercontent.com/6604230/233304781-5a3ae470-399d-4c32-b4ba-6b31047cfb60.png)

**Comment by filecxx** [comment]
我那天测试时候确实下载得到403错误，就在刚才我准备修复这个问题时候这个地址却可以正常下载了，你现在测试 正常吗？

**Comment by pedoc** [comment]
> 我那天测试时候确实下载得到403错误，就在刚才我准备修复这个问题时候这个地址却可以正常下载了，你现在测试 正常吗？


我看了一下官网的最新下载地址是
```
https://ime-sec.gtimg.com/202304260832/69e152af068631430672672c76ca27c3/pc/_sogou_pinyin_guanwang_134c.exe
```
这个地址现在是可以正常下载的,但是issue里最早给的那个地址还是403.

我觉得可以不管这个了,可能是服务器侧有什么限制,可以关闭此issue.
