### ISSUE TITLE
filec占用太多端口

### ISSUE THREAD

**Issue by pedoc** [filecxx/FileCentipede#580]
**Please provide as much information as possible.**

启动后,不开启任何下载任务,可以看到filec占用了非常多的端口号

version(>=2.0) :2.82

screenshot:
![image](https://user-images.githubusercontent.com/6604230/235054955-357d595e-4b5f-4933-87db-7c0ef45877c6.png)

![image](https://user-images.githubusercontent.com/6604230/235054730-10960e31-2de7-4289-a13d-23bdda8c83a6.png)

URL:

.......

**Comment by filecxx** [comment]
所有的本机IP地址和包括虚拟网卡都会绑定端口，DHT，LSP等各个协议也都会占用端口，这和是否下载无关，这是监听端口，并非和远程某个主机建立连接。

你可以参考一下其他客户端例如 qBittorrent, deluge 等。
