### ISSUE TITLE
添加种子链接后一直卡在 “下载元数据”

### ISSUE THREAD

**Issue by xyzWesker** [filecxx/FileCentipede#581]
我不知道这是不是作为免费版和高级版的区分，但我打开好几个种子后一直都是“下载元数据”然后就没有然后了，也没法下载

**Comment by xyzWesker** [comment]
用迅雷的话是秒解析的

**Comment by filecxx** [comment]
这个文件在 DHT网络上 找不到正在做种的用户，即便能完成元数据下载，资源下载也不会有速度。

迅雷会从其他客户端吸血，完成之后只在迅雷客户端之间上传数据，如果下载磁力链接尽量不要选择中国大陆的资源，因为这块的生态几乎已经被迅雷完全破坏，大部分的新种子都会在1个月内死亡。

3.0版本之后会开始解决这个问题。

**Comment by xyzWesker** [comment]
好吧，吸血雷真恶心，支持你！
