### ISSUE TITLE
扩展里设置了排除类型还是会调用filecxx下载

### ISSUE THREAD

**Issue by YandLiu** [filecxx/FileCentipede#583]
2.8.2
测试网址：https://mp.weixin.qq.com/s/h9KRMj4u9JB82JJYYYwAVg
里面的图片

**Comment by filecxx** [comment]
把设置截图提供下

**Comment by YandLiu** [comment]
![image](https://user-images.githubusercontent.com/26127104/236435865-ee011b59-8c7e-44e6-acd4-d9eb639def76.png)

**Comment by filecxx** [comment]
把MIME也添加了，有一些图片没有扩展名，但是能获取到MIME

**Comment by YandLiu** [comment]
这个菜单是被禁用的，没法选择
![image](https://user-images.githubusercontent.com/26127104/236452802-6d7d4cf9-94b0-4356-870c-e47f394e4514.png)

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/236454375-01b2991e-6415-4b60-95cd-2e0147209a6a.png)

这是UI上的BUG，新版的chrome上由于宽度问题导致被隐藏了，只能在F12选中，然后把 StdUI_SwitchBox 中的宽度属性删掉才能显示。

**Comment by YandLiu** [comment]
已更新，还未解决，还是不能选

**Comment by YandLiu** [comment]
发现就算通过删掉那一栏的disabled属性启用输入，添加上pdf的那一项后（即通过扩展名和MIME两项来排除），依旧会调用软件去下载pdf，例如：
http://www.nhsa.gov.cn/module/download/downfile.jsp?classid=0&filename=c04dabc3f9ef4702a43092bdebf6f1e7.pdf

**Comment by filecxx** [comment]
2.92版本浏览器插件修复了
