### ISSUE TITLE
 文件蜈蚣建议改名成文件大鹅

### ISSUE THREAD

**Issue by bawyvh** [filecxx/FileCentipede#591]
文件蜈蚣的图标是一只大鹅，建议软件官方名改名成文件大鹅或其他，毕竟文件蜈蚣真的不好听啊，而且画面蜈蚣也感觉不适，差点因为软件名字带有蜈蚣放弃了那么好的软件[捂脸]

**Comment by bawyvh** [comment]
还好软件里支持改软件名，这个要大大赞一个。改官方名仅为个人建议，仅供参考

**Comment by huanghaobaobao** [comment]
名字不是很重要，3.0尽快上线才是最重要的😁

**Comment by bawyvh** [comment]
> 名字不是很重要，3.0尽快上线才是最重要的😁

好听的名字很重要，好听的名字才能更好的传播。不过软件安装时支持改名，这点很棒，所以官方改不改对于我来影响不大，我可以自己改

**Comment by bawyvh** [comment]
> 名字不是很重要，3.0尽快上线才是最重要的😁

好听的名字很重要，好听的名字才能更好的传播。不过软件安装时支持改名，这点很棒，所以官方改不改对于我来影响不大，我可以自己改

**Comment by filecxx** [comment]
文件大鹅更难听 😁

**Comment by bawyvh** [comment]
> 文件大鹅更难听 😁

建议而已，改成其他的也好呀，不过现在我更关心3.0啥时候上线😁

**Comment by bawyvh** [comment]
> 文件大鹅更难听 😁

建议而已，改成其他的也好呀，不过现在我更关心3.0啥时候上线😁
