### ISSUE TITLE
激活码的一些疑问

### ISSUE THREAD

**Issue by bawyvh** [filecxx/FileCentipede#593]
我购买了终身激活码，激活码是UID与绑定的，每个电脑的UID是不一样的，所以我的激活码只能在一台电脑上使用，不能在多台电脑上使用吗？还有如果我重装系统，或者升级的电脑硬件，UID改变我的终身激活码也报废了吗，需要重新购买？终身激活码不能跟着帐号走吗

**Comment by filecxx** [comment]
可以参考：
https://github.com/filecxx/FileCentipede/issues/563
https://github.com/filecxx/FileCentipede/issues/504
https://github.com/filecxx/FileCentipede/issues/465

**Comment by bawyvh** [comment]
> 可以参考： #563 #504 #465

明白了
