### ISSUE TITLE
I can't stay on the 1.X free version

### ISSUE THREAD

**Issue by Majoramari** [filecxx/FileCentipede#594]
I can't stay on the 1.X free version 

I tired to turn off auto update but every it turn itself if I restarted the app

version: 1.9

screenshot:
![MajorAmari_2023-05-21_zLgq](https://github.com/filecxx/FileCentipede/assets/33487552/faa03c47-e53f-4ee1-9033-486915a855fa)

URL:
https://youtu.be/l7QByQMMMuU

**Comment by filecxx** [comment]
Redownload the 1.9 version from filecxx.com

Or remove the address. 
![image](https://github.com/filecxx/FileCentipede/assets/100348948/2c647677-b083-4b19-8684-c682a1b4e361)

**Comment by Majoramari** [comment]
> Redownload the 1.9 version from filecxx.com
> 
> Or remove the address. ![image](https://user-images.githubusercontent.com/100348948/239714297-2c647677-b083-4b19-8684-c682a1b4e361.png)

I've downloaded it 4 times every time it update itself to 2.82 now I did already remove the address and I'm cant confirm if this fixed it
