### ISSUE TITLE
win10无法启动，没有任何提示

### ISSUE THREAD

**Issue by Leroy-X** [filecxx/FileCentipede#6]
双击界面版多次无法启动，任务管理器无相关进程，杀软也退了，管理员模式也尝试了，win7兼容模式也试了，，其中有一次提示无法写入内存。

非常感谢！

(假装开发看得懂中文)

**Comment by qq5921** [comment]
> 
我的也一样 打不开

**Comment by xiaokaizhenshaui** [comment]
> 双击界面版多次无法启动，任务管理器无相关进程，杀软也退了，管理员模式也尝试了，win7兼容模式也试了，，其中有一次提示无法写入内存。
> 
> 非常感谢！
> 
> (假装开发看得懂中文)

目录中不要含有中文，例如：C:\User\张三\fileu  不可以

**Comment by Leroy-X** [comment]
感谢开发，对的，是英文路径，刚在lib目录下找到了同名fileu.exe文件，可以打开，但安装失败。
![image](https://user-images.githubusercontent.com/13515498/157796318-6f9cb24e-338a-485c-bd22-9857d53993a3.png)

哪里有报错日志

**Comment by filecxx** [comment]
> 感谢开发，对的，是英文路径，刚在lib目录下找到了同名fileu.exe文件，可以打开，但安装失败。 ![image](https://user-images.githubusercontent.com/13515498/157796318-6f9cb24e-338a-485c-bd22-9857d53993a3.png)
> 
> 哪里有报错日志

你的安装路径包含空格，导致出错，在Windows上确实会出现这个问题，我马上修复下

**Comment by filecxx** [comment]
记得删除之前的目录，重新解压安装，因为之前路径问题导致了已经写入了错误的文件。

**Comment by Leroy-X** [comment]
@filecxx 路径没空格可以运行了，希望可以修复，因为Program Files自带空格。。。
希望开发添加一个类似IDM里面的连接不成功自动走代理的功能，这样省去了来回在设置里切换，chrome扩展希望抓Youtube时可以显示其他分辨率，非常感谢！

**Comment by filecxx** [comment]
新上传的zip文件应该修复了这个问题

**Comment by filecxx** [comment]
> @filecxx 路径没空格可以运行了，希望可以修复，因为Program Files自带空格。。。 希望开发添加一个类似IDM里面的连接不成功自动走代理的功能，这样省去了来回在设置里切换，chrome扩展希望抓Youtube时可以显示其他分辨率，非常感谢！

我把这个提议放在待做事项里，目前主要是寻找和修复BUG，新功能开发将在这之后开始。

**Comment by Leroy-X** [comment]
非常感谢！
