### ISSUE TITLE
蜈蚣的浏览器插件和  singlefile 插件有冲突

### ISSUE THREAD

**Issue by asd0109** [filecxx/FileCentipede#60]
singlefile 是一个把网页存成一个  html 文件的浏览器插件，当安装了文件蜈蚣的插件后点击 singlefile 插件没有任何反应，将文件蜈蚣插件禁用后就好了。

**Comment by filecxx** [comment]
singlefile 调用了浏览器下载的API，这个和文件蜈蚣浏览器扩展冲突，只能把下载管理器切换成浏览器，没有别的解决办法。
