### ISSUE TITLE
140% download?!

### ISSUE THREAD

**Issue by Majoramari** [filecxx/FileCentipede#606]
**Please provide as much information as possible.**

version(>=1.9) :

screenshot:
![image](https://github.com/filecxx/FileCentipede/assets/33487552/0c2f1d4f-02a4-4e50-888d-bfa9fbf72351)

URL:

.......

**Comment by filecxx** [comment]
It's a bug 😯.
It has been fixed since FileCentipede 2.0.

**Comment by Majoramari** [comment]
I'll close it if it fixed
