### ISSUE TITLE
chrome插件开启状态看B站直播卡

### ISSUE THREAD

**Issue by chziyue** [filecxx/FileCentipede#617]
chrome已升级最新版,扩展插件版本2.2 ,看B站直播卡,关闭插件后正常,重装插件无效.

**Comment by filecxx** [comment]
提供一个测试地址，下次更新时候修复这个问题。

**Comment by chziyue** [comment]
[http://live.bilibili.com/27472826](https://live.bilibili.com/27472826?visit_id=321oc47agd60)

**Comment by filecxx** [comment]
临时解决方法是在文件蜈蚣扩展设置中关闭深度分析，这几天会更新浏览器扩展。

**Comment by filecxx** [comment]
已经更新到了2.3，修复了这个问题。

**Comment by chziyue** [comment]
ok 谢谢了
