### ISSUE TITLE
添加电驴链接后没有反应

### ISSUE THREAD

**Issue by asd0109** [filecxx/FileCentipede#62]
![图像 001](https://user-images.githubusercontent.com/37428027/159597454-ca3dfc11-f3de-44a1-b1df-f4080632a650.png)

![图像 002](https://user-images.githubusercontent.com/37428027/159597460-30bd9231-e00b-4765-91ea-df0047079287.png)

添加了电驴链接以后软件没有任务，没有任何反应。

具体连接是下面这个

ed2k://|file|zh-hans_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-74070.iso|630237184|EC51916C9D9B8B931195EE0D6EE9B40E|/

**Comment by paynewangw** [comment]
目前不支持啦

**Comment by asd0109** [comment]
哦  我还以为是有故障呢
