### ISSUE TITLE
safe?

### ISSUE THREAD

**Issue by MaeHeart** [filecxx/FileCentipede#623]
Hi sir. Just want to ask if this file is safe? Coz I scanned it on total virus and the file is reported as Backdoor:Win64/BruteRatel. Can you clear if this is just a false positive? Thanks https://www.virustotal.com/gui/file/f0bdef157f45ae1652ede116ebe98d889d163e5c094e88a076e917989742fe1e/relations

**Comment by filecxx** [comment]
I really don't want to answer this question. You already know how I will respond, but you have to point out that even only 2/62 of the rate means you won't believe the "Yes" answer from me, so the question is pointless.

But I believe most malware makers won't start building software from scratch, as it's a lot of work for a simple goal. Instead, they may use open-source software, such as aria2 + user interface, to make the process much easier and more efficient.
