### ISSUE TITLE
Open FileCentipede minimized in tray

### ISSUE THREAD

**Issue by Terkyz** [filecxx/FileCentipede#630]
Hello, I would like to know if it is possible to open FileCentipede minimized in the tray, at least in my case using Linux there is no real way within the interface to achieve this.

**Comment by filecxx** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/100348948/f3564292-a838-4262-b35b-8a1507e4a233)

![image](https://github.com/filecxx/FileCentipede/assets/100348948/0abb8043-be90-4b22-af0f-22601fb9c471)

**Comment by filecxx** [comment]
Settings -> General -> Tray icon
![image](https://github.com/filecxx/FileCentipede/assets/100348948/b1ac5fa0-66f7-4213-af42-bc10282992d2)

![image](https://github.com/filecxx/FileCentipede/assets/100348948/c50269a1-25c8-40d5-baac-d2f9f622eefe)

**Comment by Terkyz** [comment]
Thanks, it works but FileCentipede does not open minimized on a clean boot, but it opens as a maximized window.

**Comment by filecxx** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/100348948/6171ab2b-6709-41eb-9866-0bdc7c596a94)

Silent mode

**Comment by Terkyz** [comment]
Possibly I'm blind, [but where is that check button](https://i.imgur.com/4kTexWd.png)?

**Comment by Terkyz** [comment]
I already saw, I was using the "Free" version of FileCentipede and I went to the "Premium" version and I already have the button, although I would really like to know what the difference is.  

 Thank you very much for the support.

**Comment by filecxx** [comment]
Sure.
