### ISSUE TITLE
Program does not respect "Tray icon" & "Save window size" after startup.

### ISSUE THREAD

**Issue by LokeYourC3PH** [filecxx/FileCentipede#640]
**Please provide as much information as possible.**

The program, when set to autostart with Windows, ALWAYS comes up as a window, even when the options Tray Icon & Save window size / Save window position are enabled. According to logic, since the window was minimized to the tray area when shutting down the PC, it should also be minimized when starting. However, right after startup, I get my eyes burned out by the ultra-white File Centipede window flashing up on my screen.

Would you please make it so that there is an option which makes the program start minimized? Thank you.

version(>=2.0) : 2.82

.......

**Comment by filecxx** [comment]
Settings -> General -> Silent mode

![image](https://github.com/filecxx/FileCentipede/assets/100348948/68110225-78e1-43ea-afa8-a010601fbf55)

**Comment by LokeYourC3PH** [comment]
> Settings -> General -> Silent mode
> 
> ![image](https://user-images.githubusercontent.com/100348948/258631375-68110225-78e1-43ea-afa8-a010601fbf55.png)

Also enabled, same issue. Does not work, program opens at startup, and also makes sound when downloads are done, I had to mute in the Volume Mixer.

**Comment by filecxx** [comment]
```
"silent_mode":false,
"sound_effects":false
```
If these settings were previously saved, but they are not reflected in the "lib/fileu_win32.conf" file, it's possible that the file doesn't have writing permissions or it could be broken.

(You can delete sounds/*.wav files to mute the sound)

**Comment by LokeYourC3PH** [comment]
Silent mode is set to true, sound effects to false. While sound effects aren't the problem, the problem is that the program always shows on startup instead of starting in the tray. Can you add an option to start the program minimized in the tray?

**Comment by filecxx** [comment]
If you have both the "Tray icon" and "Silent mode" options selected in the settings, running fileu.exe will only show a tray icon and won't display the main window.

It's possible that it didn't work on your end because there are two startup items on your operating system. When you run "fileu.exe" for the second time, it will display the main window.

**Comment by LokeYourC3PH** [comment]
Some cleanup for you. Issue resolved, more or less. Impatiently waiting for v.3.0 😂
