### ISSUE TITLE
Some wrong about GitHub workflows. 

### ISSUE THREAD

**Issue by greenhandzdl** [filecxx/FileCentipede#643]
I am a new user to this project, and when I readed the zh-Readme, I has found some wrong and fixed it. 
![Screenshot_20230806-215306_GitHub.png](https://github.com/filecxx/FileCentipede/assets/61241103/a3fa94b8-0108-4753-b7e0-bc1924787ef4)

But when my pull request has been closed, my modify is recovered. I really want to solve the problem but I do not have any solutions.If you could solve the problem, I would be appreciated.

For Chinese Users:
作者好，我是新来这个项目的用户。当我准备阅读相关readme时，我发现了一些影响阅读的错误。我向这个项目提了我的修改分支，不久我的pr被合并了，但是github-bots又把我的修复改了回来。这是action的问题，但是我不知道怎么解决。如果作者有时间解决的话，我十分感谢。

**Comment by filecxx** [comment]
🤣🤣🤣
