### ISSUE TITLE
webui大概什么时候能上线啊。

### ISSUE THREAD

**Issue by hkthomas** [filecxx/FileCentipede#647]
linux没有图形界面的纯服务器没有web真的很难用。。。

**Comment by filecxx** [comment]
自从2.6版本开始，软件添加了远程功能，我认为WebUI没有必要再制作。 

![image](https://github.com/filecxx/FileCentipede/assets/100348948/73f282a1-b8d4-4841-b32e-2627a1f675f2)

不过默认Remote Access 为Disable
需要在命令行下执行 "filec remote_access on" 进行开启 

然后在客户端内添加远程主机地址
![image](https://github.com/filecxx/FileCentipede/assets/100348948/9a8026fb-db42-4257-882e-91b529f28835)

**Comment by hkthomas** [comment]
感谢，前面看到过这个功能，没找到文档，不知道咋用，感谢感谢！

**Comment by hkthomas** [comment]
我刚试下了，好像只能内网连接，我部署到服务器上 ./filec -y remote_access on，在外部连接不上呢。

-h看了下好像也没啥别的命令。: (

**Comment by filecxx** [comment]
防火墙或者selinux 阻止了外部连接.

**Comment by hkthomas** [comment]
防火墙端口开放了，selinux是关闭状态，试了两台vps都是。

**Comment by filecxx** [comment]
使用netstat 查看10111端口是否开放的, 远程使用nc或者telnet测试下是否能够连接上这个端口, 我已经在服务器上运行了1年, 远程使用正常.

**Comment by filecxx** [comment]
另外部分发行版使用的带有apparmor的内核, 默认也会屏蔽非白名单的端口, 而且很难禁用, 建议做下全面检查.

**Comment by filecxx** [comment]
执行
"filec service_port 10111"
"filec remote_access on"
"filec stop"
"filec start"

然后执行
"filec -p"

查看端口是否10111 或者指定的端口, 如果远程访问没有启用连接会被立即断开, 而非一直连接状态

另外 service_password <123>  set service password, default is empty ,密码不包含 <>

**Comment by filecxx** [comment]
远程功能不具备判断 "内网连接" 的功能, 如果内网可以连接, 那么一定是正常运行的.

**Comment by hkthomas** [comment]
我发现问题所在了。

./filec -y remote_access on，用这个的命令远程应该还是没有启动，所以连接不了。

./filec remote_access on
./filec start

这样就正常了。

我前面-h看到-y是启动，一直用了这条指令在里面。

问题解决，感谢。
