### ISSUE TITLE
下载不了，显示“超时”

### ISSUE THREAD

**Issue by Viennadd1** [filecxx/FileCentipede#650]
**Please provide as much information as possible.**
用chrome可以捕捉到，迅速建立下载，但是开始下载后，一直试0%，下载速度不动，之前还能下载，但是这次不知道为什么不能下载YouTube上面的了，而且我开了梯子，并且还重新下了最新版本，但这个状态这里显示RPC connection已经断开连接，不知道什么意思
version(>=2.0) :
2.82
screenshot:
![image](https://github.com/filecxx/FileCentipede/assets/143398964/554164a9-2d06-4026-8021-92268ca01037)
![image](https://github.com/filecxx/FileCentipede/assets/143398964/64794ce6-8ad6-4fc6-a241-a5b1ec059674)

URL:

.......

**Comment by Viennadd1** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/143398964/9a7b0dd4-d66b-4a3b-a3fc-533b37ad02ef)
请问是在这里设置代理吗？如何设置呢？用户和密码填什么呢？填我买的梯子账号吗？
可是我之前下载YouTube视频都是直接就可以下载了啊。
我不太懂这些东西，也不太会设置这些东西，麻烦指教一下，谢谢！
这个是我VPN界面
![image](https://github.com/filecxx/FileCentipede/assets/143398964/fc1397b1-d643-4b54-8f34-8618ed5dcff6)

**Comment by filecxx** [comment]
本地代理通常没有密码
保存之后在设置->网络中选中刚刚添加的这个代理就可以了

**Comment by Viennadd1** [comment]
好的，已解决了，非常感谢
