### ISSUE TITLE
Edge浏览器扩展导致浏览器卡顿

### ISSUE THREAD

**Issue by zerocen** [filecxx/FileCentipede#655]
安装了Edge浏览器扩展后，切换标签页时会卡住，浏览器无响应，等待10秒左右可恢复。
杀进程，重启浏览器后恢复流畅，使用一段时间后又开始卡。
系统: Win11 22H2
浏览器版本: 116.0.1938.69
插件版本: 2.3

**Comment by filecxx** [comment]
如果是访问指定某个网页地址时候卡顿你需要提供一个地址用于测试，如果安装插件之后在所有网页都会卡顿你可能需要检查下是否和某个其他的插件存在冲突，通常可以通过逐个禁用排除的方式发现。

**Comment by zerocen** [comment]
卸载重装后没问题了
