### ISSUE TITLE
ed2k文件无法下载

### ISSUE THREAD

**Issue by DeeEi** [filecxx/FileCentipede#662]
在免费版１.９和最新高级版２.８２都有这个问题

ed2k://|file|zh-cn_windows_10_business_editions_version_22h2_updated_sep_2023_x64_dvd_f45f750a.iso|6449618944|32B36DFD7250A2619747C4FE711D7E05|/

在导入链接后点下载，程序下载页没有响应下载。

**Comment by filecxx** [comment]
3.0 版本中会添加ed2k协议的支持。

**Comment by liuyang1850** [comment]
> 3.0 版本中会添加ed2k协议的支持。

作者，这么长时间啦，什么时候出3.0呢？

**Comment by filecxx** [comment]
> > 3.0 版本中会添加ed2k协议的支持。
> 
> 作者，这么长时间啦，什么时候出3.0呢？

另一个项目已经接近完成了，主要难点都已经解决，应该不需要太久就可以开始更新FileCentipede

**Comment by deranged11** [comment]
> > > 3.0 版本中会添加ed2k协议的支持。
> > 
> > 
> > 作者，这么长时间啦，什么时候出3.0呢？
> 
> 另一个项目已经接近完成了，主要难点都已经解决，应该不需要太久就可以开始更新FileCentipede

希望早点更新，就想用这个下载软件养老了

**Comment by liuyang1850** [comment]
haode1

deranged11 ***@***.***> 于2023年11月10日周五 13:45写道：
