### ISSUE TITLE
no support for faster/automatic torrent port change

### ISSUE THREAD

**Issue by 1mathart** [filecxx/FileCentipede#665]
forced to go into the settings each time i reconnect with my vpn.

**Comment by filecxx** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/100348948/4b20c3ea-9e0e-4d6c-87ab-c65c55eb8202)

**Comment by 1mathart** [comment]
> ![image](https://user-images.githubusercontent.com/100348948/270869837-4b20c3ea-9e0e-4d6c-87ab-c65c55eb8202.png)

RAndom is enought o automatically detect the port ?

**Comment by 1mathart** [comment]
it says i cannot do that

**Comment by 1mathart** [comment]
> it says i cannot do that

ok i have to set it to 1 and then if i click on back it set to Random but it cannot be written

**Comment by 1mathart** [comment]
> ![image](https://user-images.githubusercontent.com/100348948/270869837-4b20c3ea-9e0e-4d6c-87ab-c65c55eb8202.png)

i think it should be considered an issue the fact that **Random** cannot be written

**Comment by filecxx** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/100348948/2ee3ac7a-7bdf-42f5-b3c9-0e1aeb9cb262)
