### ISSUE TITLE
add alternative torrent speed

### ISSUE THREAD

**Issue by 1mathart** [filecxx/FileCentipede#667]
actually there is only one default option.

**Comment by filecxx** [comment]
Please provide more details.

(Please remember that short content will only get a short response.)

**Comment by 1mathart** [comment]
> Please provide more details.
> 
> (Please remember that short content will only get a short response.)

on mutliple torrent client you can set 2 speed settings and actually you can set only one main option on filecxx.

**Comment by filecxx** [comment]
Do you mean like qBittorrent? I don't know, I personally didn't like that, maybe you can implement it by yourself through the plugin after FileCentipede3.0

**Comment by 1mathart** [comment]
> Do you mean like qBittorrent? I don't know, I personally didn't like that, maybe you can implement it by yourself through the plugin after FileCentipede3.0

we'll see in 2 month then !
