### ISSUE TITLE
正在尝试与filec建立链接

### ISSUE THREAD

**Issue by guojq82** [filecxx/FileCentipede#67]
个别下载地址会导致程序弹窗  显示这个界面 一直连接不上  无法使用   拦截的时候没事  下载变为下载中后  一开始下载就出现这个
之前卡饭附件出现一次  这次是这个地址http://www.kufile.net/file/QUExNTAwNDgy.html
感觉是文件名的问题  这个链接拦截后开始下载的文件名含菱形图标之类的乱码

**Comment by guojq82** [comment]
对了 一旦出现这个问题  覆盖安装也解决不了  必须删除原来程序文件  重新解压安装才行

**Comment by filecxx** [comment]
win7系统吗

**Comment by filecxx** [comment]
这个问题已经在1.7版本中修复, 我在多个平台测试了这个链接，现在已经没问题了，你再测试一下之前的出问题那个链接，应该不会再出现这种情况。
