### ISSUE TITLE
installation process broken if not openned in administrator

### ISSUE THREAD

**Issue by 1mathart** [filecxx/FileCentipede#670]
version(>=2.82) :
could be fix by just asking by default when opening fileu.exe
.......

**Comment by filecxx** [comment]
It requires administrator privilege to create the "System service" or "File Association" .....

This is why the "Skip" button existed.

![image](https://github.com/filecxx/FileCentipede/assets/100348948/2c8f992e-21cb-486a-8a5d-fe948d3bd154)
