### ISSUE TITLE
no way to know what part of the torrent is torrenting

### ISSUE THREAD

**Issue by 1mathart** [filecxx/FileCentipede#671]
On transmission or qbitttorent clients this is a crucial option to know what you have and what you are missing.

**Comment by filecxx** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/100348948/e2c96ab0-a32d-42b9-9dbd-6c2298b2a9fb)
"Blocks"  for the torrent task is planned in version 3.0

**Comment by 1mathart** [comment]
> ![image](https://user-images.githubusercontent.com/100348948/270869330-e2c96ab0-a32d-42b9-9dbd-6c2298b2a9fb.png) "Blocks" for the torrent task is planned in version 3.0

when is 3.0 planned to ?

**Comment by filecxx** [comment]
2 **more** months.
