### ISSUE TITLE
安装文件蜈蚣edge插件后，QQ邮箱加载会特别慢

### ISSUE THREAD

**Issue by bawyvh** [filecxx/FileCentipede#672]
安装文件蜈蚣edge插件后，打开网页版QQ邮箱会特别特别慢，关闭插件文件蜈蚣插件后才加载正常。

一段时间以来，我一直以为是QQ邮箱的问题，直到我关了文件蜈蚣插件后，才知道是插件的问题。

希望赶紧修复这个问题

**Comment by filecxx** [comment]
好的

**Comment by wsy998** [comment]
原来这是文件蜈蚣的插件问题吗？！我一直没有往这个方向上考虑

**Comment by feimeng2017** [comment]
安装插件之后  左键点击插件  然后点击界面右下角设置   在常规里面有个    深度分析 (Javascript):    把这个关闭  点击上面的保存   这样QQ邮箱速度就恢复正常了

**Comment by filecxx** [comment]
这个问题新版本修复了
