### ISSUE TITLE
哪里可以取消接管浏览器下载啊 我只是随手保存个图片 不想每天输入激活码

### ISSUE THREAD

**Issue by aigos** [filecxx/FileCentipede#674]
如题 我找不到选项

**Comment by filecxx** [comment]
在设置中排除图片

![image](https://github.com/filecxx/FileCentipede/assets/100348948/8df87466-7fa7-4fdb-a838-23da1c9c2463)

![image](https://github.com/filecxx/FileCentipede/assets/100348948/e02fd580-f530-4367-b386-6ba7a795cf75)

**Comment by filecxx** [comment]
浏览器扩展图标 -> 设置 -> 不下载 
排除图片的扩展名和MIME
![image](https://github.com/filecxx/FileCentipede/assets/100348948/e8bc5c5c-8058-47fb-b818-a4877969e19e)

![image](https://github.com/filecxx/FileCentipede/assets/100348948/de7bd1fd-b031-491f-b334-2c18d9a19f0f)

**Comment by aigos** [comment]
> 浏览器扩展图标 -> 设置 -> 不下载 排除图片的扩展名和MIME ![image](https://user-images.githubusercontent.com/100348948/273365248-e8bc5c5c-8058-47fb-b818-a4877969e19e.png)
> 
> ![image](https://user-images.githubusercontent.com/100348948/273365259-de7bd1fd-b031-491f-b334-2c18d9a19f0f.png)

收到 非常感谢
