### ISSUE TITLE
疑似内存泄漏

### ISSUE THREAD

**Issue by signin404** [filecxx/FileCentipede#678]
**Please provide as much information as possible.**
大文件的BT长时间上传后内存不会释放
需要手动停止才会释放

version(>=2.0) :
2.82

screenshot:
[recording-2023-10-23-06-27-54.webm](https://github.com/filecxx/FileCentipede/assets/145902543/e339347c-28fc-48d4-876e-749cbb5fc8f7)

URL:
magnet:?xt=urn:btih:6ec865593c0b4ab75c6264c30c60dc1c59ace7c0
magnet:?xt=urn:btih:ab3ae56614d9d2484a42cab5d989ef270786f334
magnet:?xt=urn:btih:ecdb1da4f952e9e281bb7f55631b37f2aeec5038

.......

**Comment by filecxx** [comment]
使用的文件映射的这部分内存是由操作系统管理的，程序本身不占用内存，这是对硬盘IO的读写优化，因为每次都从硬盘中读取会非常慢，所以这部分已经读取的数据操作系统会保存在内存中， 当内存不足时候操作系统会自动释放。

这不是内存泄漏。

https://learn.microsoft.com/en-us/windows/win32/memory/file-mapping

**Comment by signin404** [comment]
搜到是libtorrent 2.0默认开启的
https://github.com/arvidn/libtorrent/issues/6667
计入使用中看着太吓人…

**Comment by signin404** [comment]
好像并不会自动释放
我试着用内存测试软件占满内存
手动释放前只能使用14G
手动释放后才能使用文件映射占用的5G

https://github.com/filecxx/FileCentipede/assets/145902543/1545218f-ab93-438c-b756-89dab32164f7

**Comment by filecxx** [comment]
Windows上文件映射和物理内存换出确实不是实时的，我会尝试解决下这个问题，例如对做种中上传率低的任务定时强制解除文件映射。
