### ISSUE TITLE
Linux版，如果个人目录名为中文，则无法成功创建桌面快捷方式

### ISSUE THREAD

**Issue by npnufn** [filecxx/FileCentipede#680]
现在很多发行版在安装时如果选择中文，都会默认创建中文名的个人目录。使用桌面快捷方式功能将无法创建起动器。改成英文就可以。
使用 $XDG_DESKTOP_DIR  变量是不是可以避免这个问题？
filecxx 2.82

**Comment by filecxx** [comment]
下个版本会修复这个问题。
