### ISSUE TITLE
购买了一个终生激活，如何在办公电脑和家庭个人电脑同时激活

### ISSUE THREAD

**Issue by jyligx** [filecxx/FileCentipede#685]
如果无法在两台电脑激活，如何把已激活得授权撤销后转移到另一台电脑

**Comment by filecxx** [comment]
将赠送的2800点卷兑换成28USD之后可以再获取2个终生激活码。

**Comment by jyligx** [comment]
> 将赠送的2800点卷兑换成28USD之后可以再获取2个终生激活码。

如果重装系统后重新安装软件UID又变了怎么处理？

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/issues/504

**Comment by filecxx** [comment]
重装系统之后UID不会变化，只有在更换CPU之后UID才会变。(根据硬件生成的UID)
