### ISSUE TITLE
Chrome插件提示“错误”

### ISSUE THREAD

**Issue by paynewangw** [filecxx/FileCentipede#69]
Chrome最新版本，1.3版本插件提示错误，但是可以正常使用，如下图

![image](https://user-images.githubusercontent.com/88674185/160067546-4a6cb231-ce19-475a-9f8d-be98e072f901.png)
![image](https://user-images.githubusercontent.com/88674185/160067564-cfdf58af-1683-4036-906b-f03998c4ebcb.png)
![image](https://user-images.githubusercontent.com/88674185/160067578-922d03f5-6340-4666-8645-ea9673a7b3c3.png)

**Comment by filecxx** [comment]
可以无视这个错误
