### ISSUE TITLE
How to find UID code

### ISSUE THREAD

**Issue by Malcomyoon** [filecxx/FileCentipede#690]
Hi I would like to purchase a lifetime activation code for this program.

 However, they say you need to enter the UID code. 

Where can I find the UID code? 

How to find UID code of software

I like Chinese characters, but I can't read them. I hope you answer in English

Many thanks

**Comment by filecxx** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/100348948/de720f53-0c17-4c0a-8cef-29ff60a38770)
![image](https://github.com/filecxx/FileCentipede/assets/100348948/89d70782-4c31-408e-8cba-f73199c82bbc)
