### ISSUE TITLE
onlyfans视频下载后播放异常

### ISSUE THREAD

**Issue by MIIIKASAN** [filecxx/FileCentipede#691]
请问一下onlyfans视频下载后播放的话就是灰色绿色图片来回循环，是网站本身有限制吗？用其他插件下载下来的视频就能播放。谢谢！
![屏幕截图 2023-11-17 192351](https://github.com/filecxx/FileCentipede/assets/102034505/05c97682-c95c-4d2c-9711-925db6dc5923)
![屏幕截图 2023-11-17 192451](https://github.com/filecxx/FileCentipede/assets/102034505/1a298063-75a6-4cb8-882f-18fd69aa5eee)

**Comment by filecxx** [comment]
提供一个测试地址

**Comment by MIIIKASAN** [comment]
https://onlyfans.com/asian_sexdoll
