### ISSUE TITLE
激活码填写页面是不是会阻止系统锁屏、关闭屏幕、休眠。

### ISSUE THREAD

**Issue by AmyCoa** [filecxx/FileCentipede#698]
**Please provide as much information as possible.**

version(>=2.0) :
系统：WIN11，23H2，22631.2715
系统相关设置：10分钟锁屏，15分钟关闭屏幕，5小时睡眠
软件：2.82
过程：晚上挂机下载，过12点自动弹出激活码页面，未做任何操作，早上发现笔记本屏幕未息屏。
BUG：主要问题是激活码填写页面似乎阻止了系统关闭屏幕。请确认。
screenshot:
![QQ截图20231201081718](https://github.com/filecxx/FileCentipede/assets/127638750/9cb51375-e42c-444a-9ebd-cab993562ef8)
URL:

.......

**Comment by filecxx** [comment]
目前没有这个功能，除非是全屏模式下播放电影或者游戏否则阻止关闭屏幕没有任何意义， 不过下个版本会增加一个选项：“有活动任务时阻止系统休眠”

**Comment by AmyCoa** [comment]
![3cc6456c34e805a7baf96ad1fd63145](https://github.com/filecxx/FileCentipede/assets/127638750/d5cfa8fe-87f7-45cd-a6b3-d8e4e6c2bb99)
未锁屏状态下，激活码页面会阻止系统关机、休眠
