### ISSUE TITLE
1.7版本，下载完成后，右键--打开目录，无法打开

### ISSUE THREAD

**Issue by paynewangw** [filecxx/FileCentipede#70]
如题，前面的1.5版本也是一样，我是1.5升级1.7的
![image](https://user-images.githubusercontent.com/88674185/160068283-5f005a99-8cea-4689-9cbc-883c5a8b1985.png)

**Comment by filecxx** [comment]
文件保存目录是不是根目录 例如 d:\ 这样的可能无法打开 d:\downloads 这样的可以

**Comment by paynewangw** [comment]
> 文件保存目录是不是根目录 例如 d:\ 这样的可能无法打开 d:\downloads 这样的可以

对，是根目录

**Comment by filecxx** [comment]
1.8 版本已经修复了这个问题
