### ISSUE TITLE
浏览器插件有时无法捕获B站的音频

### ISSUE THREAD

**Issue by flwwater** [filecxx/FileCentipede#700]
version(>=2.0) :
插件2.3版本

screenshot:
![Screenshot_20231208_165633](https://github.com/filecxx/FileCentipede/assets/67504938/3d334a6d-e7c6-4cb4-b0cb-ea3a5202175a)

URL:
https://www.bilibili.com/video/BV1Th411x7ii/?spm_id_from=333.337.search-card.all.click&vd_source=2f139b8fab25b812a4c09b4b3a1b003c

.......
列表里全试了，都是视频，b站大多数网页能检测到音频。
比如这个网页能检测到一个m4s文件，是一个音频文件。
https://www.bilibili.com/video/BV1m94y1J7ej/?spm_id_from=333.1007.tianma.1-1-1.click&vd_source=2f139b8fab25b812a4c09b4b3a1b003c

**Comment by filecxx** [comment]
浏览器插件可能需要一个新的判断策略，当网站提供的视频和音频格式都相同的时候很难检测出到底哪个才是音频，一个可行的办法是尝试请求每个地址，然后根据分辨率来进行判断，这样也可以做到下载后自动合并，但是浏览器和服务器资源消耗都会比较大，也有IP被webserver屏蔽的风险，不过也优于下载每个文件后来人工判断。

**Comment by sonichy** [comment]
无法获取音频
https://www.bilibili.com/video/BV1sh2GYPEQx/
