### ISSUE TITLE
File centipede2.82高级版无法正常下载ED2K链接

### ISSUE THREAD

**Issue by AdamsTime** [filecxx/FileCentipede#709]
**Please provide as much information as possible.**

准备下载最新版win11 23H2(2023年12月更新)，获取的ed2K链接在文件蜈蚣中添加下载后无反应。
ed2k如下：  ed2k://|file|zh-cn_windows_11_consumer_editions_version_23h2_updated_dec_2023_x64_dvd_7cd2c9a8.iso|6833309696|750F5C6FA76183E63E3662026C5507AC|/

version(>=2.0) :   文件蜈蚣2.82

screenshot: 
![2023-12-23_055250](https://github.com/filecxx/FileCentipede/assets/148214747/9d3a2a70-6e65-4136-bf85-23aa3986b0ee)
![2023-12-23_055345](https://github.com/filecxx/FileCentipede/assets/148214747/57c6276b-3623-48d5-8e73-fc737a36d7aa)

URL:

.......

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/issues/662
https://github.com/filecxx/FileCentipede/issues/536
https://github.com/filecxx/FileCentipede/issues/359
