### ISSUE TITLE
1.7版本，下载对话框，无法手动重命名

### ISSUE THREAD

**Issue by paynewangw** [filecxx/FileCentipede#71]
如图，软件自动抓取网页标题作为文件名了，我想自定义文件名，但是不知道在哪里改
![image](https://user-images.githubusercontent.com/88674185/160069329-855f5558-7a61-4910-ba9a-725637017730.png)

**Comment by filecxx** [comment]
双击

**Comment by paynewangw** [comment]
双击只会看到貌似弹出了一个窗口，任务栏多了一个图标，但是并没有在最前，点击也切换不出来，Win10 X64
![image](https://user-images.githubusercontent.com/88674185/160073873-ebbe5886-6a2a-483e-acb0-79cb766ebfe4.png)

**Comment by filecxx** [comment]
你确定双击名称没有出现
![image](https://user-images.githubusercontent.com/100348948/160074721-8557ddb3-c056-4ac3-bffb-b2dd27bca93e.png)
这个编辑框吗？

**Comment by filecxx** [comment]
刚测试确实存在这个问题，原因是这个对话框置顶了，所以把重命名窗口给遮住了，临时解决方法是先把这个对话框移动一下，下个版本修复这个问题。

**Comment by asd0109** [comment]
赞，更新速度真快！

**Comment by filecxx** [comment]
这个问题已经修复，1.8版本将是修复版本。

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/releases/tag/latest
