### ISSUE TITLE
My software UID is different from the one I used to activate my lifetime activation code

### ISSUE THREAD

**Issue by pete3618** [filecxx/FileCentipede#712]
I recently moved to a new PC because my old one has been destroyed. The software UID is now different from the one I got and my life time activation code no longer works.
How do I change my software UID back to my old one? Is it also possible to renew my software UID so the old one will be expired and the new one will work?

**Comment by filecxx** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/100348948/f43e8c6f-d6bc-45be-96e4-8b0040b42809)

**Comment by pete3618** [comment]
That solved it, thank you!

**Comment by filecxx** [comment]
When you recharge $28, you'll also get 2800 credits, which can be exchanged for $56. This way, you can get an extra 2  lifetime activation codes. 

Additionally, there's a reset button; every year, you can reset the recharged amount back to your balance.
