### ISSUE TITLE
浏览器插件：增加自动下载指定类型的文件

### ISSUE THREAD

**Issue by flwwater** [filecxx/FileCentipede#713]
起因：给娃买了英语阅读书籍，其中听力mp3文件要扫码才能听，我就用filecxx一个一个下载下来了，太累了。。。。。。
优化场景：设置里添加自动下载指定后缀的文件。

比如我在设置里开启自动下载，并且指定 mp3 文件，当我刷新网页到下一个音频网页后，插件自动检测到mp3文件，我再也不用点击了，我只需要再点击下下个音频网页，这样100个听力音频只要刷新鼠标点击100次，目前版本至少要点击300次

**Comment by filecxx** [comment]
我会增加一个 "crawler" 功能,  在当前网页中选中 "下一页" 链接或者手动填写css选择器规则之后点击 "开始按钮" 然后会自动获取所有匹配到网页中的 符合规则的文件，例如mp3，自动获取完成之后在文件列表筛选需要的文件(默认全选)，然后点击下载按钮。

无论多少个网页，只需要最多3次点击。

**Comment by filecxx** [comment]
扩展程序更新至 2.92  -> 弹出窗口 -> 收藏家模式

翻页之后会自动添加在列表中，之后选中列表的项，点击下载，应该可以解决这个问题。

![image](https://github.com/filecxx/FileCentipede/assets/100348948/e5afb672-bd98-42ee-95b4-1fba887a1fe0)
