### ISSUE TITLE
1.7打开目录没反应

### ISSUE THREAD

**Issue by Passerby1011** [filecxx/FileCentipede#72]
下载完成后点击打开目录没有任何反应

**Comment by filecxx** [comment]
原因是否和这个一样 

https://github.com/filecxx/FileCentipede/issues/70

**Comment by Passerby1011** [comment]
不是根目录，但目录名称中有中文

**Comment by filecxx** [comment]
这个问题已经修复，1.8版本将是修复版本。

**Comment by filecxx** [comment]
1.8 版本已经上传，这个问题应该修复了。
