### ISSUE TITLE
Suggestions and bugs

### ISSUE THREAD

**Issue by qwerty59b** [filecxx/FileCentipede#721]
Suggestions

option to turn off the pc after finishing the download
bind network interface or ip for torrent download
dark theme
option to disable torrent support from the settings since some people only want it as a download manager
#bug
When I play a video on YouTube it does not detect the name of the video

![Captura de pantalla (1)](https://github.com/filecxx/FileCentipede/assets/130035937/33f6b366-fd32-408a-91d3-c2e7c6a5a491)

**Comment by filecxx** [comment]
Conflicted:
```
bind network interface or ip for torrent download
```

```
option to disable torrent support from the settings since some people only want it as a download manager
```

Through plugins:
```
option to turn off the pc after finishing the download
```
```
dark theme
```


Update your browser extension to 2.91:
```
#bug
When I play a video on YouTube it does not detect the name of the video
```

![image](https://github.com/filecxx/FileCentipede/assets/100348948/1ee7ed01-b313-4e76-83da-7f9e98fff65a)
![image](https://github.com/filecxx/FileCentipede/assets/100348948/4ab082db-5608-456c-a8f2-b680cb2d77f7)
![image](https://github.com/filecxx/FileCentipede/assets/100348948/a259987f-2372-43c8-aaf2-6af87b95ec0e)

**Comment by qwerty59b** [comment]
Gracias
