### ISSUE TITLE
EDGE 2.92版的插件，類型的過濾無作用

### ISSUE THREAD

**Issue by bear0316** [filecxx/FileCentipede#724]
大佬您好，更新至2.92後，類型的關鍵字篩選好像沒作用了，文字的篩選則是正常

![image](https://github.com/filecxx/FileCentipede/assets/87933771/83b9bfd4-4e27-4019-924c-98b1dcbc9796)

另外能不能增加一個功能，對指定網頁固定篩選自定義的類型or文字，感謝大佬

**Comment by filecxx** [comment]
這個BUG這幾天會修復，感謝反饋。

```
對指定網頁固定篩選自定義的類型or文字
```

將來會在過濾的複選框右邊增加一個保存按鈕。

**Comment by filecxx** [comment]
這個BUG這幾天會修復，感謝反饋。

```
對指定網頁固定篩選自定義的類型or文字
```

將來會在過濾的複選框右邊增加一個保存按鈕。

**Comment by filecxx** [comment]
2.93修復了
