### ISSUE TITLE
扩展的下载方式建议改回老版的选择方式

### ISSUE THREAD

**Issue by YandLiu** [filecxx/FileCentipede#725]
现在切换下载方式要点2下，老版只需要点1下
另外，从“浏览器”切换到“文件蜈蚣”时，“忽略此站”的选项位置有问题
![image](https://github.com/filecxx/FileCentipede/assets/26127104/b524a652-d446-4181-809b-703004f08807)
![image](https://github.com/filecxx/FileCentipede/assets/26127104/eb0860f6-bcc8-44d6-96bd-ef55f39ff7f7)

**Comment by filecxx** [comment]
可能不太好改了，因为以后还会发布一个轻量级的HTTP下载工具，意味着下拉列表中会出现3条，如果平放，那么底部的布局宽度可能不够，不过可以增加一个小图标按钮用于快速切换。

**Comment by filecxx** [comment]
可能不太好改了，因为以后还会发布一个轻量级的HTTP下载工具，意味着下拉列表中会出现3条，如果平放，那么底部的布局宽度可能不够，不过可以增加一个小图标按钮用于快速切换。

**Comment by filecxx** [comment]
2.93修复了
