### ISSUE TITLE
忽略此站对有些页面不管用

### ISSUE THREAD

**Issue by YandLiu** [filecxx/FileCentipede#726]
我从 Anna's Archive 下书，图 1 圈圈里的网址 (https://zh.annas-archive.org/md5/01c2409a9c476f4945977a40303faac4) 点进去后会如图 2 一样给出文件的链接，域名在`momot.rs`等，这时必须用浏览器下载才行，我在扩展设置里添加了此域名，发现还是会调用文件蜈蚣，只能通过更改默认的下载方式为浏览器才能正常下载
# 图1
![image](https://github.com/filecxx/FileCentipede/assets/26127104/53ee62ae-04e3-4986-ac92-75b4f6bfea23)

# 图2
![image](https://github.com/filecxx/FileCentipede/assets/26127104/1a974d98-ddeb-45a9-b7d8-2c6ae8767800)

**Comment by filecxx** [comment]
这几天会修复这个问题。

**Comment by filecxx** [comment]
这几天会修复这个问题。

**Comment by filecxx** [comment]
2.93修复了
