### ISSUE TITLE
Telegram 频道/群

### ISSUE THREAD

**Issue by huomutech** [filecxx/FileCentipede#727]
考虑建 Telegram 频道或者群吗？

**Comment by filecxx** [comment]
应该不考虑了，使用社交工具讨论一个下载工具我不确定会有意义，并且可能会创造一些新问题，比如用户之间的无脑争论等。

(当然，这可能只是我不想花时间而找的借口，如果你像建一个我完全不反对。)

**Comment by filecxx** [comment]
应该不考虑了，使用社交工具讨论一个下载工具我不确定会有意义，并且可能会创造一些新问题，比如用户之间的无脑争论等。

(当然，这可能只是我不想花时间而找的借口，如果你像建一个我完全不反对。)
