### ISSUE TITLE
现在的下载是自动选择线程吗？

### ISSUE THREAD

**Issue by fengguowudi** [filecxx/FileCentipede#73]
1

**Comment by asd0109** [comment]
![图像 001](https://user-images.githubusercontent.com/37428027/160219709-ce65d9f3-6e04-4bc3-96ff-871fc287e7ae.png)


设置里面可以选择

**Comment by asd0109** [comment]
![图像 002](https://user-images.githubusercontent.com/37428027/160219758-1312516a-32d4-4c0b-b361-fc905e8eb3ef.png)

添加任务的时候也可以选择线程数

**Comment by filecxx** [comment]
在早期windows 98，2000时代，没有异步网络，下载工具必须为每个连接创建一个线程，现在windows上使用的iocp, *nix 上的epoll ,一个线程即可创建无数连接, 不过连接数不建议设置太多，否则一些服务器可能会封IP。
