### ISSUE TITLE
Add support download from video-delivery.net

### ISSUE THREAD

**Issue by Bug-Cache** [filecxx/FileCentipede#734]
**Please provide as much information as possible.**

version(>=2.0) : 2.82

screenshot:
![image](https://github.com/filecxx/FileCentipede/assets/98657967/ca08fd1f-a178-4252-9b7d-1f9104c33039)
![image](https://github.com/filecxx/FileCentipede/assets/98657967/c7800474-cffa-4961-a271-9d616e30be6b)
![image](https://github.com/filecxx/FileCentipede/assets/98657967/b06e77b2-548f-45f2-8821-9392bdf3a426)

URL:
[NSFW]
https://www4.javhdporn.net/video/nacr-624/

https://ool830ye.video-delivery.net/u5kj6smxu7e3sdgge7dqooq6juf5y5ltr62bhrblqp36vbcz67srhybuibtq/5ynhzmx4so~Pp3F3Cwu0H?token=r55ak5sqzx2uae5lnievppwm&expiry=1709968070269
.......

**Comment by filecxx** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/100348948/dface658-82ec-4bcc-a824-0e975a308790)
![image](https://github.com/filecxx/FileCentipede/assets/100348948/3b36e9fd-e243-4071-b8e2-c568ab5ba60d)

**Comment by filecxx** [comment]
![image](https://github.com/filecxx/FileCentipede/assets/100348948/fe3c4cf0-2e36-402e-baf8-042598389df3)

The video is unplayable.

**Comment by Bug-Cache** [comment]
use different ip, its working for me, 

Chrome Version 122.0.6261.111 (Official Build) (64-bit)

<details>

![image](https://github.com/filecxx/FileCentipede/assets/98657967/e9d38773-a46f-406e-b2e5-3cb2413e3353)

</details>

**Comment by filecxx** [comment]
The website verifies IP addresses, so you need to make sure that the IP address from filecentipede is the same as the IP address of your browser. You can do this by setting the proxy IP address in the software to be the same as your browser's IP address.

![image](https://github.com/filecxx/FileCentipede/assets/100348948/c36da4d3-26b0-498e-bc21-6ae1643e717f)

![image](https://github.com/filecxx/FileCentipede/assets/100348948/5251d8d2-27d8-47d2-88e4-4dc0febaaec9)

**Comment by Bug-Cache** [comment]
thanks,

**Comment by isachinkum** [comment]
Please guide me on the steps clearly here. 

I tried viewing the above video from the browser & it gave an error. When I connected the browser to a VPN connection & tried again, it was working fine. Then when I tried to download the video using the file centipede browser extension, it gave the same message on the file centipede desktop application that the author of this thread mentioned initially. Following the solution given by the developer, I found out the IP address of the browser while connected to VPN & went into the File Centipede desktop application to change the proxy IP address from "Setting > Proxy > Add".
The "Type" option was kept as "socket5"
"Host" --> Entered the browser IP address I got
"Port" --> 443 (considering the website is an https site)
"User" --> _<blank>_
"Password" --> _<blank>_

Then I retry to download again, but it gives different types of errors again (like Remote rejected or Connect failed etc) without downloading the files.

What am I missing here?

**Comment by isachinkum** [comment]
I'm using the free version of the Browsec VPN addon (https://addons.mozilla.org/en-US/firefox/addon/browsec/) for Firefox. How do I add the IP & Port (i.e. 127.0.0.1, 1080) in this browser VPN?

**Comment by filecxx** [comment]
> I'm using the free version of the Browsec VPN addon (https://addons.mozilla.org/en-US/firefox/addon/browsec/) for Firefox. How do I add the IP & Port (i.e. 127.0.0.1, 1080) in this browser VPN?

I don't know, you probably can't, because it's just a browser extension, it's not a real VPN.

**Comment by isachinkum** [comment]
Ok. Thank you.
