### ISSUE TITLE
Browser extension youtube performance issue

### ISSUE THREAD

**Issue by anar4732** [filecxx/FileCentipede#742]
When I enable File Centipede browser extension youtube starts working slow. disabling floating bars or setting browser as downloader not fixes this. only uninstalling the extension or disabling in browser setting fixes it. ignoring site not fixes too.
Version 1.81

**Comment by anar4732** [comment]
why does the extension packed with the app is older version?

**Comment by filecxx** [comment]
The browser extension was recently updated.
