### ISSUE TITLE
Unable to open and use the software

### ISSUE THREAD

**Issue by xMonTersx** [filecxx/FileCentipede#749]
I was able to use the software normally before, but today I cannot open and use it. I did not update any system or environment.

**Attached:**
Video of the issue:  https://file.io/8tuJBPWfZBJd
System information:
- Processor: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz  1.50 GHz
- Installed RAM: 16,0 GB (15,8 GB usable)
- System type: 64-bit operating system, x64-based processor
- Edition	Windows 11 Pro
- Version	22H2
- Installed on	‎29/‎07/‎2023
- OS build	22621.3296

**Steps to reproduce:**

1. Open the software.
2. The software does not open at all.

**Expected behavior**:
The software should open and run normally.
**Additional information:**
I have tried restarting my computer, but the issue persists. I have also tried uninstalling and reinstalling the software, but the issue still occurs.

Request:

Please investigate this issue and provide a solution.

**Comment by xMonTersx** [comment]
I found the reason for this issue.
Today, somehow Windown defenders recognize this as trojan and block it in silent.

**Comment by filecxx** [comment]
I've submitted the file to https://www.microsoft.com/wdsi/filesubmission, but Microsoft Defender hasn't provided any evidence that it's malicious. Even though fileu.exe is simply a GUI program for communicating with filec.exe and won't receive updates for a while, there's nothing I can do unless Microsoft Defender removes it from their virus database.

**Comment by xMonTersx** [comment]
@filecxx Could you let me know how prevent this dialog? I want it automatically run when windown startup
![image](https://github.com/filecxx/FileCentipede/assets/10475907/535eb526-2dd3-4088-96b1-c16368c9a743)

**Comment by filecxx** [comment]
Settings -> General -> System service

![image](https://github.com/filecxx/FileCentipede/assets/100348948/b1a4759d-76b3-4036-bc89-ba4d5caaae64)

**Comment by filecxx** [comment]
The Microsoft Defender issue has been fixed.

```
Analyst comments:

At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
```

**Comment by xMonTersx** [comment]
@filecxx 
I already checked from beginning 
![image](https://github.com/filecxx/FileCentipede/assets/10475907/d8e02154-a5cc-434b-a0da-021e7a626d9e)

**Comment by filecxx** [comment]
Do this:

![image](https://github.com/filecxx/FileCentipede/assets/100348948/bad5481a-ae29-403a-8115-dcf8011efd04)
![image](https://github.com/filecxx/FileCentipede/assets/100348948/bac10f58-d099-4b16-b61b-c7018fa16d00)

**Comment by xMonTersx** [comment]
Thank you, It worked now
