### ISSUE TITLE
Is the File Centipede Lifetime Activation code one-time? 

### ISSUE THREAD

**Issue by XUnkownX** [filecxx/FileCentipede#757]
Hello, I want to get a Lifetime Activation code, but I have a question, is it one-time? 
So I can't use it on another computer?

**Comment by filecxx** [comment]
When you recharge $28, you'll also get 2800 credits, which can be exchanged for $56. This way, you can get an extra 2 lifetime activation codes.

Additionally, there's a reset button; every year, you can reset the recharged amount back to your balance.
