### ISSUE TITLE
有些链接无法正常下载

### ISSUE THREAD

**Issue by Passerby1011** [filecxx/FileCentipede#76]
![image](https://user-images.githubusercontent.com/63802758/160239488-f97c12b0-b4ef-4f8e-9b4e-379d1e852de4.png)
浏览器和idm都可以正常识别和下载但是软件不行
![image](https://user-images.githubusercontent.com/63802758/160239531-d9b8b2e1-4037-47c0-879c-4ed4c5b64ca0.png)
下载显示已完成但是根本没有下载是假的，无法正确识别
这个是链接：https://appall02.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=16051585&zipcontent=%7B%22fs_id%22%3A%5B457633230205762%5D%7D&size=1700640188&sta_dx=4126cab42925ab016661eebfcae42cd1e47bcbad&time=1648297698&sign=yUdy3dSFZ0SVxtzShv1zcMqd:73XUaF%2BLXG9WllyB2KmowwhgUpg%3D&uid=1165448874&time=1648384098&dp-logid=8885509576041381584&dp-callid=0&bus_no=31&vuk=1165448874&zipname=[打包下载]需解压重命名album目录[18464bfaaf2ac070993f83708238463fb0f1628d.mp4.mp4]为[Labview_2018.7z].zip
UA提供是KinhDown（idm可以正常下载，实测其他的UA也会这样）
![image](https://user-images.githubusercontent.com/63802758/160239597-288ff098-5cb5-4526-9980-537317b04699.png)
![image](https://user-images.githubusercontent.com/63802758/160239606-04f445cc-dd61-4d79-8e93-74f8835dda5b.png)
因为链接具有一定的时效性，如果开发者看到这个时，链接已失效，可以留言我重新提供链接

**Comment by filecxx** [comment]
确实是个BUG，只下载了1字节，能提供下来源地址吗，如果每次失效了我都问你要会很麻烦。

**Comment by Passerby1011** [comment]
https://baidu.kinh.cc/?Type=LinkParsing，解析出来的用于不限速下载百度云，所有解析出来的都有这个bug

**Comment by filecxx** [comment]
如果还有其他问题尽量一块提交下，我尽量今天全部弄完发布1.9

**Comment by Passerby1011** [comment]
扩展抓取下来的视频文件时常不能被分类
还有就是自动更新没有用

**Comment by filecxx** [comment]
自动更新功能是正常，我这边没有提供更新的资源，所以更新不了，分类我稍后弄完这个看看。

**Comment by Passerby1011** [comment]
还有在设置里添加的tracker，不能自动添加到任务中（先添加再下载）

**Comment by filecxx** [comment]
包含: 下载 勾选了吗

**Comment by Passerby1011** [comment]
![image](https://user-images.githubusercontent.com/63802758/160241788-a23fc131-9acf-4159-b0f6-9066e976de93.png)
![image](https://user-images.githubusercontent.com/63802758/160241793-4877a5c4-ce7e-4ee8-aab9-be4504473896.png)

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/160241812-b540fcaa-1785-4d1f-8dc6-fe110924781b.png)
需要在这个编辑区填写
![image](https://user-images.githubusercontent.com/100348948/160241825-5c2c18b8-3369-4357-aeda-404aafc39e5f.png)

这里只是已经下载的列表，用于查看

不过tracker不要填写太多了，速度不会提高反而会让种子文件变得很大。

**Comment by Passerby1011** [comment]
我之前BitComet都是直接订阅的定期更新，明白了

**Comment by zzugyl** [comment]
谷歌浏览器安装了“文件蜈蚣”插件，如果客户端没有打开，那么网页上的图片“右键另存为”就无法弹出来，简单的图片都没法下载。

**Comment by filecxx** [comment]
> 谷歌浏览器安装了“文件蜈蚣”插件，如果客户端没有打开，那么网页上的图片“右键另存为”就无法弹出来，简单的图片都没法下载。

linux版本确实存在这个问题，root权限下xserver启动不了GUI程序。

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/160244072-7a7692d4-9f31-4dda-9e52-0ec7582ae804.png)
这个问题已经解决了，原因是服务器返回了不标准的头 
content-range: 0-1/17xxxxx
标准的头应该是 
content-range: bytes 0-1/17xxxxx

并且限制了请求块的大小

稍后会发布修复后的版本。

**Comment by filecxx** [comment]
新版本下载: https://github.com/filecxx/FileCentipede/releases/tag/latest
