### ISSUE TITLE
File type matching and page url catching

### ISSUE THREAD

**Issue by thiendt2k1** [filecxx/FileCentipede#762]
**Please provide as much information as possible.**
1. When i try to download a pdf from ggdrive, it still get the pdf extension though i skip download pdf file type in settings.
2. When i open a new tab other the current page where the content is download, the page url change to that, eg in picture below when i download from ggdrive, but when open a new tab, the page url is new tab.

<details><summary>List of extension allow matching in below picture</summary>
<p>

exe,bin,dll,dat,7z,ttf,bat,xv,xvx,apk,ipa,epub,asf,avi,mp3,mp4,mpeg,mpg,mpga,rm,rmvb,tar,wma,wmp,wmv,mov,zip,3gp,chm,mdf,iso,ra,rar,jar,msi,arj,psd,hqx,sit,lzh,gz,tgz,mobi,deb,sisx,cab,pxl,xlb,dmg,msu,bz2,xlsx,xls,doc,docx,ppt,pptx,flv,swf,mkv,tp,ts,flac,ape,wav,aac,msp,m3u8,3gpp,f4f,f4m,ogg,webm,mpg4,m4a,xbm,cda,000,001,ace,ain,alz,apz,ar,arc,cad,pax,cpio,xar,lha,mtree,xz,lzip,lzma,bzip2,uue,z,xpi,docm,dotx,dotm,xlsm,xltx,xltm,xlam,pptm,potm,ppam,ppsx,ppsm,odt,odp,ods,tsv,wps

</p>
</details> 

My debug info:
version(>=2.0) :
FileCxx 2.82
Extension 2.94
Edge 123.0.2420.97
Windows 11 latest stable 

screenshot:
![image](https://github.com/filecxx/FileCentipede/assets/58879301/51686fcf-5270-446d-acc9-33b5cc2b9711)
![image](https://github.com/filecxx/FileCentipede/assets/58879301/52abe429-a970-45f7-bcc5-19ec3750ff6e)

URL:
[https://drive.usercontent.google.com/download?id=1PGbbSLZnt3eEItagSsJnmE9Ueg-p-CWh&export=download&authuser=1&confirm=t&uuid=<redacted>&at=APZUnTXmwUdqVf8zmGwi7Dfl3zcj:xxxxxxx](url)

.......
Thanks for your time and efforts.

Update: It seem to not be able to catch both name and file type from google drive
Here is a demo link https://drive.usercontent.google.com/download?id=1Fji_AEf_f6GLZ_pcRtpvm4AwAJA088fP the file downloaded is named download.bin

**Comment by filecxx** [comment]
About the ```edge://newtab/```, it's unfixable but can be removed, remaining empty.

If you want to skip the "pdf" extension from the web browser, you should do this:

![image](https://github.com/filecxx/FileCentipede/assets/100348948/e1432a16-8abe-4231-9bd1-5a1979e8e969)

![image](https://github.com/filecxx/FileCentipede/assets/100348948/b2ec665a-89c3-453b-9c62-9ee1f2e88b5e)

![image](https://github.com/filecxx/FileCentipede/assets/100348948/d6299e96-0834-4f29-9b27-5ced9e40fb1b)

![image](https://github.com/filecxx/FileCentipede/assets/100348948/d99e0830-bdeb-44bf-a580-831fec20bb16)

![image](https://github.com/filecxx/FileCentipede/assets/100348948/076fe9a3-b7c7-41cf-b6ca-cff3f9784d85)

**Comment by thiendt2k1** [comment]
> About the `edge://newtab/`, it's unfixable but can be removed, remaining empty.
> 
> If you want to skip the "pdf" extension from the web browser, you should do this:
> 
> ![image](https://private-user-images.githubusercontent.com/100348948/327289990-e1432a16-8abe-4231-9bd1-5a1979e8e969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTk5NDksIm5iZiI6MTcxNDYxOTY0OSwicGF0aCI6Ii8xMDAzNDg5NDgvMzI3Mjg5OTkwLWUxNDMyYTE2LThhYmUtNDIzMS05YmQxLTVhMTk3OWU4ZTk2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwMzE0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWNmY2UyOTA1NjIxNWJkNTZlNzVlMTNiODRlN2QxMWUyNDdlODg1ODU5OTIzODhhODg0YzgyODhlNmY5NDRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mFS9ykuhejfwBUkmaXO2D-4F9ONzXxKLpru_UMdm3JU)
> 
> ![image](https://private-user-images.githubusercontent.com/100348948/327290034-b2ec665a-89c3-453b-9c62-9ee1f2e88b5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTk5NDksIm5iZiI6MTcxNDYxOTY0OSwicGF0aCI6Ii8xMDAzNDg5NDgvMzI3MjkwMDM0LWIyZWM2NjVhLTg5YzMtNDUzYi05YzYyLTllZTFmMmU4OGI1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwMzE0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTkyNzAzYTQ1YjA5Yjc3ZTc0ODc0M2Q5ZDg2MWRiNzM5MWMzMTc2YTc5YTc3ZGRiODFhMTBhOWZhMTUxMTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3P1HIIjZKM9Ht_BgGw-L9opn8mmdDl_Or52yLO9hu1k)
> 
> ![image](https://private-user-images.githubusercontent.com/100348948/327290093-d6299e96-0834-4f29-9b27-5ced9e40fb1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTk5NDksIm5iZiI6MTcxNDYxOTY0OSwicGF0aCI6Ii8xMDAzNDg5NDgvMzI3MjkwMDkzLWQ2Mjk5ZTk2LTA4MzQtNGYyOS05YjI3LTVjZWQ5ZTQwZmIxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwMzE0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTA0ZmI1MDg2NmJiYWMzZjk4NWQ5ODcxN2NkNmM0MTQxMTlmNTY1OWVhMDk5ZWI0NmM4NWFhMTg2MDBlZmM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7UkO-76p5G5zH_eOKGmFaZNcM4P4gQfirTr2rQEgczs)
> 
> ![image](https://private-user-images.githubusercontent.com/100348948/327290141-d99e0830-bdeb-44bf-a580-831fec20bb16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTk5NDksIm5iZiI6MTcxNDYxOTY0OSwicGF0aCI6Ii8xMDAzNDg5NDgvMzI3MjkwMTQxLWQ5OWUwODMwLWJkZWItNDRiZi1hNTgwLTgzMWZlYzIwYmIxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwMzE0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmJhNjBhNmUyYjg0NDdmNWExNTg4MWE4MTAxZGEzZTVjZTM0NjEyNThkMWUyZTA4OTM2NTczMmQ3ZGEzM2ViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.91oC6sF3ZVDv6_ck9G8JYeSLxNXqEukEAfBYvYOstSg)
> 
> ![image](https://private-user-images.githubusercontent.com/100348948/327290200-076fe9a3-b7c7-41cf-b6ca-cff3f9784d85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTk5NDksIm5iZiI6MTcxNDYxOTY0OSwicGF0aCI6Ii8xMDAzNDg5NDgvMzI3MjkwMjAwLTA3NmZlOWEzLWI3YzctNDFjZi1iNmNhLWNmZjNmOTc4NGQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwMzE0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWMyNGYxNzk1OGFjYzIxMzkxYzFhMjU4NmJjNzExMjgzOTJlYzg3OGFkMWJhNzg2MzA5ZmYwZGIxY2FiZmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xuFGrUwh1LGLfR7Pn4XCXu-6hT9TDGbTrGiTpXx-AHo)

ok, good to know that, thanks.
P/s: Just a small note, you should put all settings in one place, this is quizzing to find where to set.
