### ISSUE TITLE
软件打开没反应

### ISSUE THREAD

**Issue by YXY0517** [filecxx/FileCentipede#767]
软件打开大多数时候都是无反应添加下载链接无反应点任何东西无反应，想下载完全凭运气

**Comment by filecxx** [comment]
版本号，截图，URL

以及更多详细信息。

**Comment by YXY0517** [comment]
版本1.9免费版但是我下的2.8高级版也会有同样的情况，磁链复制也不会弹出下载框[https://share.weiyun.com/4zSSO7dL](url)

**Comment by YXY0517** [comment]
版本1.9免费版但是我下的2.8高级版也有同样的情况，磁链复制也不会弹出下载框 [https://share.weiyun.com/4zSSO7dL](url)

**Comment by filecxx** [comment]
我很难根据你的描述推断出你遇到的问题。

**Comment by filecxx** [comment]
如果是功能失效，很可能是运行环境问题，其他程序造成的冲突等。

没有收到过其他用户提交这类问题，下图是我自己使用的统计次数，从未出现过一次 “无反映”

![image](https://github.com/filecxx/FileCentipede/assets/100348948/16ce0ae6-c785-499d-96ad-822de42a2540)
