### ISSUE TITLE
下载完之后按enter播放视频没声音

### ISSUE THREAD

**Issue by zzugyl** [filecxx/FileCentipede#77]
偶尔的现象，先反馈一下。
桌面：`Ubuntu 20.04.4 LTS`
文件蜈蚣： `filecxx_latest_linux_x64.zip`
所下载文件的链接：[抖音某视频](https://www.douyin.com/video/7031098913419463944)
下载完之后，在文件蜈蚣上按enter播放，调用我默认播放器mpv，播放该视频没有声音。但是进文件夹，双击打开，也是mpv播放，就有声音。换个链接，有些又是正常有声音的。
一部分文件蜈蚣的日志：
```
error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = 没有那个文件或目录
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
couldn't open play stream: 设备或资源忙
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```
后面又下载了几个，回头再播放一下前面那个，声音又正常了。

**Comment by zzugyl** [comment]
B站视频也遇到 https://www.bilibili.com/video/BV1nF411W7qi?spm_id_from=333.1073.high_energy.content.click
这个是没有音频通道，只下载了视频通道。可能和近期B站视频编码格式改成AV1有关？
![2022-03-27_10-22](https://user-images.githubusercontent.com/27466768/160263939-4608a228-50b1-4b4d-872f-3cdc49b18434.png)

**Comment by filecxx** [comment]
程序是用的musl libc, 会遇到一些外部调用环境问题, 如果用glibc 则问题会更多, 例如不同发行版无法运行，相同发行版不同版本也无法运行等.

我自己默认播放器用的smplayer ,一直不出问题.

在Linux版本上这块很难解决, 至少短时间内这个可能解决不了.
