### ISSUE TITLE
github的releases每次都没有更新吧

### ISSUE THREAD

**Issue by zxba** [filecxx/FileCentipede#78]
https://user-images.githubusercontent.com/59327516/160273295-45909fe2-5f5a-44c2-b669-6bae25017a8e.png
如图所示的地方，我刚刚在sourceforge才找到1.9版本。

**Comment by filecxx** [comment]
文件是一样的，都是1.9版本，名称是1.2是因为有几个其他网站下载链接到了这个下载地址，实际上下载的是1.9

**Comment by zxba** [comment]
> 文件是一样的，都是1.9版本，名称是1.2是因为有几个其他网站下载链接到了这个下载地址，实际上下载的是1.9

那最好在更新介绍那块说明一下，不然一看文件名不是相应的版本，就不知道什么情况了。
