### ISSUE TITLE
Free key has expired, and no new key available

### ISSUE THREAD

**Issue by flatline-studios** [filecxx/FileCentipede#788]
Even though the date for the expiry of the following key:

2024-05-31 00:00:00 - 2024-06-02 00:00:00
0vnXRmauOfk03AkdarWkGxaLA9EAbSYLVMz-eL7VBpTgL4CilpHMUiY-uSb4sDRUgBuPOv9JwvvYH_9futEp87EARnkR6-9vwgpKoDmPYHkR8Gh50BbXB_aJYMHp64tAQUp3h_LfckS0hv0fsuNcgWbITeNTjKMRhPRGIHmzC9YKY

Hasn't happened yet, it's still erroring stating that it's expired.

**Comment by filecxx** [comment]
Please refresh the activation_code page.
