### ISSUE TITLE
Linux 打包求助

### ISSUE THREAD

**Issue by everyx** [filecxx/FileCentipede#79]
你好，我是一名 ArchLinux 用户，想把这个软件打包放到 AUR 中，目前看到双击 `fileu` 会弹出提示手动安装，请问此安装判断的具体逻辑是如何的？这样我打包的时候，能把这个放到脚本中手动初始化。

目前了解到的，包括：
1. 创建 `File Centipede.desktop` 文件，如果文件位置不再 `$HOME/desktop` 下是否会影响判断？
2. 启动服务：看起来是 `filec start` 启动的，是如何判断的？如果打包使用 systemd 的方式安装是否会影响判断？
3. 还有 GUI 配置文件 `lib/fileu_linux.conf`，这个文件是否能放到其他路径？

另外：
1. `lib/data_linux.db` 是否能制定目录？

谢谢，是否还有其他补充？

**Comment by filecxx** [comment]
很遗憾, fileu_linux.conf 和 data_linux.db 等所有文件只能在lib目录下, 和 filec 与 fileu 相同目录

关于快捷方式目录：

path home_path()
{
   auto home = getenv("HOME");

    if(home != nullptr && !(result = home).empty()){
        return home;
    }
    return (result = "/home/var_data");
}


home_path() / "Desktop" / (name + ".desktop")

启动服务：
系统服务器的启动命令行参数应该为 filec __service__ 而不是 filec start 因为 start方式启动进程在结束之前不会停止.

fileu安装过程非常简单：

启动 filec install 进程

根据返回值判断是否安装成功
https://github.com/filecxx/FileCentipede/blob/main/source_code/fileu/help/help_install.cpp
然后根据参数写入 lib/fileu_linux.conf 文件
而实际上 fileu_linux.conf 这个文件只要存在，并且 json值installed 为1或者2 不需要安装也能使用。

比较重要的是:
程序里的目录结构不能发生变化, 也就是不能放在其他路径里。

**Comment by everyx** [comment]
@filecxx 还有一些疑问，如下：

> 很遗憾, fileu_linux.conf 和 data_linux.db 等所有文件只能在lib目录下, 和 filec 与 fileu 相同目录

希望能修改一下配置文件的读取逻辑：默认使用 `lib/` 目录下的，然后 `lib/` 目录下没有，则在 `$HOME/.config` 目录下查找，都没有就初始化安装。 或者启动 GUI 时能加入配置文件路径的参数，这样就能通过启动脚本的方式来定制


> 启动服务： 系统服务器的启动命令行参数应该为 `filec __service__` 而不是 "filec start" 因为 start方式启动进程在结束之前不会停止.

所以如果我使用 systemd 的方式来启动这个服务的话，命令不需要转入后台的话，是可以用 `filec start` 命令的，对吧？
另外是否必须要使用 `root` 权限启动服务进程？

**Comment by filecxx** [comment]
所以如果我使用 systemd 的方式来启动这个服务的话，命令不需要转入后台的话，是可以用 filec start 命令的，对吧？
另外是否必须要使用 root 权限启动服务进程？

是的, filec start 不会立即返回 `filec __service__` 会

linux下可以不使用root权限（大部分发行版） , windows 上必须使用administrator权限，否则无法监听端口。

**Comment by filecxx** [comment]
希望能修改一下配置文件的读取逻辑：默认使用 lib/ 目录下的，然后 lib/ 目录下没有，则在 $HOME/.config 目录下查找，都没有就初始化安装。 或者启动 GUI 时能加入配置文件路径的参数，这样就能通过启动脚本的方式来定制

这样设计的目的是因为一台机器可以安装多个副本，互相拥有自己的数据库从而互不影响，部分用户可以用一个来下载色情片，另一个来下载正常资源。

**Comment by everyx** [comment]
> 希望能修改一下配置文件的读取逻辑：默认使用 lib/ 目录下的，然后 lib/ 目录下没有，则在 $HOME/.config 目录下查找，都没有就初始化安装。 或者启动 GUI 时能加入配置文件路径的参数，这样就能通过启动脚本的方式来定制
> 
> 这样设计的目的是因为一台机器可以安装多个副本，互相拥有自己的数据库从而互不影响，部分用户可以用一个来下载色情片，另一个来下载正常资源。

理解，不过这样打包就不好处理了，配置文件放在执行文件同目录，就需要用户有root 权限。

能否通过环境变量或者其他方式来切换默认使用用户目录 home/.config 下的配置文件呢？

这样才能方便打包

**Comment by filecxx** [comment]
配置文件不需要root权限，但是必须保证普通用户有可写权限，至于放置home/.config目录，应该不行，不过是否可以通过符号链接方式将lib下文件链接到.config目录我并没有测试过，所以不太确定。

不过有一个可行方式就是将所有文件放置到.config目录。

**Comment by everyx** [comment]
> 配置文件不需要root权限，但是必须保证普通用户有可写权限，至于放置home/.config目录，应该不行，不过是否可以通过符号链接方式将lib下文件链接到.config目录我并没有测试过，所以不太确定。
> 
> 不过有一个可行方式就是将所有文件放置到.config目录。

因为打包后安装的目录不是在家目录下的，设置所有用户均可读写又不符合一般打包的习惯，不支持通过命令参数配置这些文件的目录的确比较麻烦 🤔

**Comment by filecxx** [comment]
暂时应该没有别的办法了，如果对此进行改动，牵动的范围可能比较大，包括会影响windows版本，至于打包最稳定的方法应该是释放到指定目录，比如 /opt/ 下面, 然后调用 filec install

**Comment by everyx** [comment]
> 暂时应该没有别的办法了，如果对此进行改动，牵动的范围可能比较大，包括会影响windows版本，至于打包最稳定的方法应该是释放到指定目录，比如 /opt/ 下面, 然后调用 filec install

是的，一般放在 `/opt/` 目录下，包安装的时候运行 `filec install` 也不太好，如果切换为其他用户就要重新安装包才行了，如果放到启动脚本中，也需要软连接用户目录的到 `/opt/` 目录下，这也会影响到其他用户

**Comment by filecxx** [comment]
如果不运行 filec install 那么需要创建文件 到 /usr/share/applications/ 或 ~/.local/share/applications/ 来设置文件关联，和filec与fileu协议, 然后需要执行 xdg-mime 来更新mime，最后还需要 执行 update-desktop-database 来让其生效，是个很繁琐的过程.

**Comment by everyx** [comment]
> 如果不运行 filec install 那么需要创建文件 到 /usr/share/applications/ 或 ~/.local/share/applications/ 来设置文件关联，和filec与fileu协议, 然后需要执行 xdg-mime 来更新mime，最后还需要 执行 update-desktop-database 来让其生效，是个很繁琐的过程.

这些在包安装过程中可以做到，还好，是常规操作，主要是各个用户之间的配置文件的隔离问题

**Comment by hosxy** [comment]
在我的 ArchLinux 上简单试了一下，用 bwrap 来启动 filec 和 fileu 可以做到把配置文件从 /opt 下隔离到 XDG_CONFIG_HOME 里面，而且这个操作不需要提权

但是因为涉及到从用户家目录加载配置文件，如果要用systemd 服务实现自启，应该要用用户级别的？

**Comment by everyx** [comment]
> 在我的 ArchLinux 上简单试了一下，用 bwrap 来启动 filec 和 fileu 可以做到把配置文件从 /opt 下隔离到 XDG_CONFIG_HOME 里面，而且这个操作不需要提权
> 
> 但是因为涉及到从用户家目录加载配置文件，如果要用systemd 服务实现自启，应该要用用户级别的？

是的，既然服务在 Linux 下不需要 root 权限，应该优先使用用户级别的 systemd 服务。

除了让程序原生提供支持，其他办法都太 hack 了 😂

**Comment by everyx** [comment]
> 暂时应该没有别的办法了，如果对此进行改动，牵动的范围可能比较大，包括会影响windows版本，至于打包最稳定的方法应该是释放到指定目录，比如 /opt/ 下面, 然后调用 filec install

@filecxx 你好，加入一个命令行参数来指定 `fileu_linux.conf` 和 `data_linux.db` 的位置，例如 `filec start -c ~/.config/filecxx/fileu_linux.conf -d ~/.config/filecxx/data_linux.db` 应该不会影响其他逻辑吧？是否能加入一下这个功能？

**Comment by filecxx** [comment]
这个没有问题
fileu_linux.conf 这个是fileu的参数 
data_linux.db  这个是filec的参数

**Comment by everyx** [comment]
> 这个没有问题 fileu_linux.conf 这个是fileu的参数 data_linux.db 这个是filec的参数

嗯嗯，只要是能分别配置就行，这样在打包的时候，就能通过脚本手动指定指定这些文件的位置



> 另外，在2.0版本data_linux.db不再是一个文件了，而是3个 data_linux.db data_linux.db-wal data_linux.db-shm
> 
> 这个是sqlite wal模式自动创建的

这个没关系， `db-wal` `db-shm` 应该是 sqlite 自动创建的临时文件，只要制定了 db 文件的位置，这些文件的位置也就相当于指定了

**Comment by filecxx** [comment]
但是软件目录还是必须保持可写，因为2.0的文件浏览器会对网络文件夹列表创建缓存文件，包括以后icons目录可能会将所有图片文件定期构建为一个文件用来提升启动速度。

不过多个用户之间不会产生影响，因为这些是缓存，可以共用。

**Comment by leonevilred** [comment]
菜鸟表示能否在aur.archlinux.org搜到它并安装？

**Comment by everyx** [comment]
> 菜鸟表示能否在aur.archlinux.org搜到它并安装？

目前没有哦，目前软件行为还不适合打包

**Comment by filecxx** [comment]
我放弃制作这个功能了，这和软件的自动更新功能冲突，如果打包可能需要将整个目录全部放入用户文件夹内，我目前想不到别的方法了，通常打包主要目的应该是解决程序依赖问题，这个程序并不依赖任何库，甚至连glibc都不依赖。我尝试过了，找不到取舍方法，非常抱歉。
