### ISSUE TITLE
在下载软件时，点击删除任务和文件，出现卡住，而且重新软件后，那个任务还在，怎么删都删不去

### ISSUE THREAD

**Issue by SlientTime** [filecxx/FileCentipede#8]
![image](https://user-images.githubusercontent.com/77520256/157817004-339771bc-32c9-412c-b7a1-4900d451ec84.png)
下载pycharm.exe时，想要删除任务，点击之后，软件卡了

**Comment by stdjs** [comment]
尝试 安装路径/filec.exe stop 后重新打开软件, 如果还是卡住, 提供URL地址, 最好有更详细的信息, 比如: 只是任务卡住, 别的任务正常, 还是所有操作都出现问题, 这样我能知道是否由windows共享内存导致的, 能更快修复。

**Comment by filecxx** [comment]
尝试 安装路径/filec.exe stop 后重新打开软件, 如果还是卡住, 提供URL地址, 最好有更详细的信息, 比如: 只是任务卡住, 别的任务正常, 还是所有操作都出现问题, 这样我能知道是否由windows共享内存导致的, 能更快修复。
