### ISSUE TITLE
能不能设置默认使用系统代理

### ISSUE THREAD

**Issue by YulinChan** [filecxx/FileCentipede#80]
![image](https://user-images.githubusercontent.com/48314862/160323013-15a5fd72-1ec5-4171-8ad6-154a67edaac7.png)
就像上图一样，使用系统代理，会方便很多

**Comment by filecxx** [comment]
很好，你找到问题所在了，是没使用浏览器代理导致的下载速度慢，2.0版本我会尝试添加使用系统代理功能，但不能保证。
