### ISSUE TITLE
Important vital please add support of this capital website : fullmatchsports highlights

### ISSUE THREAD

**Issue by trimechee** [filecxx/FileCentipede#803]
Hello, my laoptop broke down so I use my little laoptop which dates from 2012 windws 7 and when I watch a live football match, it's almost impossible to watch so much that it lags, the solution to this problem is to download the match highlights and the site "fullmatchsports.cc" seems to be one of the rare sites to offer long highlights, i.e. highlights which last 25 minutes or 30 minutes :

https://fullmatchsports.cc/spain-vs-france-full-match-euro-2024/?tab=highlights

hence the capital importance of this website because many other highlights websites offer highlights of only 10 minutes.... and so the problem is it is impossible to download the video highlights on this rare site and we hope it will be fixed soon please, thank you very much :)

**Comment by filecxx** [comment]
![image](https://github.com/user-attachments/assets/8d305740-5215-40bd-8ee6-533b898d5767)

**Comment by filecxx** [comment]
I just tested the website, and the browser extension is working properly. Could you please try testing it again?

![image](https://github.com/user-attachments/assets/f5b5bf50-df7e-42d6-af07-5a5838e2f3c6)
![image](https://github.com/user-attachments/assets/c75d7b33-d2cd-4dd4-a338-7d6b434ea31a)
![image](https://github.com/user-attachments/assets/780bca8a-ee57-49f2-a878-d3c37c406e2b)
![image](https://github.com/user-attachments/assets/5dc79f85-1da3-4f2f-91b4-c15e64e930d3)
