### ISSUE TITLE
I downloaded an mp4 video on YouTube using the app and it couldn't be opened. All other formats can be opened, but mp4 cannot

### ISSUE THREAD

**Issue by yukiharasensei** [filecxx/FileCentipede#804]
**Please provide as much information as possible.**

Link download video: youtube.com

quanlity: FHD - 4K

Version: Lasted

version(>=2.0) :

screenshot:

URL:
![image](https://github.com/filecxx/FileCentipede/assets/121099758/9675f266-d7df-4448-bc03-ed79bab2d2ae)

.......

**Comment by filecxx** [comment]
Due to recent updates on YouTube, it is currently impossible to capture YouTube videos, The new version of the browser extension will fix this issue.

**Comment by yukiharasensei** [comment]
Oh no, I've tried downloading on other platforms and they all have format errors like .mp4, they all don't work.

**Comment by filecxx** [comment]
Could you provide me with a URL address for the test?

**Comment by yukiharasensei** [comment]
You can check with Social Media sites like Facebook

**Comment by filecxx** [comment]
Your media player is likely missing the necessary decoders. I've downloaded numerous MP4 files without issues.

**Comment by yukiharasensei** [comment]
There are MP4 files that can still be opened, but when I download them on Facebook, they don't. I've tried changing from Media Player default to VLC or anything else but it won't open

**Comment by filecxx** [comment]
I don't use Facebook, if it happens on other websites, please let me know.

**Comment by yukiharasensei** [comment]
Oh... oke thank you
