### ISSUE TITLE
内存无限占用不释放

### ISSUE THREAD

**Issue by bingcp123** [filecxx/FileCentipede#805]
![fileu_Q98IgHnPQF](https://github.com/user-attachments/assets/6245b2c5-562f-41fb-a6e2-06c2f9780ff1)
今天遇到个问题，打开之后内存占用一直在提升也不会释放。我已经停止了所有正在下载和做种的任务，但是这个问题还在。请大佬帮忙看一下

**Comment by filecxx** [comment]
UPSecurityInput 和 UPSecurityInputService也有CPU占用和磁盘写入，可以检查下是否这个程序给filec.exe挂上了钩子导致一个线程挂起另一个线程还处于自旋锁的状态，进行一下逐个排除来定位问题，我也是第一次收到这样的反馈，不确定是什么导致的。

**Comment by bingcp123** [comment]
![NVIDIA_Overlay_ZsCwtQA35S](https://github.com/user-attachments/assets/944f4ba7-03e5-494a-bf29-53358a83ac15)
我已经尝试禁用 UPSecurityInputService，但仍然有这种情况。如果你需要的话我可以提供一下必要的日志或文件给你，不需要的话我想试一下重新安装

**Comment by filecxx** [comment]
结束进程后重新打开，可以尝试复现一下操作流程，是否只有下载某个文件才会出现这个情况，或者修改保存路径等。在新文件夹里也安装一个副本，进行相同的操作，看看问题是否会复现。

**Comment by bingcp123** [comment]
我参考你在另一个issue里说的文件列表
lib/data_windows.db
lib/data_windows.db-shm
lib/data_windows.db-wal
把正在下载的任务一个一个删掉，终于发现原因了：一个96G的torrent任务。
把这个任务删掉之后重启程序一切正常了
