### ISSUE TITLE
油管上的视频无法下载

### ISSUE THREAD

**Issue by Leekrun** [filecxx/FileCentipede#811]
之前可以爬取YouTube上的视频文件，现在能解析出文件地址，但是下载都会请求超时，能不能解决一下？

**Comment by filecxx** [comment]
当我把目前正在工作中的模块完成了之后会对浏览器扩展进行更新，会修复这个问题。

**Comment by filecxx** [comment]
当我把目前正在工作中的模块完成了之后会对浏览器扩展进行更新，会修复这个问题。

**Comment by fearmusa** [comment]
> 当我把目前正在工作中的模块完成了之后会对浏览器扩展进行更新，会修复这个问题。

which module are you working on?

**Comment by filecxx** [comment]
> > 当我把目前正在工作中的模块完成了之后会对浏览器扩展进行更新，会修复这个问题。
> 
> which module are you working on?

Compiler's memory module.
![image](https://github.com/user-attachments/assets/e2c28765-d9b8-4a20-b981-b176f98270ba)

**Comment by filecxx** [comment]
https://github.com/filecxx/PublicLists/discussions
