### ISSUE TITLE
feature request：增加对mpd格式的支持

### ISSUE THREAD

**Issue by YandLiu** [filecxx/FileCentipede#816]
现在下载m3u8文件的时候可以自动获取视频片段并合并，非常方便，希望也能支持mpd！
mpd 举例：https://vod2.wsw.com/vod/canaccord98.cmps.main.mp4/manifest_w890445861_ps501000_pd1506000_qXz0xNzI1NTA4MjMxNjU5.mpd

**Comment by filecxx** [comment]
下个版本会支持mpd.

**Comment by filecxx** [comment]
2.99.x 版本浏览器扩展可以检测和预览MPD，但是主程序需要在下次更新之后才能直接下载视频，目前只能下载到mpd文件。
