### ISSUE TITLE
建议增加对特定网站的规则设置

### ISSUE THREAD

**Issue by chrisxvin** [filecxx/FileCentipede#82]
使用指定代理、使用指定cookie之类的。

例如，我粘贴了一堆url，根据它们的域名，设置下载的时候套用的代理和cookie。
如果域名能支持通配符那就更强大了。

**Comment by chrisxvin** [comment]
另外能不能开放一些插件或者接口？比如我想做个随机切代理，或者下载了多少个文件换一套cookie之类的……这种可能比较小众的功能适合直接内置嘛（卑微脸）🤣🤣

**Comment by filecxx** [comment]
> 另外能不能开放一些插件或者接口？比如我想做个随机切代理，或者下载了多少个文件换一套cookie之类的……这种可能比较小众的功能适合直接内置嘛（卑微脸）roflrofl

这个功能实际上在设计时候考虑过了，我自己也有这个需求，实际上可以通过制作插件方式来实现，这个以后再增加进来。

**Comment by chrisxvin** [comment]
期待~

**Comment by filecxx** [comment]
2.1版本中增加站点规则，但是还不能同时随即切换多个，随即切换功能会在以后通过插件方式实现。
