### ISSUE TITLE
10月25日,来晚了,今天激活码又没了.激活码页面只有26日的.

### ISSUE THREAD

**Issue by Evilfoxster1981** [filecxx/FileCentipede#829]
**Please provide as much information as possible.**

version(>=2.0) :

screenshot:

URL:

.......

**Comment by filecxx** [comment]
2024-10-25 00:00:00 - 2024-11-24 00:00:00
0rx7eq9pfS807nxTO37y3q0JWrSqW0aEs1G6pv1GinBoVj4yTLFvaRmiUDXlA0GS2tVPWUWQ6zJoclehgCj2OIisqh4-Wo5AuPTTQ-yaJJq9yPlvWnmkwCGkGTSzi3m3sxZSgARqA9c7GiG_wsNwyzLtesqepQLl9iPDhEU_4td4Y

**Comment by AmyCoa** [comment]
> 2024-10-25 00：00：00 - 2024-11-24 00：00：00 0rx7eq9pfS807nxTO37y3q0JWrSqW0aEs1G6pv1GinBoVj4yTLFvaRmiUDXlA0GS2tVPWUWQ6zJoclehgCj2OIisqh4-Wo5AuPTTQ-yaJJq9yPlvWnmkwCGkGTSzi3m3sxZSgARqA9c7GiG_wsNwyzLtesqepQLl9iPDhEU_4td4Y

哇，这么长时间的激活码，快点出3.0，提供买断制，现在的买断太贵了

**Comment by LeeSin-Su** [comment]
> 2024-10-25 00:00:00 - 2024-11-24 00:00:00 0rx7eq9pfS807nxTO37y3q0JWrSqW0aEs1G6pv1GinBoVj4yTLFvaRmiUDXlA0GS2tVPWUWQ6zJoclehgCj2OIisqh4-Wo5AuPTTQ-yaJJq9yPlvWnmkwCGkGTSzi3m3sxZSgARqA9c7GiG_wsNwyzLtesqepQLl9iPDhEU_4td4Y

请问大佬支持ed2k的3.0版本什么时候会上啊
