### ISSUE TITLE
多个大文件同时下载会爆内存

### ISSUE THREAD

**Issue by Passerby1011** [filecxx/FileCentipede#83]
同时下载多个大容量文件时会爆内存，下载时会一点一点占掉内存，直至满，而且占掉的内存在任务管理器里不可见。内存占用过高后会导致软件卡顿，filec.exe服务退出

**Comment by filecxx** [comment]
是HTTP还是Torrent, 理论上不会出现这种情况，程序对文件的读写不使用内存，这部分使用的文件映射，由操作系统管理（共享内存字段可以显示），系统会定时或内存不足时候刷盘将所有内存中的数据提交到文件，当然不排除下载速度过快时候磁盘IO响应不过来，特别是多个大文件会出现随即IO写入，这导致在非SSD硬盘上会更慢.

不过 "filec.exe服务退出"  就很特别，可能是操作系统清空多余进程来释放内存时候把进程给关了。

可以限制一下下载速度或者同时下载任务数量试试。

**Comment by felipeav** [comment]
I'm having the same issue when downloading torrent, after a few minutes downloading it consumes more than 5 GB of ram.

**Comment by filecxx** [comment]
Don't worry about it, those ram were auto-managed by the operating system, just like all those BitTorrent clients who used "libtorrent"

basically, file centipede's torrent engine is the same as qBittorrent.

**Comment by Passerby1011** [comment]
http下载

**Comment by Passerby1011** [comment]
总文件下载大小在30g左右

**Comment by filecxx** [comment]
这个问题不太好解决，要么就像迅雷一样，下载几秒然后卡上几秒，或者就像IDM一样，下载完成之后花很长时间重建文件，在2.0版本之后再找找对应方案，目前这种案例解决方法就是限制同时下载文件数量.

**Comment by Leao9203** [comment]
> 这个问题不太好解决，要么就像迅雷一样，下载几秒然后卡上几秒，或者就像IDM一样，下载完成之后花很长时间重建文件，在2.0版本之后再找找对应方案，目前这种案例解决方法就是限制同时下载文件数量.

有没有办法实现边下载边写入磁盘...当然，可以加个限定值，到达一定限度再写入磁盘（参考迅雷）但是不用完全参考，可以在写入磁盘时开一个子线程写入硬盘，不知道这样能不能降低下卡顿感...

我刚刚下载了一个 16G 的大文件，结果内存爆了...整个操作系统都没有响应，直接断电重启才恢复了。

**Comment by filecxx** [comment]
> > 这个问题不太好解决，要么就像迅雷一样，下载几秒然后卡上几秒，或者就像IDM一样，下载完成之后花很长时间重建文件，在2.0版本之后再找找对应方案，目前这种案例解决方法就是限制同时下载文件数量.
> 
> 有没有办法实现边下载边写入磁盘...当然，可以加个限定值，到达一定限度再写入磁盘（参考迅雷）但是不用完全参考，可以在写入磁盘时开一个子线程写入硬盘，不知道这样能不能降低下卡顿感...
> 
> 我刚刚下载了一个 16G 的大文件，结果内存爆了...整个操作系统都没有响应，直接断电重启才恢复了。

这个问题目前只存在于windows版本，linux我测试过超过100G没有问题，这个issue会在2.0解决。

**Comment by filecxx** [comment]
这个问题在2.0中应该已经完全解决。
