### ISSUE TITLE
How to download Uncertain section videos?

### ISSUE THREAD

**Issue by isachinkum** [filecxx/FileCentipede#838]
File centipede shows some videos under the "Uncertain" section of the Browser extension dropdown. When I try to play the video from the browser extension, it plays normally. But when I try to download this video by clicking the download button on the browser extension against that video, it pop ups on the File Centipede desktop application for download but does not download the file. The file downloaded shows just zero (0) Kb/Mb as the file size or in other words the file does not download. Please advise on what should be done to download such files successfully. I have added 2 snapshots of the video file showing on the browser extension under the Uncertain tab & the snapshot of the video after download on the file centipede desktop application.

Please don't ask me to share the web link for the zoom recording since I cannot for privacy reasons. This issue can be checked on any zoon recorded video link which has Gallery view, Speaker view. I believe there is a third view within the webpage code which is not available to users. Please advise how this third view be downloaded as well.

![image](https://github.com/user-attachments/assets/984b79de-dbdb-49ea-9d87-9b9f2023a285)

![image](https://github.com/user-attachments/assets/75179048-107d-40f0-bd5c-4e3fb462fb5f)

**Comment by filecxx** [comment]
If there isn't a specific URL available for testing, it can be challenging to pinpoint the issue.

However, the browser extension will be significantly updated in the coming days. Once it's released, you can test it again with the new version.

**Comment by isachinkum** [comment]
Thank you. I will check this with your new release & confirm.
