### ISSUE TITLE
作者你好，想给你一个功能建议

### ISSUE THREAD

**Issue by Waradise** [filecxx/FileCentipede#855]
将软件设置为开机启动后，每次开机都会显示主界面，能否增加开机自启后默认进入通知栏，不显示主界面，每次都得点一次关闭按键，有些麻烦。
另外3.0啥时候来，等好久了~~~~

**Comment by filecxx** [comment]
在设置中勾选 “静默模式” 和 “托盘图标”，在没有运行的情况下运行后不会出现主界面，当然，这只是在windows下。

浏览器扩展已经更新了，firefox附加组件已经可以直接更新，chrome和edge至少还要审核1周，主程序还要过段时间。

**Comment by despairTK** [comment]
> 浏览器扩展已经更新了，firefox附加组件已经可以直接更新，chrome和edge至少还要审核1周，主程序还要过段时间。

请问浏览器插件有更新内容日志？

**Comment by filecxx** [comment]
> > 浏览器扩展已经更新了，firefox附加组件已经可以直接更新，chrome和edge至少还要审核1周，主程序还要过段时间。
> 
> 请问浏览器插件有更新内容日志？

除了功能优化和BUG修复以外增加了几个重要的功能

1：资源管理器

![image](https://github.com/user-attachments/assets/8bcd68c1-1590-43d4-9452-818ea235bfa7)

2: 自定义文件规则

![image](https://github.com/user-attachments/assets/b9c2f24c-529b-422f-8445-8469909dccc2)

3:  第三方查询接口
![image](https://github.com/user-attachments/assets/7705d802-18f6-4e32-a300-4b977a6c4587)
![image](https://github.com/user-attachments/assets/5ec07753-efe8-411f-aec1-aad773743e86)


现在可以不再依赖浏览器扩展本身的功能来抓取文件，一些网站如果获取不到资源不需要再等扩展更新，可以经过自己配置来针对指定网站的规则，比使用油猴脚本更方便。

比如Youtube可以添加第三方查询接口
![image](https://github.com/user-attachments/assets/3cf82aa7-e7a7-40b5-a2cd-617feabadb30)

![image](https://github.com/user-attachments/assets/74e30bc0-1cb7-4338-b5ef-2b2de8f96163)

![image](https://github.com/user-attachments/assets/f1cc8e39-5f79-4e86-b0c1-47d641b4ad16)

**Comment by Waradise** [comment]
> 在设置中勾选 “静默模式” 和 “托盘图标”，在没有运行的情况下运行后不会出现主界面，当然，这只是在windows下。
> 
> 浏览器扩展已经更新了，firefox附加组件已经可以直接更新，chrome和edge至少还要审核1周，主程序还要过段时间。

办公电脑用的1.9，NAS用的付费的，1.9没有静默模式，只能等3.0再买个会员

**Comment by filecxx** [comment]
> > 在设置中勾选 “静默模式” 和 “托盘图标”，在没有运行的情况下运行后不会出现主界面，当然，这只是在windows下。
> > 浏览器扩展已经更新了，firefox附加组件已经可以直接更新，chrome和edge至少还要审核1周，主程序还要过段时间。
> 
> 办公电脑用的1.9，NAS用的付费的，1.9没有静默模式，只能等3.0再买个会员，另外新版插件我看日期还是2月的，请问大佬哪里下新的，我自己打包就行，不用要审核过的现成的

可以再等几天，因为对应功能的wiki文档还没写完。

**Comment by Waradise** [comment]
> > > 在设置中勾选 “静默模式” 和 “托盘图标”，在没有运行的情况下运行后不会出现主界面，当然，这只是在windows下。
> > > 浏览器扩展已经更新了，firefox附加组件已经可以直接更新，chrome和edge至少还要审核1周，主程序还要过段时间。
> > 
> > 
> > 办公电脑用的1.9，NAS用的付费的，1.9没有静默模式，只能等3.0再买个会员，另外新版插件我看日期还是2月的，请问大佬哪里下新的，我自己打包就行，不用要审核过的现成的
> 
> 可以再等几天，因为对应功能的wiki文档还没写完。

收到，大佬加油~
