### ISSUE TITLE
通配符批量下载建议加上

### ISSUE THREAD

**Issue by paynewangw** [filecxx/FileCentipede#86]
如题，用通配符创建链接，下载资料或者连续剧的时候特别有用

![image](https://user-images.githubusercontent.com/88674185/160739890-601611af-6054-4de0-85e2-e4779d07c1d1.png)

**Comment by filecxx** [comment]
OK

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/187044639-a4ec3d10-0d29-4ceb-b77a-80fa8d8533ab.png)
![image](https://user-images.githubusercontent.com/100348948/187044649-b9ebd08f-6eae-4ce0-aa3f-5f7a206d671d.png)
![image](https://user-images.githubusercontent.com/100348948/187044672-b6cf9d68-b572-438a-8b91-4d79164c1e97.png)

这块还有没有别的需求，2.7发布之后这块会很长时间都不再修改了。
