### ISSUE TITLE
浏览器拓展的功能建议(结合N_m3u8DL-RE或yt-dlp)

### ISSUE THREAD

**Issue by yudong2ao** [filecxx/FileCentipede#860]
文件蜈蚣的浏览器扩展嗅探网页视频的能力非常强悍，而且浏览器扩展的页面功能设计页比较美观，只是必须要搭配文件蜈蚣才能使用，建议把浏览器扩展独立出来，让拓展嗅探到的音视频地址可以传递给其他网页媒体下载软件，如搭配N_m3u8DL-RE或yt-dlp来使用，这样作者可以节省很大一部分精力，不用关心视频下载功能的开发优化，而且N_m3u8DL-RE或yt-dlp的发展势头很好，功能更新很快。

**Comment by filecxx** [comment]
可以支持，实际上现在的2.99.x 版本已经可以自己通过 设置中的 "第三方查询接口" 来实现

![image](https://github.com/user-attachments/assets/a2dfbcdc-e367-4666-b9a2-83f4c217d460)
![image](https://github.com/user-attachments/assets/2536d769-826a-4328-a4d2-efbe6fcb65fa)

对于用户来说，只要安装过这个浏览器扩展的只要点击一个链接就能添加接口，例如在youtube上添加一个下载按钮。

[https://filecxx-extension/eyJ0eXBlIjoidGhpcmRfcGFydGllcyIsImRhdGEiOnsiYnV0dG9uX2NsYXNzIjoieHgtYnRuIiwiYnV0dG9uX2luc2VydF90byI6Inl0ZC1tZW51LXJlbmRlcmVyLnN0eWxlLXNjb3BlLnl0ZC13YXRjaC1tZXRhZGF0YSIsImJ1dHRvbl9pbnNlcnRpb25fbWV0aG9kIjozLCJidXR0b25fc3R5bGVzIjoiLnh4LWJ0bntcblx0Ym9yZGVyLXJhZGl1czogMjBweDtcbiAgXHRiYWNrZ3JvdW5kOiNmMmYyZjI7XG4gIFx0Ym9yZGVyOjA7XG4gIFx0Zm9udC1zaXplOjE0cHg7XG4gIFx0cGFkZGluZzo2cHggMTJweCA2cHggMTJweDtcbiAgXHRtYXJnaW46MnB4XG59XG5cbi54eC1idG46aG92ZXJ7XG5cdGJhY2tncm91bmQ6ICNkZmRmZGY7XG59XG5cbi54eC1idG46YWN0aXZle1xuXHRiYWNrZ3JvdW5kOiAjYzhjOGM4O1xufSIsImJ1dHRvbl90ZXh0IjoiRG93bmxvYWQiLCJjcmVhdGVfYnV0dG9uIjp0cnVlLCJkZXNjcmlwdGlvbiI6IiIsImV4cGxpY2l0X3dpbmRvdyI6eyJoaWRkZW5fZWxlbWVudHMiOiIjc2hhcmUtcGxhY2UtZG93bmxvYWRcbi5oZXJvLWhlYWRlclxuLnNtYWxsXG5oci5tLXQtMC5tLWItbWRcbmg0LnRleHQtbGVmdC5tLWItMFxuI2xpc3QtdmlkZW9cbmhlYWRlci5leHRlbnNpb24taGVhZGVyXG5kaXYudGV4dC1jZW50ZXIuYWxlcnQuYWxlcnQtZGFuZ2VyXG5kaXYudGh1bWJuYWlsLmNvdmVyIiwidXJsIjoiaHR0cHM6Ly93d3cueTJtYXRlLmNvbS95b3V0dWJlLyR7cGFyYW1zLnZ9Lz91dG1fc291cmNlPWNocm9tZV9hZGRvbiIsInZpc2libGVfZWxlbWVudCI6ImRpdi5wYW5lbC1ib2R5Iiwid2luZG93X2hlaWdodCI6NDAwLCJ3aW5kb3dfd2lkdGgiOjYwMH0sImZpbGVfdHlwZSI6MSwiaG9zdHMiOiJ5b3V0dWJlLmNvbVxud3d3LnlvdXR1YmUuY29tIiwiaWNvbiI6Imh0dHBzOi8vd3d3LnkybWF0ZS5jb20vdGhlbWVzL2ltYWdlcy9sb2dvLnBuZyIsImludGVyZmFjZV90eXBlIjowLCJuYW1lIjoieTJtYXRlX3dpbmRvdyIsInBhdGhzIjoiXFwvd2F0Y2hcXD92PS4rIiwicHJvdmlkZXIiOiJ5Mm1hdGUiLCJwcm92aWRlcl93ZWJzaXRlIjoiaHR0cHM6Ly93d3cueTJtYXRlLmNvbS8iLCJ2ZXJzaW9uIjoxLCJ2aWRlb19iYXIiOnRydWV9fQ==](https://filecxx-extension/eyJ0eXBlIjoidGhpcmRfcGFydGllcyIsImRhdGEiOnsiYnV0dG9uX2NsYXNzIjoieHgtYnRuIiwiYnV0dG9uX2luc2VydF90byI6Inl0ZC1tZW51LXJlbmRlcmVyLnN0eWxlLXNjb3BlLnl0ZC13YXRjaC1tZXRhZGF0YSIsImJ1dHRvbl9pbnNlcnRpb25fbWV0aG9kIjozLCJidXR0b25fc3R5bGVzIjoiLnh4LWJ0bntcblx0Ym9yZGVyLXJhZGl1czogMjBweDtcbiAgXHRiYWNrZ3JvdW5kOiNmMmYyZjI7XG4gIFx0Ym9yZGVyOjA7XG4gIFx0Zm9udC1zaXplOjE0cHg7XG4gIFx0cGFkZGluZzo2cHggMTJweCA2cHggMTJweDtcbiAgXHRtYXJnaW46MnB4XG59XG5cbi54eC1idG46aG92ZXJ7XG5cdGJhY2tncm91bmQ6ICNkZmRmZGY7XG59XG5cbi54eC1idG46YWN0aXZle1xuXHRiYWNrZ3JvdW5kOiAjYzhjOGM4O1xufSIsImJ1dHRvbl90ZXh0IjoiRG93bmxvYWQiLCJjcmVhdGVfYnV0dG9uIjp0cnVlLCJkZXNjcmlwdGlvbiI6IiIsImV4cGxpY2l0X3dpbmRvdyI6eyJoaWRkZW5fZWxlbWVudHMiOiIjc2hhcmUtcGxhY2UtZG93bmxvYWRcbi5oZXJvLWhlYWRlclxuLnNtYWxsXG5oci5tLXQtMC5tLWItbWRcbmg0LnRleHQtbGVmdC5tLWItMFxuI2xpc3QtdmlkZW9cbmhlYWRlci5leHRlbnNpb24taGVhZGVyXG5kaXYudGV4dC1jZW50ZXIuYWxlcnQuYWxlcnQtZGFuZ2VyXG5kaXYudGh1bWJuYWlsLmNvdmVyIiwidXJsIjoiaHR0cHM6Ly93d3cueTJtYXRlLmNvbS95b3V0dWJlLyR7cGFyYW1zLnZ9Lz91dG1fc291cmNlPWNocm9tZV9hZGRvbiIsInZpc2libGVfZWxlbWVudCI6ImRpdi5wYW5lbC1ib2R5Iiwid2luZG93X2hlaWdodCI6NDAwLCJ3aW5kb3dfd2lkdGgiOjYwMH0sImZpbGVfdHlwZSI6MSwiaG9zdHMiOiJ5b3V0dWJlLmNvbVxud3d3LnlvdXR1YmUuY29tIiwiaWNvbiI6Imh0dHBzOi8vd3d3LnkybWF0ZS5jb20vdGhlbWVzL2ltYWdlcy9sb2dvLnBuZyIsImludGVyZmFjZV90eXBlIjowLCJuYW1lIjoieTJtYXRlX3dpbmRvdyIsInBhdGhzIjoiXFwvd2F0Y2hcXD92PS4rIiwicHJvdmlkZXIiOiJ5Mm1hdGUiLCJwcm92aWRlcl93ZWJzaXRlIjoiaHR0cHM6Ly93d3cueTJtYXRlLmNvbS8iLCJ2ZXJzaW9uIjoxLCJ2aWRlb19iYXIiOnRydWV9fQ==)

**Comment by filecxx** [comment]
如果需要在下载管理器列表中默认自带的某个其他工具的支持

![image](https://github.com/user-attachments/assets/7e57a3ae-0bd7-4c24-bf2e-5405b589c867)

作为公平交换，我需要对应的工具也支持或者推荐这个浏览器扩展。
