### ISSUE TITLE
WINDOWS 报毒

### ISSUE THREAD

**Issue by xspeed1989** [filecxx/FileCentipede#863]
![image](https://github.com/user-attachments/assets/48668146-3411-4653-a65d-18eb979fde89)

OS 名称:            Microsoft Windows 11 专业版
OS 版本:            10.0.26100 暂缺 Build 26100

**Comment by filecxx** [comment]
你确定是在 https://www.filecxx.com 或者 https://github.com/filecxx/FileCentipede
上下载的吗？

我刚才检查过Windows defender 并没有扫描出任何问题。

**Comment by filecxx** [comment]
另外：如果是下载了所谓的 “破解版”，那么这个问题反馈在这里就没任何意义了。

**Comment by xspeed1989** [comment]
> 另外：如果是下载了所谓的 “破解版”，那么这个问题反馈在这里就没任何意义了。

没有下载破解版，官网web下载的版本

**Comment by xspeed1989** [comment]
filecxx_latest_win_x64.zip

CRC32: 7EB4BB95
MD5: 8DE2040757117539581F685C6ADD1005
SHA-1: 7A5EA399FAFF33427209B390207A577E7B563389

**Comment by filecxx** [comment]
把这个 fileu.exe  上传一下

**Comment by xspeed1989** [comment]
[fileu.zip](https://github.com/user-attachments/files/18252551/fileu.zip)

**Comment by filecxx** [comment]
我本地测试Windows defender 和 Windows smartscreen 均没有问题，这个exe是个快捷启动器，只有几十行代码
https://github.com/filecxx/FileCentipede/blob/main/source_code/fileu_launch/main.cpp

我找不到问题在哪里，不管了。
