### ISSUE TITLE
建议在开机启动的基础上添加静默模式

### ISSUE THREAD

**Issue by YulinChan** [filecxx/FileCentipede#87]
![image](https://user-images.githubusercontent.com/48314862/160740596-92b72170-1fc0-4d01-96c0-58e8751fdedd.png)
现在的开机启动是，开机之后，会弹出fileu的交互界面窗口。我希望它能开机之后不要弹出交互窗口，显示程序图标在状态栏托盘就好。
另外，有没有可能不用设置开机启动，当从浏览器下载文件时通过拓展自动唤醒下载程序？

**Comment by filecxx** [comment]
这个功能很简单，2.0时候放进去。

系统服务启动了应该会自动唤醒。

**Comment by paynewangw** [comment]
有没有可能不用设置开机启动，当从浏览器下载文件时通过拓展自动唤醒下载程序？
---------------------------附议这个，我的没有开机启动，点击就弹出红色半透明框，说要我安装，体验不好

另外，filec这个进程有时候会卡住或者退出，过程现象是：我同一个文件点了三次下载，打开软件界面后没看到有东西在下载，这个时候把软件关了重新打开，会发现同个链接创建了3个在同时下载，而且可能已经下了很大一部分了

**Comment by YulinChan** [comment]
> 系统服务启动了应该会自动唤醒。
![image](https://user-images.githubusercontent.com/48314862/160790564-e0d26f41-a0b2-44d0-8dfb-7cd739dc53e2.png)

确实能唤醒，就是显示有点问题，DPI变了，整个程序窗口显示的比例比原来的要大，字体变模糊了。

**Comment by filecxx** [comment]
有可能是磁盘IO读写慢导致线程暂时卡住了，这个不会发生太频繁，2.0之后再完善

**Comment by paynewangw** [comment]
> 有可能是磁盘IO读写慢导致线程暂时卡住了，这个不会发生太频繁，2.0之后再完善

我是250G的SSD，点下载时没有别的任务的下载，此问题在我这里100%可以复现

**Comment by filecxx** [comment]
我这边很难测试出来，如果能提供点更详细的信息会更好，比如这个filec是在fileu界面上启动的还是开机时候以服务形式启动的，也不排除杀毒软件等其他程序扫描进程暂时冻结了等，原因我也不太确定，等其他工作完成了我再仔细分析下。

**Comment by paynewangw** [comment]
> 我这边很难测试出来，如果能提供点更详细的信息会更好，比如这个filec是在fileu界面上启动的还是开机时候以服务形式启动的，也不排除杀毒软件等其他程序扫描进程暂时冻结了等，原因我也不太确定，等其他工作完成了我再仔细分析下。

在任务管理器中结束filec.exe，再更新版本后在界面上启动，如果方便的话，你可以联系我VX：19853961，开向日葵给你远程看

**Comment by filecxx** [comment]
这个问题暂时延缓下，2.0版本制作完成后再处理。
