### ISSUE TITLE
死机重启后突然运行不了了。

### ISSUE THREAD

**Issue by mantis3d** [filecxx/FileCentipede#88]
死机重启后突然运行不了了。
运行就出这个
![图片](https://user-images.githubusercontent.com/2351096/160867800-92180c22-c3d4-489d-9efa-6be945131536.png)

点启动就出这个
![图片](https://user-images.githubusercontent.com/2351096/160868032-2302161c-dbc6-4b7a-bfa1-971629dc1fdc.png)

然后就回到上面的状态。

**Comment by filecxx** [comment]
现在还有这个情况吗

**Comment by mantis3d** [comment]
发过去了

**Comment by filecxx** [comment]
临时的解决方法是删除 libicu.dat 这个缓存文件，这个bug应该只存在win7下，2.0版本时候再修复。
