### ISSUE TITLE
两个UI小问题

### ISSUE THREAD

**Issue by chrisxvin** [filecxx/FileCentipede#89]
![image](https://user-images.githubusercontent.com/628293/160959815-0ff3d034-e5f8-4114-aea3-264d530410b9.png)
左边，分类后面的数量，背景圆形被拉长了。
右边，进度里面的百分比，水平和垂直都没有居中。

小问题，不着急~~

**Comment by filecxx** [comment]
进度条的文字没居中是一直这样吗，怎么做到的。

**Comment by chrisxvin** [comment]
忽然发现的。我再下载个东西试试

**Comment by chrisxvin** [comment]
![无标题](https://user-images.githubusercontent.com/628293/160992072-5408e82b-07c8-4cb1-808b-0ae4586646c7.jpg)

这样看的更明显。
另外好多图标都模糊了。
这是在远程桌面上运行的，Windows Server 2019, 缩放 125%

**Comment by chrisxvin** [comment]
![无标题](https://user-images.githubusercontent.com/628293/160992583-dee8cd59-0a91-43f5-b7b1-8285a1731ee7.jpg)

应该是系统的问题。兼容性-高DPI设置，手动改成 替代--应用程序，就可以了。对齐和图标都正常了。
就是分类数量那个背景圆形还不圆。

**Comment by chrisxvin** [comment]
Server 版本是 1809，挺老的了，微软也不给更新😂

**Comment by filecxx** [comment]
我也怀疑是缩放造成的，再加上远程桌面上绘制，小圆圈暂时不管它，以后可能有替代的设计方案。

**Comment by chrisxvin** [comment]
👌
