### ISSUE TITLE
EDGE浏览器安装Chrome extension 1.4，重启浏览器就没有了

### ISSUE THREAD

**Issue by zqs7985** [filecxx/FileCentipede#90]
EDGE浏览器安装Chrome extension 1.4，重启浏览器就没有了，希望能解决一下，软件很好用。
![QQ截图20220331151647](https://user-images.githubusercontent.com/34728550/160999362-b3e893a9-f60b-4a33-9968-5abed9000747.jpg)

**Comment by filecxx** [comment]
可以尝试解压chrome.zip 加载已解压的文件夹。

**Comment by zzugyl** [comment]
现在谷歌浏览器版本100 不支持安装未上架的插件了。

**Comment by zqs7985** [comment]
> 

前两天是这样的，现在貌似好了，我就是这样装的，奇怪。
另外，新建下载建议可选不弹出主程序界面，类似迅雷那样，只弹出下载窗口或者我点了不再显示以后，直接后台下载。

**Comment by filecxx** [comment]
https://microsoftedge.microsoft.com/addons/detail/jeekmibdibcjeihbjnjgbegjalfelhon
