### ISSUE TITLE
复制已下载文件链接有问题

### ISSUE THREAD

**Issue by mantis3d** [filecxx/FileCentipede#91]
你的官网最新版，下载下来之后，右键复制链接，粘贴出来是这个：

�tp://www.filecxx.com/release/filecxx_latest_win_x64.zip

前面应该是http吧？前两个字母成了乱码。

**Comment by filecxx** [comment]
1.9版本吗

**Comment by mantis3d** [comment]
对

**Comment by psychic1999** [comment]
是的，复制地址乱码

**Comment by filecxx** [comment]
这个问题修复了。
(std::string_view out of scope)
