### ISSUE TITLE
Publish on FlatHub

### ISSUE THREAD

**Issue by catsout** [filecxx/FileCentipede#92]
It would be great it you could publish the FileCentipede flatpak on flathub.   
Instructions on how to do this can be found here:
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by catsout** [comment]
Some examples:  
https://beta.flathub.org/apps/details/org.qbittorrent.qBittorrent  
https://github.com/flathub/org.qbittorrent.qBittorrent/blob/master/org.qbittorrent.qBittorrent.yaml  
https://github.com/flathub/com.transmissionbt.Transmission  

BTW, may need to support [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html)

**Comment by filecxx** [comment]
I will do that when I am available, it would be great if you could do that for me.

thank you.

**Comment by catsout** [comment]
Why closed?

**Comment by filecxx** [comment]
Sorry, I give up, leaning someone else's rule is too difficult for me. I tried.
