### ISSUE TITLE
Firefox 中点击下载连接没反应

### ISSUE THREAD

**Issue by liaozhaishusheng** [filecxx/FileCentipede#93]
在Firefox中安装了插件，让插件接管下载管理器，点击资源下载连接后浏览器自带下载管理器闪一下，然后就没反应了。文件蜈蚣也可以识别到音频视频连接，点击下载也是没有反应。这个是不是需要依赖客户端使用？

另外，源码可以下载编译吧（mac平台），需要依赖的库不开源情况下，是否可以放在源码中用来编译？

**Comment by filecxx** [comment]
是的，必须下载客户端才能使用，浏览器的API功能做不到。
你无法手动编译，依赖库其中有一个是非常重量级的库，比boost更大，并不开源，也没做MAC兼容，再4.0之后或者5.0我再做MAC版本，目前只能用wine模拟windows版本。
