### ISSUE TITLE
蓝奏云不会自动提示下载

### ISSUE THREAD

**Issue by LingInit** [filecxx/FileCentipede#96]
蓝奏云不支持复制下载链接   点击下载没反应
1.9版本  已经装了浏览器插件  EDGE浏览器

**Comment by filecxx** [comment]
提供下测试地址

**Comment by LingInit** [comment]
https://423down.lanzouo.com/b0f19403i

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/161371236-6cfb25f8-d4bb-4b73-92b5-d13650d0258b.png)

该链接点击下载是正常

**Comment by LingInit** [comment]
跟系统有关系吗? 我是WIN11 22000.593
而且我发现服务没有启动成功
![2022040203273848](https://user-images.githubusercontent.com/26811168/161372160-b3dd195a-e60d-44d7-a674-1d04a163ed6a.jpg)

**Comment by filecxx** [comment]
应该和系统没有关系，下载其他文件能够正常吗

**Comment by filecxx** [comment]
如果filec是通过软件手动启动的，那么手动启动服务弹出提示是正常的，因为filec已经运行的情况下会重复运行。

**Comment by LingInit** [comment]
手动复制个链接 在软件中添加任务可以 
但是不会在浏览器中点击一个下载链接自动弹出下载的选项   不止蓝奏的  类似这种点击按钮下载的都不好使

**Comment by filecxx** [comment]
如果浏览器扩展不是1.4版本的，那么很大概率是和其他扩展冲突。

**Comment by LingInit** [comment]
尝试了一下  跟ADGUARD 广告过滤软件有冲突  退出或是暂停保护就可以了   
但是这种需要怎么解决?  为什么会被拦截呢

**Comment by filecxx** [comment]
https://github.com/filecxx/FileCentipede/issues/23

**Comment by LingInit** [comment]
可以了  感谢
