### ISSUE TITLE
新建任务对话框的建议

### ISSUE THREAD

**Issue by chrisxvin** [filecxx/FileCentipede#97]
![image](https://user-images.githubusercontent.com/628293/161362481-4f821743-df8c-4618-80be-0b50164f56d0.png)

能否参照Motrix，把重命名和下载位置挪到第一页？跟粘贴链接的文本框放一起。
这两个应该是最常用的。

**Comment by filecxx** [comment]
不打算更改新建任务对话框布局，不过可以考虑增加一个更简单的单任务新建任务对话框。

**Comment by chrisxvin** [comment]
这个建议的本意，是让这些链接下载到同一个目录里。
今天试了一下 1.9 版本，粘贴一堆http链接，每个都要挨个改下载目录，这就挺累的。

**Comment by filecxx** [comment]
我明白了

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/182483699-12ee42a0-0986-4559-a8f0-1805ba8bad95.png)
![image](https://user-images.githubusercontent.com/100348948/182483759-dabf16c2-2a33-48b4-8d10-205ff20f84bf.png)
2.4
