### ISSUE TITLE
图片（jpg等）不在设置里面的匹配文件扩展名里也会调用程序下载

### ISSUE THREAD

**Issue by zqs7985** [filecxx/FileCentipede#98]
![QQ截图20220402154832](https://user-images.githubusercontent.com/34728550/161372826-b8fc381c-1027-4965-bf63-87b50b730fcc.jpg)

如图，默认的文件扩展名里就没有jpg文件，但是图片还是会调用程序下载

![QQ截图20220402154706](https://user-images.githubusercontent.com/34728550/161372766-959e86b3-1b15-403d-89a0-39c064023df7.jpg)

哦，我好想突然懂了，这个匹配文件扩展名单指的是剪贴板里的下载链接，那普通下载能不能也区分文件扩展名呢？

**Comment by filecxx** [comment]
如果是从浏览器里下载，可以点击扩展图标，下方有个选项，将下载管理器切换为浏览器

**Comment by zqs7985** [comment]
> 如果是从浏览器里下载，可以点击扩展图标，下方有个选项，将下载管理器切换为浏览器

我只是想图片不用下载器下载而已，这来回切换还是比较麻烦，如果下载不拉起主窗口，只显示下载窗口也行

**Comment by filecxx** [comment]
好的

**Comment by zqs7985** [comment]
> 好的

谢谢，用过一些第三方下载器，这个还真的更好用
